grant create on schema public,cp7_payroll to cp7_payroll_read,cp7_nota_write,cp7_payroll_header;
alter function cp7_payroll.note_access() owner to cp7_payroll_read;
alter function cp7_payroll.note_capture(jsonb,uuid,date) owner to cp7_payroll_read;
alter function cp7_payroll.note_payroll(uuid,uuid,date,date) owner to cp7_payroll_read;
alter function cp7_payroll.note_header(uuid,uuid,date,date,text,uuid) owner to cp7_payroll_header;
alter function cp7_payroll.note_allocation(uuid) owner to cp7_payroll_read;
alter function cp7_payroll.note_verify_allocation(uuid,jsonb,jsonb) owner to cp7_payroll_read;
alter function cp7_payroll.note_command(text,jsonb,uuid,text) owner to cp7_nota_write;
alter function cp7_payroll.note_project_card(jsonb,boolean) owner to cp7_payroll_read;
alter function cp7_payroll.note_document(cp7_payroll.notes,boolean) owner to cp7_payroll_read;
alter function cp7_payroll.note_workspace(text,jsonb) owner to cp7_payroll_read;
alter function public.erp_cp7_get_nota_workspace_v1(text,jsonb) owner to cp7_payroll_read;
alter function public.erp_cp7_save_nota_v1(text,jsonb,uuid,text) owner to cp7_nota_write;
revoke create on schema public,cp7_payroll from cp7_payroll_read,cp7_nota_write,cp7_payroll_header;
revoke all on all functions in schema cp7_payroll from public,anon,authenticated,service_role,cp7_capture;
grant execute on function cp7_payroll.note_access() to cp7_nota_write,cp7_payroll_header;
grant execute on function cp7_payroll.note_capture(jsonb,uuid,date),cp7_payroll.note_payroll(uuid,uuid,date,date),cp7_payroll.note_header(uuid,uuid,date,date,text,uuid),cp7_payroll.note_allocation(uuid),cp7_payroll.note_verify_allocation(uuid,jsonb,jsonb) to cp7_nota_write;
revoke all on function public.erp_cp7_get_nota_workspace_v1(text,jsonb),public.erp_cp7_save_nota_v1(text,jsonb,uuid,text) from public,anon,authenticated,service_role,cp7_capture;
grant execute on function public.erp_cp7_get_nota_workspace_v1(text,jsonb),public.erp_cp7_save_nota_v1(text,jsonb,uuid,text) to authenticated;
