import { test, expect } from '@playwright/test'

test('six consumers share the fixture, remain isolated, and retain caveats', async ({ page }, testInfo) => {
  const requests: string[] = []
  const errors: string[] = []
  page.on('request', request => {
    if (new URL(request.url()).origin !== 'http://127.0.0.1:4187') requests.push(request.url())
    if (/\/rest\/|\/rpc\/|\/api\//.test(request.url())) requests.push(request.url())
  })
  page.on('pageerror', error => errors.push(error.message))
  page.on('console', message => { if (message.type() === 'error') errors.push(message.text()) })
  await page.goto('/cp7-preview')
  await expect(page.getByRole('heading', { name: 'Ruang kerja siap menerima data' })).toBeVisible()
  await expect(page.locator('[data-fact-state]')).toHaveCount(0)
  await page.getByLabel('Isi pratinjau').selectOption('FRAMEWORK')
  await expect(page.getByRole('heading', { name: 'Periksa kecocokan dan ETA batch' })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Terapkan rencana' })).toBeDisabled()
  await page.screenshot({ path: `cp7-shell-proof/${testInfo.project.name}-planner.png`, fullPage: true })
  await page.getByRole('button', { name: 'Lihat detail', exact: true }).click()
  await expect(page.getByRole('dialog')).toContainText('Keanggotaan komersial: fixture-A-members-v1')
  await expect(page.getByRole('dialog')).toContainText('Kekurangan belum teratasi')
  await page.keyboard.press('Escape')
  await expect(page.getByRole('dialog')).toHaveCount(0)
  await page.getByRole('button', { name: 'Stok & saran SKU', exact: true }).click()
  await expect(page.getByText('18 PCS', { exact: true })).toBeVisible()
  await page.getByLabel('Cari SKU atau ukuran').fill('tidak-ada')
  await expect(page.getByRole('heading', { name: 'Tidak ada hasil filter' })).toBeVisible()
  await page.getByLabel('Cari SKU atau ukuran').fill('30')
  await expect(page.getByText('8 PCS · asumsi', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Panel Potongan', exact: true }).click()
  await page.getByRole('button', { name: 'Dari Buat Potongan', exact: true }).click()
  await expect(page.getByText('8 PCS · asumsi', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Tutup panel', exact: true }).click()
  await page.getByRole('button', { name: 'Dari Bagi Potongan', exact: true }).click()
  await expect(page.getByText('8 PCS · asumsi', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Business Report', exact: true }).click()
  await expect(page.locator('.cp7-report')).toContainText('kebutuhan bersyarat 8 PCS · asumsi')
  await expect(page.getByRole('button', { name: 'Terbitkan laporan' })).toBeDisabled()
  await page.getByRole('button', { name: 'Arsip', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Belum ada laporan terbit' })).toBeVisible()
  await page.getByRole('button', { name: 'Reminder', exact: true }).click()
  await expect(page.getByText('8 PCS · asumsi', { exact: true })).toBeVisible()
  for (const domain of ['Aksesori', 'Utang', 'Piutang']) {
    await page.getByRole('button', { name: domain, exact: true }).click()
    await expect(page.locator('.cp7-main')).toContainText(domain === 'Aksesori' ? 'belum dapat dipastikan' : 'belum dibaca')
  }
  await page.getByRole('button', { name: 'Tanya AI', exact: true }).click()
  await expect(page.getByLabel('Prompt Tanya AI')).toHaveValue(/kebutuhan bersyarat 8 PCS · asumsi/)
  await expect(page.getByRole('link', { name: 'Buka ChatGPT' })).toHaveAttribute('href', 'https://chatgpt.com/')
  await page.getByRole('button', { name: 'Sambungan WhatsApp', exact: true }).click()
  await page.getByRole('button', { name: 'Pratinjau isi pesan' }).click()
  await expect(page.getByLabel('Pratinjau lokal · tidak dikirim')).toHaveValue(/kebutuhan bersyarat 8 PCS · asumsi/)
  await expect(page.getByRole('button', { name: 'Kirim WhatsApp' })).toBeDisabled()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  expect(requests).toEqual([])
  expect(errors).toEqual([])
})

test('partial/error/stale and access changes cannot masquerade as ready output', async ({ page }) => {
  await page.goto('/cp7-preview')
  for (const mode of ['PARTIAL', 'ERROR']) {
    await page.getByLabel('Isi pratinjau').selectOption(mode)
    await expect(page.locator('.cp7-notice')).toHaveAttribute('data-state', mode)
    await expect(page.locator('[data-fact-state]')).toHaveCount(0)
  }
  await page.getByLabel('Isi pratinjau').selectOption('STALE')
  await page.getByRole('button', { name: 'Tanya AI', exact: true }).click()
  await expect(page.getByLabel('Prompt Tanya AI')).toHaveValue(/DATA BERUBAH/)
  await page.getByLabel('Hak akses contoh').selectOption('OPERATIONS')
  await expect(page.getByLabel('Prompt Tanya AI')).not.toHaveValue(/GROSS_MARGIN/)
  await page.getByLabel('Hak akses contoh').selectOption('DENIED')
  await expect(page.getByRole('heading', { name: 'Akses contoh ditolak' })).toBeVisible()
  await expect(page.locator('textarea')).toHaveCount(0)
  await expect(page.locator('.cp7-context')).toHaveCount(0)
})

test('clipboard rejection keeps selectable text, benchmark links and old app remain reachable', async ({ page }) => {
  await page.addInitScript(() => Object.defineProperty(navigator, 'clipboard', { configurable: true, value: { writeText: async () => { throw new Error('test clipboard denied') } } }))
  await page.goto('/cp7-preview')
  await page.getByLabel('Isi pratinjau').selectOption('FRAMEWORK')
  await page.getByRole('button', { name: 'Tanya AI', exact: true }).click()
  await page.getByRole('button', { name: 'Salin teks' }).click()
  await expect(page.getByText('Salin otomatis gagal. Pilih teks di bawah dan salin manual.')).toBeVisible()
  await expect(page.getByLabel('Prompt Tanya AI')).toHaveValue(/DATA_CONTOH/)
  await page.getByRole('button', { name: 'Benchmark & metode', exact: true }).click()
  await expect(page.locator('.cp7-method-grid a')).toHaveCount(6)
  await expect(page.locator('.cp7-method-grid')).toContainText('90%, 95%, dan 99%')
  await page.getByRole('link', { name: 'Kembali ke ERP' }).click()
  await expect(page.locator('.app-shell')).toBeVisible()
  const mobileMenu = page.getByRole('button', { name: 'Buka menu', exact: true })
  if (await mobileMenu.isVisible()) await mobileMenu.click()
  await page.getByRole('link', { name: 'Pratinjau CP7', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Ruang kerja siap menerima data' })).toBeVisible()
})
