-- BE T1_FAMILY development install, NOT release evidence. Stage 1; remaining flows recorded in writer progress.
-- Generated by scripts/cp6_be_build.py; do not edit by hand.
begin;set local search_path='';set local lock_timeout='10s';set local statement_timeout='240s';
do $guard$ begin if not exists(select 1 from erp.schema_migrations where version='v2.6.20bd') then raise exception 'BE_REQUIRES_BD';end if;
if exists(select 1 from erp.schema_migrations where version='v2.6.20be') then raise exception 'BE_ALREADY_INSTALLED';end if;end $guard$;
-- BE: one selected physical lot becomes one target SKU. M:4828-4843/5057-5096.
-- Native product_conversions, allocations, movements and HPP versions remain the facts.
create table erp.be_execution_context_v1(
  backend_pid integer not null, transaction_id bigint not null, request_id uuid not null,
  primary key(backend_pid,transaction_id)
);
create table erp.be_conversion_sources_v1(
  conversion_id uuid primary key references erp.product_conversions(id),
  source_lot_id uuid not null references erp.fg_lots(id),
  origin_kind text not null check(origin_kind in('FG','REWORK','REDYE')),
  rework_id uuid references erp.rework_orders(id),
  source_revision text not null,
  created_by uuid, created_at timestamptz not null default statement_timestamp(),
  check((origin_kind='FG')=(rework_id is null))
);
create table erp.be_conversion_returns_v1(
  outstanding_id uuid primary key references erp.bc_outstanding_returns_v1(id),
  conversion_id uuid not null references erp.product_conversions(id),
  line_no integer not null check(line_no>0),
  unique(conversion_id,line_no)
);

CREATE OR REPLACE FUNCTION erp.be_in_context_v1()
 RETURNS boolean LANGUAGE sql STABLE SECURITY DEFINER SET search_path TO ''
AS $function$
 select exists(select 1 from erp.be_execution_context_v1
   where backend_pid=pg_backend_pid() and transaction_id=txid_current())
$function$;

CREATE OR REPLACE FUNCTION erp.be_guard_fact_v1()
 RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path TO ''
AS $function$
begin
 if not erp.be_in_context_v1() then raise exception 'BE_FACADE_REQUIRED: gunakan alur konversi';end if;
 if TG_OP<>'INSERT' then raise exception 'BE_IMMUTABLE_FACT: fakta konversi tidak dapat ditimpa';end if;
 return new;
end;$function$;
create trigger be_conversion_sources_fact before insert or update or delete on erp.be_conversion_sources_v1
 for each row execute function erp.be_guard_fact_v1();
create trigger be_conversion_returns_fact before insert or update or delete on erp.be_conversion_returns_v1
 for each row execute function erp.be_guard_fact_v1();

CREATE OR REPLACE FUNCTION erp.be_source_revision_v1(p_lot uuid,p_location uuid)
 RETURNS text LANGUAGE sql STABLE SECURITY DEFINER SET search_path TO ''
AS $function$
 select md5(jsonb_build_object('lot',p_lot,'location',p_location,
   'hpp',(select hv.id from erp.hpp_versions hv where hv.lot_id=p_lot and hv.is_current),
   'movements',coalesce((select jsonb_agg(jsonb_build_array(m.id,m.qty_signed,m.physical_at) order by m.id)
      from erp.fg_stock_movements m where m.lot_id=p_lot and m.location_id=p_location),'[]'::jsonb))::text)
$function$;

CREATE OR REPLACE FUNCTION erp.be_conversion_preview_v1(p_payload jsonb)
 RETURNS jsonb LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path TO ''
AS $function$
declare l erp.fg_lots%rowtype;s erp.products%rowtype;t erp.products%rowtype;v_location uuid;v_qty integer;
 v_at timestamptz;v_current numeric;v_dated numeric;v_hpp numeric;v_cost jsonb;
begin
 perform erp.require_permission('warehouse.brand_conversion.view');
 perform erp._cp3_assert_closed_json_object(p_payload,
   array['source_lot_id','target_product_id','location_id','qty_pcs','physical_at','reason','expected_version'],
   array['source_lot_id','target_product_id','location_id','qty_pcs','physical_at','reason','expected_version','expected_returns'],'konversi');
 select * into l from erp.fg_lots where id=erp.bd_uuid_v1(p_payload,'source_lot_id',true);
 if l.id is null then raise exception 'BE_SOURCE_NOT_FOUND: lot sumber tidak ditemukan';end if;
 select * into s from erp.products where id=l.product_id;
 select * into t from erp.products where id=erp.bd_uuid_v1(p_payload,'target_product_id',true);
 if t.id is null or not t.is_active then raise exception 'BE_TARGET_NOT_ACTIVE: SKU tujuan tidak aktif';end if;
 if t.id=s.id then raise exception 'BE_SAME_SKU: pilih SKU tujuan yang berbeda';end if;
 if t.model_id is distinct from s.model_id or t.size_id is distinct from s.size_id then
   raise exception 'BE_DIMENSION_MISMATCH: model konstruksi dan ukuran harus tetap';end if;
 v_location:=erp.bd_uuid_v1(p_payload,'location_id',true);
 v_qty:=erp.bd_qty_v1(p_payload->'qty_pcs','qty_pcs');
 v_at:=erp.bd_at_v1(p_payload->>'physical_at','physical_at');
 perform erp.bc_text_v1(p_payload,'reason',true,1000);
 if v_at<l.produced_at then raise exception 'BE_BEFORE_SOURCE: waktu konversi sebelum lot tersedia';end if;
 perform erp.assert_product_identity_time(s.id,v_at,'EXISTING_STOCK');
 perform erp.assert_product_identity_time(t.id,v_at,'NEW_STOCK');
 if jsonb_typeof(p_payload->'expected_version') is distinct from 'string'
   or p_payload->>'expected_version' is distinct from erp.be_source_revision_v1(l.id,v_location) then
   raise exception 'STALE_VERSION: stok atau HPP sumber berubah; muat ulang';end if;
 select coalesce(sum(m.qty_signed),0),coalesce(sum(m.qty_signed) filter(where m.physical_at<=v_at),0)
   into v_current,v_dated from erp.fg_stock_movements m
   where m.lot_id=l.id and m.location_id=v_location and m.quality_grade='GRADE_A';
 if v_qty>least(v_current,v_dated) then raise exception 'BE_SOURCE_CAPACITY: jumlah melebihi stok sumber pada tanggalnya';end if;
 select hpp_per_pcs into v_hpp from erp.v_current_hpp where lot_id=l.id;
 if v_hpp is null then raise exception 'BE_SOURCE_HPP_UNKNOWN: nilai sumber belum diketahui';end if;
 v_cost:=case when erp.has_permission('finance.hpp.view') then
   jsonb_build_object('source_unit_hpp',v_hpp::text,'source_value',round(v_hpp*v_qty,2)::text) else '{}'::jsonb end;
 return jsonb_build_object('source_lot_id',l.id,'source_product_id',s.id,'target_product_id',t.id,
   'source_sku',s.sku,'target_sku',t.sku,'location_id',v_location,'qty_pcs',v_qty,'physical_at',v_at,
   'source_revision',p_payload->>'expected_version','cost',v_cost);
end;$function$;

CREATE OR REPLACE FUNCTION erp.be_post_conversion_v1(p_payload jsonb,p_request uuid,p_origin text default 'FG',p_rework uuid default null)
 RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path TO ''
AS $function$
declare v jsonb;l erp.fg_lots%rowtype;r jsonb;i integer:=0;v_return uuid;v_qty numeric;v_material uuid;v_dest uuid;
begin
 perform erp.require_permission('warehouse.brand_conversion.post');
 if not erp.be_in_context_v1() then raise exception 'BE_FACADE_REQUIRED';end if;
 perform pg_advisory_xact_lock(hashtextextended('FG_HPP_SALES_V2620C',0));
 select * into l from erp.fg_lots where id=erp.bd_uuid_v1(p_payload,'source_lot_id',true) for update;
 v:=erp.be_conversion_preview_v1(p_payload);
 insert into erp.product_conversions(id,conversion_number,from_product_id,to_product_id,location_id,qty_pcs,conversion_type,
   physical_at,status,conversion_cost_total,notes,created_by)
 values(p_request,'BE-'||p_request::text,l.product_id,(v->>'target_product_id')::uuid,(v->>'location_id')::uuid,
   (v->>'qty_pcs')::int,'REBRAND',(v->>'physical_at')::timestamptz,'DRAFT',0,btrim(p_payload->>'reason'),erp.current_app_user_id());
 insert into erp.be_conversion_sources_v1(conversion_id,source_lot_id,origin_kind,rework_id,source_revision,created_by)
 values(p_request,l.id,p_origin,p_rework,v->>'source_revision',erp.current_app_user_id());
 perform erp.post_product_conversion(p_request);
 if p_payload ? 'expected_returns' then
   if jsonb_typeof(p_payload->'expected_returns') is distinct from 'array' or jsonb_array_length(p_payload->'expected_returns')>100 then
     raise exception 'BE_RETURN_LINES: maksimal 100 baris bongkaran';end if;
   for r in select value from jsonb_array_elements(p_payload->'expected_returns') loop
     perform erp._cp3_assert_closed_json_object(r,array['material_id','qty','holder'],array['material_id','qty','holder'],'bongkaran');
     v_material:=erp.bc_uuid_v1(r,'material_id',true);v_qty:=erp.bc_parse_qty_v1(v_material,r->'qty','qty');
     insert into erp.bc_outstanding_returns_v1(source_kind,owner_kind,material_id,qty_expected,holder,reference)
     values('CONVERSION','COMPANY',v_material,v_qty,erp.bc_text_v1(r,'holder',true,120),'BE-'||p_request::text) returning id into v_return;
     i:=i+1;insert into erp.be_conversion_returns_v1(outstanding_id,conversion_id,line_no) values(v_return,p_request,i);
   end loop;
 end if;
 select destination_lot_id into strict v_dest from erp.product_conversion_allocations where conversion_id=p_request;
 return v||jsonb_build_object('conversion_id',p_request,'destination_lot_id',v_dest,'status','POSTED','pending_returns',i);
end;$function$;

CREATE OR REPLACE FUNCTION erp.save_product_conversion_action_v1(p_action text,p_payload jsonb,p_client_request_id uuid)
 RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path TO '' SET "TimeZone" TO 'UTC' SET "DateStyle" TO 'ISO, YMD'
AS $function$
declare a text:=upper(btrim(coalesce(p_action,'')));v jsonb;v_cached jsonb;v_id uuid;
begin
 perform erp.require_permission('warehouse.brand_conversion.view');
 if a not in('POST','REVERSE') then raise exception 'BE_ACTION_UNKNOWN: tindakan tidak dikenal';end if;
 perform erp.require_permission(case when a='REVERSE' then 'warehouse.brand_conversion.reverse' else 'warehouse.brand_conversion.post' end);
 if a='REVERSE' then perform erp.require_owner_admin();end if;
 perform erp.require_internal();
 if p_client_request_id is null or jsonb_typeof(p_payload) is distinct from 'object' or octet_length(p_payload::text)>30000 then
   raise exception 'BE_REQUEST_INVALID: request id dan data wajib';end if;
 v_cached:=erp._idempotency_begin('save_product_conversion_action_v1',p_client_request_id,
   erp._request_hash(jsonb_build_object('action',a,'payload',p_payload)));
 if v_cached is not null then return v_cached;end if;
 perform set_config('app.change_reason',erp.bc_text_v1(p_payload,'reason',true,1000),true);
 insert into erp.be_execution_context_v1 values(pg_backend_pid(),txid_current(),p_client_request_id);
 if a='POST' then v:=erp.be_post_conversion_v1(p_payload,p_client_request_id);
 else
   perform erp._cp3_assert_closed_json_object(p_payload,array['conversion_id','reason'],array['conversion_id','reason'],'pembatalan konversi');
   v_id:=erp.bd_uuid_v1(p_payload,'conversion_id',true);
   perform pg_advisory_xact_lock(hashtextextended('FG_HPP_SALES_V2620C',0));
   if not exists(select 1 from erp.be_conversion_sources_v1 where conversion_id=v_id) then raise exception 'BE_DOCUMENT_NOT_FOUND';end if;
   if exists(select 1 from erp.be_conversion_returns_v1 s join erp.bc_return_lots_v1 l on l.outstanding_id=s.outstanding_id
       where s.conversion_id=v_id) then raise exception 'BE_REVERSE_DEPENDANTS: batalkan dahulu penerimaan bongkaran';end if;
   perform erp.reverse_product_conversion(v_id,p_payload->>'reason');
   update erp.bc_outstanding_returns_v1 set status='CANCELLED' where id in(select outstanding_id from erp.be_conversion_returns_v1 where conversion_id=v_id);
   v:=jsonb_build_object('conversion_id',v_id,'status','REVERSED');
 end if;
 delete from erp.be_execution_context_v1 where backend_pid=pg_backend_pid() and transaction_id=txid_current();
 insert into erp.audit_logs(entity_type,entity_id,action,new_data,changed_by,change_reason)
 values('product_conversions',(v->>'conversion_id')::uuid,case when a='POST' then 'POST' else 'REVERSE' end,v,erp.current_app_user_id(),p_payload->>'reason');
 return erp._idempotency_complete('save_product_conversion_action_v1',p_client_request_id,v||jsonb_build_object('request_id',p_client_request_id));
end;$function$;

CREATE OR REPLACE FUNCTION erp.get_product_conversion_workspace_v1(p_filters jsonb default '{}'::jsonb)
 RETURNS jsonb LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path TO ''
AS $function$
declare v_page integer;v_size integer:=25;v_query text;v_lot uuid;v_result jsonb;v_values boolean;
begin
 perform erp.require_permission('warehouse.brand_conversion.view');
 perform erp._cp3_assert_closed_json_object(p_filters,array[]::text[],array['query','page','source_lot_id','preview'],'konversi filters');
 if p_filters ? 'preview' then return jsonb_build_object('preview',erp.be_conversion_preview_v1(p_filters->'preview'));end if;
 if p_filters ? 'page' and (jsonb_typeof(p_filters->'page')<>'number' or (p_filters->>'page')!~'^[1-9][0-9]{0,5}$') then
   raise exception 'BE_PAGE_INVALID';end if;
 v_page:=coalesce((p_filters->>'page')::int,1);v_query:=lower(coalesce(erp.bc_text_v1(p_filters,'query',false,120),''));
 v_lot:=erp.bd_uuid_v1(p_filters,'source_lot_id',false);v_values:=erp.has_permission('finance.hpp.view');
 with lots as(select l.id,l.lot_number,l.product_id,l.po_id,l.produced_at,p.sku,p.product_name,p.model_id,p.size_id,
       m.location_id,loc.location_name,sum(m.qty_signed)::integer qty
     from erp.fg_lots l join erp.products p on p.id=l.product_id join erp.fg_stock_movements m on m.lot_id=l.id
     join erp.locations loc on loc.id=m.location_id
     where m.quality_grade='GRADE_A' and (v_lot is null or l.id=v_lot)
       and (v_query='' or lower(p.sku||' '||p.product_name||' '||l.lot_number) like '%'||v_query||'%')
     group by l.id,p.id,m.location_id,loc.location_name having sum(m.qty_signed)>0),
   pg as(select * from lots order by produced_at,id,location_id limit v_size offset (v_page-1)*v_size)
 select jsonb_build_object('total',(select count(*) from lots),'page',v_page,'page_size',v_size,
   'lots',coalesce(jsonb_agg(to_jsonb(pg)||jsonb_build_object('source_revision',erp.be_source_revision_v1(id,location_id),
     'unit_hpp',case when v_values then (select hpp_per_pcs::text from erp.v_current_hpp where lot_id=pg.id) end) order by produced_at,id,location_id),'[]'::jsonb))
 into v_result from pg;
 return v_result||jsonb_build_object('targets',coalesce((select jsonb_agg(to_jsonb(x) order by x.sku,x.id) from
   (select p.id,p.sku,p.product_name,p.model_id,p.size_id from erp.products p join erp.fg_lots l on l.id=v_lot
    join erp.products s on s.id=l.product_id where p.is_active and p.model_id=s.model_id and p.size_id=s.size_id and p.id<>s.id
    order by p.sku,p.id limit 500) x),'[]'::jsonb));
end;$function$;

CREATE OR REPLACE FUNCTION public.erp_save_product_conversion_action_v1(p_action text,p_payload jsonb,p_client_request_id uuid)
 RETURNS jsonb LANGUAGE sql SECURITY DEFINER SET search_path TO ''
AS $function$ select erp.save_product_conversion_action_v1(p_action,p_payload,p_client_request_id) $function$;
CREATE OR REPLACE FUNCTION public.erp_get_product_conversion_workspace_v1(p_filters jsonb default '{}'::jsonb)
 RETURNS jsonb LANGUAGE sql STABLE SECURITY DEFINER SET search_path TO ''
AS $function$ select erp.get_product_conversion_workspace_v1(p_filters) $function$;
CREATE OR REPLACE FUNCTION erp.post_product_conversion(p_conversion_id uuid)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'erp', 'public'
AS $function$
declare
  h erp.product_conversions%rowtype;
  r record;
  v_need integer;
  v_take integer;
  v_source_hpp numeric(18,6);
  v_dest_hpp numeric(18,6);
  v_dest_lot uuid;
  v_dest_lot_no text;
  v_source_value numeric(24,6):=0;
  v_lock_product uuid;
  v_po uuid;
begin
  perform erp.require_internal();
  perform pg_advisory_xact_lock(hashtextextended('FG_HPP_SALES_V2620C',0));
  select * into h from erp.product_conversions
  where id=p_conversion_id for update;
  if h.id is null or h.status<>'DRAFT' then
    raise exception 'Product conversion must be DRAFT';
  end if;
  if coalesce(h.conversion_cost_total,0)<>0 then
    raise exception 'Non-zero conversion cost requires a sourced accounting workflow; unsafe unsourced HPP capitalization is blocked';
  end if;

  perform erp.assert_product_identity_time(
    h.from_product_id,h.physical_at,'EXISTING_STOCK');
  perform erp.assert_product_identity_time(
    h.to_product_id,h.physical_at,'NEW_STOCK');

  -- Fail before the first new fact.  A mixed PO/non-PO FIFO pool is also
  -- rejected rather than silently attributing only part of the conversion.
  if exists(
    select 1
    from erp.fg_lots fl
    join erp.fg_stock_movements fm on fm.lot_id=fl.id
    where fl.product_id=h.from_product_id and fl.po_id is null
      and (not exists(select 1 from erp.be_conversion_sources_v1 where conversion_id=h.id)
        or fl.id=(select source_lot_id from erp.be_conversion_sources_v1 where conversion_id=h.id))
      and fm.location_id=h.location_id and fm.quality_grade='GRADE_A'
    group by fl.id
    having sum(fm.qty_signed)>0
  ) then
    raise exception 'NON_PO_CONVERSION_REQUIRES_SOURCED_HPP_WORKFLOW';
  end if;

  insert into erp.fg_inventory_balances(
    product_id,location_id,quality_grade,cached_qty_pcs
  ) values(h.from_product_id,h.location_id,'GRADE_A',0)
  on conflict(product_id,location_id,quality_grade) do nothing;
  insert into erp.fg_inventory_balances(
    product_id,location_id,quality_grade,cached_qty_pcs
  ) values(h.to_product_id,h.location_id,'GRADE_A',0)
  on conflict(product_id,location_id,quality_grade) do nothing;
  for v_lock_product in
    select x from (values(h.from_product_id),(h.to_product_id)) v(x)
    group by x order by x
  loop
    perform 1 from erp.fg_inventory_balances
    where product_id=v_lock_product and location_id=h.location_id
      and quality_grade='GRADE_A' for update;
  end loop;

  v_need:=h.qty_pcs;
  delete from erp.product_conversion_allocations where conversion_id=h.id;
  for r in
    select fl.id,fl.po_id,fl.produced_at,
      sum(fm.qty_signed)::integer location_qty
    from erp.fg_lots fl
    join erp.fg_stock_movements fm on fm.lot_id=fl.id
    where fl.product_id=h.from_product_id and fl.po_id is not null
      and (not exists(select 1 from erp.be_conversion_sources_v1 where conversion_id=h.id)
        or fl.id=(select source_lot_id from erp.be_conversion_sources_v1 where conversion_id=h.id))
      and fm.location_id=h.location_id and fm.quality_grade='GRADE_A'
    group by fl.id,fl.po_id,fl.produced_at
    having sum(fm.qty_signed)>0
    order by fl.produced_at,fl.id
  loop
    exit when v_need<=0;
    v_take:=least(v_need,r.location_qty);
    perform 1 from erp.fg_lots where id=r.id for update;
    v_source_hpp:=coalesce(erp.lock_current_hpp_per_pcs(r.id),0);
    v_dest_hpp:=v_source_hpp;
    v_dest_lot_no:=h.conversion_number||'-'||substr(r.id::text,1,8)
      ||'-'||substr(gen_random_uuid()::text,1,6);
    insert into erp.fg_lots(
      lot_number,po_id,qc_item_id,product_id,initial_qty_pcs,cached_qty_pcs,
      produced_at,is_open,lot_origin,source_lot_id
    ) values(
      v_dest_lot_no,r.po_id,null,h.to_product_id,v_take,0,h.physical_at,
      true,'CONVERSION',r.id
    ) returning id into v_dest_lot;
    insert into erp.hpp_versions(
      lot_id,version_no,cost_state,qty_basis_pcs,total_cost,is_current,
      calculation_reason,created_by
    ) values(
      v_dest_lot,1,'ADJUSTED',v_take,v_take*v_dest_hpp,true,
      'SKU conversion/rebrand carry-forward',erp.current_app_user_id()
    );
    insert into erp.hpp_version_components(
      hpp_version_id,component_type,description,qty_basis,unit_cost,
      total_cost,source_type,source_id
    )
    select hv.id,'OTHER','HPP carried from source lot',v_take,
      v_source_hpp,v_take*v_source_hpp,'FG_LOT',r.id
    from erp.hpp_versions hv
    where hv.lot_id=v_dest_lot and hv.version_no=1;
    perform erp.post_fg_movement(
      h.from_product_id,r.id,h.location_id,'GRADE_A','REBRAND_OUT',-v_take,
      v_source_hpp,null,'PRODUCT_CONVERSION',h.id,h.physical_at,
      'SKU conversion OUT',false
    );
    perform erp.post_fg_movement(
      h.to_product_id,v_dest_lot,h.location_id,'GRADE_A','REBRAND_IN',v_take,
      v_dest_hpp,null,'PRODUCT_CONVERSION',h.id,h.physical_at,
      'SKU conversion IN',false
    );
    insert into erp.product_conversion_allocations(
      conversion_id,source_lot_id,destination_lot_id,qty_pcs,
      original_hpp_per_pcs,conversion_cost_allocated
    ) values(h.id,r.id,v_dest_lot,v_take,v_source_hpp,0);
    v_source_value:=v_source_value+(v_take*v_source_hpp);
    v_need:=v_need-v_take;
  end loop;
  if v_need>0 then
    raise exception 'Insufficient source stock for conversion; short % pcs',v_need;
  end if;

  update erp.product_conversions set status='POSTED' where id=h.id;
  if round(v_source_value,2)>0.005 then
    perform erp.post_journal(
      'PRODUCT_CONVERSION',h.id,(h.physical_at AT TIME ZONE 'Asia/Jakarta')::date,'SKU conversion/rebrand',
      jsonb_build_array(
        jsonb_build_object('mapping_key','FG_INVENTORY','debit',
          round(v_source_value,2),'credit',0,'product_id',h.to_product_id),
        jsonb_build_object('mapping_key','FG_INVENTORY','debit',0,'credit',
          round(v_source_value,2),'product_id',h.from_product_id)
      )
    );
  end if;

  for v_po in
    select distinct fl.po_id
    from erp.product_conversion_allocations a
    join erp.fg_lots fl on fl.id=a.source_lot_id
    where a.conversion_id=h.id order by fl.po_id
  loop
    perform erp.propagate_conversion_hpp_for_po(v_po);
    perform erp.refresh_po_hpp_gl_baseline(v_po);
    perform erp.assert_po_hpp_target_book_v2620e(v_po);
  end loop;
end
$function$;
do $grants$
declare t text;f text;
begin
 foreach t in array array['be_execution_context_v1','be_conversion_sources_v1','be_conversion_returns_v1'] loop
   execute format('alter table erp.%I enable row level security',t);
   execute format('revoke all on erp.%I from public,anon,authenticated,service_role',t);
 end loop;
 for f in select p.oid::regprocedure::text from pg_proc p join pg_namespace n on n.oid=p.pronamespace
   where n.nspname='erp' and (p.proname like 'be\_%' or p.proname in('save_product_conversion_action_v1','get_product_conversion_workspace_v1')) loop
   execute format('revoke all on function %s from public,anon,authenticated,service_role',f);
 end loop;
end $grants$;
revoke all on function public.erp_save_product_conversion_action_v1(text,jsonb,uuid) from public,anon;
revoke all on function public.erp_get_product_conversion_workspace_v1(jsonb) from public,anon;
grant execute on function public.erp_save_product_conversion_action_v1(text,jsonb,uuid) to authenticated,service_role;
grant execute on function public.erp_get_product_conversion_workspace_v1(jsonb) to authenticated,service_role;

insert into erp.schema_migrations(version,description) values('v2.6.20be','BE development family: SKU conversion, rework/redye and pocket cutover');
commit;
