-- CP6 AY PO HPP corrections dated from the goods: T1_FAMILY development install (NOT a release package).
-- Generated by scripts/cp6_ay_build.py from the AS definition of erp.sync_po_hpp_to_gl; do not edit by hand.
begin;
set local lock_timeout='10s';set local statement_timeout='240s';set local search_path='';
do $t1_guard$
begin
 if (select count(*) from erp.schema_migrations where version in('v2.6.20av','v2.6.20aw','v2.6.20ax'))<>3 then raise exception 'AY_T1_REQUIRES_AV_AW_AX'; end if;
 if exists(select 1 from erp.schema_migrations where version='v2.6.20ay') or to_regprocedure('erp.po_hpp_gl_leg_add_v1(jsonb,date,numeric,numeric,numeric)') is not null or to_regclass('erp.po_hpp_gl_lot_state_v1') is not null then raise exception 'AY_T1_ALREADY_INSTALLED'; end if;
end $t1_guard$;
create table erp.po_hpp_gl_lot_state_v1(
  lot_id uuid primary key,
  po_id uuid not null,
  hpp_per_pcs numeric not null,
  updated_at timestamptz not null default statement_timestamp());
comment on table erp.po_hpp_gl_lot_state_v1 is 'AY rev4: HPP per piece of each lot as erp.sync_po_hpp_to_gl last posted it (base of the per-lot change of the next sync).';
alter table erp.po_hpp_gl_lot_state_v1 enable row level security;
revoke all on erp.po_hpp_gl_lot_state_v1 from public,anon,authenticated,service_role;
CREATE OR REPLACE FUNCTION erp.po_hpp_gl_leg_add_v1(p_acc jsonb, p_day date, p_fg numeric, p_cogs numeric, p_other numeric)
 RETURNS jsonb
 LANGUAGE sql
 IMMUTABLE
 SET search_path TO ''
AS $function$
-- AY: add one dated leg (FG, COGS, other) to the per-date accumulator of erp.sync_po_hpp_to_gl.
select coalesce(p_acc,'{}'::jsonb)||jsonb_build_object(p_day::text,jsonb_build_object(
  'fg',coalesce((p_acc->(p_day::text)->>'fg')::numeric,0)+coalesce(p_fg,0),
  'cogs',coalesce((p_acc->(p_day::text)->>'cogs')::numeric,0)+coalesce(p_cogs,0),
  'other',coalesce((p_acc->(p_day::text)->>'other')::numeric,0)+coalesce(p_other,0)))
$function$;
revoke all on function erp.po_hpp_gl_leg_add_v1(jsonb,date,numeric,numeric,numeric) from public,anon,authenticated,service_role;
CREATE OR REPLACE FUNCTION erp.sync_po_hpp_to_gl(p_po_id uuid, p_effective_date date DEFAULT ((statement_timestamp() AT TIME ZONE 'Asia/Jakarta'::text))::date)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'erp', 'public'
AS $function$
declare
  t record;
  s erp.po_hpp_gl_state%rowtype;
  v_target_qty integer:=0;
  v_target_hpp numeric(24,6):=0;
  v_target_fg numeric(24,6):=0;
  v_target_cogs numeric(24,6):=0;
  v_target_other numeric(24,6):=0;
  v_df numeric(24,6);v_dc numeric(24,6);v_do numeric(24,6);v_sum numeric(24,6);
  v_lines jsonb:='[]'::jsonb;v_event uuid;v_journal uuid;v_documented_gain numeric(24,6):=0;
  v_acc jsonb:='{}'::jsonb;v_t numeric(24,6);v_q numeric;v_w numeric;v_n integer;v_i integer;v_left numeric(24,6);
  v_amt numeric(24,6);v_last date;v_f numeric(24,6);v_c numeric(24,6);v_o numeric(24,6);v_wip numeric(24,6);r record;
  v_cap date;v_lots jsonb;
begin
  perform erp.require_internal();
  p_effective_date:=coalesce(erp.invoice_recost_economic_date_v1(),p_effective_date);
  perform pg_advisory_xact_lock(hashtextextended('FG_HPP_SALES_V2620C',0));
  select * into t from erp.compute_po_hpp_gl_targets_v2620d(p_po_id);
  select * into s from erp.po_hpp_gl_state where po_id=p_po_id for update;

  if coalesce(t.base_output_qty,0)>0 then
    v_target_qty:=t.base_output_qty;
    -- Cumulative targets, deltas, journal lines, and saved state all use the
    -- same minor-unit values. The balancing bucket receives the deterministic remainder.
    v_target_hpp:=round(coalesce(t.hpp_total_cost,0),2);
    v_target_fg:=round(coalesce(t.fg_value,0),2);
    v_target_cogs:=round(coalesce(t.cogs_value,0),2);
    v_target_other:=v_target_hpp-v_target_fg-v_target_cogs;

    with lot_hpp as(
      select fl.id lot_id,case when coalesce(hv.qty_basis_pcs,0)>0
        then hv.total_cost/hv.qty_basis_pcs else 0 end::numeric hpp_per_pcs
      from erp.fg_lots fl left join erp.hpp_versions hv on hv.lot_id=fl.id and hv.is_current=true
      where fl.po_id=p_po_id and fl.lot_origin<>'VOIDED_PRODUCTION'
    ), adj_net as(
      select fm.lot_id,sum(fm.qty_signed)::numeric qty
      from erp.fg_stock_movements fm join erp.fg_lots fl on fl.id=fm.lot_id
      where fl.po_id=p_po_id and fl.lot_origin<>'VOIDED_PRODUCTION'
        and((fm.movement_type='ADJUSTMENT' and fm.source_type='FG_ADJUSTMENT_ITEM')
          or(fm.movement_type='REVERSAL' and exists(
            select 1 from erp.fg_stock_movements orig where orig.id=fm.reversal_of_id
              and orig.movement_type='ADJUSTMENT' and orig.source_type='FG_ADJUSTMENT_ITEM')))
      group by fm.lot_id
    )
    select coalesce(sum(greatest(a.qty,0)*lh.hpp_per_pcs),0) into v_documented_gain
    from adj_net a join lot_hpp lh on lh.lot_id=a.lot_id;
    if v_target_other < -v_documented_gain-0.01 then
      raise exception 'PO HPP allocation inconsistent: financial FG + net sold exceeds production output without a matching documented positive FG adjustment';
    end if;
  else
    v_target_qty:=0;v_target_hpp:=0;v_target_fg:=0;v_target_cogs:=0;v_target_other:=0;
    if s.po_id is null then return; end if;
  end if;

  v_df:=v_target_fg-round(coalesce(s.fg_value,0),2);
  v_dc:=v_target_cogs-round(coalesce(s.cogs_value,0),2);
  v_do:=v_target_other-round(coalesce(s.other_out_value,0),2);
  v_sum:=v_df+v_dc+v_do;

  -- AY (owner, 24 Sep 2026): the correction reaches FG from the physical date of the goods and COGS from the sale date,
  -- never before the goods existed, with the decided closed/open period rule. Totals per account are exactly the
  -- previous single journal (cents, remainder on the last bucket).
  -- The period rule is applied as before AY when the effective date E is already closed: every leg stays on E, so the
  -- correction is one journal with economic date E that post_journal (erp.resolve_accounting_transaction_date) posts on
  -- the recognition day; no report before that day changes and the economic date is kept. Only an open E moves forward
  -- to the goods (v_cap caps the physical dates at E when E is closed; every date after an open E is open as well; an
  -- open E caps them at today, since the product allows a physical time a few minutes ahead of the clock).
  v_cap:=erp._cp3_business_date(statement_timestamp());
  if exists(select 1 from erp.accounting_period_control c
            where c.singleton_id=1 and c.closed_through is not null and p_effective_date<=c.closed_through) then
    v_cap:=p_effective_date;
  end if;
  v_t:=v_df+v_dc;
  -- AY rev4 (independent review 24 Sep; T1 AZ:MULTI_CUT_* run 35968507694): erp.rebuild_po_hpp allocates material to a
  -- lot by its cutting-group lineage, so lots of one PO change by different amounts per piece; rev3 split the PO change
  -- over the lot dates by pieces and put a later cut's correction on an earlier lot (PO WIP -2.29 on the day between the
  -- cuts). The change of each lot is now its own HPP change since the last sync times its quantity (FG owned + net sold,
  -- as erp.compute_po_hpp_gl_targets_v2620d counts it). The previous HPP is the one this function last posted for the lot
  -- (erp.po_hpp_gl_lot_state_v1) or, for a lot last synced before that table existed, its HPP version current at the
  -- last sync (calculated_at <= the state's updated_at, both statement timestamps); a lot never synced counts from zero.
  select coalesce(jsonb_object_agg(x.id::text,jsonb_build_object('d',x.d,'h',x.h,'dh',x.h-x.o,'q',x.q)),'{}'::jsonb),max(x.d)
  into v_lots,v_last
  from(
    select fl.id,greatest(p_effective_date,least(v_cap,erp._cp3_business_date(fl.produced_at))) d,
      coalesce((select case when coalesce(hv.qty_basis_pcs,0)>0 then hv.total_cost/hv.qty_basis_pcs else 0 end
                from erp.hpp_versions hv where hv.lot_id=fl.id and hv.is_current),0)::numeric h,
      coalesce((select ls.hpp_per_pcs from erp.po_hpp_gl_lot_state_v1 ls where ls.lot_id=fl.id),
               (select case when coalesce(ov.qty_basis_pcs,0)>0 then ov.total_cost/ov.qty_basis_pcs else 0 end
                from erp.hpp_versions ov where ov.lot_id=fl.id and ov.calculated_at<=s.updated_at
                order by ov.calculated_at desc,ov.version_no desc limit 1),0)::numeric o,
      (greatest(coalesce((select sum(fm.qty_signed) from erp.fg_stock_movements fm where fm.lot_id=fl.id),0)
          +coalesce((select sum(abs(fm.qty_signed)) from erp.fg_stock_movements fm where fm.lot_id=fl.id
                     and fm.movement_type='SALE_RESERVE' and not exists(select 1 from erp.fg_stock_movements rv where rv.reversal_of_id=fm.id)),0),0)
       +greatest(coalesce((select sum(a.qty_pcs) from erp.sale_stock_allocations a join erp.sales_items i on i.id=a.sale_item_id
                     join erp.sales_headers h on h.id=i.sale_id where a.lot_id=fl.id and h.status in('POSTED','PARTIAL_PAID','PAID')),0)
          -coalesce((select sum(ri.qty_pcs) from erp.sales_return_items ri join erp.sales_returns h on h.id=ri.return_id
                     where ri.lot_id=fl.id and h.status='POSTED'),0),0))::numeric q
    from erp.fg_lots fl where fl.po_id=p_po_id and fl.lot_origin in('PRODUCTION','CONVERSION')
  ) x;
  v_last:=coalesce(v_last,p_effective_date);
  -- Leg A: FG (and the sold part, moved on in leg B) take each lot's own change on the lot's date; WIP balances each date.
  select count(distinct value->>'d') into v_n from jsonb_each(v_lots);
  if v_n>0 then
    v_i:=0;v_left:=v_t;
    for r in select (value->>'d')::date d,sum((value->>'dh')::numeric*(value->>'q')::numeric) a
      from jsonb_each(v_lots) group by 1 order by 1
    loop
      v_i:=v_i+1;
      v_amt:=case when v_i=v_n then v_left else round(r.a,2) end;
      v_left:=v_left-v_amt;
      v_acc:=erp.po_hpp_gl_leg_add_v1(v_acc,r.d,v_amt,0,0);
    end loop;
  else
    v_acc:=erp.po_hpp_gl_leg_add_v1(v_acc,p_effective_date,v_t,0,0);
  end if;
  v_acc:=erp.po_hpp_gl_leg_add_v1(v_acc,v_last,0,0,v_do);
  -- Leg B: the sold change moves FG -> COGS on the sale (or return) date: each lot's HPP change times the pieces sold
  -- (a posted return is negative) on that date.
  select count(distinct f.d) into v_n from(
    select greatest((l.value->>'d')::date,least(v_cap,erp._cp3_business_date(h.sale_date))) d
    from erp.sale_stock_allocations a join erp.sales_items i on i.id=a.sale_item_id
    join erp.sales_headers h on h.id=i.sale_id join jsonb_each(v_lots) l on l.key=a.lot_id::text
    where h.status in('POSTED','PARTIAL_PAID','PAID')
    union all
    select greatest((l.value->>'d')::date,least(v_cap,erp._cp3_business_date(h.physical_at)))
    from erp.sales_return_items ri join erp.sales_returns h on h.id=ri.return_id join jsonb_each(v_lots) l on l.key=ri.lot_id::text
    where h.status='POSTED') f;
  if v_n>0 then
    v_i:=0;v_left:=v_dc;
    for r in select f.d,sum(f.a) a from(
        select greatest((l.value->>'d')::date,least(v_cap,erp._cp3_business_date(h.sale_date))) d,
               a.qty_pcs::numeric*(l.value->>'dh')::numeric a
        from erp.sale_stock_allocations a join erp.sales_items i on i.id=a.sale_item_id
        join erp.sales_headers h on h.id=i.sale_id join jsonb_each(v_lots) l on l.key=a.lot_id::text
        where h.status in('POSTED','PARTIAL_PAID','PAID')
        union all
        select greatest((l.value->>'d')::date,least(v_cap,erp._cp3_business_date(h.physical_at))),
               -ri.qty_pcs::numeric*(l.value->>'dh')::numeric
        from erp.sales_return_items ri join erp.sales_returns h on h.id=ri.return_id join jsonb_each(v_lots) l on l.key=ri.lot_id::text
        where h.status='POSTED') f
      group by f.d order by f.d
    loop
      v_i:=v_i+1;
      v_amt:=case when v_i=v_n then v_left else round(r.a,2) end;
      v_left:=v_left-v_amt;
      v_acc:=erp.po_hpp_gl_leg_add_v1(v_acc,r.d,-v_amt,v_amt,0);
    end loop;
  elsif abs(v_dc)>0.005 then
    v_acc:=erp.po_hpp_gl_leg_add_v1(v_acc,v_last,-v_dc,v_dc,0);
  end if;
  -- One event and one journal per requested date; WIP balances each date.
  for r in select key::date d,value v from jsonb_each(v_acc) order by 1 loop
    v_f:=(r.v->>'fg')::numeric;v_c:=(r.v->>'cogs')::numeric;v_o:=(r.v->>'other')::numeric;v_wip:=-(v_f+v_c+v_o);
    v_lines:='[]'::jsonb;
    if abs(v_f)>0.005 then v_lines:=v_lines||jsonb_build_array(case when v_f>0
      then jsonb_build_object('mapping_key','FG_INVENTORY','debit',v_f,'credit',0,'po_id',p_po_id)
      else jsonb_build_object('mapping_key','FG_INVENTORY','debit',0,'credit',abs(v_f),'po_id',p_po_id) end); end if;
    if abs(v_c)>0.005 then v_lines:=v_lines||jsonb_build_array(case when v_c>0
      then jsonb_build_object('mapping_key','COGS','debit',v_c,'credit',0,'po_id',p_po_id)
      else jsonb_build_object('mapping_key','COGS','debit',0,'credit',abs(v_c),'po_id',p_po_id) end); end if;
    if abs(v_o)>0.005 then
      if v_o>0 then v_lines:=v_lines||jsonb_build_array(jsonb_build_object(
        'mapping_key','OTHER_EXPENSE','debit',v_o,'credit',0,'po_id',p_po_id));
      else v_lines:=v_lines||jsonb_build_array(jsonb_build_object(
        'mapping_key','OTHER_INCOME','debit',0,'credit',abs(v_o),'po_id',p_po_id)); end if;
    end if;
    if abs(v_wip)>0.005 then v_lines:=v_lines||jsonb_build_array(case when v_wip>0
      then jsonb_build_object('mapping_key','WIP','debit',v_wip,'credit',0,'po_id',p_po_id)
      else jsonb_build_object('mapping_key','WIP','debit',0,'credit',abs(v_wip),'po_id',p_po_id) end); end if;
    if jsonb_array_length(v_lines)>=2 then
      insert into erp.po_hpp_gl_events(po_id,effective_date,old_hpp_total,new_hpp_total,fg_delta,cogs_delta,other_delta)
      values(p_po_id,r.d,round(coalesce(s.hpp_total_cost,0),2),v_target_hpp,v_f,v_c,v_o)
      returning id into v_event;
      v_journal:=erp.post_journal('PO_HPP_GL_SYNC',v_event,r.d,
        'Latest corrected HPP allocation · exact minor-unit targets · dated from the goods',v_lines);
      update erp.po_hpp_gl_events set journal_entry_id=v_journal,
        effective_date=(select transaction_date from erp.journal_entries where id=v_journal) where id=v_event;
    end if;
  end loop;
  -- AY rev4: the HPP this sync posted for each lot, the base of the next sync's per-lot change.
  insert into erp.po_hpp_gl_lot_state_v1(lot_id,po_id,hpp_per_pcs,updated_at)
  select key::uuid,p_po_id,(value->>'h')::numeric,statement_timestamp() from jsonb_each(v_lots)
  on conflict(lot_id) do update set po_id=excluded.po_id,hpp_per_pcs=excluded.hpp_per_pcs,updated_at=excluded.updated_at;

  insert into erp.po_hpp_gl_state(po_id,base_output_qty,hpp_total_cost,fg_value,cogs_value,other_out_value,updated_at)
  values(p_po_id,v_target_qty,v_target_hpp,v_target_fg,v_target_cogs,v_target_other,statement_timestamp())
  on conflict(po_id) do update set base_output_qty=excluded.base_output_qty,
    hpp_total_cost=excluded.hpp_total_cost,fg_value=excluded.fg_value,
    cogs_value=excluded.cogs_value,other_out_value=excluded.other_out_value,updated_at=statement_timestamp();
end
$function$;
insert into erp.schema_migrations(version,description) values('v2.6.20ay','T1_FAMILY development install of AY (PO HPP corrections dated from the goods); not a release package');
commit;
