grant create on schema public,cp7_invoice to cp7_invoice_read,cp7_invoice_write;
alter function cp7_invoice.access_now() owner to cp7_invoice_read;
alter function cp7_invoice.assert_single_receipt(uuid,uuid) owner to cp7_invoice_read;
alter function cp7_invoice.workspace(uuid,integer,integer) owner to cp7_invoice_read;
alter function cp7_invoice.command(text,jsonb,uuid,text) owner to cp7_invoice_write;
alter function cp7_invoice.document_command(text,jsonb,uuid,text) owner to cp7_invoice_write;
alter function cp7_invoice.source_lines(uuid) owner to cp7_invoice_read;
alter function cp7_invoice.sources(uuid,text,integer,integer) owner to cp7_invoice_read;
alter function cp7_invoice.validate_sources(uuid,uuid,jsonb) owner to cp7_invoice_read;
alter function cp7_invoice.assert_document(uuid,uuid,jsonb) owner to cp7_invoice_read;
alter function public.erp_cp7_get_invoice_sources_v1(uuid,text,integer,integer) owner to cp7_invoice_read;
alter function public.erp_cp7_get_purchase_invoices_v1(uuid,integer,integer) owner to cp7_invoice_read;
alter function public.erp_cp7_save_purchase_invoice_v1(text,jsonb,uuid,text) owner to cp7_invoice_write;
revoke create on schema public,cp7_invoice from cp7_invoice_read,cp7_invoice_write;
revoke all on all functions in schema cp7_invoice from public,anon,authenticated,service_role,cp7_capture;
grant execute on function cp7_invoice.access_now(),cp7_invoice.assert_single_receipt(uuid,uuid) to cp7_invoice_write;
grant execute on function cp7_invoice.validate_sources(uuid,uuid,jsonb),cp7_invoice.assert_document(uuid,uuid,jsonb) to cp7_invoice_write;
revoke all on function public.erp_cp7_get_invoice_sources_v1(uuid,text,integer,integer) from public,anon,authenticated,service_role,cp7_capture;
grant execute on function public.erp_cp7_get_invoice_sources_v1(uuid,text,integer,integer) to authenticated;
revoke all on function public.erp_cp7_get_purchase_invoices_v1(uuid,integer,integer),public.erp_cp7_save_purchase_invoice_v1(text,jsonb,uuid,text) from public,anon,authenticated,service_role,cp7_capture;
grant execute on function public.erp_cp7_get_purchase_invoices_v1(uuid,integer,integer),public.erp_cp7_save_purchase_invoice_v1(text,jsonb,uuid,text) to authenticated;
