#!/usr/bin/env python3
"""Generate a disposable local Supabase restore from the CP2 catalog snapshot.

This is test infrastructure only. It never connects to hosted Supabase and never
writes the legacy project. The generated SQL is intentionally not committed.
"""
from __future__ import annotations

import json
from collections import defaultdict
from pathlib import Path

ROOT = Path("restore")


def qi(value: object) -> str:
    return '"' + str(value).replace('"', '""') + '"'


def ql(value: object) -> str:
    return "'" + str(value).replace("'", "''") + "'"


def stmt(value: object) -> str:
    text = str(value).rstrip()
    return text if text.endswith(";") else text + ";"


def topological_views(views: list[dict], dependencies: list[dict]) -> list[dict]:
    by_key = {(v["schema_name"], v["view_name"]): v for v in views}
    deps: dict[tuple[str, str], set[tuple[str, str]]] = defaultdict(set)
    for item in dependencies:
        child = (item["dependent_schema"], item["dependent_name"])
        parent = (item["referenced_schema"], item["referenced_name"])
        if child in by_key and parent in by_key and child != parent:
            deps[child].add(parent)
    pending = set(by_key)
    result: list[dict] = []
    while pending:
        ready = sorted(key for key in pending if not (deps[key] & pending))
        if not ready:
            raise SystemExit("view dependency cycle: " + json.dumps({str(k): list(deps[k] & pending) for k in pending}, indent=2))
        for key in ready:
            result.append(by_key[key])
            pending.remove(key)
    return result


def main() -> None:
    catalog = json.loads((ROOT / "ERP_ENTENG_CATALOG_SNAPSHOT.json").read_text())
    columns_by_table: dict[tuple[str, str], list[dict]] = defaultdict(list)
    for column in catalog["columns"]:
        columns_by_table[(column["schema_name"], column["table_name"])].append(column)

    ddl = [
        r"\set ON_ERROR_STOP on",
        "set client_min_messages=warning;",
        "create extension if not exists pgcrypto with schema extensions;",
        'create extension if not exists "uuid-ossp" with schema extensions;',
        "create extension if not exists pg_stat_statements with schema extensions;",
        "create extension if not exists supabase_vault with schema vault;",
        "create extension if not exists pg_cron with schema pg_catalog;",
        "drop schema if exists erp cascade;",
        "create schema erp authorization postgres;",
    ]

    for custom_type in catalog["custom_types"]:
        schema = qi(custom_type["schema_name"])
        name = qi(custom_type["type_name"])
        if custom_type["typtype"] == "e":
            labels = ",".join(ql(label) for label in custom_type["enum_labels"])
            ddl.append(f"create type {schema}.{name} as enum ({labels});")
        elif custom_type["typtype"] == "d":
            text = f"create domain {schema}.{name} as {custom_type['domain_base_type']}"
            if custom_type["domain_default"]:
                text += f" default {custom_type['domain_default']}"
            if custom_type["domain_not_null"]:
                text += " not null"
            ddl.append(text + ";")

    for sequence in catalog["sequences"]:
        ddl.append(
            f"create sequence {qi(sequence['schema_name'])}.{qi(sequence['sequence_name'])} "
            f"as {sequence['data_type']} increment by {sequence['seqincrement']} minvalue {sequence['seqmin']} "
            f"maxvalue {sequence['seqmax']} start with {sequence['seqstart']} cache {sequence['seqcache']}"
            + (" cycle;" if sequence["seqcycle"] else " no cycle;")
        )
        ddl.append(
            f"alter sequence {qi(sequence['schema_name'])}.{qi(sequence['sequence_name'])} "
            f"owner to {qi(sequence['owner_name'])};"
        )

    for table in catalog["tables"]:
        key = (table["schema_name"], table["table_name"])
        definitions = []
        for column in columns_by_table[key]:
            suffix = ""
            if column["attgenerated"] == "s":
                suffix += f" generated always as ({column['default_expression']}) stored"
            elif column["attidentity"] == "a":
                suffix += " generated always as identity"
            elif column["attidentity"] == "d":
                suffix += " generated by default as identity"
            elif column["default_expression"]:
                suffix += f" default {column['default_expression']}"
            if column["not_null"]:
                suffix += " not null"
            definitions.append(f"{qi(column['column_name'])} {column['data_type']}{suffix}")
        ddl.append(
            f"create table {qi(table['schema_name'])}.{qi(table['table_name'])} (\n  "
            + ",\n  ".join(definitions)
            + "\n);"
        )
        ddl.append(
            f"alter table {qi(table['schema_name'])}.{qi(table['table_name'])} "
            f"owner to {qi(table['owner_name'])};"
        )

    for constraint in catalog["constraints"]:
        ddl.append(
            f"alter table only {qi(constraint['schema_name'])}.{qi(constraint['table_name'])} "
            f"add constraint {qi(constraint['constraint_name'])} {constraint['definition']};"
        )
    for index in catalog["indexes"]:
        ddl.append(stmt(index["definition"]))

    # Bodies may reference views/functions created later; validate them after the
    # full catalog exists by exercising the actual CP3 migration and fixtures.
    ddl.append("set check_function_bodies=off;")
    for function in catalog["functions"]:
        ddl.append(stmt(function["definition"]))
        ddl.append(
            f"alter function {qi(function['schema_name'])}.{qi(function['function_name'])}"
            f"({function['identity_arguments']}) owner to {qi(function['owner_name'])};"
        )
    ddl.append("set check_function_bodies=on;")

    for view in topological_views(catalog["views"], catalog["view_dependencies"]):
        options = ""
        if view["reloptions"]:
            options = " with (" + ",".join(view["reloptions"]) + ")"
        ddl.append(
            f"create or replace view {qi(view['schema_name'])}.{qi(view['view_name'])}{options} as\n"
            f"{view['definition']};"
        )
        ddl.append(
            f"alter view {qi(view['schema_name'])}.{qi(view['view_name'])} owner to {qi(view['owner_name'])};"
        )

    for trigger in catalog["triggers"]:
        ddl.append(stmt(trigger["definition"]))
    for table in catalog["tables"]:
        relation = f"{qi(table['schema_name'])}.{qi(table['table_name'])}"
        if table["rls_enabled"]:
            ddl.append(f"alter table {relation} enable row level security;")
        if table["rls_forced"]:
            ddl.append(f"alter table {relation} force row level security;")

    for policy in catalog["policies"]:
        roles = ", ".join("public" if str(role).lower() == "public" else qi(role) for role in policy["roles"])
        permissive = "permissive" if str(policy["permissive"]).upper() == "PERMISSIVE" else "restrictive"
        text = (
            f"create policy {qi(policy['policy_name'])} on {qi(policy['schema_name'])}.{qi(policy['table_name'])} "
            f"as {permissive} for {str(policy['cmd']).lower()} to {roles}"
        )
        if policy["qual"]:
            text += f" using ({policy['qual']})"
        if policy["with_check"]:
            text += f" with check ({policy['with_check']})"
        ddl.append(text + ";")

    for grant in catalog["table_grants"]:
        grantee = "public" if str(grant["grantee"]).upper() == "PUBLIC" else qi(grant["grantee"])
        text = (
            f"grant {grant['privilege_type']} on table {qi(grant['schema_name'])}.{qi(grant['table_name'])} "
            f"to {grantee}"
        )
        if grant["is_grantable"] == "YES":
            text += " with grant option"
        ddl.append(text + ";")
    for grant in catalog["routine_grants"]:
        grantee = "public" if str(grant["grantee"]).upper() == "PUBLIC" else qi(grant["grantee"])
        ddl.append(
            f"grant {grant['privilege_type']} on function {qi(grant['schema_name'])}.{qi(grant['routine_name'])}"
            f"({grant['identity_arguments']}) to {grantee};"
        )

    ddl.append("select cron.unschedule(jobid) from cron.job;")
    for job in catalog["cron_jobs"]:
        ddl.append(f"select cron.schedule({ql(job['jobname'])},{ql(job['schedule'])},{ql(job['command'])});")
        if not job["active"]:
            ddl.append(f"update cron.job set active=false where jobname={ql(job['jobname'])};")
    ddl.append("notify pgrst,'reload schema';")
    (ROOT / "cp3-catalog-schema-restore.sql").write_text("\n\n".join(ddl) + "\n")


if __name__ == "__main__":
    main()
