#!/usr/bin/env python3
"""Render a reviewed CP3 migration into an outer-rollback fixture.

The transform is deliberately fail-closed:
- exact SHA-256 and byte length are mandatory inputs;
- UTF-8/LF bytes only;
- exactly one standalone BEGIN and one standalone COMMIT;
- COMMIT must be the last executable line;
- exactly one supported CP3 migration-ledger insertion marker;
- output records source/output digests and transformed line indexes.

This tool does not parse or rewrite arbitrary SQL. It only removes the exact
outer transaction statements from bytes whose identity has already been reviewed.
"""

from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path
import re
import sys


SUPPORTED_LEDGER_VERSIONS = frozenset({"v2.6.14a", "v2.6.14b", "v2.6.14c", "v2.6.14d"})
LEDGER_INSERT_RE = re.compile(
    r"\binsert\s+into\s+erp\.schema_migrations\s*"
    r"\(\s*version\s*,\s*description\s*,\s*installed_at\s*\)\s*"
    r"values\s*\(\s*'([^']+)'",
    re.IGNORECASE | re.DOTALL,
)


def sha256(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def executable_lines(lines: list[str]) -> list[tuple[int, str]]:
    result: list[tuple[int, str]] = []
    in_block_comment = False
    for index, line in enumerate(lines):
        stripped = line.strip()
        if in_block_comment:
            if "*/" in stripped:
                in_block_comment = False
                stripped = stripped.split("*/", 1)[1].strip()
            else:
                continue
        while stripped.startswith("/*"):
            if "*/" not in stripped:
                in_block_comment = True
                stripped = ""
                break
            stripped = stripped.split("*/", 1)[1].strip()
        if not stripped or stripped.startswith("--"):
            continue
        result.append((index, stripped))
    return result


def render(source: Path, expected_sha: str, expected_bytes: int, output: Path, report: Path) -> None:
    raw = source.read_bytes()
    actual_sha = sha256(raw)
    if actual_sha != expected_sha.lower():
        raise ValueError(f"source sha256 mismatch: expected {expected_sha}, actual {actual_sha}")
    if len(raw) != expected_bytes:
        raise ValueError(f"source byte-length mismatch: expected {expected_bytes}, actual {len(raw)}")
    if b"\r" in raw:
        raise ValueError("source contains CR/CRLF; reviewed bytes require LF-only encoding")
    try:
        text = raw.decode("utf-8")
    except UnicodeDecodeError as exc:
        raise ValueError("source is not valid UTF-8") from exc

    lines = text.splitlines(keepends=True)
    executable = executable_lines([line.rstrip("\n") for line in lines])
    begin_lines = [index for index, value in executable if value.lower() == "begin;"]
    commit_lines = [index for index, value in executable if value.lower() == "commit;"]
    if len(begin_lines) != 1:
        raise ValueError(f"expected exactly one standalone BEGIN; found {len(begin_lines)}")
    if len(commit_lines) != 1:
        raise ValueError(f"expected exactly one standalone COMMIT; found {len(commit_lines)}")
    if executable[-1][0] != commit_lines[0]:
        raise ValueError("standalone COMMIT is not the terminal executable statement")
    if begin_lines[0] >= commit_lines[0]:
        raise ValueError("BEGIN must precede terminal COMMIT")

    ledger_versions = LEDGER_INSERT_RE.findall(text)
    if len(ledger_versions) != 1:
        raise ValueError(f"expected exactly one CP3 ledger marker; found {len(ledger_versions)}")
    ledger_version = ledger_versions[0].lower()
    if ledger_version not in SUPPORTED_LEDGER_VERSIONS:
        raise ValueError(f"CP3 ledger version is absent or unsupported: {ledger_versions[0]!r}")

    body = [line for index, line in enumerate(lines) if index not in {begin_lines[0], commit_lines[0]}]
    rendered_text = (
        "-- GENERATED BY scripts/cp3_render_reviewed_rollback.py\n"
        f"-- SOURCE_SHA256: {actual_sha}\n"
        f"-- SOURCE_BYTES: {len(raw)}\n"
        "\\set ON_ERROR_STOP on\n"
        "begin;\n"
        + "".join(body)
        + "\nrollback;\n"
    )
    rendered = rendered_text.encode("utf-8")
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_bytes(rendered)

    payload = {
        "status": "PASS",
        "source": str(source),
        "source_sha256": actual_sha,
        "source_bytes": len(raw),
        "begin_line_1_based": begin_lines[0] + 1,
        "terminal_commit_line_1_based": commit_lines[0] + 1,
        "ledger_marker_count": len(ledger_versions),
        "ledger_version": ledger_version,
        "output": str(output),
        "output_sha256": sha256(rendered),
        "output_bytes": len(rendered),
    }
    report.parent.mkdir(parents=True, exist_ok=True)
    report.write_text(json.dumps(payload, indent=2, sort_keys=True) + "\n", encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--source", required=True, type=Path)
    parser.add_argument("--expected-sha256", required=True)
    parser.add_argument("--expected-bytes", required=True, type=int)
    parser.add_argument("--output", required=True, type=Path)
    parser.add_argument("--report", required=True, type=Path)
    args = parser.parse_args()
    try:
        render(args.source, args.expected_sha256, args.expected_bytes, args.output, args.report)
    except Exception as exc:  # fail closed with one useful line for CI
        print(f"CP3_RENDER_FAIL: {exc}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
