#!/usr/bin/env python3
"""Build the AX T1 family install: finished goods entering without a production source (owner §15.1-FG, §19.2).

Label T1_FAMILY (owner decision A+B): a development install for targeted family tests on the disposable chain
AN -> AU -> AV -> AW. Not a release package: no capsule, no rollback file, no closed admission. Evidence produced with
it must never be cited as release evidence.

The new table has no product column on purpose: the AV coverage registry classifies every product reference, and the
product of a receipt is the product of its lot.
Usage: python3 scripts/cp6_ax_build.py            # writes supabase/dev/cp6_ax_t1_family.sql
       python3 scripts/cp6_ax_build.py --check
"""
from pathlib import Path
import hashlib,re,sys

ROOT=Path(__file__).resolve().parents[1]
OUT=ROOT/'supabase/dev/cp6_ax_t1_family.sql'
SOURCE=ROOT/'scripts/cp6_ax_functions.sql'
VERSION='v2.6.20ax'
TABLE='fg_unsourced_receipts_v1'
PRIVATE=['erp.guard_fg_unsourced_receipt_immutable_v1()','erp.fg_unsourced_valuation_v1(uuid,timestamp with time zone)',
         'erp.post_fg_unsourced_receipt_v1(jsonb,uuid)','erp.reverse_fg_unsourced_receipt_v1(uuid,text,uuid)']
PUBLIC=['public.erp_preview_fg_unsourced_value_v1(uuid,timestamp with time zone)','public.erp_post_fg_unsourced_receipt_v1(jsonb,uuid)',
        'public.erp_reverse_fg_unsourced_receipt_v1(uuid,text,uuid)']

SCHEMA=f"""create table erp.{TABLE} (
  id uuid primary key default gen_random_uuid(),
  source_kind text not null check (source_kind in('FOUND_AT_OPNAME','GOOD_FROM_UNSOURCED_BS','REDYE_MIXED')),
  lot_id uuid not null unique references erp.fg_lots(id),
  bs_case_id uuid references erp.bs_cases(id),
  bs_resolution_id uuid,
  location_id uuid not null references erp.locations(id),
  quality_grade text not null,
  qty_pcs integer not null check (qty_pcs>0),
  physical_at timestamptz not null,
  unit_value numeric(18,2) not null check (unit_value>=0 and unit_value<>'NaN'::numeric),
  total_value numeric(20,2) not null check (total_value>=0 and total_value<>'NaN'::numeric),
  valuation jsonb not null check (valuation ? 'tier'),
  reason text not null check (length(btrim(reason))>0),
  status text not null default 'POSTED' check (status in('POSTED','REVERSED')),
  journal_entry_id uuid references erp.journal_entries(id),
  movement_id uuid not null,
  created_by uuid,
  created_at timestamptz not null default statement_timestamp(),
  reversed_by uuid,
  reversed_at timestamptz,
  reversal_reason text,
  check ((source_kind='GOOD_FROM_UNSOURCED_BS')=(bs_case_id is not null)),
  check ((status='REVERSED')=(reversed_at is not null))
);
alter table erp.{TABLE} enable row level security;
revoke all on erp.{TABLE} from public,anon,authenticated,service_role;
create index idx_{TABLE}_bs_case on erp.{TABLE}(bs_case_id) where bs_case_id is not null;
"""

TRIGGERS=f"""create trigger trg_guard_{TABLE}_immutable before update or delete on erp.{TABLE}
  for each row execute function erp.guard_fg_unsourced_receipt_immutable_v1();
create trigger trg_guard_{TABLE}_truncate before truncate on erp.{TABLE}
  for each statement execute function erp.guard_fg_unsourced_receipt_immutable_v1();
"""


def functions():
    text=SOURCE.read_text()
    parts=re.split(r'(?=^CREATE OR REPLACE FUNCTION )',text,flags=re.M)
    out=[p.rstrip()+'\n' for p in parts if p.startswith('CREATE OR REPLACE FUNCTION ')]
    assert len(out)==len(PRIVATE)+len(PUBLIC),len(out)
    return out


def build():
    parts=['-- CP6 AX finished goods without a production source: T1_FAMILY development install (NOT a release package).',
           '-- Generated by scripts/cp6_ax_build.py from scripts/cp6_ax_functions.sql; do not edit by hand.',
           'begin;',"set local lock_timeout='10s';set local statement_timeout='240s';set local search_path='';",
           'do $t1_guard$','begin',
           " if (select count(*) from erp.schema_migrations where version in('v2.6.20av','v2.6.20aw'))<>2 then raise exception 'AX_T1_REQUIRES_AV_AND_AW'; end if;",
           f" if exists(select 1 from erp.schema_migrations where version='{VERSION}') or to_regclass('erp.{TABLE}') is not null then raise exception 'AX_T1_ALREADY_INSTALLED'; end if;",
           'end $t1_guard$;',SCHEMA.strip()]
    parts+=[f.rstrip()+';' for f in functions()]
    parts.append(TRIGGERS.strip())
    for key in PRIVATE:parts.append(f'revoke all on function {key} from public,anon,authenticated,service_role;')
    for key in PUBLIC:parts+=[f'revoke all on function {key} from public,anon;',f'grant execute on function {key} to authenticated,service_role;']
    parts+=["do $coverage$ begin perform erp.assert_new_stock_cutoff_coverage_v1(); end $coverage$;",
            f"insert into erp.schema_migrations(version,description) values('{VERSION}',"
            "'T1_FAMILY development install of AX (finished goods without a production source); not a release package');",'commit;','']
    return '\n'.join(parts)


if __name__=='__main__':
    text=build()
    if '--check' in sys.argv:
        assert OUT.read_text()==text,'supabase/dev/cp6_ax_t1_family.sql is stale; rerun scripts/cp6_ax_build.py'
        print('fresh',hashlib.sha256(text.encode()).hexdigest())
    else:
        OUT.parent.mkdir(parents=True,exist_ok=True);OUT.write_text(text)
        print(OUT.relative_to(ROOT),len(text),hashlib.sha256(text.encode()).hexdigest())
