#!/usr/bin/env python3
"""G-01 option 1 (owner decision 23 Sep 2026): align the disposable test baseline with hosted Enteng.

Only the definitions that differ are changed, from read-only hosted metadata kept in
docs/evidence/cp6-g01/hosted_alignment_metadata.json (every text verified by md5):
  * 23 CHECK constraints and 5 views: same meaning, different stored text. Postgres keeps a varchar IN list as
    `(col)::text = ANY ((ARRAY['a'::character varying])::text[])`, but re-parsing that deparsed text (the CP4.5a
    fixture stores it) pushes the cast into every element. The hosted form comes back from the IN-list source,
    so the source is rebuilt as IN / NOT IN and the resulting catalog text is compared with the hosted md5.
  * sequences: the fixture restore left a standalone `<t>_id_seq` next to the identity sequence `<t>_id_seq1`
    for two identity columns, and two serial sequences are not OWNED BY their columns.
  * schema erp: hosted grants USAGE to authenticated and service_role.

It runs only on the local disposable endpoint (asserted) and never on hosted. Label: G01_ALIGNMENT (test side only).

Usage: python scripts/cp6_g01_align.py sql            # print the alignment SQL
       python scripts/cp6_g01_align.py apply OUT.json # apply on $PGURL (disposable only) and verify per object
"""
from pathlib import Path
import hashlib,json,os,re,sys

ROOT=Path(__file__).resolve().parents[1]
META=ROOT/'docs/evidence/cp6-g01/hosted_alignment_metadata.json'
LOCAL='postgresql://postgres:postgres@127.0.0.1:54322/postgres'
ANY=re.compile(r"\(\(([\w.]+)\)::text (= ANY|<> ALL) \(\((ARRAY\[[^\]]*\])\)::text\[\]\)\)")
EQ=re.compile(r"\(\(([\w.]+)\)::text (=|<>) '([^']*)'::text\)")


def to_source(text):
    """Rebuild the IN-list source whose parse gives the hosted deparse (see module docstring)."""
    def arr(m):
        values=re.findall(r"'([^']*)'::character varying",m.group(3))
        op='IN' if m.group(2)=='= ANY' else 'NOT IN'
        return "(%s %s (%s))"%(m.group(1),op,", ".join("'%s'"%v for v in values))
    return ANY.sub(arr,text)


def check_source(text):
    return EQ.sub(lambda m:"(%s %s '%s')"%(m.group(1),m.group(2),m.group(3)),to_source(text))


def load():
    meta=json.loads(META.read_text())
    for c in meta['constraints']:
        assert hashlib.md5(('c|'+c['def']+'|true').encode()).hexdigest()[:10]==c['md5_prefix'],c['key']
    for v in meta['views']:assert hashlib.md5(v['def'].encode()).hexdigest()==v['md5'],v['view']
    return meta


def sql(meta):
    out=["-- G-01 alignment of the disposable test baseline with hosted Enteng (generated by scripts/cp6_g01_align.py).",
         "set local lock_timeout='10s';"]
    for c in meta['constraints']:
        table,name=c['key'].split('.')
        out.append('alter table erp.%s drop constraint %s, add constraint %s %s;'%(table,name,name,check_source(c['def'])))
    for v in meta['views']:
        body=to_source(v['def']).strip().rstrip(';')
        out.append('create or replace view %s with (%s) as\n%s;'%(v['view'],','.join(v['reloptions']),body))
    for s in meta['sequences']['identity']:
        seq=s['sequence'];extra=seq+'1'
        # The standalone twin must be unused (no DEFAULT depends on it): DROP without CASCADE fails closed otherwise.
        out.append('drop sequence %s;'%seq)
        out.append('alter sequence %s rename to %s;'%(extra,seq.split('.')[1]))
    for s in meta['sequences']['owned_by']:
        out.append('alter sequence %s owned by %s;'%(s['sequence'],s['column']))
    out.append('grant usage on schema erp to authenticated,service_role;')
    return '\n'.join(out)+'\n'


VERIFY=r"""
select jsonb_build_object(
 'constraints',(select jsonb_object_agg(c.relname||'.'||co.conname,left(md5(co.contype::text||'|'||pg_get_constraintdef(co.oid)||'|'||co.convalidated),10))
   from pg_constraint co join pg_class c on c.oid=co.conrelid join pg_namespace n on n.oid=c.relnamespace
   where n.nspname='erp' and c.relname||'.'||co.conname=any(%(constraints)s)),
 'views',(select jsonb_object_agg(n.nspname||'.'||c.relname,md5(pg_get_viewdef(c.oid)))
   from pg_class c join pg_namespace n on n.oid=c.relnamespace where n.nspname||'.'||c.relname=any(%(views)s)),
 'sequences',(select jsonb_agg(jsonb_build_object('seq',n.nspname||'.'||c.relname,'owned',(select d.deptype::text||':'||n2.nspname||'.'||dc.relname||'.'||da.attname
      from pg_depend d join pg_class dc on dc.oid=d.refobjid join pg_namespace n2 on n2.oid=dc.relnamespace
      join pg_attribute da on da.attrelid=d.refobjid and da.attnum=d.refobjsubid
      where d.classid='pg_class'::regclass and d.objid=c.oid and d.deptype in('a','i') limit 1)) order by c.relname)
   from pg_class c join pg_namespace n on n.oid=c.relnamespace where c.relkind='S' and n.nspname in('erp','public')),
 'schema_erp',(select string_agg(v,',' order by v) from (select case a.grantee when 0 then 'PUBLIC' else pg_get_userbyid(a.grantee)::text end
      ||':'||a.privilege_type||':'||a.is_grantable v from pg_namespace s,aclexplode(coalesce(s.nspacl,acldefault('n',s.nspowner))) a
      where s.nspname='erp') z))
"""


def apply(out):
    import psycopg
    assert os.environ.get('PGURL')==LOCAL,'G01_ALIGN_DISPOSABLE_ENDPOINT_ONLY'
    meta=load();text=sql(meta)
    with psycopg.connect(LOCAL) as conn,conn.cursor() as cur:
        cur.execute(text,prepare=False)
        got=cur.execute(VERIFY,dict(constraints=[c['key'] for c in meta['constraints']],views=[v['view'] for v in meta['views']])).fetchone()[0]
        conn.commit()
    want_c={c['key']:c['md5_prefix'] for c in meta['constraints']};want_v={v['view']:v['md5'] for v in meta['views']}
    hosted_seq={s['sequence']:s['deptype']+':'+s['column'] for s in meta['sequences']['identity']+meta['sequences']['owned_by']}
    got_seq={s['seq']:s['owned'] for s in got['sequences']}
    report=dict(label='G01_ALIGNMENT',sql_sha256=hashlib.sha256(text.encode()).hexdigest(),
                constraints={k:dict(hosted=v,aligned=got['constraints'].get(k)) for k,v in want_c.items()},
                views={k:dict(hosted=v,aligned=got['views'].get(k)) for k,v in want_v.items()},
                sequences=dict(aligned=got_seq,hosted_owned=hosted_seq,hosted_count=meta['sequences']['hosted_count']),
                schema_erp=dict(hosted=meta['schema_acl']['erp'],aligned=got['schema_erp']))
    report['constraints_equal']=all(r['hosted']==r['aligned'] for r in report['constraints'].values())
    report['views_equal']=all(r['hosted']==r['aligned'] for r in report['views'].values())
    report['sequences_equal']=(len(got_seq)==meta['sequences']['hosted_count']
        and all(got_seq.get(k)==v for k,v in hosted_seq.items())
        and all(got_seq.get(k) is None for k in meta['sequences']['standalone']))
    report['schema_equal']=report['schema_erp']['hosted']==report['schema_erp']['aligned']
    report['status']='ALIGNED_PER_OBJECT' if all(report[k] for k in ('constraints_equal','views_equal','sequences_equal','schema_equal')) else 'DIFFERENCES_REMAIN'
    Path(out).write_text(json.dumps(report,indent=2)+'\n')
    print(json.dumps({k:report[k] for k in ('status','constraints_equal','views_equal','sequences_equal','schema_equal')}))
    return 0 if report['status']=='ALIGNED_PER_OBJECT' else 1


if __name__=='__main__':
    if sys.argv[1]=='sql':print(sql(load()),end='')
    elif sys.argv[1]=='apply':raise SystemExit(apply(sys.argv[2]))
    else:raise SystemExit(__doc__)
