"""Candidate AU successor (AV) for AU-R1: one NEW_STOCK physical cutoff source.

Built exactly like AU from AU's own pinned model: the predecessor catalog is the
complete AU installed catalog, every earlier capsule and platform row is
re-checked, and the only catalog delta is one replaced function plus two new
private functions. The migration timestamp is chosen here, not generated by the
Supabase CLI; CLI provenance is therefore NOT_TESTED for this candidate.
"""
from pathlib import Path
import copy,json
import cp6_ao_ap_build as package
import cp6_ao_ap_inventory as inventory
import cp6_au_build as predecessor
import cp6_au_runtime as predecessor_runtime
from cp6_au_r1_definitions import OLD,FUNCTIONS,NEW_FUNCTIONS,PRIVATE_ACL,HELPER,COVERAGE

ROOT=Path(__file__).resolve().parents[1]
STAMP='20260923090000'
NAME='erp_v2_6_20av_cp6_new_stock_physical_cutoff'
VERSION='v2.6.20av'
CAP='erp.cp6_v2620av_rollback_capsule'
# Pins store repo-relative paths; IO resolves against this checkout because the
# probe runs from the frozen AU writer directory.
MIGRATION_REL=f'supabase/migrations/{STAMP}_{NAME}.sql'
ROLLBACK_REL=f'supabase/rollbacks/{STAMP}_{NAME}.rollback.sql'
MIGRATION=ROOT/MIGRATION_REL
ROLLBACK=ROOT/ROLLBACK_REL
PINS=ROOT/'docs/evidence/cp6-av-pins.json'
DEFINITIONS=ROOT/'scripts/cp6_au_r1_definitions.py'
q,j,sha=package.q,package.j,inventory.sha
INVENTORY_SQL=predecessor.INVENTORY_SQL.replace("'cp6_v2620au_rollback_capsule')","'cp6_v2620au_rollback_capsule','cp6_v2620av_rollback_capsule')")
assert INVENTORY_SQL!=predecessor.INVENTORY_SQL
assert STAMP>predecessor.STAMP


def model():
    assert sha(predecessor.PINS.read_bytes())==predecessor_runtime.EXPECTED_PINS
    au=json.loads(predecessor.PINS.read_text())
    assert sha(Path(predecessor.__file__).read_bytes())==au['builder_sha256']
    for key in ('migration','rollback'):assert sha(Path(au[key]).read_bytes())==au[key+'_sha256']
    base,capture,_,before,_=predecessor.model();after=copy.deepcopy(before);functions=[]
    for identity,new in FUNCTIONS.items():
        original=before['functions'][identity];old=OLD[identity]
        assert sha(old)==original['sha256']
        assert sha(json.dumps([old,original['owner'],original['acl']],ensure_ascii=False))==before['objects']['FUNCTION:'+identity]
        after['functions'][identity]=dict(original,sha256=sha(new))
        after['objects']['FUNCTION:'+identity]=sha(json.dumps([new,original['owner'],original['acl']],ensure_ascii=False))
        functions.append(dict(identity=identity,predecessor_sha256=sha(old),installed_sha256=sha(new),owner=original['owner'],acl=original['acl']))
    for identity,new in NEW_FUNCTIONS.items():
        assert identity not in before['functions'] and 'FUNCTION:'+identity not in before['objects']
        after['functions'][identity]=dict(sha256=sha(new),owner='postgres',acl=PRIVATE_ACL)
        after['objects']['FUNCTION:'+identity]=sha(json.dumps([new,'postgres',PRIVATE_ACL],ensure_ascii=False))
    pin=dict(version=VERSION,stamp=STAMP,name=NAME,migration=MIGRATION_REL,rollback=ROLLBACK_REL,capsule=CAP,previous='AU',
             functions=functions,new_functions=[dict(identity=i,installed_sha256=sha(d),owner='postgres',acl=PRIVATE_ACL) for i,d in NEW_FUNCTIONS.items()])
    return base,capture,before,after,pin,au


def guard(objects,label):
    return package.guard(objects,label).replace(inventory.INVENTORY_SQL,INVENTORY_SQL)


def prior_guard(base,capture,au):
    return predecessor.prior_guard(base,capture)+package.capsule_guard('AU',au)+f"""do $au_platform$ begin
 if not exists(select 1 from erp.schema_migrations where version={q(au['version'])})
  or (select count(*) from supabase_migrations.schema_migrations where name={q(au['name'])})<>1
  or not exists(select 1 from supabase_migrations.schema_migrations where version={q(au['stamp'])} and name={q(au['name'])}
   and encode(extensions.digest(convert_to(array_to_string(statements,E'\\n'),'UTF8'),'sha256'),'hex')={q(au['migration_sha256'])})
 then raise exception 'AV_PRIOR_AU_PLATFORM_DRIFT';end if;
end $au_platform$;
"""


def build():
    base,capture,before,after,pin,au=model();cap_name=CAP.split('.')[1]
    s='-- CP6 AV candidate (AU-R1): the successor cutoff reads every NEW_STOCK physical fact.\n'+package.START
    s+=f"""do $admission$ begin
 if exists(select 1 from erp.schema_migrations where version={q(VERSION)}) or to_regclass({q(CAP)}) is not null
  or to_regprocedure({q(HELPER)}) is not null or to_regprocedure({q(COVERAGE)}) is not null
  or exists(select 1 from supabase_migrations.schema_migrations where version>{q(au['stamp'])})
 then raise exception 'AV_EXACT_AU_WITHOUT_SUCCESSOR_REQUIRED';end if;
end $admission$;
"""+guard(before['objects'],'AV_PREDECESSOR')+prior_guard(base,capture,au)
    s+=f"""create table {CAP}(like erp.cp6_v2620an_rollback_capsule including all);
alter table {CAP} enable row level security;
revoke all on {CAP} from public,anon,authenticated,service_role;
insert into {CAP}(object_identity,object_regidentity,object_definition,definition_sha256,acl_snapshot,owner_snapshot)
select format('%I.%I(%s)',n.nspname,p.proname,pg_get_function_identity_arguments(p.oid)),i.identity,pg_get_functiondef(p.oid),
 encode(extensions.digest(convert_to(pg_get_functiondef(p.oid),'UTF8'),'sha256'),'hex'),
 array(select a::text from unnest(p.proacl)a order by a::text),pg_get_userbyid(p.proowner)
from unnest(array[{','.join(q(i) for i in FUNCTIONS)}]) i(identity)
join pg_proc p on p.oid=i.identity::regprocedure join pg_namespace n on n.oid=p.pronamespace;
do $before_data$ declare v_table text;v_hash jsonb;v_before jsonb; begin
 {package.data_sql('v_before',['schema_migrations',cap_name])}
 update {CAP} set boundary_snapshot=jsonb_build_object('before',v_before,'platform_before',{package.history_hash('supabase_migrations','schema_migrations')},'markers_before',{package.history_hash('erp','schema_migrations')});
end $before_data$;
"""
    for identity,new in NEW_FUNCTIONS.items():
        s+=new.rstrip('\n')+';\n'+f'revoke all on function {identity} from public,anon,authenticated,service_role;\n'
    s+=''.join(new.rstrip('\n')+';\n' for new in FUNCTIONS.values())+guard(after['objects'],'AV_INSTALLED')
    s+=f"""update {CAP} set installed_definition_sha256=encode(extensions.digest(convert_to(pg_get_functiondef(to_regprocedure(object_regidentity)),'UTF8'),'sha256'),'hex');
do $after_data$ declare v_table text;v_hash jsonb;v_after jsonb; begin
 {package.data_sql('v_after',['schema_migrations',cap_name])}
 if v_after is distinct from (select boundary_snapshot->'before' from {CAP} limit 1) then raise exception 'AV_INSTALL_CHANGED_DATA';end if;
 update {CAP} set boundary_snapshot=boundary_snapshot||jsonb_build_object('after',v_after);
end $after_data$;
do $coverage$ begin perform {COVERAGE.replace('()','')}();end $coverage$;
insert into erp.schema_migrations(version,description) values({q(VERSION)},'Successor cutoff covers every NEW_STOCK physical fact (AU-R1 candidate)');
"""+package.capsule_guard('AV',pin)+'commit;\n'
    MIGRATION.write_text(s);pin['migration_sha256']=sha(s)
    s='-- CP6 AV candidate: exact pre-use restore to AU under closed admission.\n'+package.START
    s+=f"""do $platform$ begin
 if not exists(select 1 from erp.schema_migrations where version={q(VERSION)})
  or (select count(*) from supabase_migrations.schema_migrations where name={q(NAME)})<>1
  or not exists(select 1 from supabase_migrations.schema_migrations where version={q(STAMP)} and name={q(NAME)}
   and encode(extensions.digest(convert_to(array_to_string(statements,E'\\n'),'UTF8'),'sha256'),'hex')={q(pin['migration_sha256'])})
  or exists(select 1 from supabase_migrations.schema_migrations where version>{q(STAMP)})
 then raise exception 'AV_ROLLBACK_PLATFORM_OR_SUCCESSOR';end if;
end $platform$;
"""+guard(after['objects'],'AV_ROLLBACK')+prior_guard(base,capture,au)+package.capsule_guard('AV',pin)
    s+=f"""create temporary table cp6_av_restore_boundary on commit drop as select boundary_snapshot from {CAP} limit 1;
do $pre_use$ declare v_table text;v_hash jsonb;v_after jsonb;b jsonb; begin
 select boundary_snapshot into b from {CAP} limit 1;
 {package.data_sql('v_after',['schema_migrations',cap_name])}
 if v_after is distinct from b->'after' then raise exception 'AV_POST_USE_ROLLBACK_REFUSED';end if;
 if {package.history_hash('supabase_migrations','schema_migrations','version='+q(STAMP))} is distinct from b->>'platform_before'
  or {package.history_hash('erp','schema_migrations','version='+q(VERSION))} is distinct from b->>'markers_before'
 then raise exception 'AV_PRIOR_HISTORY_DRIFT';end if;
end $pre_use$;
do $restore_function$ declare r record; begin for r in select object_definition from {CAP} order by object_regidentity loop execute r.object_definition;end loop;end $restore_function$;
{''.join(f'drop function {i};'+chr(10) for i in NEW_FUNCTIONS)}drop table {CAP};
delete from erp.schema_migrations where version={q(VERSION)};
delete from supabase_migrations.schema_migrations where version={q(STAMP)} and name={q(NAME)};
"""+guard(before['objects'],'AV_RESTORED')
    s+=f"""do $restored_data$ declare v_table text;v_hash jsonb;v_before jsonb;b jsonb; begin
 select boundary_snapshot into b from pg_temp.cp6_av_restore_boundary;
 {package.data_sql('v_before',['schema_migrations'])}
 if v_before is distinct from b->'before'
  or {package.history_hash('supabase_migrations','schema_migrations')} is distinct from b->>'platform_before'
  or {package.history_hash('erp','schema_migrations')} is distinct from b->>'markers_before'
 then raise exception 'AV_EXACT_RESTORE_FAILED';end if;
end $restored_data$;
commit;
"""
    ROLLBACK.write_text(s);pin['rollback_sha256']=sha(s)
    pin.update(builder_sha256=sha(Path(__file__).read_bytes()),definitions_sha256=sha(DEFINITIONS.read_bytes()),
               au_pins_sha256=predecessor_runtime.EXPECTED_PINS,cli_provenance='NOT_TESTED',production_go=False,independent_acceptance=False)
    PINS.write_text(json.dumps(pin,indent=2)+'\n')
    print(json.dumps({k:pin[k] for k in ('migration','migration_sha256','rollback','rollback_sha256')}))


if __name__=='__main__':build()
