#!/usr/bin/env python3
"""Build the AW T1 family install (label T1_FAMILY, owner decision A+B, handoff §18/§19).

This is a development install for targeted family tests on the disposable chain AN -> AU -> AV. It is not a release
package: no capsule, no rollback file, no closed admission. The release package (T3) is built once for the combined
candidate from a hosted-equivalent baseline. Evidence produced with this file must never be cited as release evidence.

Guards kept: AV must be recorded, AW must not be, and the two functions AW replaces must still have the exact text
AW was written against (fail closed on drift).
Usage: python3 scripts/cp6_aw_build.py            # writes supabase/dev/cp6_aw_t1_family.sql
       python3 scripts/cp6_aw_build.py --check    # fails if the file is stale
"""
from pathlib import Path
import hashlib,sys

ROOT=Path(__file__).resolve().parents[1]
sys.path.insert(0,str(ROOT/'scripts'))
import cp6_aw_definitions as aw

OUT=ROOT/'supabase/dev/cp6_aw_t1_family.sql'
VERSION='v2.6.20aw'

# Dependency order: guards and pure helpers first, then the engine, then its readers.
ORDER=[aw.FILING_GUARD,aw.ESTIMATE_GUARD,aw.REGISTRY,aw.BLOCKERS,aw.READINESS,aw.COMPLETENESS_FROM,aw.PREFLIGHT,aw.ESTIMATE]
assert sorted(ORDER)==sorted(aw.NEW_FUNCTIONS),'every new function must be ordered exactly once'


def md5(text):return hashlib.md5(text.encode()).hexdigest()


def build():
    parts=['-- CP6 AW close readiness engine: T1_FAMILY development install (NOT a release package).',
           '-- Generated by scripts/cp6_aw_build.py from scripts/cp6_aw_definitions.py; do not edit by hand.',
           'begin;',"set local lock_timeout='10s';set local statement_timeout='240s';set local search_path='';",
           'do $t1_guard$','begin',
           f" if not exists(select 1 from erp.schema_migrations where version='v2.6.20av') then raise exception 'AW_T1_REQUIRES_AV'; end if;",
           f" if exists(select 1 from erp.schema_migrations where version='{VERSION}') or to_regclass('erp.{aw.FILINGS}') is not null",
           f"    or to_regclass('erp.{aw.ESTIMATES}') is not null then raise exception 'AW_T1_ALREADY_INSTALLED'; end if;"]
    for key in (aw.CLOSE,aw.SNAPSHOT):
        parts.append(f" if md5(pg_get_functiondef('{key}'::regprocedure))<>'{md5(aw.OLD[key])}' then raise exception 'AW_T1_PREDECESSOR_DRIFT: {key}'; end if;")
    parts+=['end $t1_guard$;',aw.SCHEMA.strip()]
    for key in ORDER:parts+=[aw.NEW_FUNCTIONS[key].rstrip()+';']
    for key in (aw.CLOSE,aw.SNAPSHOT):parts+=[aw.FUNCTIONS[key].rstrip()+';']
    for key in aw.PUBLIC_FUNCTIONS:parts+=[aw.PUBLIC_FUNCTIONS[key].rstrip()+';']
    parts.append(aw.TRIGGERS.strip())
    for key in ORDER:parts.append(f'revoke all on function {key} from public,anon,authenticated,service_role;')
    for key in aw.PUBLIC_FUNCTIONS:
        parts+=[f'revoke all on function {key} from public,anon;',f'grant execute on function {key} to authenticated,service_role;']
    parts+=[f"insert into erp.schema_migrations(version,description) values('{VERSION}',"
            "'T1_FAMILY development install of the AW close readiness engine; not a release package');",'commit;','']
    return '\n'.join(parts)


if __name__=='__main__':
    text=build()
    if '--check' in sys.argv:
        assert OUT.read_text()==text,'supabase/dev/cp6_aw_t1_family.sql is stale; rerun scripts/cp6_aw_build.py'
        print('fresh',hashlib.sha256(text.encode()).hexdigest())
    else:
        OUT.parent.mkdir(parents=True,exist_ok=True);OUT.write_text(text)
        print(OUT.relative_to(ROOT),len(text),hashlib.sha256(text.encode()).hexdigest())
