#!/usr/bin/env python3
"""BE family builder. Development stages remain NOT_READY until all four flows and CI gates are complete.

Existing function changes use exactly-once substitutions from the pinned predecessor definitions.
The selected-lot adapter never falls back to a different FIFO lot.
"""
from pathlib import Path
import hashlib,re,sys
from cp6_bc_build import last_definition,substitute

ROOT=Path(__file__).resolve().parents[1]
AC=ROOT/'supabase/migrations/20260915031500_erp_v2_6_20ac_cp6_temporal_surface_closure.sql'
OUT=ROOT/'supabase/dev/cp6_be_t1_family.sql'
VERSION='v2.6.20be'
REPLACED=['erp.post_product_conversion(uuid)']
NEW_TABLES=['be_execution_context_v1','be_conversion_sources_v1','be_conversion_returns_v1']
OBJECTS=[ROOT/'scripts/cp6_be_objects_conversion.sql']

def objects():return '\n'.join(p.read_text().rstrip() for p in OBJECTS)

def new_functions():
    return [m.group(1) for m in re.finditer(r'(?i)create or replace function ((?:erp|public)\.[a-z0-9_]+)\(',objects())]

def conversion():
    return substitute(last_definition(AC,'post_product_conversion'),[
      ("where fl.product_id=h.from_product_id and fl.po_id is null\n",
       "where fl.product_id=h.from_product_id and fl.po_id is null\n"
       "      and (not exists(select 1 from erp.be_conversion_sources_v1 where conversion_id=h.id)\n"
       "        or fl.id=(select source_lot_id from erp.be_conversion_sources_v1 where conversion_id=h.id))\n"),
      ("where fl.product_id=h.from_product_id and fl.po_id is not null\n",
       "where fl.product_id=h.from_product_id and fl.po_id is not null\n"
       "      and (not exists(select 1 from erp.be_conversion_sources_v1 where conversion_id=h.id)\n"
       "        or fl.id=(select source_lot_id from erp.be_conversion_sources_v1 where conversion_id=h.id))\n")
    ],'BE exact source conversion')

def build():
    grants=r"""do $grants$
declare t text;f text;
begin
 foreach t in array array['be_execution_context_v1','be_conversion_sources_v1','be_conversion_returns_v1'] loop
   execute format('alter table erp.%I enable row level security',t);
   execute format('revoke all on erp.%I from public,anon,authenticated,service_role',t);
 end loop;
 for f in select p.oid::regprocedure::text from pg_proc p join pg_namespace n on n.oid=p.pronamespace
   where n.nspname='erp' and (p.proname like 'be\_%' or p.proname in('save_product_conversion_action_v1','get_product_conversion_workspace_v1')) loop
   execute format('revoke all on function %s from public,anon,authenticated,service_role',f);
 end loop;
end $grants$;
revoke all on function public.erp_save_product_conversion_action_v1(text,jsonb,uuid) from public,anon;
revoke all on function public.erp_get_product_conversion_workspace_v1(jsonb) from public,anon;
grant execute on function public.erp_save_product_conversion_action_v1(text,jsonb,uuid) to authenticated,service_role;
grant execute on function public.erp_get_product_conversion_workspace_v1(jsonb) to authenticated,service_role;
"""
    return '\n'.join([
      '-- BE T1_FAMILY development install, NOT release evidence. Stage 1; remaining flows recorded in writer progress.',
      '-- Generated by scripts/cp6_be_build.py; do not edit by hand.',
      "begin;set local search_path='';set local lock_timeout='10s';set local statement_timeout='240s';",
      "do $guard$ begin if not exists(select 1 from erp.schema_migrations where version='v2.6.20bd') then raise exception 'BE_REQUIRES_BD';end if;",
      "if exists(select 1 from erp.schema_migrations where version='v2.6.20be') then raise exception 'BE_ALREADY_INSTALLED';end if;end $guard$;",
      objects(),conversion(),grants,
      "insert into erp.schema_migrations(version,description) values('v2.6.20be','BE development family: SKU conversion, rework/redye and pocket cutover');",
      'commit;',''])

if __name__=='__main__':
    text=build()
    if '--check' in sys.argv:assert OUT.read_text()==text,'BE_BUILD_STALE'
    else:OUT.write_text(text)
    print(OUT.relative_to(ROOT),len(text),hashlib.sha256(text.encode()).hexdigest())
