import assert from 'node:assert/strict'
import {execFileSync} from 'node:child_process'
import {mkdirSync,writeFileSync} from 'node:fs'
import {cases as historyCases} from './cp7_f04_history_browser.mjs'
const fixture=(op,p)=>JSON.parse(execFileSync('python',['../auditor/scripts/cp7_f04_baseline_browser_fixture.py',op],{input:JSON.stringify(p),cwd:'../writer',encoding:'utf8',maxBuffer:16*1024*1024}).trim())
async function navigate(page){await page.locator('.sidebar .nav-main').filter({hasText:'Gudang'}).waitFor({state:'attached'});const menu=page.getByRole('button',{name:'Buka menu',exact:true});if(await menu.isVisible())await menu.click();const link=page.getByRole('button',{name:'• Ringkasan Barang Jadi',exact:true});if(!await link.isVisible())await page.locator('.sidebar .nav-main').filter({hasText:'Gudang'}).click();await link.click()}
async function screen(ui,page,name){await ui.expect.poll(()=>page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);await page.screenshot({path:'cp6-proof/t3/'+name,fullPage:true})}
async function journey(ui,today,mobile){
 const f=fixture('prepare',{today}),user=await ui.login('OWNER',{label:'p06-profile-'+mobile,mobile,timezoneId:mobile?'America/Los_Angeles':'Asia/Jakarta'}),page=user.page,suffix=mobile?'MOBILE':'DESKTOP',history=page.getByRole('region',{name:'Data permintaan ERP',exact:true}),panel=page.getByRole('region',{name:'Aturan dan target produksi',exact:true}),shots=[]
 let lost=null,targetLost=null,originalTarget=null
 const state=()=>fixture('state',{fixture:f,actor:user.user.id})
 try{
  mkdirSync('cp6-proof/t3',{recursive:true});await navigate(page);const dirty=page.getByLabel('Cari barang jadi',{exact:true});await dirty.fill('P06 ISIAN GUDANG TETAP ADA')
  await history.getByRole('button',{name:'Data permintaan & stok',exact:true}).click();const captured=page.waitForResponse(r=>r.url().endsWith('/rpc/erp_cp7_capture_demand_history_v1'));await history.getByRole('button',{name:'Muat data permintaan',exact:true}).click();const wire=await(await captured).json(),sku=wire.current_stock.find(x=>x.root_id===f.product).sku
  await history.getByLabel('Cari data permintaan',{exact:true}).fill(sku);await history.getByRole('button',{name:'Atur target '+sku,exact:true}).click();await ui.expect(panel).toContainText('Belum ada aturan yang diperiksa');assert.equal(await dirty.inputValue(),'P06 ISIAN GUDANG TETAP ADA')
  const before=state();assert.equal(before.profile_count,0);assert.equal(await panel.getByLabel('Waktu proses pilihan (hari kalender)',{exact:true}).inputValue(),'');assert.equal(await panel.getByLabel('Minimal hari riwayat tersedia',{exact:true}).inputValue(),'')
  await panel.getByLabel('Dasar permintaan',{exact:true}).selectOption('SELECTED_MANUAL');await panel.getByLabel('Permintaan pilihan PCS per hari',{exact:true}).fill('10');await panel.getByLabel('Minimal hari riwayat tersedia',{exact:true}).fill('20');await panel.getByLabel('Waktu proses pilihan (hari kalender)',{exact:true}).fill('3');await panel.getByLabel('Jarak pemeriksaan (hari kalender)',{exact:true}).fill('7');await panel.getByLabel('Cadangan waktu (hari kalender)',{exact:true}).fill('0');await panel.getByLabel('Alasan aturan target',{exact:true}).fill('Owner reviewed scenario10 PCS/day and3+7+0 calendar days')
  await page.route('**/rest/v1/rpc/erp_cp7_save_planning_profile_v1',async route=>{if(!lost){const r=await route.fetch();assert.equal(r.status(),200);lost={envelope:route.request().postDataJSON(),body:await r.json()};await route.abort('failed')}else await route.continue()})
  await panel.getByRole('button',{name:'Simpan aturan target',exact:true}).click();await ui.expect(panel.getByRole('button',{name:'Ulangi simpan aturan yang sama',exact:true})).toBeEnabled();assert.equal(state().profile_count,1);assert.deepEqual(state().business,before.business)
  await screen(ui,page,`P06_UNCERTAIN_PROFILE_${suffix}.png`);shots.push(`P06_UNCERTAIN_PROFILE_${suffix}.png`)
  const saved=page.waitForResponse(r=>r.url().endsWith('/rpc/erp_cp7_save_planning_profile_v1'));await panel.getByRole('button',{name:'Ulangi simpan aturan yang sama',exact:true}).click();const savedResponse=await saved;assert.equal(savedResponse.status(),200);assert.deepEqual(savedResponse.request().postDataJSON(),lost.envelope);assert.deepEqual(await savedResponse.json(),lost.body);assert.equal(state().profile_count,1)
  await panel.getByRole('button',{name:'Muat aturan terbaru',exact:true}).click();await ui.expect(panel).toContainText('Versi aturan 1');await panel.getByRole('button',{name:'Gunakan aturan terbaru',exact:true}).click()
  await page.route('**/rest/v1/rpc/erp_cp7_capture_baseline_v1',async route=>{if(!targetLost){const r=await route.fetch();assert.equal(r.status(),200);targetLost={envelope:route.request().postDataJSON(),body:await r.json()};await route.abort('failed')}else await route.continue()})
  await panel.getByRole('button',{name:'Hitung target dari ERP',exact:true}).click();await ui.expect(panel.getByRole('button',{name:'Ulangi permintaan target yang sama',exact:true})).toBeEnabled();assert.equal(state().baseline_count,1)
  const replayed=page.waitForResponse(r=>r.url().endsWith('/rpc/erp_cp7_capture_baseline_v1'));await panel.getByRole('button',{name:'Ulangi permintaan target yang sama',exact:true}).click();const replay=await replayed;assert.deepEqual(replay.request().postDataJSON(),targetLost.envelope);assert.deepEqual(await replay.json(),targetLost.body);originalTarget=targetLost.body
  await ui.expect(panel.locator('.native-planning-result')).toContainText('100 PCS');await ui.expect(panel.locator('.native-planning-result')).toContainText('76 PCS');await ui.expect(panel.locator('.native-planning-result')).toContainText('Jumlah yang masih perlu diproduksi belum diketahui');assert.equal(state().baseline_count,1);assert.deepEqual(state().business,before.business);assert.equal(await dirty.inputValue(),'P06 ISIAN GUDANG TETAP ADA')
  await screen(ui,page,`P06_TARGET100_${suffix}.png`);shots.push(`P06_TARGET100_${suffix}.png`)
  fixture('update_profile',{fixture:f});await panel.getByRole('button',{name:'Periksa sumber target',exact:true}).click();await ui.expect(panel.locator('.native-planning-result')).toContainText('Arsip lama: sumber ERP atau aturan sudah berubah.');await ui.expect(panel.locator('.native-planning-result')).toContainText('100 PCS')
  await screen(ui,page,`P06_STALE100_${suffix}.png`);shots.push(`P06_STALE100_${suffix}.png`)
  await panel.getByRole('button',{name:'Hitung target dari ERP',exact:true}).click();await ui.expect(panel.locator('.native-planning-result')).toContainText('200 PCS');assert.equal(state().baseline_count,2);assert.equal(state().profile_count,2)
  await screen(ui,page,`P06_TARGET200_${suffix}.png`);shots.push(`P06_TARGET200_${suffix}.png`)
  if(mobile){fixture('deactivate',{actor:user.user.id});const refusal=page.waitForResponse(r=>r.url().endsWith('/rpc/erp_cp7_read_baseline_v1')),parent=page.waitForResponse(r=>r.url().endsWith('/rpc/erp_cp7_get_fg_v1'));await panel.getByRole('button',{name:'Periksa sumber target',exact:true}).click();assert.equal((await refusal).status(),403);assert.equal((await parent).status(),403);await ui.expect(panel.locator('.native-planning-result')).toHaveCount(0);await ui.expect(page.locator('.cfg-totals')).toHaveCount(0);await ui.expect(history.locator('table')).toHaveCount(0);await screen(ui,page,`P06_REVOKED_${suffix}.png`);shots.push(`P06_REVOKED_${suffix}.png`)}
  return{status:'PASS',actual_Auth_native_version_bound_profile:true,unknown_inputs_blank:true,lost_profile_reply_same_UUID_one_revision:true,lost_target_reply_same_UUID_one_immutable_run:true,selected_target100_native_FG76_final_gap_unknown_apply_false:true,profile_revision20_stales_old100_new200:true,native_business_unchanged:true,original_stock_search_preserved:true,current_mobile403_retires_target_history_and_parent:mobile,screenshots:shots}
 }catch(e){writeFileSync(`cp6-proof/t3/P06_${suffix}_FAILURE.json`,JSON.stringify({error:String(e),text:await panel.innerText().catch(()=>''),lost,targetLost,originalTarget},null,2));await page.screenshot({path:`cp6-proof/t3/P06_${suffix}_FAILURE.png`,fullPage:true}).catch(()=>{});throw e}
 finally{fixture('restore',{actor:user.user.id});await user.context.close()}
}
export function cases(ui,today){return[...historyCases(ui,today),['P06_BROWSER_DESKTOP_NATIVE_PROFILE',()=>journey(ui,today,false)],['P06_BROWSER_MOBILE_NATIVE_PROFILE',()=>journey(ui,today,true)]]}
