import assert from'node:assert/strict'
import{execFileSync}from'node:child_process'
import{mkdirSync,writeFileSync}from'node:fs'
import{withActualHttpTrace}from'./cp7_f05_http_trace.mjs'
const fixture=(op,p)=>JSON.parse(execFileSync('python',['../auditor/scripts/cp7_f05_other_browser_fixture.py',op],{input:JSON.stringify(p),cwd:'../writer',encoding:'utf8',maxBuffer:16*1024*1024}).trim())
async function navigate(page){await page.locator('.sidebar .nav-main').filter({hasText:'Gudang'}).waitFor({state:'attached'});const menu=page.getByRole('button',{name:'Buka menu',exact:true});if(await menu.isVisible())await menu.click();const link=page.getByRole('button',{name:'• Ringkasan Barang Jadi',exact:true});if(!await link.isVisible())await page.locator('.sidebar .nav-main').filter({hasText:'Gudang'}).click();await link.click()}
async function journey(ui,today,mobile){
 const native=fixture('prepare',{today}),user=await ui.login('OWNER',{label:'p16-other-obligations-'+mobile,mobile,timezoneId:'America/Los_Angeles'}),page=user.page,suffix=mobile?'MOBILE':'DESKTOP'
 const panel=page.getByRole('region',{name:'Analisis ERP bersama',exact:true}),history=page.getByRole('region',{name:'Data permintaan ERP',exact:true}),conditions=panel.getByRole('region',{name:'Kondisi masalah dan pratinjau lokal',exact:true}),shots=[]
 let original=null,lastSource=null,partial=null
 const load=async()=>{const response=page.waitForResponse(r=>r.url().endsWith('/rpc/erp_cp7_get_rule_conditions_v1'));await conditions.getByRole('button',{name:'Periksa kondisi masalah ERP',exact:true}).click();const r=await response;assert.equal(r.status(),200);const body=await r.json();assert.equal(body.contract_version,'cp7.native-rule-conditions.v2');assert.deepEqual(body.analysis.analysis,original.analysis);lastSource=body;return body}
 const find=async key=>{const idx=lastSource.rows.findIndex(r=>r.key===key);assert.ok(idx>=0);for(let n=0;n<Math.floor(idx/25);n++)await conditions.getByRole('button',{name:'Kondisi berikutnya',exact:true}).click();const a=conditions.getByRole('article',{name:'Kondisi '+key,exact:true});await ui.expect(a).toBeVisible();return a}
 const shot=async name=>{await ui.expect.poll(()=>page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);await page.screenshot({path:'cp6-proof/t3/'+name,fullPage:true});shots.push(name)}
 const payrollKey='AP_DUE:PAYROLL_AP:'+native.payroll.payroll
 try{
  mkdirSync('cp6-proof/t3',{recursive:true});await navigate(page);const dirty=page.getByLabel('Cari barang jadi',{exact:true});await dirty.fill('P16 TAGIHAN ISIAN GUDANG');await history.getByRole('button',{name:'Data permintaan & stok',exact:true}).click();await history.getByRole('button',{name:'Analisis, laporan & pengingat seluruh produk',exact:true}).click()
  const captured=await withActualHttpTrace('F05_CAPTURE','OTHER_'+suffix,async()=>{const response=page.waitForResponse(r=>r.url().endsWith('/rpc/erp_cp7_capture_analysis_v1'));await panel.getByRole('button',{name:'Ambil analisis ERP terbaru',exact:true}).click();return await response});assert.equal(captured.status(),200);original=await captured.json();const before=fixture('state',{actor:user.user.id});await panel.getByRole('tab',{name:'Pengingat',exact:true}).click()
  await load();let a=await find(payrollKey);await ui.expect(a).toContainText('9.007.199.254.740.993,01');await ui.expect(a).toContainText('Tanggal jatuh tempo belum dicatat');await ui.expect(a).toContainText('Saldo kewajiban masih terbuka');assert.equal(lastSource.rows.find(r=>r.key===payrollKey).business_resolved,false);await shot('P16_OTHER_EXACT_UNKNOWN_DUE_'+suffix+'.png')
  await load();a=await find('AP_DUE:OPENING_AP:'+native.opening_id);await ui.expect(a).toContainText('65,00');await ui.expect(a).toContainText('Belum ada bukti sumber bahwa masalah ini selesai.')
  await load();a=await find('AP_DUE:LAUNDRY_RECEIPT:'+native.receipt_line);await ui.expect(a).toContainText('Belum diketahui');await ui.expect(a).toContainText('Nota belum lengkap');assert.equal(lastSource.rows.find(r=>r.key==='AP_DUE:LAUNDRY_RECEIPT:'+native.receipt_line).business_resolved,false);await shot('P16_OTHER_PENDING_LAUNDRY_'+suffix+'.png')
  partial=fixture('partial',{payroll:native.payroll});await load();a=await find(payrollKey);await ui.expect(a).toContainText('0,01');assert.equal(lastSource.rows.find(r=>r.key===payrollKey).financial_source.remaining.value,'0.01');await shot('P16_OTHER_PARTIAL_CENT_'+suffix+'.png')
  fixture('final',{payroll:native.payroll});await load();a=await find(payrollKey);await ui.expect(a).toContainText('Sumber membuktikan selesai.');assert.equal(lastSource.rows.find(r=>r.key===payrollKey).business_resolved,true)
  fixture('inverse',{payroll:native.payroll,payment_id:partial.payment_id});await load();a=await find(payrollKey);await ui.expect(a).toContainText('9.007.199.254.740.993');assert.equal(lastSource.rows.find(r=>r.key===payrollKey).business_resolved,false);await shot('P16_OTHER_NATIVE_INVERSE_'+suffix+'.png')
  fixture('deactivate',{actor:user.user.id});const denied=page.waitForResponse(r=>r.url().endsWith('/rpc/erp_cp7_get_rule_conditions_v1')),parent=page.waitForResponse(r=>r.url().endsWith('/rpc/erp_cp7_get_fg_v1'));await conditions.getByRole('button',{name:'Periksa kondisi masalah ERP',exact:true}).click();assert.equal((await denied).status(),403);assert.equal((await parent).status(),403);await ui.expect(conditions.getByRole('article')).toHaveCount(0);await ui.expect(panel.locator('.native-analysis-result')).toHaveCount(0);await ui.expect(page.locator('.cfg-totals')).toHaveCount(0);assert.equal(await dirty.inputValue(),'P16 TAGIHAN ISIAN GUDANG');assert.equal(fixture('state',{actor:user.user.id}).analysis_count,before.analysis_count);await shot('P16_OTHER_CURRENT_AUTH_'+suffix+'.png')
  return{status:'PASS',actual_Auth_Native_opening_payroll_unpriced_laundry_complete_source:true,exact_large_cent_under_foreign_device_timezone_no_fake_due:true,actual_payroll_partial_final_inverse_not_UI_financial_formula:true,current403_retires_all_obligation_Original_and_parent_facts:true,dirty_stock_search_same_immutable_Original_no_implicit_capture_or_delivery:true,screenshots:shots}
 }catch(e){try{const diagnostic=JSON.parse(execFileSync('python',['../auditor/scripts/cp7_native_read_profile.py'],{input:JSON.stringify({actor:user.user.id,today}),cwd:'../writer',encoding:'utf8',timeout:30000,maxBuffer:1024*1024}).trim());writeFileSync('cp6-proof/t3/P16_OTHER_'+suffix+'_READ_PROFILE.json',JSON.stringify(diagnostic,null,2))}catch{};writeFileSync('cp6-proof/t3/P16_OTHER_'+suffix+'_FAILURE.json',JSON.stringify({error:String(e),text:await panel.innerText().catch(()=>''),native,original,lastSource,partial},null,2));await page.screenshot({path:'cp6-proof/t3/P16_OTHER_'+suffix+'_FAILURE.png',fullPage:true}).catch(()=>{});throw e}
 finally{await page.unrouteAll({behavior:'wait'});fixture('restore',{actor:user.user.id});await user.context.close()}
}
export function cases(ui,today){return[['P16_OTHER_BROWSER_DESKTOP',()=>journey(ui,today,false)],['P16_OTHER_BROWSER_MOBILE',()=>journey(ui,today,true)]]}
