import assert from 'node:assert/strict'
import {execFileSync} from 'node:child_process'
import {mkdirSync,writeFileSync} from 'node:fs'
import {cases as previousCases} from './cp7_f04_baseline_browser.mjs'
const fixture=(op,p)=>JSON.parse(execFileSync('python',['../auditor/scripts/cp7_f04_netting_browser_fixture.py',op],{input:JSON.stringify(p),cwd:'../writer',encoding:'utf8',maxBuffer:16*1024*1024}).trim())
const wib=x=>new Date(Date.parse(x)+7*3600000).toISOString().slice(0,19)
async function navigate(page){await page.locator('.sidebar .nav-main').filter({hasText:'Gudang'}).waitFor({state:'attached'});const menu=page.getByRole('button',{name:'Buka menu',exact:true});if(await menu.isVisible())await menu.click();const link=page.getByRole('button',{name:'• Ringkasan Barang Jadi',exact:true});if(!await link.isVisible())await page.locator('.sidebar .nav-main').filter({hasText:'Gudang'}).click();await link.click()}
async function screen(ui,page,name){await ui.expect.poll(()=>page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);await page.screenshot({path:'cp6-proof/t3/'+name,fullPage:true})}
async function journey(ui,today,mobile){
 const f=fixture('prepare',{today}),user=await ui.login('OWNER',{label:'p06-netting-'+mobile,mobile,timezoneId:mobile?'America/Los_Angeles':'Asia/Jakarta'}),page=user.page,suffix=mobile?'MOBILE':'DESKTOP',history=page.getByRole('region',{name:'Data permintaan ERP',exact:true}),panel=page.getByRole('region',{name:'Jadwal dan kekurangan produksi',exact:true}),shots=[]
 let source=null,guide=null,lostSave=null,lostNet=null,original=null
 const state=()=>fixture('state',{actor:user.user.id})
 try{
  mkdirSync('cp6-proof/t3',{recursive:true});await navigate(page);const dirty=page.getByLabel('Cari barang jadi',{exact:true});await dirty.fill('P06 JADWAL ISIAN GUDANG')
  await history.getByRole('button',{name:'Data permintaan & stok',exact:true}).click();await history.getByRole('button',{name:'Muat data permintaan',exact:true}).click();await history.getByRole('button',{name:'Jadwal & kekurangan seluruh produk',exact:true}).click()
  const loaded=page.waitForResponse(r=>r.url().endsWith('/rpc/erp_cp7_capture_production_supply_v1')),guided=page.waitForResponse(r=>r.url().endsWith('/rpc/erp_cp7_get_production_schedule_v1'));await panel.getByRole('button',{name:'Ambil stok proses terbaru',exact:true}).click();source=await(await loaded).json();guide=await(await guided).json();await ui.expect(panel.getByLabel('Waktu satu PCS baru',{exact:true})).toBeVisible();assert.equal(await panel.getByLabel('Waktu satu PCS baru',{exact:true}).inputValue(),'');assert.equal(source.wip.status,'COMPLETE');assert.ok(guide.position_requirements.length>0);assert.equal(state().supply_count,1);const before=state()
  await panel.getByLabel('Tempat kerja pilihan',{exact:true}).fill('Explicit Native browser selected centre');await panel.getByLabel('Batas jadwal WIB',{exact:true}).fill(wib(f.through));await panel.getByLabel('Waktu satu PCS baru',{exact:true}).fill('2');await panel.getByLabel('Mulai kerja 1 WIB',{exact:true}).fill(wib(f.window_start));await panel.getByLabel('Selesai kerja 1 WIB',{exact:true}).fill(wib(f.window_end));await panel.getByLabel('Beban lain 1',{exact:true}).fill('0')
  for(const p of guide.position_requirements){assert.equal(p.remaining_pcs,'8');assert.equal(await panel.getByLabel('SEWING menit '+p.position_key,{exact:true}).inputValue(),'');if(p.eligible_company_wip){await panel.getByLabel('Bagus '+p.position_key,{exact:true}).fill('9');await panel.getByLabel('Acuan '+p.position_key,{exact:true}).fill('10')}for(const stage of p.remaining_route)await panel.getByLabel(stage+' menit '+p.position_key,{exact:true}).fill(String({SEWING:15,LAUNDRY:20,QC:10,REWORK:15,REWASH:20}[stage]))}
  await panel.getByLabel('Alasan jadwal',{exact:true}).fill('Explicit reviewed source-bound Native browser work and yield scenario')
  await page.route('**/rest/v1/rpc/erp_cp7_save_production_schedule_v1',async route=>{if(!lostSave){const r=await route.fetch();assert.equal(r.status(),200);lostSave={envelope:route.request().postDataJSON(),body:await r.json()};await route.abort('failed')}else await route.continue()})
  await panel.getByRole('button',{name:'Simpan jadwal yang diperiksa',exact:true}).click();await ui.expect(panel.getByRole('button',{name:'Ulangi simpan jadwal yang sama',exact:true})).toBeEnabled();assert.equal(state().plan_count,before.plan_count+1);assert.deepEqual(state().business,before.business);await screen(ui,page,`P06_WORK_UNCERTAIN_${suffix}.png`);shots.push(`P06_WORK_UNCERTAIN_${suffix}.png`)
  const saved=page.waitForResponse(r=>r.url().endsWith('/rpc/erp_cp7_save_production_schedule_v1'));await panel.getByRole('button',{name:'Ulangi simpan jadwal yang sama',exact:true}).click();const sr=await saved;assert.equal(sr.status(),200);assert.deepEqual(sr.request().postDataJSON(),lostSave.envelope);assert.deepEqual(await sr.json(),lostSave.body);assert.equal(state().plan_count,before.plan_count+1)
  await panel.getByRole('button',{name:'Ambil stok proses terbaru',exact:true}).click();await ui.expect(panel.getByRole('button',{name:'Gunakan sumber jadwal terbaru',exact:true})).toBeEnabled();await panel.getByRole('button',{name:'Gunakan sumber jadwal terbaru',exact:true}).click();await panel.getByLabel('Waktu satu PCS baru',{exact:true}).fill('3')
  fixture('update_schedule',{today});await panel.getByRole('button',{name:'Periksa sumber stok proses',exact:true}).click();await ui.expect(panel).toContainText('Isianmu masih ada');assert.equal(await panel.getByLabel('Waktu satu PCS baru',{exact:true}).inputValue(),'3');await ui.expect(panel.getByRole('button',{name:'Simpan jadwal yang diperiksa',exact:true})).toBeDisabled();await panel.getByRole('button',{name:'Gunakan sumber jadwal terbaru',exact:true}).click();assert.equal(await panel.getByLabel('Waktu satu PCS baru',{exact:true}).inputValue(),'4');await screen(ui,page,`P06_WORK_REVIEW_${suffix}.png`);shots.push(`P06_WORK_REVIEW_${suffix}.png`)
  await page.route('**/rest/v1/rpc/erp_cp7_capture_netting_v1',async route=>{if(!lostNet){const r=await route.fetch();assert.equal(r.status(),200);lostNet={envelope:route.request().postDataJSON(),body:await r.json()};await route.abort('failed')}else await route.continue()})
  await panel.getByRole('button',{name:'Hitung kekurangan seluruh produk',exact:true}).click();await ui.expect(panel.getByRole('button',{name:'Ulangi kekurangan yang sama',exact:true})).toBeEnabled();assert.equal(state().net_count,1);const replayed=page.waitForResponse(r=>r.url().endsWith('/rpc/erp_cp7_capture_netting_v1'));await panel.getByRole('button',{name:'Ulangi kekurangan yang sama',exact:true}).click();const nr=await replayed;assert.equal(nr.status(),200);assert.deepEqual(nr.request().postDataJSON(),lostNet.envelope);original=await nr.json();assert.equal(original.run_id,lostNet.body.run_id);assert.deepEqual(original.rows,lostNet.body.rows);assert.equal(state().net_count,1);assert.equal(original.allocation.status,'SCENARIO');assert.equal(original.new_start_capacity.capacity_pcs,state().expected_capacity);const target=original.rows.find(r=>r.target_key.split(':')[0]===f.product);assert.equal(target.available_fg_pcs,'0');assert.equal(target.directed_on_time_good_pcs,'7');assert.equal(target.base_gap_pcs,'93');assert.equal(original.apply_enabled,false);await ui.expect(panel.locator('.native-production-result')).toContainText('93 PCS');assert.deepEqual(state().business,before.business);assert.equal(await dirty.inputValue(),'P06 JADWAL ISIAN GUDANG');await screen(ui,page,`P06_NETTING93_${suffix}.png`);shots.push(`P06_NETTING93_${suffix}.png`)
  await panel.getByLabel('Cari hasil kekurangan',{exact:true}).fill(target.sku);assert.equal(await panel.locator('.native-production-result tbody tr').count(),1);assert.equal(state().net_count,1)
  fixture('update_schedule',{today});await panel.getByRole('button',{name:'Periksa sumber kekurangan',exact:true}).click();await ui.expect(panel.locator('.native-production-result')).toContainText('Arsip lama: hitung kekurangan baru.');await ui.expect(panel.locator('.native-production-result')).toContainText('93 PCS');await screen(ui,page,`P06_NETTING_ARCHIVE_${suffix}.png`);shots.push(`P06_NETTING_ARCHIVE_${suffix}.png`)
  fixture('deactivate',{actor:user.user.id});const denied=page.waitForResponse(r=>r.url().endsWith('/rpc/erp_cp7_read_netting_v1')),parent=page.waitForResponse(r=>r.url().endsWith('/rpc/erp_cp7_get_fg_v1'));await panel.getByRole('button',{name:'Periksa sumber kekurangan',exact:true}).click();assert.equal((await denied).status(),403);assert.equal((await parent).status(),403);await ui.expect(panel.locator('.native-production-result')).toHaveCount(0);await ui.expect(page.locator('.cfg-totals')).toHaveCount(0);assert.equal(await dirty.inputValue(),'P06 JADWAL ISIAN GUDANG');await screen(ui,page,`P06_NETTING_REVOKED_${suffix}.png`);shots.push(`P06_NETTING_REVOKED_${suffix}.png`)
  return{status:'PASS',actual_Auth_native_global_source_and_server_remaining_routes:true,unknown_work_yield_unit_inputs_blank:true,metadata_response_loss_same_UUID_one_global_revision:true,dirty_work_input_preserved_on_new_revision_explicit_adoption:true,actual_native8_selected_good7_target100_FG0_gap93:true,independent_remaining_work_capacity_oracle:true,netting_reply_loss_same_UUID_one_original_run:true,presentation_filter_does_not_reallocate:true,archive93_preserved_after_changed_schedule:true,current403_retires_netting_and_parent_FG_Hpp:true,native_business_unchanged:true,original_stock_search_preserved:true,screenshots:shots}
 }catch(e){writeFileSync(`cp6-proof/t3/P06_NETTING_${suffix}_FAILURE.json`,JSON.stringify({error:String(e),text:await panel.innerText().catch(()=>''),source,guide,lostSave,lostNet,original},null,2));await page.screenshot({path:`cp6-proof/t3/P06_NETTING_${suffix}_FAILURE.png`,fullPage:true}).catch(()=>{});throw e}
 finally{fixture('restore',{actor:user.user.id});await user.context.close()}
}
export function cases(ui,today){return[...previousCases(ui,today),['P06_BROWSER_DESKTOP_NATIVE_NETTING',()=>journey(ui,today,false)],['P06_BROWSER_MOBILE_NATIVE_NETTING',()=>journey(ui,today,true)]]}
