import assert from'node:assert/strict'
import{execFileSync}from'node:child_process'
import{createHash}from'node:crypto'
import{mkdirSync,writeFileSync}from'node:fs'
import{withActualHttpTrace}from'./cp7_f05_http_trace.mjs'
const fixture=(op,p)=>JSON.parse(execFileSync('python',['../auditor/scripts/cp7_f05_rule_browser_fixture.py',op],{input:JSON.stringify(p),cwd:'../writer',encoding:'utf8',maxBuffer:16*1024*1024}).trim())
async function navigate(page){await page.locator('.sidebar .nav-main').filter({hasText:'Gudang'}).waitFor({state:'attached'});const menu=page.getByRole('button',{name:'Buka menu',exact:true});if(await menu.isVisible())await menu.click();const link=page.getByRole('button',{name:'• Ringkasan Barang Jadi',exact:true});if(!await link.isVisible())await page.locator('.sidebar .nav-main').filter({hasText:'Gudang'}).click();await link.click()}
async function journey(ui,today,mobile){
 const native=fixture('prepare',{today}),user=await ui.login('OWNER',{label:'p16-rule-local-'+mobile,mobile,timezoneId:'America/Los_Angeles'}),page=user.page,suffix=mobile?'MOBILE':'DESKTOP',panel=page.getByRole('region',{name:'Analisis ERP bersama',exact:true}),history=page.getByRole('region',{name:'Data permintaan ERP',exact:true}),policies=panel.getByRole('region',{name:'Pengaturan aturan pengingat',exact:true}),conditions=panel.getByRole('region',{name:'Kondisi masalah dan pratinjau lokal',exact:true}),screenshots=[]
 let original=null,lost=null,lastReply=null,routeError=null
 const rpcTimings=[]
 const current=()=>fixture('state',{actor:user.user.id}),shot=async name=>{await ui.expect.poll(()=>page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);await page.screenshot({path:'cp6-proof/t3/'+name,fullPage:true});screenshots.push(name)}
 const click=async(region,label,name)=>{const started=performance.now();const response=page.waitForResponse(r=>r.url().endsWith('/rpc/'+name));await region.getByRole('button',{name:label,exact:true}).click();const r=await response;rpcTimings.push({rpc:name,status:r.status(),elapsed_ms:Math.round(performance.now()-started)});assert.equal(r.status(),200);lastReply=await r.json();return lastReply}
 const loadLocal=()=>click(conditions,'Muat pratinjau lokal tersimpan','erp_cp7_get_local_reminders_v1')
 try{
  mkdirSync('cp6-proof/t3',{recursive:true});await navigate(page);const dirty=page.getByLabel('Cari barang jadi',{exact:true});await dirty.fill('P16 KONDISI ISIAN GUDANG');await history.getByRole('button',{name:'Data permintaan & stok',exact:true}).click();await history.getByRole('button',{name:'Analisis, laporan & pengingat seluruh produk',exact:true}).click()
  const capture=page.waitForResponse(r=>r.url().endsWith('/rpc/erp_cp7_capture_analysis_v1'));await panel.getByRole('button',{name:'Ambil analisis ERP terbaru',exact:true}).click();const c=await capture;assert.equal(c.status(),200);original=await c.json();const before=current();await panel.getByRole('tab',{name:'Pengingat',exact:true}).click()
  await click(policies,'Muat pengaturan pengingat','erp_cp7_get_reminder_policy_v1');await policies.getByLabel('Aturan yang diperiksa',{exact:true}).selectOption('AR_DUE');await policies.getByLabel('Status aturan',{exact:true}).selectOption('true');await policies.getByLabel('Batas pengingat',{exact:true}).fill('0');await policies.getByLabel('Jeda pengingat dalam menit',{exact:true}).fill('0');await policies.getByLabel('Waktu tenang',{exact:true}).selectOption('false');await policies.getByLabel('Alasan perubahan pengingat',{exact:true}).fill('Explicit Native recorded-due local rehearsal '+suffix);await policies.getByLabel('Pengaturan pengingat sudah ditinjau',{exact:true}).check();await click(policies,'Simpan versi pengaturan pengingat','erp_cp7_save_reminder_policy_v1')
  const policyHistory=await click(policies,'Buka riwayat versi pengingat','erp_cp7_get_reminder_policy_history_v1');assert.ok(policyHistory.rows.length);assert.equal(policyHistory.rule_id,'AR_DUE');await shot(`P16_RULE_POLICY_HISTORY_${suffix}.png`)
  let w=await loadLocal();const row=w.source.rows.find(r=>r.key===native.condition_key);assert.equal(row.state,'ACTIVE');assert.equal(row.value.value,'1');assert.equal(row.eligibility,'LOCAL_PREVIEW_ELIGIBLE');assert.equal(w.binding,null)
  const observed=await click(conditions,'Catat pemeriksaan kondisi ERP','erp_cp7_evaluate_rule_episodes_v1');const episode=observed.result.rows.find(r=>r.condition.key===native.condition_key).episode;assert.equal(episode.state,'ACTIVE');await loadLocal()
  await conditions.getByLabel('Nama tujuan lokal',{exact:true}).fill('Pemeriksaan lokal '+suffix);await conditions.getByLabel('Status tujuan lokal',{exact:true}).selectOption('true');await conditions.getByLabel('Tujuan lokal Piutang jatuh tempo',{exact:true}).check();await conditions.getByLabel('Alasan tujuan lokal',{exact:true}).fill('Explicit local destination, no recipient or transport');await conditions.getByLabel('Tujuan lokal sudah ditinjau',{exact:true}).check();await click(conditions,'Simpan versi tujuan lokal','erp_cp7_save_local_binding_v1');assert.equal(current().bindings,before.bindings+1)
  await conditions.getByLabel('Kondisi untuk pratinjau',{exact:true}).selectOption(native.condition_key)
  await page.route('**/rest/v1/rpc/erp_cp7_claim_local_preview_v1',async route=>{try{if(!lost){const r=await withActualHttpTrace('F05_LOCAL_CLAIM',suffix,()=>route.fetch());assert.equal(r.status(),200);lost={envelope:route.request().postDataJSON(),body:await r.json()};await route.abort('failed')}else await route.continue()}catch(error){routeError=error;await route.abort('failed').catch(()=>{})}})
  const failed=page.waitForEvent('requestfailed',{predicate:r=>r.url().endsWith('/rpc/erp_cp7_claim_local_preview_v1'),timeout:60000})
  await conditions.getByRole('button',{name:'Buat pratinjau lokal',exact:true}).click();await failed;if(routeError)throw routeError;assert.ok(lost);await ui.expect(conditions.getByRole('button',{name:'Pastikan hasil kondisi di server',exact:true})).toBeEnabled();assert.equal(current().claims.length,before.claims.length+1);await ui.expect(panel.getByRole('button',{name:'Ambil analisis ERP terbaru',exact:true})).toBeDisabled();await shot(`P16_RULE_LOCAL_UNCERTAIN_${suffix}.png`)
  await panel.getByRole('button',{name:'Tutup analisis bersama',exact:true}).click();await history.getByRole('button',{name:'Analisis, laporan & pengingat seluruh produk',exact:true}).click();const recovered=await click(conditions,'Pastikan hasil kondisi di server','erp_cp7_get_local_reminder_request_v1');assert.deepEqual(recovered.result,lost.body.result);assert.deepEqual(recovered.workspace.source.analysis.analysis,original.analysis);assert.equal(current().claims.length,before.claims.length+1)
  const first=recovered.workspace.claims.find(c=>c.id===recovered.result.claim_id);assert.equal(first.body_sha256,createHash('sha256').update(first.body,'utf8').digest('hex'));assert.ok(first.body.includes(native.number));assert.equal(first.status,'CLAIMED');await shot(`P16_RULE_LOCAL_RECOVERED_${suffix}.png`)
  const claim=conditions.getByRole('article',{name:'Pratinjau lokal '+first.id,exact:true});const unknown=await click(claim,'Hasil pratinjau belum pasti','erp_cp7_finish_local_preview_v1');assert.equal(unknown.workspace.claims.find(c=>c.id===first.id).status,'UNKNOWN');await claim.getByLabel('Hasil pemeriksaan manual',{exact:true}).selectOption('NOT_CAPTURED_CONFIRMED');await claim.getByLabel('Alasan pemeriksaan manual',{exact:true}).fill('Operator inspected the local result, explicit next attempt');await claim.getByLabel('Hasil lokal sudah diperiksa',{exact:true}).check();const resolved=await click(claim,'Simpan kepastian hasil lokal','erp_cp7_resolve_local_preview_v1');assert.equal(resolved.workspace.claims.find(c=>c.id===first.id).status,'UNKNOWN');assert.equal(current().resolutions,before.resolutions+1)
  await conditions.getByLabel('Kondisi untuk pratinjau',{exact:true}).selectOption(native.condition_key);const next=await click(conditions,'Buat pratinjau lokal','erp_cp7_claim_local_preview_v1'),second=next.workspace.claims.find(c=>c.id===next.result.claim_id);assert.notEqual(second.id,first.id);assert.notEqual(second.fence,first.fence);const captured=await click(conditions.getByRole('article',{name:'Pratinjau lokal '+second.id,exact:true}),'Catat hasil pratinjau lokal','erp_cp7_finish_local_preview_v1');assert.equal(captured.workspace.claims.find(c=>c.id===second.id).status,'LOCAL_SINK_CAPTURED');assert.equal(captured.workspace.sent,false);assert.equal(captured.workspace.source.rows.find(r=>r.key===native.condition_key).business_resolved,false);await shot(`P16_RULE_LOCAL_CONFIRMED_${suffix}.png`)
  await conditions.getByLabel('Nama tujuan lokal',{exact:true}).fill('P16 tujuan lokal belum disimpan');await conditions.getByLabel('Alasan tujuan lokal',{exact:true}).fill('P16 alasan operator dipertahankan');fixture('deactivate',{actor:user.user.id});const denied=page.waitForResponse(r=>r.url().endsWith('/rpc/erp_cp7_get_local_reminders_v1')),parent=page.waitForResponse(r=>r.url().endsWith('/rpc/erp_cp7_get_fg_v1'));await conditions.getByRole('button',{name:'Muat pratinjau lokal tersimpan',exact:true}).click();assert.equal((await denied).status(),403);assert.equal((await parent).status(),403);await ui.expect(conditions.getByLabel('Isi pratinjau lokal',{exact:true})).toHaveCount(0);await ui.expect(panel.locator('.native-analysis-result')).toHaveCount(0);await ui.expect(page.locator('.cfg-totals')).toHaveCount(0);assert.equal(await dirty.inputValue(),'P16 KONDISI ISIAN GUDANG');await shot(`P16_RULE_LOCAL_REVOKED_${suffix}.png`)
  fixture('restore',{actor:user.user.id});await panel.getByText('Arsip analisis yang pernah dibuka',{exact:true}).click();await panel.getByRole('button',{name:'Buka arsip analisis 1',exact:true}).click();await panel.getByRole('tab',{name:'Pengingat',exact:true}).click();w=await loadLocal();assert.equal(w.claims.length,before.claims.length+2);assert.equal(await conditions.getByLabel('Nama tujuan lokal',{exact:true}).inputValue(),'P16 tujuan lokal belum disimpan');assert.equal(await conditions.getByLabel('Alasan tujuan lokal',{exact:true}).inputValue(),'P16 alasan operator dipertahankan');assert.equal(current().analysis_count,before.analysis_count);assert.equal(current().native_manual_count,before.native_manual_count)
  return{status:'PASS',actual_Auth_Native_recorded_due_source_and_immutable_policy_history:true,shared_episode_not_closed_by_review_or_local_capture:true,local_binding_claim_lost_reply_remount_exact_UUID_one_occurrence:true,exact_UTF8_body_hash_and_new_manual_non_capture_attempt_distinct_fence:true,UNKNOWN_original_stays_immutable_no_automatic_or_external_delivery:true,current403_retires_all_source_local_body_parent_FG_HPP:true,dirty_local_fields_stock_search_and_Original_preserved:true,actual_PostgREST_rpc_timings:rpcTimings,screenshots}
 }catch(e){try{const diagnostic=JSON.parse(execFileSync('python',['../auditor/scripts/cp7_native_read_profile.py'],{input:JSON.stringify({actor:user.user.id,today}),cwd:'../writer',encoding:'utf8',timeout:30000,maxBuffer:1024*1024}).trim());writeFileSync('cp6-proof/t3/P16_RULE_LOCAL_'+suffix+'_READ_PROFILE.json',JSON.stringify(diagnostic,null,2))}catch{};writeFileSync(`cp6-proof/t3/P16_RULE_LOCAL_${suffix}_FAILURE.json`,JSON.stringify({error:String(e),text:await panel.innerText().catch(()=>''),original,lost,lastReply,rpcTimings},null,2));await page.screenshot({path:`cp6-proof/t3/P16_RULE_LOCAL_${suffix}_FAILURE.png`,fullPage:true}).catch(()=>{});throw e}
 finally{await page.unrouteAll({behavior:'wait'});fixture('restore',{actor:user.user.id});await user.context.close()}
}
export function cases(ui,today){return[['P16_RULE_LOCAL_BROWSER_DESKTOP',()=>journey(ui,today,false)],['P16_RULE_LOCAL_BROWSER_MOBILE',()=>journey(ui,today,true)]]}
