import assert from 'node:assert/strict'
import {execFileSync} from 'node:child_process'
import {mkdirSync,writeFileSync} from 'node:fs'
const fixture=(op,p)=>JSON.parse(execFileSync('python',['../auditor/scripts/cp7_f05_analysis_browser_fixture.py',op],{input:JSON.stringify(p),cwd:'../writer',encoding:'utf8',maxBuffer:16*1024*1024}).trim())
const state=actor=>JSON.parse(execFileSync('python',['../auditor/scripts/cp7_f05_publication_browser_fixture.py','state'],{input:JSON.stringify({actor}),cwd:'../writer',encoding:'utf8',maxBuffer:16*1024*1024}).trim())
async function navigate(page){await page.locator('.sidebar .nav-main').filter({hasText:'Gudang'}).waitFor({state:'attached'});const menu=page.getByRole('button',{name:'Buka menu',exact:true});if(await menu.isVisible())await menu.click();const link=page.getByRole('button',{name:'• Ringkasan Barang Jadi',exact:true});if(!await link.isVisible())await page.locator('.sidebar .nav-main').filter({hasText:'Gudang'}).click();await link.click()}
async function journey(ui,today,mobile){
 fixture('prepare',{today});const user=await ui.login('OWNER',{label:'p15-publication-'+mobile,mobile,timezoneId:mobile?'America/Los_Angeles':'Asia/Jakarta'}),page=user.page,suffix=mobile?'MOBILE':'DESKTOP',panel=page.getByRole('region',{name:'Analisis ERP bersama',exact:true}),reports=page.getByRole('region',{name:'Laporan ERP tersimpan',exact:true}),history=page.getByRole('region',{name:'Data permintaan ERP',exact:true}),shots=[]
 let original=null,lost=null,one=null,two=null,negative=null
 const savedShot=async name=>{await ui.expect.poll(()=>page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);await page.screenshot({path:'cp6-proof/t3/'+name,fullPage:true});shots.push(name)}
 const list=async()=>{const response=page.waitForResponse(r=>r.url().endsWith('/rpc/erp_cp7_list_reports_v1'));await reports.getByRole('button',{name:'Muat laporan tersimpan dari server',exact:true}).click();return await response}
 try{
  mkdirSync('cp6-proof/t3',{recursive:true});await navigate(page);const dirty=page.getByLabel('Cari barang jadi',{exact:true});await dirty.fill('P15 ISIAN GUDANG TETAP');await history.getByRole('button',{name:'Data permintaan & stok',exact:true}).click();await history.getByRole('button',{name:'Analisis, laporan & pengingat seluruh produk',exact:true}).click()
  const capture=page.waitForResponse(r=>r.url().endsWith('/rpc/erp_cp7_capture_operational_analysis_v1'));await panel.getByRole('button',{name:'Ambil analisis ERP terbaru',exact:true}).click();const c=await capture;assert.equal(c.status(),200);original=await c.json();await panel.getByRole('tab',{name:'Laporan',exact:true}).click();const before=state(user.user.id)
  await reports.getByLabel('Jenis laporan tersimpan',{exact:true}).selectOption('PERIOD');await reports.getByLabel('Judul laporan tersimpan',{exact:true}).fill('Review periode ERP pertama');await reports.getByLabel('Alasan laporan tersimpan',{exact:true}).fill('Sumber dan angka asli sudah diperiksa');await reports.getByLabel('Laporan sudah ditinjau',{exact:true}).check()
  await page.route('**/rest/v1/rpc/erp_cp7_publish_report_v1',async route=>{if(!lost){const r=await route.fetch();assert.equal(r.status(),200);lost={payload:route.request().postDataJSON(),body:await r.json()};await route.abort('failed')}else await route.continue()})
  await reports.getByRole('button',{name:'Simpan laporan yang ditinjau',exact:true}).click();await ui.expect(reports.getByRole('button',{name:'Periksa hasil laporan tersimpan',exact:true})).toBeEnabled();assert.equal(state(user.user.id).publication_count,before.publication_count+1);await savedShot(`P15_PUBLICATION_UNCERTAIN_${suffix}.png`)
  await panel.getByRole('button',{name:'Tutup analisis bersama',exact:true}).click();await history.getByRole('button',{name:'Analisis, laporan & pengingat seluruh produk',exact:true}).click();await ui.expect(reports.getByRole('button',{name:'Periksa hasil laporan tersimpan',exact:true})).toBeEnabled();const recovered=page.waitForResponse(r=>r.url().endsWith('/rpc/erp_cp7_get_report_request_v1'));await reports.getByRole('button',{name:'Periksa hasil laporan tersimpan',exact:true}).click();const r=await recovered;assert.equal(r.status(),200);assert.deepEqual(r.request().postDataJSON(),lost.payload);const reply=await r.json();one=reply.document;assert.equal(one.id,lost.body.document.id);assert.equal(one.body,lost.body.document.body);assert.equal(one.body_sha256,lost.body.document.body_sha256);assert.equal(reply.analysis.source_state,'UNCHANGED');assert.deepEqual(reply.analysis.analysis,original.analysis);assert.equal(state(user.user.id).publication_count,before.publication_count+1);await ui.expect(reports.getByLabel('Teks laporan tersimpan',{exact:true})).toHaveText(one.body);assert.equal(await reports.getByLabel('Judul laporan tersimpan',{exact:true}).inputValue(),'Review periode ERP pertama');await savedShot(`P15_PUBLICATION_RECOVERED_${suffix}.png`)
  await reports.getByRole('button',{name:'Buat revisi dari laporan ini',exact:true}).click();await reports.getByLabel('Judul laporan tersimpan',{exact:true}).fill('Review periode ERP revisi kedua');await reports.getByLabel('Alasan laporan tersimpan',{exact:true}).fill('Penjelasan diperbaiki; fakta asli tidak diganti');await reports.getByLabel('Laporan sudah ditinjau',{exact:true}).check();const revised=page.waitForResponse(r=>r.url().endsWith('/rpc/erp_cp7_publish_report_v1'));await reports.getByRole('button',{name:'Simpan revisi laporan',exact:true}).click();const rev=await revised;assert.equal(rev.status(),200);two=(await rev.json()).document;assert.equal(two.series_id,one.series_id);assert.equal(two.revision,'2');assert.notEqual(two.id,one.id);assert.equal(state(user.user.id).publication_count,before.publication_count+2);await ui.expect(reports.getByLabel('Teks laporan tersimpan',{exact:true})).toHaveText(two.body);assert.deepEqual(state(user.user.id).business,before.business);await savedShot(`P15_PUBLICATION_REVISION_${suffix}.png`)
  assert.equal((await list()).status(),200);await reports.getByLabel('Laporan sebelum',{exact:true}).selectOption(one.id);await reports.getByLabel('Laporan sesudah',{exact:true}).selectOption(two.id);const compared=page.waitForResponse(r=>r.url().endsWith('/rpc/erp_cp7_compare_reports_v1'));await reports.getByRole('button',{name:'Bandingkan dua laporan ERP',exact:true}).click();const cmp=await compared;assert.equal(cmp.status(),200);const comparison=await cmp.json();assert.equal(comparison.before.body,one.body);assert.equal(comparison.before.is_latest,false);assert.equal(comparison.after.body,two.body);assert.ok(comparison.rows.some(r=>r.difference.state==='UNKNOWN'&&!('value'in r.difference)));assert.ok(comparison.rows.some(r=>r.difference.state==='KNOWN'&&Number(r.difference.value)===0));await ui.expect(reports.getByRole('article',{name:'Perbandingan laporan ERP',exact:true})).toBeVisible();await savedShot(`P15_PUBLICATION_COMPARISON_${suffix}.png`)
  await reports.getByRole('button',{name:'Jadikan laporan baru',exact:true}).click();await reports.getByLabel('Judul laporan tersimpan',{exact:true}).fill('Permintaan yang belum sampai server');await reports.getByLabel('Alasan laporan tersimpan',{exact:true}).fill('Uji pemulihan permintaan yang belum tersimpan');await reports.getByLabel('Laporan sudah ditinjau',{exact:true}).check();await page.unroute('**/rest/v1/rpc/erp_cp7_publish_report_v1');await page.route('**/rest/v1/rpc/erp_cp7_publish_report_v1',async route=>{if(!negative){negative=route.request().postDataJSON();await route.abort('failed')}else await route.continue()})
  await reports.getByRole('button',{name:'Simpan laporan yang ditinjau',exact:true}).click();await ui.expect(reports.getByRole('button',{name:'Periksa hasil laporan tersimpan',exact:true})).toBeEnabled();assert.equal(state(user.user.id).publication_count,before.publication_count+2);const sealed=page.waitForResponse(r=>r.url().endsWith('/rpc/erp_cp7_get_report_request_v1'));await reports.getByRole('button',{name:'Periksa hasil laporan tersimpan',exact:true}).click();const seal=await sealed;assert.equal(seal.status(),200);assert.deepEqual(seal.request().postDataJSON(),negative);assert.equal((await seal.json()).status,'CLOSED_UNCOMMITTED');await ui.expect(reports.getByText('Server memastikan permintaan lama belum tersimpan dan sudah ditutup. Periksa sumber sebelum menyimpan permintaan baru.',{exact:true})).toBeVisible();assert.equal(state(user.user.id).publication_count,before.publication_count+2);assert.ok(state(user.user.id).requests.some(r=>r[0]===negative.p_request&&r[1]==='CLOSED_UNCOMMITTED'));await savedShot(`P15_PUBLICATION_ABSENT_${suffix}.png`)
  await reports.getByLabel('Judul laporan tersimpan',{exact:true}).fill('Judul operator belum dikirim');await reports.getByLabel('Alasan laporan tersimpan',{exact:true}).fill('Catatan operator tetap utuh');fixture('update_schedule',{today});assert.equal((await list()).status(),200);const opened=page.waitForResponse(r=>r.url().endsWith('/rpc/erp_cp7_read_report_v1'));await reports.getByRole('button',{name:'Buka laporan tersimpan 1',exact:true}).click();const archive=await opened;assert.equal(archive.status(),200);const old=await archive.json();assert.equal(old.id,two.id);assert.equal(old.source_state,'ARCHIVED_STALE');assert.equal(old.body,two.body);assert.deepEqual(old.analysis.analysis,original.analysis);await ui.expect(reports.getByLabel('Teks laporan tersimpan',{exact:true})).toHaveText(two.body);assert.equal(await reports.getByLabel('Judul laporan tersimpan',{exact:true}).inputValue(),'Judul operator belum dikirim');await savedShot(`P15_PUBLICATION_ARCHIVED_${suffix}.png`)
  fixture('deactivate',{actor:user.user.id});const parent=page.waitForResponse(r=>r.url().endsWith('/rpc/erp_cp7_get_fg_v1'));assert.equal((await list()).status(),403);assert.equal((await parent).status(),403);await ui.expect(reports.getByLabel('Teks laporan tersimpan',{exact:true})).toHaveCount(0);await ui.expect(reports.getByRole('article',{name:'Perbandingan laporan ERP',exact:true})).toHaveCount(0);await ui.expect(reports.getByRole('button',{name:'Buka laporan tersimpan 1',exact:true})).toHaveCount(0);await ui.expect(panel.locator('.native-analysis-result')).toHaveCount(0);await ui.expect(page.locator('.cfg-totals')).toHaveCount(0);assert.equal(await reports.getByLabel('Judul laporan tersimpan',{exact:true}).inputValue(),'Judul operator belum dikirim');assert.equal(await reports.getByLabel('Alasan laporan tersimpan',{exact:true}).inputValue(),'Catatan operator tetap utuh');assert.equal(await dirty.inputValue(),'P15 ISIAN GUDANG TETAP');await savedShot(`P15_PUBLICATION_REVOKED_${suffix}.png`)
  fixture('restore',{actor:user.user.id});assert.equal((await list()).status(),200);const restored=page.waitForResponse(r=>r.url().endsWith('/rpc/erp_cp7_read_report_v1'));await reports.getByRole('button',{name:'Buka laporan tersimpan 2',exact:true}).click();const reopened=await restored;assert.equal(reopened.status(),200);assert.equal((await reopened.json()).body,one.body);assert.equal(state(user.user.id).publication_count,before.publication_count+2)
  assert.equal(await page.evaluate(()=>Object.keys(localStorage).filter(k=>k.startsWith('erp.cp7.report-request.v1:')).length),0)
  return{status:'PASS',actual_Auth_Native_publication_lost_reply_remount_exact_UUID_one_document:true,immutable_linked_second_revision_and_original_first_body:true,Native_unknown_comparison_not_zero:true,negative_lookup_seals_unsent_old_UUID_without_publication:true,actual_SourceChanged_keeps_frozen_body_and_draft_fields:true,current403_retires_all_report_index_comparison_analysis_and_parent_FG_HPP:true,no_report_financial_fact_cache_or_native_business_DML:true,desktop_and_foreign_timezone_mobile:true,screenshots:shots}
 }catch(e){writeFileSync(`cp6-proof/t3/P15_PUBLICATION_${suffix}_FAILURE.json`,JSON.stringify({error:String(e),text:await panel.innerText().catch(()=>''),original,lost,one,two,negative},null,2));await page.screenshot({path:`cp6-proof/t3/P15_PUBLICATION_${suffix}_FAILURE.png`,fullPage:true}).catch(()=>{});throw e}
 finally{fixture('restore',{actor:user.user.id});await user.context.close()}
}
export function cases(ui,today){return[['P15_BROWSER_DESKTOP_NATIVE_PUBLICATION',()=>journey(ui,today,false)],['P15_BROWSER_MOBILE_NATIVE_PUBLICATION',()=>journey(ui,today,true)]]}
