import assert from 'node:assert/strict'
import {execFileSync} from 'node:child_process'
import {mkdirSync,writeFileSync} from 'node:fs'
const fixture=(op,p)=>JSON.parse(execFileSync('python',['../auditor/scripts/cp7_f04_material_browser_fixture.py',op],{input:JSON.stringify(p),cwd:'../writer',encoding:'utf8',maxBuffer:16*1024*1024}).trim())
async function navigate(page){await page.locator('.sidebar .nav-main').filter({hasText:'Gudang'}).waitFor({state:'attached'});const menu=page.getByRole('button',{name:'Buka menu',exact:true});if(await menu.isVisible())await menu.click();const link=page.getByRole('button',{name:'• Ringkasan Barang Jadi',exact:true});if(!await link.isVisible())await page.locator('.sidebar .nav-main').filter({hasText:'Gudang'}).click();await link.click()}
async function journey(ui,today,mobile){
 const f=fixture('prepare',{today}),user=await ui.login('OWNER',{label:'p06-material-'+mobile,mobile,timezoneId:mobile?'America/Los_Angeles':'Asia/Jakarta'}),page=user.page,suffix=mobile?'MOBILE':'DESKTOP',panel=page.getByRole('region',{name:'Analisis ERP bersama',exact:true}),history=page.getByRole('region',{name:'Data permintaan ERP',exact:true}),materials=panel.getByRole('region',{name:'Kebutuhan bahan dari BOM ERP',exact:true}),screenshots=[]
 const state=()=>fixture('state',{actor:user.user.id});let original=null,fresh=null
 async function shot(name){await ui.expect.poll(()=>page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);await page.screenshot({path:'cp6-proof/t3/'+name,fullPage:true});screenshots.push(name)}
 async function capture(){const pending=page.waitForResponse(r=>r.url().endsWith('/rpc/erp_cp7_capture_analysis_v1'));await panel.getByRole('button',{name:'Ambil analisis ERP terbaru',exact:true}).click();const r=await pending;assert.equal(r.status(),200);return r.json()}
 async function filter(e){const target=e.analysis.recommendations.find(r=>r.target.product_id===f.product);assert.equal(target.q_conditional.value,'93');await panel.getByLabel('Cari hasil analisis bersama',{exact:true}).fill(e.product_labels.find(l=>l.target_key===target.target.key).sku);return target}
 function row(e){const r=e.analysis.material_needs.find(m=>m.target_key.split(':')[0]===f.product&&m.material_key==='ACCESSORY_CATEGORY:'+f.category_id);assert.equal(r.gross.state,'ASSUMED');assert.equal(r.gross.unit,f.unit);for(const k of['installed_proven','unused_allocated_proven','additional_external']){assert.equal(r[k].state,'UNKNOWN');assert.equal(r[k].value,undefined)}assert.ok(r.gross.refs.some(r=>r.kind==='erp.accessory_bom_versions'));return r}
 try{
  mkdirSync('cp6-proof/t3',{recursive:true});await navigate(page);const dirty=page.getByLabel('Cari barang jadi',{exact:true});await dirty.fill('P06 MATERIAL ISIAN GUDANG');await history.getByRole('button',{name:'Data permintaan & stok',exact:true}).click();await history.getByRole('button',{name:'Analisis, laporan & pengingat seluruh produk',exact:true}).click();const before=state()
  original=await capture();await filter(original);assert.equal(Number(row(original).gross.value),186);await ui.expect(materials.locator('article')).toHaveCount(2);await ui.expect(materials.locator('article').filter({hasText:'Pengeluaran bukan pemasangan'})).toHaveCount(1);await ui.expect(materials).toContainText('Resep kain untuk produk dan ukuran ini belum direview');await ui.expect(materials).toContainText('Pengeluaran bukan pemasangan');await ui.expect(materials).toContainText('Belum diketahui');assert.equal(state().analysis_count,before.analysis_count+1);assert.deepEqual(state().business,before.business);await shot(`P06_MATERIAL_BOM186_${suffix}.png`)
  await panel.getByRole('tab',{name:'Laporan',exact:true}).click();await ui.expect(panel.getByLabel('Isi laporan ERP',{exact:true})).toContainText('erp.accessory_bom_items');await panel.getByRole('tab',{name:'Produksi',exact:true}).click();assert.equal(state().analysis_count,before.analysis_count+1)
  fixture('successor',{...f,run:original.run_id,actor:user.user.id});const changedState=state(),pending=page.waitForResponse(r=>r.url().endsWith('/rpc/erp_cp7_read_analysis_v1'));await panel.getByRole('button',{name:'Periksa sumber analisis',exact:true}).click();const response=await pending;assert.equal(response.status(),200);const archived=await response.json();assert.equal(archived.source_state,'ARCHIVED_STALE');assert.deepEqual(archived.analysis,original.analysis);assert.equal(Number(row(archived).gross.value),186);await ui.expect(panel).toContainText('Arsip lama: sumber berubah.');await shot(`P06_MATERIAL_ARCHIVE186_${suffix}.png`)
  fresh=await capture();await filter(fresh);assert.equal(Number(row(fresh).gross.value),279);assert.notEqual(fresh.analysis.snapshot.source_hash,original.analysis.snapshot.source_hash);assert.deepEqual(state().business,changedState.business);await shot(`P06_MATERIAL_FRESH279_${suffix}.png`)
  fixture('deactivate',{actor:user.user.id});const denied=page.waitForResponse(r=>r.url().endsWith('/rpc/erp_cp7_read_analysis_v1')),parent=page.waitForResponse(r=>r.url().endsWith('/rpc/erp_cp7_get_fg_v1'));await panel.getByRole('button',{name:'Periksa sumber analisis',exact:true}).click();assert.equal((await denied).status(),403);assert.equal((await parent).status(),403);await ui.expect(materials).toHaveCount(0);await ui.expect(panel.locator('.native-analysis-result')).toHaveCount(0);await ui.expect(page.locator('.cfg-totals')).toHaveCount(0);assert.equal(await dirty.inputValue(),'P06 MATERIAL ISIAN GUDANG');await shot(`P06_MATERIAL_REVOKED_${suffix}.png`)
  return{status:'PASS',actual_Auth_Native_BOM2_times_gap93_equals186:true,installed_allocated_external_remain_UNKNOWN:true,report_and_UI_one_Original:true,lawful_Native_successor_archives186_fresh279:true,all_business_state_unchanged_by_reads:true,current403_retires_material_and_parent_FG_HPP:true,dirty_stock_input_retained:true,screenshots}
 }catch(e){writeFileSync(`cp6-proof/t3/P06_MATERIAL_${suffix}_FAILURE.json`,JSON.stringify({error:String(e),text:await panel.innerText().catch(()=>''),original,fresh},null,2));await page.screenshot({path:`cp6-proof/t3/P06_MATERIAL_${suffix}_FAILURE.png`,fullPage:true}).catch(()=>{});throw e}
 finally{fixture('restore',{actor:user.user.id});await user.context.close()}
}
export function cases(ui,today){return[['P06_MATERIAL_BROWSER_DESKTOP',()=>journey(ui,today,false)],['P06_MATERIAL_BROWSER_MOBILE',()=>journey(ui,today,true)]]}
