"""Exact old/new full compiler control on the same immutable Native facts.

The predecessor definition exists only in a rolled-back savepoint. No result,
ACL, Native fact, request count or HTTP timeout is replaced or relaxed.
"""
import hashlib
from time import monotonic

OLD_TIMELINE = "  for event in select value from jsonb_array_elements(coalesce(r->'timeline'->'events','[]'))loop\n   -- Each chronological Native kernel event is retained as an intraday row;\n   -- same-day events are not collapsed into a fabricated end-day net.\n   e:=event->'event';\n   supply_match:=null;\n   if e->>'kind'='SUPPLY'then\n    select x->>'match'into supply_match from jsonb_array_elements(coalesce(n->'allocation'->'allocation'->'edges','[]'))x\n     where 'supply-'||(x->>'key')=e->>'key'and x->>'target_key'=r->>'target_key';\n    if supply_match is null and exists(select 1 from jsonb_array_elements(n->'match_results')x\n     where 'supply-'||(x->>'position_key')=e->>'key'and x->>'target_key'=r->>'target_key'and x->'result'->>'match'='CONFIRMED_TARGET')then\n     supply_match:='CONFIRMED_TARGET';end if;\n   end if;\n   timeline:=timeline||jsonb_build_array(jsonb_build_object('date',((e->>'at')::timestamptz at time zone 'Asia/Jakarta')::date::text,\n    'target_key',r->'target_key','demand',cp7_analysis_native.fact(case when e->>'kind'='DEMAND'then e->>'qty_pcs'else '0'end,'PCS',e->'refs',row_aids),\n    'directed_supply',cp7_analysis_native.fact(case when e->>'kind'='DEMAND'or supply_match='CANDIDATE_MATCH'then '0'\n     when supply_match='CONFIRMED_TARGET'then e->>'qty_pcs'else null end,'PCS',e->'refs',row_aids),\n    'candidate_supply',cp7_analysis_native.fact(case when e->>'kind'='DEMAND'or supply_match='CONFIRMED_TARGET'then '0'\n     when supply_match='CANDIDATE_MATCH'then e->>'qty_pcs'else null end,'PCS',e->'refs',row_aids),\n    'proposed_new_supply',cp7_analysis_native.fact(null,'PCS',e->'refs'),'balance_end',cp7_analysis_native.fact(event->>'balance_pcs','PCS',e->'refs',row_aids),\n    'mode','BACKLOG','assumed',true,'unmet_demand',cp7_analysis_native.fact(event->>'new_unmet_pcs','PCS',e->'refs',row_aids),\n    'backlog_qty',cp7_analysis_native.fact(case when event->>'balance_pcs'is not null then greatest(0,-(event->>'balance_pcs')::numeric)::text else null end,'PCS',e->'refs',row_aids),\n    'min_intraday_balance',cp7_analysis_native.fact(r->'timeline'->>'minimum_balance_pcs','PCS',e->'refs',row_aids),\n    'first_gap_at',r->'timeline'->'first_known_gap'->'at','timing_basis','DATE_POLICY',\n    'timing_policy_id','selected-native-each24h-from-capture-1','event_refs',e->'refs'));\n  end loop;"
NEW_TIMELINE = "  -- Build each chronological row once in original event order. Repeated\n  -- concatenation copied the entire growing multi-target timeline per event.\n  -- This aggregate retains every row, field, reference and decimal operand.\n  with events as materialized(\n   select x.value event,x.value->'event' e,x.ordinality ordinal\n    from jsonb_array_elements(coalesce(r->'timeline'->'events','[]'))with ordinality x),\n  classified as materialized(\n   select events.*,case when events.e->>'kind'='SUPPLY'then coalesce(\n    (select x->>'match'from jsonb_array_elements(coalesce(n->'allocation'->'allocation'->'edges','[]'))x\n     where 'supply-'||(x->>'key')=events.e->>'key'and x->>'target_key'=r->>'target_key'limit 1),\n    case when exists(select 1 from jsonb_array_elements(n->'match_results')x\n     where 'supply-'||(x->>'position_key')=events.e->>'key'and x->>'target_key'=r->>'target_key'and x->'result'->>'match'='CONFIRMED_TARGET')then'CONFIRMED_TARGET'end)\n    else null end supply_match from events)\n  select coalesce(jsonb_agg(jsonb_build_object('date',((t.e->>'at')::timestamptz at time zone 'Asia/Jakarta')::date::text,\n    'target_key',r->'target_key','demand',cp7_analysis_native.fact(case when t.e->>'kind'='DEMAND'then t.e->>'qty_pcs'else '0'end,'PCS',t.e->'refs',row_aids),\n    'directed_supply',cp7_analysis_native.fact(case when t.e->>'kind'='DEMAND'or t.supply_match='CANDIDATE_MATCH'then '0'\n     when t.supply_match='CONFIRMED_TARGET'then t.e->>'qty_pcs'else null end,'PCS',t.e->'refs',row_aids),\n    'candidate_supply',cp7_analysis_native.fact(case when t.e->>'kind'='DEMAND'or t.supply_match='CONFIRMED_TARGET'then '0'\n     when t.supply_match='CANDIDATE_MATCH'then t.e->>'qty_pcs'else null end,'PCS',t.e->'refs',row_aids),\n    'proposed_new_supply',cp7_analysis_native.fact(null,'PCS',t.e->'refs'),'balance_end',cp7_analysis_native.fact(t.event->>'balance_pcs','PCS',t.e->'refs',row_aids),\n    'mode','BACKLOG','assumed',true,'unmet_demand',cp7_analysis_native.fact(t.event->>'new_unmet_pcs','PCS',t.e->'refs',row_aids),\n    'backlog_qty',cp7_analysis_native.fact(case when t.event->>'balance_pcs'is not null then greatest(0,-(t.event->>'balance_pcs')::numeric)::text else null end,'PCS',t.e->'refs',row_aids),\n    'min_intraday_balance',cp7_analysis_native.fact(r->'timeline'->>'minimum_balance_pcs','PCS',t.e->'refs',row_aids),\n    'first_gap_at',r->'timeline'->'first_known_gap'->'at','timing_basis','DATE_POLICY',\n    'timing_policy_id','selected-native-each24h-from-capture-1','event_refs',t.e->'refs')order by t.ordinal),'[]'::jsonb)into target_timeline from classified t;\n  timeline:=timeline||target_timeline;"

def compare(cur, run, api):
 api.admin(cur)
 source,query,actor,expected=cur.execute('select facts::text,query::text,access_at_capture::text,result::text from cp7_analysis_native.runs where id=%s',(run,)).fetchone()
 signature='cp7_analysis_native.build_operational(jsonb,jsonb,uuid,jsonb)'
 definition=cur.execute('select pg_get_functiondef(%s::regprocedure)',(signature,)).fetchone()[0]
 assert definition.count(NEW_TIMELINE)==1 and definition.count('target_timeline jsonb;')==1,'UNEXPECTED_TIMELINE_CANDIDATE'
 predecessor=definition.replace(NEW_TIMELINE,OLD_TIMELINE).replace('target_timeline jsonb;','')
 sql='select cp7_analysis_native.build(%s::jsonb,%s::jsonb,%s,%s::jsonb)::text'
 args=(source,query,run,actor);elapsed={}
 cur.execute('savepoint compile_timeline_control')
 try:
  cur.execute('set local role cp7_capture');started=monotonic();candidate=cur.execute(sql,args).fetchone()[0];elapsed['candidate_ms']=round((monotonic()-started)*1000)
  assert candidate==expected,'CURRENT_PURE_COMPILER_NOT_IDENTICAL_TO_SAVED_ORIGINAL'
  api.admin(cur);cur.execute(predecessor,prepare=False);cur.execute('set local role cp7_capture');started=monotonic();old=cur.execute(sql,args).fetchone()[0];elapsed['predecessor_ms']=round((monotonic()-started)*1000)
  assert old==candidate,'TIMELINE_FULL_COMPILER_BYTE_DIFFERENCE'
 finally:
  cur.execute('rollback to savepoint compile_timeline_control');cur.execute('release savepoint compile_timeline_control');api.admin(cur)
 assert cur.execute('select pg_get_functiondef(%s::regprocedure)',(signature,)).fetchone()[0]==definition
 return dict(status='BYTE_IDENTICAL',utf8_bytes=len(candidate.encode()),sha256=hashlib.sha256(candidate.encode()).hexdigest(),definition_restored=True,Native_HTTP_timeout_changed=False,**elapsed)
