import assert from'node:assert/strict'
import{execFileSync}from'node:child_process'
import{mkdirSync,writeFileSync}from'node:fs'
const fixture=(op,p)=>JSON.parse(execFileSync('python',['../auditor/scripts/cp7_f04_plan_browser_fixture.py',op],{input:JSON.stringify(p),cwd:'../writer',encoding:'utf8',maxBuffer:16*1024*1024}).trim())
async function navigate(page){await page.locator('.sidebar .nav-main').filter({hasText:'Gudang'}).waitFor({state:'attached'});const menu=page.getByRole('button',{name:'Buka menu',exact:true});if(await menu.isVisible())await menu.click();const link=page.getByRole('button',{name:'• Ringkasan Barang Jadi',exact:true});if(!await link.isVisible())await page.locator('.sidebar .nav-main').filter({hasText:'Gudang'}).click();await link.click()}
async function response(page,name,action){const[request]=await Promise.all([page.waitForRequest(r=>r.method()==='POST'&&r.url().endsWith('/rpc/'+name)),action()]);const result=await request.response();assert.ok(result,'The new Native request must receive its own response');return result}
function wib(t){return new Date(Date.parse(t)+7*3600000).toISOString().slice(0,19)}
async function journey(ui,today,mobile,actualCheck=false){
 const user=await ui.login('OWNER',{label:'p08-native-plan-'+mobile,mobile,timezoneId:'America/Los_Angeles'}),page=user.page,suffix=(mobile?'MOBILE':'DESKTOP')+(actualCheck?'_ACTUAL':''),shots=[]
 const f=fixture('prepare',{today,actor:user.user.id,actual_check:actualCheck}),state=()=>fixture('state',{actor:user.user.id}),history=page.getByRole('region',{name:'Data permintaan ERP',exact:true}),analysis=page.getByRole('region',{name:'Analisis ERP bersama',exact:true}),panel=page.getByRole('region',{name:'Rencana Potongan ERP',exact:true})
 let lost=null,original=null,options=null
 const shot=async name=>{await ui.expect.poll(()=>page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);await page.screenshot({path:'cp6-proof/t3/'+name,fullPage:true});shots.push(name)}
 async function open(){await navigate(page);await history.getByRole('button',{name:'Data permintaan & stok',exact:true}).click();await history.getByRole('button',{name:'Analisis, laporan & pengingat seluruh produk',exact:true}).click();const r=await response(page,'erp_cp7_capture_analysis_v1',()=>analysis.getByRole('button',{name:'Ambil analisis ERP terbaru',exact:true}).click());assert.equal(r.status(),200);original=await r.json();const label=original.product_labels.find(x=>x.target_key===f.payload.target_key);assert.ok(label);await analysis.getByLabel('Cari hasil analisis bersama',{exact:true}).fill(label.sku);await analysis.getByRole('button',{name:/^Rencanakan Potongan /}).click()}
 try{
  mkdirSync('cp6-proof/t3',{recursive:true});await open();const dirty=page.getByLabel('Cari barang jadi',{exact:true});await dirty.fill('P08 ISIAN GUDANG TETAP');const before=state();assert.equal(before.drafts,0);assert.equal(before.intents,0)
  let r=await response(page,'erp_cp7_get_plan_options_v1',()=>panel.getByRole('button',{name:'Muat pilihan Potongan dari ERP',exact:true}).click());assert.equal(r.status(),200);await panel.getByLabel('Gudang bahan rencana',{exact:true}).selectOption(f.payload.cutting.source_location_id)
  r=await response(page,'erp_cp7_get_plan_options_v1',()=>panel.getByRole('button',{name:'Muat pilihan Potongan dari ERP',exact:true}).click());assert.equal(r.status(),200);options=await r.json();const roll=options.rolls.find(x=>x.id===f.payload.cutting.rolls[0].roll_id);assert.ok(roll)
  await panel.getByLabel('PO rencana',{exact:true}).selectOption(f.payload.cutting.po_id);await panel.getByLabel('Pola rencana',{exact:true}).selectOption(f.payload.cutting.pattern_id);await panel.getByLabel('Waktu pencatatan draf WIB',{exact:true}).fill(wib(f.payload.cutting.cut_at));await panel.getByRole('button',{name:'Pilih roll '+roll.number,exact:true}).click()
  for(const[name,value]of[['Keluar roll rencana 1','1'],['Terpakai roll rencana 1','0.5'],['Sisa roll rencana 1','0.5'],['Hasil roll rencana 1','2']])await panel.getByLabel(name,{exact:true}).fill(value)
  await panel.getByLabel('Alasan rencana Potongan',{exact:true}).fill('Native P08 browser reviewed draft only');await panel.getByLabel('Asumsi dan komposisi rencana sudah diperiksa',{exact:true}).check()
  r=await response(page,'erp_cp7_save_plan_draft_v1',()=>panel.getByRole('button',{name:'Simpan rencana Potongan',exact:true}).click());assert.equal(r.status(),200);const saved=await r.json();await ui.expect(panel.getByRole('button',{name:'Periksa pratinjau rencana',exact:true})).toBeEnabled();assert.equal(state().drafts,1);assert.equal(state().domain_drafts,before.domain_drafts);assert.equal(state().ledger_hash,before.ledger_hash)
  r=await response(page,'erp_cp7_preview_plan_action_v1',()=>panel.getByRole('button',{name:'Periksa pratinjau rencana',exact:true}).click());assert.equal(r.status(),200);const preview=await r.json();assert.equal(preview.selected_new_pcs,'2');assert.equal(preview.reservation_created,false);await shot(`P08_NATIVE_PREVIEW_${suffix}.png`)
  await panel.getByLabel('Alasan membuat draf Potongan',{exact:true}).fill('One explicit Native draft, no posting or reservation');await panel.getByLabel('Pratinjau sudah diperiksa untuk membuat draf',{exact:true}).check();await page.route('**/rest/v1/rpc/erp_cp7_apply_plan_action_v1',async route=>{if(!lost){const rr=await route.fetch();assert.equal(rr.status(),200);lost={envelope:route.request().postDataJSON(),body:await rr.json()};await route.abort('failed')}else await route.continue()})
  await panel.getByRole('button',{name:'Buat draf Potongan di ERP',exact:true}).click();await ui.expect(panel.getByRole('button',{name:'Reconcile transaksi',exact:true})).toBeEnabled();assert.equal(state().intents,1);assert.equal(state().domain_drafts,before.domain_drafts+1);assert.equal(state().ledger_hash,before.ledger_hash);await shot(`P08_NATIVE_UNCERTAIN_${suffix}.png`)
  await page.reload();await open();r=await response(page,'erp_cp7_apply_plan_action_v1',()=>panel.getByRole('button',{name:'Reconcile transaksi',exact:true}).click());assert.equal(r.status(),200);assert.deepEqual(r.request().postDataJSON(),lost.envelope);assert.deepEqual(await r.json(),lost.body);await ui.expect(panel).toContainText('draf Potongan sudah dibuat');assert.equal(state().intents,1);assert.equal(state().domain_drafts,before.domain_drafts+1);assert.equal(state().ledger_hash,before.ledger_hash);await shot(`P08_NATIVE_RECONCILED_${suffix}.png`)
  if(actualCheck){
   const actualRegion=panel.getByLabel('Perbandingan rencana dan hasil produksi',{exact:true})
   const compare=async()=>{const beforeRead=state();const rr=await response(page,'erp_cp7_read_plan_actual_v1',()=>panel.getByRole('button',{name:'Bandingkan rencana dengan hasil produksi',exact:true}).click());assert.equal(rr.status(),200);const body=await rr.json();await ui.expect(actualRegion).toBeVisible();assert.deepEqual(state(),beforeRead);return body}
   let compared=await compare();assert.equal(compared.actual.state,'NOT_STARTED');assert.equal(compared.actual.facts.input_pcs.value,'0');assert.equal(compared.planned_pcs,'2');await shot(`P08_ACTUAL_UNPOSTED_${suffix}.png`)
   const progress={actor:user.user.id,draft_id:saved.draft_id,vendor_id:f.fixture.vendor,process_id:f.fixture.process}
   fixture('actual_progress',{...progress,stage:'POST'});compared=await compare();assert.equal(compared.actual.state,'COMPLETE');assert.equal(compared.actual.facts.input_pcs.value,'2');assert.equal(compared.actual.facts.wip_pcs.value,'2');assert.equal(compared.actual.facts.matched_fg_pcs.value,'0');assert.equal(compared.actual.original_source_state,'ARCHIVED_STALE')
   fixture('actual_progress',{...progress,stage:'QC_ONE'});compared=await compare();assert.equal(compared.actual.facts.input_pcs.value,'2');assert.equal(compared.actual.facts.wip_pcs.value,'1');assert.equal(compared.actual.facts.matched_fg_pcs.value,'1');assert.equal(compared.remaining_to_plan_pcs.value,'1');await ui.expect(actualRegion).toContainText('Sumber rencana lama sudah berubah');await ui.expect(actualRegion).toContainText('rincian potong dan jahit belum terbukti');await shot(`P08_ACTUAL_PARTIAL_QC_${suffix}.png`)
  }
  await dirty.fill('P08 ISIAN GUDANG TETAP');await panel.getByLabel('Catatan rencana Potongan',{exact:true}).fill('P08 catatan sendiri belum dikirim');fixture('deactivate',{actor:user.user.id})
  const[denied,parent]=await Promise.all([page.waitForRequest(r=>r.method()==='POST'&&r.url().endsWith('/rpc/'+(actualCheck?'erp_cp7_read_plan_actual_v1':'erp_cp7_read_plan_draft_v1'))).then(r=>r.response()),page.waitForRequest(r=>r.method()==='POST'&&r.url().endsWith('/rpc/erp_cp7_get_fg_v1')).then(r=>r.response()),panel.getByRole('button',{name:actualCheck?'Bandingkan rencana dengan hasil produksi':'Muat rencana tersimpan',exact:true}).click()]);assert.ok(denied);assert.ok(parent);assert.equal(denied.status(),403);assert.equal(parent.status(),403);await ui.expect(panel.locator('.native-plan-result')).toHaveCount(0);await ui.expect(page.locator('.cfg-totals')).toHaveCount(0);assert.equal(await dirty.inputValue(),'P08 ISIAN GUDANG TETAP');assert.equal(await panel.getByLabel('Catatan rencana Potongan',{exact:true}).inputValue(),'P08 catatan sendiri belum dikirim');await shot(`P08_NATIVE_REVOKED_${suffix}.png`)
  return{status:'PASS',actual_Auth_Native_context_choices_draft_and_preview:true,actual_Native_domain_and_intent_atomic_reply_loss_reload_exact_UUID:true,stock_money_HPP_unchanged_no_reservation_or_physical_confirmation:true,current403_retires_prepared_facts_parent_FG_HPP_preserves_own_notes:true,foreign_timezone_desktop_mobile:true,linked_Native_plan_actual_cut_two_WIP_one_FG_one:actualCheck,saved_draft:saved.draft_id,screenshots:shots}
 }catch(e){writeFileSync(`cp6-proof/t3/P08_NATIVE_${suffix}_FAILURE.json`,JSON.stringify({error:String(e),text:(await panel.innerText().catch(()=>'' )).slice(0,16000),lost,originalRun:original?.run_id,options},null,2));await page.screenshot({path:`cp6-proof/t3/P08_NATIVE_${suffix}_FAILURE.png`,fullPage:true}).catch(()=>{});throw e}
 finally{fixture('restore',{actor:user.user.id});await user.context.close()}
}
export function cases(ui,today){return[['P08_BROWSER_DESKTOP_NATIVE_DRAFT',()=>journey(ui,today,false)],['P08_BROWSER_MOBILE_NATIVE_DRAFT',()=>journey(ui,today,true)],['P08_BROWSER_DESKTOP_NATIVE_ACTUAL',()=>journey(ui,today,false,true)],['P08_BROWSER_MOBILE_NATIVE_ACTUAL',()=>journey(ui,today,true,true)]]}
