import assert from'node:assert/strict'
import{execFileSync}from'node:child_process'
import{mkdirSync,writeFileSync}from'node:fs'
const fixture=(op,p)=>JSON.parse(execFileSync('python',['../auditor/scripts/cp7_f05_analysis_browser_fixture.py',op],{input:JSON.stringify(p),cwd:'../writer',encoding:'utf8',maxBuffer:16*1024*1024}).trim())
const state=p=>JSON.parse(execFileSync('python',['../auditor/scripts/cp7_f05_policy_browser_fixture.py','state'],{input:JSON.stringify(p),cwd:'../writer',encoding:'utf8'}).trim())
async function navigate(page){await page.locator('.sidebar .nav-main').filter({hasText:'Gudang'}).waitFor({state:'attached'});const menu=page.getByRole('button',{name:'Buka menu',exact:true});if(await menu.isVisible())await menu.click();const link=page.getByRole('button',{name:'• Ringkasan Barang Jadi',exact:true});if(!await link.isVisible())await page.locator('.sidebar .nav-main').filter({hasText:'Gudang'}).click();await link.click()}
async function journey(ui,today,mobile){
 fixture('prepare',{today});const user=await ui.login('OWNER',{label:'p16-policy-'+mobile,mobile,timezoneId:'America/Los_Angeles'}),page=user.page,suffix=mobile?'MOBILE':'DESKTOP',panel=page.getByRole('region',{name:'Analisis ERP bersama',exact:true}),history=page.getByRole('region',{name:'Data permintaan ERP',exact:true}),policies=panel.getByRole('region',{name:'Pengaturan aturan pengingat',exact:true}),screenshots=[]
 let original=null,lost=null,lastReply=null,routeError=null
 const current=()=>state({actor:user.user.id}),shot=async name=>{await ui.expect.poll(()=>page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);await page.screenshot({path:'cp6-proof/t3/'+name,fullPage:true});screenshots.push(name)}
 const load=async()=>{const pending=page.waitForResponse(r=>r.url().endsWith('/rpc/erp_cp7_get_reminder_policy_v1'));await policies.getByRole('button',{name:'Muat pengaturan pengingat',exact:true}).click();const r=await pending;assert.equal(r.status(),200);const e=await r.json();assert.deepEqual(e.analysis.analysis,original.analysis);return e}
 try{
  mkdirSync('cp6-proof/t3',{recursive:true});await navigate(page);const dirty=page.getByLabel('Cari barang jadi',{exact:true});await dirty.fill('P16 PENGATURAN ISIAN GUDANG');await history.getByRole('button',{name:'Data permintaan & stok',exact:true}).click();await history.getByRole('button',{name:'Analisis, laporan & pengingat seluruh produk',exact:true}).click()
  const capture=page.waitForResponse(r=>r.url().endsWith('/rpc/erp_cp7_capture_analysis_v1'));await panel.getByRole('button',{name:'Ambil analisis ERP terbaru',exact:true}).click();const c=await capture;assert.equal(c.status(),200);original=await c.json();const before=current();await panel.getByRole('tab',{name:'Pengingat',exact:true}).click();await load();assert.equal(current().policy_count,before.policy_count);assert.equal(await policies.getByLabel('Batas pengingat',{exact:true}).inputValue(),'');assert.equal(await policies.getByLabel('Jeda pengingat dalam menit',{exact:true}).inputValue(),'');await shot(`P16_POLICY_NULL_${suffix}.png`)
  await policies.getByLabel('Status aturan',{exact:true}).selectOption('false');await policies.getByLabel('Batas pengingat',{exact:true}).fill('0');await policies.getByLabel('Jeda pengingat dalam menit',{exact:true}).fill('0');await policies.getByLabel('Waktu tenang',{exact:true}).selectOption('false');await policies.getByLabel('Alasan perubahan pengingat',{exact:true}).fill('Explicit Native browser decision '+suffix);await policies.getByLabel('Pengaturan pengingat sudah ditinjau',{exact:true}).check()
  await page.route('**/rest/v1/rpc/erp_cp7_save_reminder_policy_v1',async route=>{try{if(!lost){const r=await route.fetch();assert.equal(r.status(),200);lost={envelope:route.request().postDataJSON(),body:await r.json()};await route.abort('failed')}else await route.continue()}catch(error){routeError=error;await route.abort('failed').catch(()=>{})}})
  // Wait for the actual committed-response loss, not merely the pending-intent
  // button created while the Native source read is still running. The UI must
  // remain locked during that read; 5s is not a transaction-completion proof.
  const failed=page.waitForEvent('requestfailed',{predicate:r=>r.url().endsWith('/rpc/erp_cp7_save_reminder_policy_v1'),timeout:60000})
  await policies.getByRole('button',{name:'Simpan versi pengaturan pengingat',exact:true}).click();await failed;if(routeError)throw routeError;assert.ok(lost);await ui.expect(policies.getByRole('button',{name:'Pastikan hasil pengaturan di server',exact:true})).toBeEnabled();assert.equal(current().policy_count,before.policy_count+1);await shot(`P16_POLICY_UNCERTAIN_${suffix}.png`)
  await panel.getByRole('button',{name:'Tutup analisis bersama',exact:true}).click();await history.getByRole('button',{name:'Analisis, laporan & pengingat seluruh produk',exact:true}).click();const lookup=page.waitForResponse(r=>r.url().endsWith('/rpc/erp_cp7_get_reminder_policy_request_v1'));await policies.getByRole('button',{name:'Pastikan hasil pengaturan di server',exact:true}).click();const recovered=await lookup;assert.equal(recovered.status(),200);assert.deepEqual(recovered.request().postDataJSON(),lost.envelope);lastReply=await recovered.json();assert.deepEqual(lastReply.request_result,lost.body.request_result);assert.deepEqual(lastReply.analysis.analysis,original.analysis);assert.deepEqual(lastReply.analysis.financial_source,original.financial_source);assert.equal(current().policy_count,before.policy_count+1);await ui.expect(policies).toContainText('Status: dimatikan');assert.equal(await policies.getByLabel('Batas pengingat',{exact:true}).inputValue(),'');await shot(`P16_POLICY_RECOVERED_${suffix}.png`)
  await policies.getByRole('button',{name:'Isi formulir dari versi tersimpan',exact:true}).click();assert.equal(await policies.getByLabel('Status aturan',{exact:true}).inputValue(),'false');assert.equal(await policies.getByLabel('Batas pengingat',{exact:true}).inputValue(),'0');await policies.getByLabel('Status aturan',{exact:true}).selectOption('true');await policies.getByLabel('Waktu tenang',{exact:true}).selectOption('true');await policies.getByLabel('Mulai waktu tenang WIB',{exact:true}).fill('22:00');await policies.getByLabel('Akhir waktu tenang WIB',{exact:true}).fill('06:00');await policies.getByLabel('Alasan perubahan pengingat',{exact:true}).fill('Explicit overnight WIB review '+suffix);await policies.getByLabel('Pengaturan pengingat sudah ditinjau',{exact:true}).check();const save=page.waitForResponse(r=>r.url().endsWith('/rpc/erp_cp7_save_reminder_policy_v1'));await policies.getByRole('button',{name:'Simpan versi pengaturan pengingat',exact:true}).click();const saved=await save;assert.equal(saved.status(),200);lastReply=await saved.json();const row=lastReply.rows.find(p=>p.rule_id==='PRODUCTION_GAP'&&p.scope_kind==='GLOBAL');assert.equal(row.previous_id,lost.body.request_result.policy_id);assert.equal(BigInt(row.revision),BigInt(lost.body.request_result.revision)+1n);assert.deepEqual(row.config.quiet,{enabled:true,starts_at:'22:00',ends_at:'06:00',timezone:'Asia/Jakarta'});assert.equal(current().policy_count,before.policy_count+2);await shot(`P16_POLICY_WIB_HISTORY_${suffix}.png`)
  await policies.getByLabel('Batas pengingat',{exact:true}).fill('17');await policies.getByLabel('Alasan perubahan pengingat',{exact:true}).fill('P16 nilai operator belum disimpan');fixture('deactivate',{actor:user.user.id});const denied=page.waitForResponse(r=>r.url().endsWith('/rpc/erp_cp7_get_reminder_policy_v1')),parent=page.waitForResponse(r=>r.url().endsWith('/rpc/erp_cp7_get_fg_v1'));await policies.getByRole('button',{name:'Muat pengaturan pengingat',exact:true}).click();assert.equal((await denied).status(),403);assert.equal((await parent).status(),403);await ui.expect(panel.locator('.native-analysis-result')).toHaveCount(0);await ui.expect(page.locator('.cfg-totals')).toHaveCount(0);await ui.expect(policies).not.toContainText('Pengaturan diperiksa');assert.equal(await dirty.inputValue(),'P16 PENGATURAN ISIAN GUDANG');await shot(`P16_POLICY_REVOKED_${suffix}.png`)
  fixture('restore',{actor:user.user.id});await panel.getByText('Arsip analisis yang pernah dibuka',{exact:true}).click();await panel.getByRole('button',{name:'Buka arsip analisis 1',exact:true}).click();await panel.getByRole('tab',{name:'Pengingat',exact:true}).click();await load();assert.equal(await policies.getByLabel('Batas pengingat',{exact:true}).inputValue(),'17');assert.equal(await policies.getByLabel('Alasan perubahan pengingat',{exact:true}).inputValue(),'P16 nilai operator belum disimpan');assert.equal(current().analysis_count,before.analysis_count);assert.equal(current().native_manual_count,before.native_manual_count)
  return{status:'PASS',actual_Auth_explicit_NULL_zero_disabled_versioned_policy:true,committed_lost_reply_remount_exact_UUID_one_version:true,explicit_adoption_only_and_WIB_under_foreign_device_timezone:true,immutable_predecessor_reference_and_no_automatic_Native_task:true,current403_retires_policy_Original_parent_FG_HPP:true,unsent_operator_values_and_stock_search_retained:true,no_extra_Original_or_external_delivery:true,screenshots}
 }catch(e){writeFileSync(`cp6-proof/t3/P16_POLICY_${suffix}_FAILURE.json`,JSON.stringify({error:String(e),text:await panel.innerText().catch(()=>''),original,lost,lastReply},null,2));await page.screenshot({path:`cp6-proof/t3/P16_POLICY_${suffix}_FAILURE.png`,fullPage:true}).catch(()=>{});throw e}
 finally{await page.unrouteAll({behavior:'wait'});fixture('restore',{actor:user.user.id});await user.context.close()}
}
export function cases(ui,today){return[['P16_POLICY_BROWSER_DESKTOP',()=>journey(ui,today,false)],['P16_POLICY_BROWSER_MOBILE',()=>journey(ui,today,true)]]}
