import assert from'node:assert/strict'
import{execFileSync}from'node:child_process'
import{mkdirSync,writeFileSync}from'node:fs'
const fixture=(op,p)=>JSON.parse(execFileSync('python',['../auditor/scripts/cp7_f05_analysis_browser_fixture.py',op],{input:JSON.stringify(p),cwd:'../writer',encoding:'utf8',maxBuffer:16*1024*1024}).trim())
async function navigate(page){await page.locator('.sidebar .nav-main').filter({hasText:'Gudang'}).waitFor({state:'attached'});const menu=page.getByRole('button',{name:'Buka menu',exact:true});if(await menu.isVisible())await menu.click();const link=page.getByRole('button',{name:'• Ringkasan Barang Jadi',exact:true});if(!await link.isVisible())await page.locator('.sidebar .nav-main').filter({hasText:'Gudang'}).click();await link.click()}
async function journey(ui,today,mobile,automaticRequired=false){
 fixture('prepare',{today});const user=await ui.login('OWNER',{label:'p17-handoff-'+mobile,mobile,timezoneId:'America/Los_Angeles'}),page=user.page,suffix=(automaticRequired?'AUTO_':'')+(mobile?'MOBILE':'DESKTOP'),panel=page.getByRole('region',{name:'Analisis ERP bersama',exact:true}),history=page.getByRole('region',{name:'Data permintaan ERP',exact:true}),shots=[]
 let original=null,lastRead=null,explicitCaptures=0,clockArchives=0,initialCopyMode='AUTOMATIC',controlledDenialCount=0,byteBoundCount=0
 const state=()=>fixture('state',{actor:user.user.id}),manual=()=>panel.getByLabel('Salinan manual pertanyaan dan sumber ERP',{exact:true}),question='P17 periksa saldo 🧵 "asli" dan jangan mengarang HPP',readRpc='**/rest/v1/rpc/erp_cp7_read_analysis_v1'
 const shot=async name=>{await ui.expect.poll(()=>page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);await page.screenshot({path:'cp6-proof/t3/'+name,fullPage:true});shots.push(name)}
 const checked=async action=>{const before=state();const[r]=await Promise.all([page.waitForResponse(r=>r.url().endsWith('/rpc/erp_cp7_read_analysis_v1')),action()]);assert.equal(r.status(),200);lastRead=await r.json();assert.deepEqual(lastRead.analysis,original.analysis);assert.deepEqual(lastRead.financial_source,original.financial_source);assert.deepEqual(state(),before);return lastRead}
 const prepare=async denied=>{
  // A real minute boundary may archive the Original. The operator explicitly
  // captures again; the handoff itself must never silently recapture/recalculate.
  for(let attempt=0;attempt<3;attempt++){
   const before=state(),response=page.waitForResponse(r=>r.url().endsWith('/rpc/erp_cp7_capture_analysis_v1'));await panel.getByRole('button',{name:'Ambil analisis ERP terbaru',exact:true}).click();const r=await response;assert.equal(r.status(),200);original=await r.json();explicitCaptures++;assert.equal(state().analysis_count,before.analysis_count+1);assert.deepEqual(state().business,before.business)
   await panel.getByRole('tab',{name:'Tanya AI',exact:true}).click();await panel.getByLabel('Pertanyaan analisis ERP',{exact:true}).fill(question)
   const e=await checked(()=>panel.getByRole('button',{name:'Periksa & salin pertanyaan untuk AI',exact:true}).click())
   if(e.source_state==='ARCHIVED_STALE'){clockArchives++;await ui.expect(manual()).toHaveCount(0);continue}
   assert.equal(e.source_state,'UNCHANGED');await ui.expect(manual()).toBeVisible();const text=await manual().inputValue(),overBound=Buffer.byteLength(text,'utf8')>1000000;const message=overBound?'Data lengkap sudah diperiksa. Salinan otomatis terlalu besar; pilih teks dan salin manual.':denied?'Salin otomatis gagal. Pilih teks yang sudah diperiksa dan salin manual.':'Pertanyaan dan data sumber disalin; siap ditinjau di AI pilihanmu.';await ui.expect(panel.getByText(message,{exact:true})).toBeVisible();if(overBound)byteBoundCount++;else if(denied)controlledDenialCount++;if(!denied)initialCopyMode=overBound?'MANUAL_UTF8_BOUND':'AUTOMATIC';return text
  }
  throw Error('Three explicit fresh Native captures each archived before handoff')
 }
 // These popup controls exercise application branches without contacting an
 // external provider. The Auth/Native read remains the real loopback service.
 const popup=async blocked=>page.evaluate(blocked=>{window.__p17Popup={calls:[],opener:'unretired',location:{href:'about:blank'},closed:false};window.open=(...args)=>{window.__p17Popup.calls.push(args);return blocked?null:{set opener(v){window.__p17Popup.opener=v},get location(){return window.__p17Popup.location},close(){window.__p17Popup.closed=true}}}},blocked)
 const popupState=()=>page.evaluate(()=>window.__p17Popup)
 const openCurrent=async blocked=>{
  for(let attempt=0;attempt<3;attempt++){
   await popup(blocked);const e=await checked(()=>panel.getByRole('button',{name:'Periksa sumber & buka ChatGPT',exact:true}).click())
   if(e.source_state==='ARCHIVED_STALE'){clockArchives++;if(!blocked)await ui.expect.poll(async()=>(await popupState()).closed).toBe(true);await prepare(true);continue}
   await ui.expect(panel.getByText(blocked?'Tab diblokir. Gunakan tautan manual ChatGPT, lalu tempel data yang sudah diperiksa.':'ChatGPT dibuka. Tempel data yang sudah diperiksa secara manual.',{exact:true})).toBeVisible();return
  }
  throw Error('Native clock archived every checked popup attempt')
 }
 try{
  mkdirSync('cp6-proof/t3',{recursive:true});await user.context.grantPermissions(['clipboard-read','clipboard-write'],{origin:ui.origin});await page.bringToFront();await navigate(page);const dirty=page.getByLabel('Cari barang jadi',{exact:true});await dirty.fill('P17 ISIAN GUDANG TETAP');await history.getByRole('button',{name:'Data permintaan & stok',exact:true}).click();await history.getByRole('button',{name:'Analisis, laporan & pengingat seluruh produk',exact:true}).click();const initialCount=state().analysis_count
  const copied=await prepare(false);if(automaticRequired)assert.equal(initialCopyMode,'AUTOMATIC','Actual early Native source must qualify automatic copy below the full UTF8 bound');if(initialCopyMode==='MANUAL_UTF8_BOUND'){await manual().focus();await page.keyboard.press('ControlOrMeta+C')}const clipboard=await page.evaluate(()=>navigator.clipboard.readText());assert.equal(clipboard,copied);assert.ok(copied.includes(JSON.stringify(original.analysis)));assert.ok(copied.includes(JSON.stringify(original.financial_source)));assert.ok(copied.includes(JSON.stringify(question)));const coverage=JSON.parse(copied.split('CAKUPAN SUMBER\n\n')[1].split('\n\n')[0]);assert.equal(coverage.actor_scope_id,user.user.id);assert.equal(coverage.original_run_id,original.run_id);assert.equal(coverage.original_request_id,original.request_id);assert.equal(coverage.source_hash,original.analysis.snapshot.source_hash);assert.equal(coverage.semantic_hash,original.analysis.semantic_hash);assert.equal(coverage.financial_source_hash,original.financial_source.source_hash);assert.equal(coverage.presentation_filter,'NOT_APPLIED');assert.equal(coverage.truncation,'NONE');assert.equal(coverage.serialized_source_utf8_bytes,Buffer.byteLength(JSON.stringify({analysis:original.analysis,financial_source:original.financial_source}),'utf8'));await shot(`P17_COPIED_${suffix}.png`)
  await page.evaluate(()=>Object.defineProperty(navigator.clipboard,'writeText',{configurable:true,value:async()=>{throw new DOMException('Controlled browser clipboard permission denial','NotAllowedError')}}));await prepare(true);await openCurrent(false);let p=await popupState();assert.deepEqual(p.calls,[['about:blank','_blank']]);assert.equal(p.opener,null);assert.equal(p.location.href,'https://chatgpt.com/');assert.equal(p.closed,false)
  await prepare(true);await openCurrent(true);p=await popupState();assert.equal(p.location.href,'about:blank');await ui.expect(manual()).toBeVisible();const link=panel.getByRole('link',{name:'Tautan manual ChatGPT',exact:true});assert.equal(await link.getAttribute('href'),'https://chatgpt.com/');assert.equal(await link.getAttribute('rel'),'noopener noreferrer');await shot(`P17_MANUAL_BLOCKED_${suffix}.png`)
  await prepare(true);await popup(false);let release;const held=new Promise(resolve=>{release=resolve});let fetched;const ready=new Promise(resolve=>{fetched=resolve});await page.route(readRpc,async route=>{const response=await route.fetch();assert.equal(response.status(),200);fetched();await held;await route.fulfill({response})});await panel.getByRole('button',{name:'Periksa sumber & buka ChatGPT',exact:true}).click();await ready;await ui.expect(panel.locator('.native-analysis-result')).toHaveCount(0);await ui.expect(page.locator('.cfg-totals')).toHaveCount(0);await page.evaluate(()=>window.dispatchEvent(new StorageEvent('storage',{key:null})));release();await ui.expect.poll(async()=>(await popupState()).closed).toBe(true);await ui.expect(manual()).toHaveCount(0);await ui.expect(panel.locator('.native-analysis-result')).toHaveCount(0);assert.equal((await popupState()).location.href,'about:blank');await page.unroute(readRpc)
  await prepare(true);await popup(false);fixture('update_schedule',{today});const changed=await checked(()=>panel.getByRole('button',{name:'Periksa sumber & buka ChatGPT',exact:true}).click());assert.equal(changed.source_state,'ARCHIVED_STALE');await ui.expect.poll(async()=>(await popupState()).closed).toBe(true);await ui.expect(manual()).toHaveCount(0);await ui.expect(panel.locator('.native-analysis-result')).toContainText('Arsip lama: sumber berubah.');assert.equal((await popupState()).location.href,'about:blank');await shot(`P17_STALE_${suffix}.png`)
  await prepare(true);await popup(false);fixture('deactivate',{actor:user.user.id});const denied=page.waitForResponse(r=>r.url().endsWith('/rpc/erp_cp7_read_analysis_v1')),parent=page.waitForResponse(r=>r.url().endsWith('/rpc/erp_cp7_get_fg_v1'));await panel.getByRole('button',{name:'Periksa sumber & buka ChatGPT',exact:true}).click();assert.equal((await denied).status(),403);assert.equal((await parent).status(),403);await ui.expect.poll(async()=>(await popupState()).closed).toBe(true);assert.equal((await popupState()).location.href,'about:blank');await ui.expect(manual()).toHaveCount(0);await ui.expect(panel.locator('.native-analysis-result')).toHaveCount(0);await ui.expect(page.locator('.cfg-totals')).toHaveCount(0);assert.equal(await dirty.inputValue(),'P17 ISIAN GUDANG TETAP');fixture('restore',{actor:user.user.id});await panel.getByText('Arsip analisis yang pernah dibuka',{exact:true}).click();const response=page.waitForResponse(r=>r.url().endsWith('/rpc/erp_cp7_read_analysis_v1'));await panel.getByRole('button',{name:'Buka arsip analisis 1',exact:true}).click();assert.equal((await response).status(),200);await panel.getByRole('tab',{name:'Tanya AI',exact:true}).click();assert.equal(await panel.getByLabel('Pertanyaan analisis ERP',{exact:true}).inputValue(),question);assert.equal(state().analysis_count,initialCount+explicitCaptures);await shot(`P17_RECOVERED_${suffix}.png`)
  const local=await page.evaluate(()=>Object.entries(localStorage).filter(([key])=>key.startsWith('erp.cp7.')).map(([,value])=>value).join('\n'));assert.ok(!local.includes('financial_source'));assert.ok(!local.includes('allocation_edges'));assert.ok(!local.includes(question))
  if(automaticRequired)assert.ok(controlledDenialCount>0,'Actual below-bound Native copy must visit the clipboard-denial fallback');
  return{status:'PASS',actual_Auth_Native_original_before_every_copy_or_open:true,actual_browser_clipboard_complete_UTF8_scope_hash_finance_and_question:true,initial_copy_mode:initialCopyMode,initial_prompt_utf8_bytes:Buffer.byteLength(copied,'utf8'),controlled_clipboard_denial_visited_count:controlledDenialCount,complete_manual_byte_bound_visited_count:byteBoundCount,controlled_popup_branches_only_static_data_free_URL_no_provider_contact:true,held_actual_Native_read_scope_invalidation_closes_blank_and_retires_source:true,actual_source_change_keeps_archived_Original_no_handoff:true,current403_closes_blank_retires_parent_FG_HPP_and_all_prepared_source:true,own_question_stock_search_retained_no_fact_cache:true,explicit_capture_count:explicitCaptures,legitimate_clock_archives:clockArchives,no_implicit_capture_business_write_or_delivery:true,screenshots:shots}
 }catch(e){writeFileSync(`cp6-proof/t3/P17_HANDOFF_${suffix}_FAILURE.json`,JSON.stringify({error:String(e),text:await panel.innerText().catch(()=>''),original,lastRead,prompt_utf8_bytes:await manual().inputValue().then(t=>Buffer.byteLength(t,'utf8')).catch(()=>null),clipboard_permission:await page.evaluate(async()=>({focused:document.hasFocus(),read:(await navigator.permissions.query({name:'clipboard-read'})).state,write:(await navigator.permissions.query({name:'clipboard-write'})).state})).catch(()=>null)},null,2));await page.screenshot({path:`cp6-proof/t3/P17_HANDOFF_${suffix}_FAILURE.png`,fullPage:true}).catch(()=>{});throw e}
 finally{fixture('restore',{actor:user.user.id});await user.context.close()}
}
export function cases(ui,today){return[['P17_BROWSER_DESKTOP_NATIVE_HANDOFF',()=>journey(ui,today,false)],['P17_BROWSER_MOBILE_NATIVE_HANDOFF',()=>journey(ui,today,true)]]}

// Independent journeys before cumulative fixtures retain complete Native scope.
export function automaticCases(ui,today){return[['P17_BROWSER_DESKTOP_NATIVE_AUTOMATIC_HANDOFF',()=>journey(ui,today,false,true)],['P17_BROWSER_MOBILE_NATIVE_AUTOMATIC_HANDOFF',()=>journey(ui,today,true,true)]]}
