import assert from 'node:assert/strict'
import {execFileSync} from 'node:child_process'
import {mkdirSync,writeFileSync} from 'node:fs'
const fixture=(op,p)=>JSON.parse(execFileSync('python',['../auditor/scripts/cp7_p12_browser_fixture.py',op,JSON.stringify(p)],{cwd:'../writer',encoding:'utf8'}).trim())
const changed=(a,b)=>Object.fromEntries([...new Set([...Object.keys(a),...Object.keys(b)])].sort().flatMap(k=>{const v=Number(b[k]??0)-Number(a[k]??0);return v?[[k,v]]:[]}))
async function open(ui,p,section,label,selector){
 await ui.expect(p.locator('.sidebar .nav-main').filter({hasText:section})).toBeAttached()
 const menu=p.getByRole('button',{name:'Buka menu',exact:true});if(await menu.isVisible())await menu.click()
 const link=p.getByRole('button',{name:'• '+label,exact:true});if(!await link.isVisible())await p.locator('.sidebar .nav-main').filter({hasText:section}).click();await link.click();await ui.expect(p.locator(selector).getByRole('heading',{name:label,exact:true})).toBeVisible()
}
async function lifecycle(ui,today,mobile){
 // Native setup creates only mandor, prior FG work cards, cash and permissions.
 // Workers, rates, attendance, Nota and the entire payroll cycle use actual UI.
 const f=fixture('create_attendance_write',{today}),user=await ui.login('ADMIN',{label:'p12-source-cycle-'+mobile,mobile,timezoneId:mobile?'America/Los_Angeles':'Asia/Jakarta'}),p=user.page,suffix=mobile?'MOBILE':'DESKTOP',number='ABS-'+f.label.split(' ').at(-1)
 const panel=p.locator('.catt'),editor=panel.getByRole('region',{name:'Pencatatan absensi'}),detail=panel.getByRole('region',{name:'Rincian sumber absensi'})
 const source=()=>fixture('read_attendance_pipeline',f),period=number=>source().periods.find(x=>x[1]===number)
 async function openAttendance(){
  await open(ui,p,'Keuangan','Absensi & Rate Harian','.catt');await panel.getByLabel('Pencarian absensi',{exact:true}).fill(f.label);await panel.getByLabel('Absensi dari tanggal',{exact:true}).fill(today);await panel.getByLabel('Absensi sampai tanggal',{exact:true}).fill(today);await panel.getByRole('button',{name:'Tampilkan absensi',exact:true}).click();await ui.expect(panel.locator('.cproc-receipt')).toHaveCount(1);await panel.locator('.cproc-receipt').click()
 }
 async function select(number){await panel.locator('.cproc-receipt').filter({has:p.getByText(number,{exact:true})}).click();await ui.expect(detail).toContainText(number)}
 async function act(label,commit){await detail.getByRole('button',{name:label,exact:true}).click();await ui.expect(editor.getByRole('button',{name:commit,exact:true})).toBeDisabled();await editor.getByLabel('Alasan tindakan absensi',{exact:true}).fill('P12 pemeriksaan seluruh sumber melalui browser');await editor.getByLabel('Absensi sudah diperiksa',{exact:true}).check();await editor.getByRole('button',{name:commit,exact:true}).click();await ui.expect(editor).toHaveCount(0)}
 async function previewSave(amount){await editor.getByLabel('Alasan tindakan absensi',{exact:true}).fill('P12 catatan harian eksplisit melalui browser');await editor.getByRole('button',{name:'Pratinjau hitungan absensi',exact:true}).click();await ui.expect(editor.locator('.catt-review')).toContainText('Perkiraan upah Rp'+amount)}
 try{
  await openAttendance()
  for(const [name,rate] of [['Pekerja Harian','100'],['Pekerja Setengah','50']]){
   await panel.getByRole('button',{name:'Tambah pekerja',exact:true}).click();const form=panel.getByRole('region',{name:'Form pekerja dan tarif'});await form.getByLabel('Nama pekerja',{exact:true}).fill(name);await form.getByLabel('Pekerjaan pekerja',{exact:true}).fill('Jahit');await form.getByLabel('Tarif harian pekerja',{exact:true}).fill(rate);await form.getByLabel('Alasan perubahan pekerja',{exact:true}).fill('P12 pekerja baru melalui browser');await form.getByRole('button',{name:'Simpan pekerja',exact:true}).click();await ui.expect(form).toHaveCount(0);await ui.expect(panel.getByRole('button',{name:'Tambah pekerja',exact:true})).toBeEnabled()
  }
  assert.equal(source().workers,2);assert.equal(source().rates,2)
  await panel.getByRole('button',{name:'Periode absensi',exact:true}).click();await panel.getByRole('button',{name:'Tambah periode absensi',exact:true}).click();await ui.expect(editor.locator('.catt-cell')).toHaveCount(2)
  await ui.expect(editor.getByLabel('Kehadiran Pekerja Harian '+today,{exact:true})).toHaveValue('');await ui.expect(editor.getByLabel('Kehadiran Pekerja Setengah '+today,{exact:true})).toHaveValue('')
  await editor.getByLabel('Nomor periode absensi',{exact:true}).fill(number);await editor.getByLabel('Kehadiran Pekerja Harian '+today,{exact:true}).selectOption('PRESENT');await editor.getByLabel('Kehadiran Pekerja Setengah '+today,{exact:true}).selectOption('HALF_DAY');await previewSave('125')
  await ui.expect.poll(()=>panel.evaluate(el=>{const b=el.getBoundingClientRect();return b.left>=0&&b.right<=innerWidth+1&&document.documentElement.scrollWidth<=innerWidth+1})).toBe(true)
  mkdirSync('cp6-proof/t3',{recursive:true});await p.evaluate(()=>window.scrollTo(0,0));await p.screenshot({path:`cp6-proof/t3/P12_ATTENDANCE_ENTRY_${suffix}.png`,fullPage:true});await editor.getByRole('button',{name:'Simpan draft absensi',exact:true}).click();await ui.expect.poll(()=>period(number)?.[2]).toBe('DRAFT');await select(number)
  let first=null,replay=null,lost=false
  if(mobile)await p.route('**/rest/v1/rpc/erp_cp7_save_attendance_v1',async route=>{const body=route.request().postDataJSON();if(body.p_action==='POST'&&!lost){first=body;const response=await route.fetch();assert.equal(response.status(),200,'Attendance must commit before response loss');lost=true;await route.abort('failed')}else{if(body.p_action==='POST'&&replay===null)replay=body;await route.continue()}})
  await act('Posting absensi','Posting absensi sekarang');await ui.expect.poll(()=>period(number)?.[2]).toBe('POSTED')
  if(mobile){await ui.expect(panel.getByRole('button',{name:'Periksa status simpan absensi',exact:true})).toBeVisible();await p.reload();await open(ui,p,'Keuangan','Absensi & Rate Harian','.catt');await panel.getByRole('button',{name:'Periksa status simpan absensi',exact:true}).click();await ui.expect(panel.getByRole('button',{name:'Periksa status simpan absensi',exact:true})).toHaveCount(0);assert.ok(lost);assert.deepEqual(replay,first)}
  let actual=source();assert.equal(actual.periods.length,1);assert.equal(actual.records.length,2);assert.deepEqual(changed(f.base_gl,actual.gl),{});const originalIds=actual.records.map(x=>x[0]).sort()
  await select(number);await detail.getByRole('button',{name:'Koreksi absensi',exact:true}).click();await ui.expect(editor.getByLabel('Nomor periode absensi',{exact:true})).toHaveValue(number+'-K');await editor.getByLabel('Kehadiran Pekerja Setengah '+today,{exact:true}).selectOption('ABSENT');await previewSave('100');await editor.getByRole('button',{name:'Simpan draft absensi',exact:true}).click();await ui.expect.poll(()=>period(number+'-K')?.[2]).toBe('DRAFT');await select(number+'-K');await act('Posting absensi','Posting absensi sekarang');await ui.expect.poll(()=>period(number)?.[2]).toBe('CORRECTED')
  actual=source();const corrected=actual.records.filter(x=>x[1]===period(number+'-K')[0]);assert.deepEqual(corrected.map(x=>x[6]).sort(),originalIds)
  await select(number+'-K');await act('Batalkan absensi','Batalkan absensi sekarang');await ui.expect.poll(()=>period(number)?.[2]).toBe('POSTED');assert.equal(period(number+'-K')[2],'REVERSED')
  await open(ui,p,'Produksi','Susun Nota FG','.cnota');const nota=p.locator('.cnota'),composer=nota.getByRole('region',{name:'Susunan nota'});await p.getByLabel('Cari kartu nota',{exact:true}).fill(f.label);await p.getByRole('button',{name:'Cari kartu',exact:true}).click();await ui.expect(nota.locator('.cnota-source')).toHaveCount(2)
  if(!mobile){const grip=nota.locator('.cnota-source .cnota-grip').first();await grip.scrollIntoViewIfNeeded();const box=await grip.boundingBox();assert.ok(box);await p.mouse.move(box.x+box.width/2,box.y+box.height/2);await p.mouse.down();await p.mouse.move(box.x+box.width/2+18,box.y+box.height/2+4,{steps:8});const target=await composer.boundingBox();assert.ok(target);await p.mouse.move(target.x+target.width/2,target.y+100,{steps:18});await p.mouse.move(target.x+target.width/2+3,target.y+104,{steps:2});await p.mouse.up();await ui.expect(nota.locator('.cnota-selected article')).toHaveCount(1)}else await nota.locator('.cnota-source').first().getByRole('button',{name:'Tambahkan ke nota',exact:true}).click()
  await nota.locator('.cnota-source').getByRole('button',{name:'Tambahkan ke nota',exact:true}).click();await p.getByRole('button',{name:'Simpan draft nota',exact:true}).click();await ui.expect(nota.locator('.cnota-review')).toContainText('Draft');await p.getByLabel('Nota sudah diperiksa',{exact:true}).check();await p.getByRole('button',{name:'Posting ke payroll',exact:true}).click();await ui.expect.poll(()=>fixture('read',f).notes[0]?.status).toBe('POSTED')
  const posted=fixture('read',f);assert.equal(posted.notes.length,1);assert.equal(posted.payroll.length,1);assert.equal(posted.payroll[0][1],'CALCULATED');assert.equal(posted.payroll[0][2],'6000.00');f.note=posted.notes[0].id;f.payroll=posted.notes[0].payroll_id
  await open(ui,p,'Keuangan','Payroll & Kasbon','.cpay');const pay=p.locator('.cpay'),payDetail=pay.getByRole('region',{name:'Rincian payroll'})
  async function selectPayroll(){await pay.getByLabel('Cari payroll',{exact:true}).fill(f.label);await pay.getByRole('button',{name:'Cari payroll',exact:true}).click();await ui.expect(pay.locator('.cproc-receipt')).toHaveCount(1);await pay.locator('.cproc-receipt').click()}
  async function confirm(label,setup){await payDetail.getByRole('button',{name:label,exact:true}).click();const form=payDetail.getByRole('region',{name:'Periksa tindakan payroll'});if(setup)await setup(form);await form.getByLabel('Alasan tindakan payroll',{exact:true}).fill('P12 sumber absensi dan nota telah diperiksa');await form.getByLabel('Rincian payroll sudah diperiksa',{exact:true}).check();await form.getByRole('button',{name:label==='Koreksi payroll lunas'?'Batalkan payroll dan pembayaran sekarang':label+' sekarang',exact:true}).click()}
  await selectPayroll();await payDetail.getByRole('button',{name:'Hitung sumber',exact:true}).click();await ui.expect(payDetail.locator('.cpay-net')).toHaveText('Bersih payrollRp6.125');await payDetail.getByRole('button',{name:/^Absensi /}).click();await ui.expect(payDetail.locator('.cpay-line')).toHaveCount(2)
  let payroll=fixture('read_settlement',f);assert.equal(payroll.document.attendance_total,'125.00');assert.deepEqual(changed(f.base_gl,payroll.gl),{});await confirm('Setujui payroll');await ui.expect(payDetail.getByRole('button',{name:'Lunasi payroll',exact:true})).toBeEnabled();payroll=fixture('read_settlement',f);assert.deepEqual(payroll.accrual.map(Number),[2,125,125]);assert.deepEqual(changed(f.base_gl,payroll.gl),{[f.wip]:125,[f.payable]:-125})
  await confirm('Lunasi payroll',async form=>{await ui.expect(form.getByLabel('Tanggal pembayaran payroll',{exact:true})).toHaveValue(today);await form.getByLabel('Cari akun pembayaran payroll',{exact:true}).fill(f.bank_code);await form.getByRole('button',{name:'Cari akun pembayaran',exact:true}).click();await ui.expect(form.locator('.cpay-cash-row')).toHaveCount(1);await form.locator('.cpay-cash-row').click()});await ui.expect(payDetail.locator('.cpay-net')).toHaveText('Jumlah dilunasiRp6.125');payroll=fixture('read_settlement',f);assert.deepEqual(payroll.payment.map(Number),[2,6125,6125]);assert.deepEqual(changed(f.base_gl,payroll.gl),{[f.wip]:125,[f.payable]:6000,[f.bank_coa]:-6125});assert.deepEqual(payroll.physical,f.physical)
  await openAttendance();await panel.getByRole('button',{name:'Periode absensi',exact:true}).click();await select(number);await ui.expect(detail.getByRole('button',{name:'Koreksi absensi',exact:true})).toBeDisabled();await ui.expect(detail.getByRole('button',{name:'Batalkan absensi',exact:true})).toBeDisabled()
  await open(ui,p,'Keuangan','Payroll & Kasbon','.cpay');await selectPayroll();await confirm('Koreksi payroll lunas');await ui.expect(payDetail.locator('.cpay-net')).toHaveText('Jumlah pada dokumen batalRp6.125');payroll=fixture('read_settlement',f);assert.equal(payroll.document.status,'REVERSED');assert.equal(payroll.note.status,'POSTED');assert.equal(payroll.sources,'2');assert.deepEqual(changed(f.base_gl,payroll.gl),{})
  await openAttendance();await panel.getByRole('button',{name:'Periode absensi',exact:true}).click();await select(number);await act('Batalkan absensi','Batalkan absensi sekarang');await ui.expect.poll(()=>period(number)?.[2]).toBe('REVERSED');actual=source();assert.ok(actual.periods.every(x=>x[2]==='REVERSED'));assert.equal(actual.records.length,4);assert.deepEqual(actual.records.filter(x=>x[1]===period(number)[0]).map(x=>x[0]).sort(),originalIds);assert.deepEqual(changed(f.base_gl,actual.gl),{});assert.deepEqual(actual.physical,f.physical)
  return {status:'PASS',mobile,native_fixture_only_mandor_fg_cash_permissions:true,browser_creates_workers_rates_explicit_attendance:true,blank_not_inferred:true,attendance:'125',correction:'100',correction_inverse_restores_original:true,original_record_ids_preserved:true,desktop_nota_drag:!mobile,mobile_nota_tap:mobile,browser_nota_prepare_approve_full_pay_reverse:true,labor:'6000',net:'6125',attendance_accrual_once:true,payment_once:true,consumed_attendance_controls_refuse:true,payroll_inverse_then_attendance_inverse:true,exact_lost_post_reply_replay:mobile?true:null,final_gl_neutral_stock_hpp_unchanged:true,screenshot:`P12_ATTENDANCE_ENTRY_${suffix}.png`}
 }catch(error){mkdirSync('cp6-proof/t3',{recursive:true});writeFileSync(`cp6-proof/t3/P12_ATTENDANCE_WRITE_${suffix}_FAILURE.json`,JSON.stringify({error:String(error),attendance:await panel.innerText().catch(()=>''),nota:await p.locator('.cnota').innerText().catch(()=>''),payroll:await p.locator('.cpay').innerText().catch(()=>''),source:source()},null,2));await p.screenshot({path:`cp6-proof/t3/P12_ATTENDANCE_WRITE_${suffix}_FAILURE.png`,fullPage:true});throw error}finally{await user.context.close()}
}
export async function cases(ui,today){return [['P12_ATTENDANCE_BROWSER_DESKTOP_CYCLE',()=>lifecycle(ui,today,false)],['P12_ATTENDANCE_BROWSER_MOBILE_POST_RECOVERY',()=>lifecycle(ui,today,true)]]}
