import assert from 'node:assert/strict'
import {execFileSync} from 'node:child_process'
import {mkdirSync,writeFileSync} from 'node:fs'
const fixture=(op,p)=>JSON.parse(execFileSync('python',['../auditor/scripts/cp7_p11_browser_fixture.py',op,JSON.stringify(p)],{cwd:'../writer',encoding:'utf8'}).trim())
async function open(ui,p,title='Penjualan & Invoice'){
 await ui.expect(p.locator('.sidebar .nav-main').filter({hasText:'Penjualan'})).toBeAttached()
 const menu=p.getByRole('button',{name:'Buka menu',exact:true});if(await menu.isVisible())await menu.click()
 const link=p.getByRole('button',{name:'• '+title,exact:true});if(!await link.isVisible())await p.locator('.sidebar .nav-main').filter({hasText:'Penjualan'}).click();await link.click();await ui.expect(p.locator('.csales').getByRole('heading',{name:title,exact:true})).toBeVisible()
}
const cents=(n)=>{const raw=String(n),negative=raw.startsWith('-'),[a,b='']=raw.replace(/^-/,'').split('.');assert.match(b.slice(2),/^0*$/);return (BigInt(a)*100n+BigInt(b.slice(0,2).padEnd(2,'0')))*(negative?-1n:1n)}
const delta=(a,b)=>Object.fromEntries([...new Set([...Object.keys(a),...Object.keys(b)])].map(k=>[k,cents(b[k]??'0')-cents(a[k]??'0')]).filter(([,v])=>v!==0n))
async function historyPageTools(ui,p,panel,form,f,kind){
 const payment=kind==='pembayaran',title=`Riwayat ${kind} invoice`,history=panel.getByRole('region',{name:title,exact:true}),number=f.tag+(payment?'-PAY':'-RET'),rows=history.locator('.cproc-item')
 const search=payment?'Cari pembayaran di halaman ini':'Cari riwayat retur di halaman ini',order=`Urutkan halaman riwayat ${kind} invoice`,status=`Status ${kind} di halaman ini`,browse=`Semua ${kind} di halaman ini`
 await ui.expect(rows).toHaveCount(1);await ui.expect(rows.first()).toContainText(number)
 const before=fixture('read_return',f),calls=[],observe=request=>{if(request.url().includes('/rest/v1/rpc/erp_cp7_')&&request.method()==='POST')calls.push(request.url().split('/').at(-1))}
 if(!payment){await form.getByLabel('Nomor retur pelanggan',{exact:true}).fill(f.tag+'-UNSENT');await form.getByLabel('Retur pelanggan sudah diperiksa',{exact:true}).check()}
 else await ui.expect(form).toHaveCount(0) // The unchanged Native invoice is PAID; a new payment is unavailable.
 p.on('request',observe)
 try{
  await history.getByLabel(order,{exact:true}).selectOption('LABEL_DESC');await history.getByLabel(status,{exact:true}).selectOption('REVERSED');await ui.expect(rows).toHaveCount(0);await ui.expect(history).toContainText(`Tidak ada ${kind} sesuai pencarian pada halaman ini.`)
  await history.getByLabel(status,{exact:true}).selectOption('POSTED');await history.getByLabel(search,{exact:true}).fill(number);await history.getByRole('button',{name:search,exact:true}).click();await ui.expect(rows).toHaveCount(1);await ui.expect(rows.first()).toContainText(number)
  await history.getByLabel(search,{exact:true}).fill(f.tag+'-NO-SUCH-RECORD');await history.getByRole('button',{name:search,exact:true}).click();await ui.expect(rows).toHaveCount(0)
  await history.getByRole('button',{name:browse,exact:true}).click();await ui.expect(rows).toHaveCount(1);await ui.expect(history.getByLabel(search,{exact:true})).toHaveValue('');await ui.expect(history.getByLabel(status,{exact:true})).toHaveValue('ALL');await ui.expect(history.getByLabel(order,{exact:true})).toHaveValue('SOURCE')
  if(!payment){await ui.expect(form.getByLabel('Nomor retur pelanggan',{exact:true})).toHaveValue(f.tag+'-UNSENT');await ui.expect(form.getByLabel('Retur pelanggan sudah diperiksa',{exact:true})).toBeChecked()}
  else await ui.expect(form).toHaveCount(0)
  assert.deepEqual(calls,[]);assert.deepEqual(fixture('read_return',f),before)
 }finally{p.off('request',observe)}
 return {actual_Native_posted_original_retained:true,current_page_search_status_order_and_complete_reset:true,all_Native_document_payment_return_FG_positions_and_accounts_unchanged:true,additional_browser_RPC_or_writer:0,unsent_return_number_and_review_preserved:payment?null:true,paid_invoice_new_payment_form_absent:payment?true:null}
}
async function lifecycle(ui,today,mobile,sourceLinks=false){
 const f=fixture('create_return_source',{today}),before=fixture('read_return',f),user=await ui.login('OWNER',{label:'p11-r10-'+mobile,mobile,timezoneId:mobile?'America/Los_Angeles':'Asia/Jakarta'}),p=user.page,ws=p.locator('.csales'),detail=ws.getByRole('complementary',{name:'Rincian invoice'}),ret=ws.getByRole('region',{name:'Retur fisik invoice'}),retForm=ret.getByRole('form',{name:'Catat retur pelanggan'}),cash=ws.getByRole('region',{name:'Pembayaran invoice',exact:true}),cashForm=cash.getByRole('form',{name:'Catat pembayaran pelanggan'})
 const select=async()=>{await ws.getByLabel('Cari invoice',{exact:true}).fill(f.tag);await ws.getByRole('button',{name:'Cari invoice',exact:true}).click();await ui.expect(ws.getByRole('region',{name:'Daftar invoice'}).locator('.cproc-receipt')).toHaveCount(1);await ws.getByRole('region',{name:'Daftar invoice'}).locator('.cproc-receipt').click();await ui.expect(detail.getByRole('heading',{name:f.tag,exact:true})).toBeVisible()}
 try{
  await open(ui,p);await ws.getByRole('button',{name:'Buat invoice',exact:true}).click();const draft=ws.getByRole('form',{name:'Draft invoice'})
  await draft.getByLabel('Nomor draft invoice',{exact:true}).fill(f.tag);await draft.getByLabel('Waktu draft invoice WIB',{exact:true}).fill(new Date(new Date(f.sale_at).getTime()+7*60*60*1000).toISOString().slice(0,16))
  await draft.getByLabel('Cari pelanggan draft',{exact:true}).fill(f.tag);await draft.getByRole('button',{name:'Cari pelanggan draft',exact:true}).click();await ui.expect(draft.getByRole('region',{name:'Pilih pelanggan invoice'}).locator('.cproc-receipt')).toHaveCount(1);await draft.getByRole('region',{name:'Pilih pelanggan invoice'}).locator('.cproc-receipt').click()
  await draft.getByLabel('Cari barang draft',{exact:true}).fill(f.sku);await draft.getByRole('button',{name:'Cari barang draft',exact:true}).click();await ui.expect(draft.getByRole('region',{name:'Pilih barang invoice'}).locator('.cproc-receipt')).toHaveCount(1);await draft.getByRole('region',{name:'Pilih barang invoice'}).locator('.cproc-receipt').click()
  await draft.getByLabel('Jumlah invoice 1',{exact:true}).fill('4');await draft.getByLabel('Harga invoice 1',{exact:true}).fill('20');await draft.getByLabel('Alasan simpan invoice',{exact:true}).fill('R10 barang pelanggan harga diperiksa');await draft.getByLabel('Draft invoice sudah diperiksa',{exact:true}).check();await draft.getByRole('button',{name:'Simpan draft invoice',exact:true}).click();await ui.expect(draft).toHaveCount(0);await ui.expect(detail).toContainText('4 PCS masih dipesan')
  const reserved=fixture('read_return',f);assert.deepEqual(reserved.accounts,before.accounts);assert.equal(reserved.available,6)
  await detail.getByLabel('Invoice sudah diperiksa',{exact:true}).check();await detail.getByRole('button',{name:'Sahkan invoice',exact:true}).click();await ui.expect(detail).toContainText('Sisa pembayaran Rp80');const sold=fixture('read_return',f)
  assert.deepEqual(delta(before.accounts,sold.accounts),{[f.mapping.AR_CUSTOMER]:8000n,[f.mapping.SALES_REVENUE]:-8000n,[f.mapping.FG_INVENTORY]:-4000n,[f.mapping.COGS]:4000n})
  // Both dedicated navigation entries must reach the same real connected flow.
  await open(ui,p,'Retur Penjualan');await select();await detail.getByRole('button',{name:'Retur fisik invoice',exact:true}).click();await ui.expect(ret.getByRole('heading',{name:'Riwayat retur',exact:true})).toBeVisible()
  await retForm.getByLabel('Nomor retur pelanggan',{exact:true}).fill(f.tag+'-RET');await retForm.getByLabel('Cari gudang retur',{exact:true}).fill(f.destination_name);await retForm.getByRole('button',{name:'Cari gudang retur',exact:true}).click();await ui.expect(retForm.getByRole('region',{name:'Pilih gudang retur'}).locator('.cproc-receipt')).toHaveCount(1);await retForm.getByRole('region',{name:'Pilih gudang retur'}).locator('.cproc-receipt').click()
  await ui.expect(retForm.getByRole('region',{name:'Pilih alokasi retur'}).locator('.cproc-receipt')).toHaveCount(1);await retForm.getByRole('region',{name:'Pilih alokasi retur'}).locator('.cproc-receipt').click();await retForm.getByLabel('Jumlah retur 1',{exact:true}).fill('1');await retForm.getByLabel('Nilai retur 1',{exact:true}).fill('20');await retForm.getByLabel('Grade retur 1',{exact:true}).selectOption(mobile?'GRADE_B':'GRADE_A');await retForm.getByLabel('Catatan barang retur 1',{exact:true}).fill('Barang asli kembali');await retForm.getByLabel('Retur pelanggan sudah diperiksa',{exact:true}).check()
  let lost=false,first=null,replay=null
  if(mobile)await p.route('**/rest/v1/rpc/erp_cp7_save_sale_v1',async route=>{const body=route.request().postDataJSON();if(body.p_action==='RETURN'&&!lost){first=body;const response=await route.fetch();if(response.status()!==200){await route.fulfill({response});return}lost=true;await route.abort('failed')}else{if(body.p_action==='RETURN'&&replay===null)replay=body;await route.continue()}})
  await retForm.getByRole('button',{name:'Catat retur pelanggan',exact:true}).click()
  if(mobile){await ui.expect(ws.getByRole('button',{name:'Reconcile transaksi',exact:true})).toBeVisible();await p.reload();await open(ui,p,'Retur Penjualan');await ws.getByRole('button',{name:'Reconcile transaksi',exact:true}).click();await ui.expect(ws.getByRole('button',{name:'Reconcile transaksi',exact:true})).toHaveCount(0);assert.ok(lost);assert.deepEqual(replay,first)}
  await ui.expect(ret).toHaveCount(0);await ui.expect(detail).toContainText('Sisa pembayaran Rp60');const returned=fixture('read_return',f);assert.equal(returned.available,7);assert.equal(returned.returns.page.total,'1');assert.deepEqual(returned.positions,[{location:f.location,grade:'GRADE_A',qty:6},{location:f.destination,grade:mobile?'GRADE_B':'GRADE_A',qty:1}].sort((a,b)=>a.location.localeCompare(b.location)||a.grade.localeCompare(b.grade)))
  assert.deepEqual(delta(sold.accounts,returned.accounts),{[f.mapping.AR_CUSTOMER]:-2000n,[f.mapping.SALES_REVENUE]:2000n,[f.mapping.FG_INVENTORY]:1000n,[f.mapping.COGS]:-1000n})
  await detail.getByRole('button',{name:'Retur fisik invoice',exact:true}).click();await ui.expect(ret).toContainText(mobile?'Grade B':'Grade A');await ui.expect(ret).toContainText(f.destination_name);const returnHistoryTools=await historyPageTools(ui,p,ret,retForm,f,'retur')
  await ui.expect.poll(()=>ws.evaluate(el=>{const r=el.getBoundingClientRect();return r.left>=0&&r.right<=innerWidth+1&&document.documentElement.scrollWidth<=innerWidth+1})).toBe(true);mkdirSync('cp6-proof/t3',{recursive:true});await p.evaluate(()=>window.scrollTo(0,0));await p.screenshot({path:`cp6-proof/t3/P11_RETURN_${mobile?'MOBILE':'DESKTOP'}.png`,fullPage:true});await ret.getByRole('button',{name:'Tutup retur invoice',exact:true}).click()
  await open(ui,p,'Pembayaran Pelanggan');await select();await detail.getByRole('button',{name:'Pembayaran invoice',exact:true}).click();await ui.expect(cash.getByRole('heading',{name:'Riwayat pembayaran',exact:true})).toBeVisible();await cashForm.getByLabel('Nomor pembayaran pelanggan',{exact:true}).fill(f.tag+'-PAY');await cashForm.getByLabel('Nominal pembayaran pelanggan',{exact:true}).fill('60');await cashForm.getByLabel('Cari rekening pembayaran pelanggan',{exact:true}).fill(f.bank_code);await cashForm.getByRole('button',{name:'Cari rekening pelanggan',exact:true}).click();await ui.expect(cashForm.getByRole('region',{name:'Pilih rekening pembayaran pelanggan'}).locator('.cproc-receipt')).toHaveCount(1);await cashForm.getByRole('region',{name:'Pilih rekening pembayaran pelanggan'}).locator('.cproc-receipt').click();await cashForm.getByLabel('Pembayaran pelanggan sudah diperiksa',{exact:true}).check();await cashForm.getByRole('button',{name:'Catat pembayaran pelanggan',exact:true}).click();await ui.expect(cash).toHaveCount(0);await ui.expect(detail).toContainText('Sisa pembayaran Rp0');const paid=fixture('read_return',f);assert.equal(paid.document.status,'PAID');assert.deepEqual(delta(returned.accounts,paid.accounts),{[f.cash_coa]:6000n,[f.mapping.AR_CUSTOMER]:-6000n});assert.equal(paid.available,7)
  const dependencies=detail.getByRole('region',{name:'Dokumen penghalang '+f.tag,exact:true});await dependencies.getByRole('button',{name:'Lihat dokumen penghalang',exact:true}).click();await ui.expect(dependencies.locator(`[data-invoice-payment-dependency-id="${paid.cash.payments.rows[0].id}"]`)).toContainText(f.tag+'-PAY');await ui.expect(dependencies.locator(`[data-invoice-return-dependency-id="${paid.returns.page.rows[0].id}"]`)).toContainText(f.tag+'-RET');assert.deepEqual(fixture('read_return',f),paid)
  const dependencyScreenshot=`P11_DEPENDENCIES_${mobile?'MOBILE':'DESKTOP'}.png`;await p.screenshot({path:'cp6-proof/t3/'+dependencyScreenshot,fullPage:true})
  await detail.getByRole('button',{name:'Pembayaran invoice',exact:true}).click();const paymentHistoryTools=await historyPageTools(ui,p,cash,cashForm,f,'pembayaran')
  if(sourceLinks){await cash.getByRole('button',{name:'Tutup pembayaran invoice',exact:true}).click();await dependencies.getByRole('button',{name:'Buka pembayaran '+f.tag+'-PAY',exact:true}).click();await ui.expect(cash.locator('[data-source-selected="true"]')).toHaveCount(1);await ui.expect(cash.locator('[data-source-selected="true"]')).toContainText(f.tag+'-PAY');await ui.expect(cash.getByLabel('Urutkan halaman riwayat pembayaran invoice',{exact:true})).toBeDisabled()}
  await cash.getByRole('button',{name:'Koreksi pembayaran '+f.tag+'-PAY',exact:true}).click();await cashForm.getByLabel('Alasan tindakan pembayaran',{exact:true}).fill('R10 pembayaran dikoreksi dahulu');await cashForm.getByLabel('Pembayaran pelanggan sudah diperiksa',{exact:true}).check();await cashForm.getByRole('button',{name:'Batalkan pembayaran tercatat',exact:true}).click();await ui.expect(cash).toHaveCount(0);await ui.expect(detail).toContainText('Sisa pembayaran Rp60')
  await dependencies.getByRole('button',{name:'Lihat dokumen penghalang',exact:true}).click();await ui.expect(dependencies.locator('[data-invoice-payment-dependency-id]')).toHaveCount(0)
  if(sourceLinks){await dependencies.getByRole('button',{name:'Buka retur '+f.tag+'-RET',exact:true}).click();await ui.expect(ret.locator('[data-source-selected="true"]')).toHaveCount(1);await ui.expect(ret.locator('[data-source-selected="true"]')).toContainText(f.tag+'-RET');await ui.expect(ret.getByLabel('Urutkan halaman riwayat retur invoice',{exact:true})).toBeDisabled()}
  else await detail.getByRole('button',{name:'Retur fisik invoice',exact:true}).click()
  await ret.getByRole('button',{name:'Koreksi retur '+f.tag+'-RET',exact:true}).click();await retForm.getByLabel('Alasan tindakan retur',{exact:true}).fill('R10 retur dikoreksi setelah pembayaran');await retForm.getByLabel('Retur pelanggan sudah diperiksa',{exact:true}).check();await retForm.getByRole('button',{name:'Batalkan retur tercatat',exact:true}).click();await ui.expect(ret).toHaveCount(0);await ui.expect(detail).toContainText('Sisa pembayaran Rp80')
  await detail.getByLabel('Alasan pembatalan penjualan',{exact:true}).fill('R10 seluruh transaksi penjualan dibatalkan');await detail.getByLabel('Pembatalan penjualan sudah diperiksa',{exact:true}).check();await detail.getByRole('button',{name:'Batalkan penjualan tercatat',exact:true}).click();await ui.expect(detail).toContainText('Penjualan dibatalkan');const final=fixture('read_return',f);assert.equal(final.document.status,'REVERSED');assert.equal(final.available,10);assert.deepEqual(final.positions,[{location:f.location,grade:'GRADE_A',qty:10}]);assert.deepEqual(final.accounts,before.accounts);assert.equal(final.cash.payments.total,'1');assert.equal(final.cash.payments.rows[0].status,'REVERSED');assert.equal(final.returns.page.total,'1');assert.equal(final.returns.page.rows[0].status,'REVERSED')
  return {status:'PASS',mobile,only_master_and_FG_stock_are_native_fixtures:true,real_browser_source_create_post_return_payment_and_full_inverse:true,dedicated_return_and_payment_navigation_connected:true,sale80_return20_cash60:true,grade:mobile?'GRADE_B':'GRADE_A',destination:'OTHER_ACTIVE_FG_WAREHOUSE',source_available6_after_sale_total7_after_return_final10:true,exact_cash_AR_revenue_FG_COGS_assertions:true,all_final_GL_accounts_neutral:true,lost_return_response_replay_identical:mobile?true:null,original_payment_and_return_history_retained:true,return_history_page_tools:returnHistoryTools,payment_history_page_tools:paymentHistoryTools,actual_named_dependencies_preserve_all_Native_source_facts:true,Native_resolver_opens_exact_payment_and_return_UUIDs_with_focus:sourceLinks?true:null,source_resolver_scope:sourceLinks?'DECLARED_FULL_TRANSACTION_SOURCE_CASE':'NOT_INSTALLED_IN_STANDALONE_P11_NO_SOURCE_CREDIT',active_dependency_refresh_excludes_reversed_payment:true,dependency_screenshot:dependencyScreenshot,screenshot:`P11_RETURN_${mobile?'MOBILE':'DESKTOP'}.png`}
 }catch(e){let source;try{source=fixture('read_return',f)}catch(x){source={error:String(x)}}mkdirSync('cp6-proof/t3',{recursive:true});writeFileSync(`cp6-proof/t3/P11_RETURN_${mobile?'MOBILE':'DESKTOP'}_FAILURE.json`,JSON.stringify({error:String(e),stack:e.stack,text:await ws.innerText().catch(()=>''),source},null,2));await p.screenshot({path:`cp6-proof/t3/P11_RETURN_${mobile?'MOBILE':'DESKTOP'}_FAILURE.png`,fullPage:true}).catch(()=>{});throw e}
 finally{await user.context.close()}
}
export async function cases(ui,today){return [['P11_RETURN_BROWSER_R10_DESKTOP_A',()=>lifecycle(ui,today,false)],['P11_RETURN_BROWSER_R10_MOBILE_B_RECOVERY',()=>lifecycle(ui,today,true)]]}
export function sourceCases(ui,today){return [['CP7_SOURCE_INVOICE_DEPENDENCIES_DESKTOP',()=>lifecycle(ui,today,false,true)],['CP7_SOURCE_INVOICE_DEPENDENCIES_MOBILE',()=>lifecycle(ui,today,true,true)]]}
