import assert from 'node:assert/strict'
import{execFileSync}from 'node:child_process'
import{mkdirSync,writeFileSync}from 'node:fs'
const fixture=(op,p)=>JSON.parse(execFileSync('python',['../auditor/scripts/cp7_f03_e05_browser_fixture.py',op],{input:JSON.stringify(p),cwd:'../writer',encoding:'utf8',maxBuffer:16*1024*1024}).trim())
const save=r=>r.url().endsWith('/rpc/erp_cp7_save_payroll_installment_v1')
async function navigate(page,name='• Payroll & Kasbon'){
 const menu=page.getByRole('button',{name:'Buka menu',exact:true});if(await menu.isVisible())await menu.click()
 const link=page.getByRole('button',{name,exact:true});if(!await link.isVisible())await page.locator('.sidebar .nav-main').filter({hasText:'Keuangan'}).click();await link.click()
}
async function capture(ui,page,name){await ui.expect.poll(()=>page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);await page.evaluate(()=>scrollTo(0,0));await page.screenshot({path:'cp6-proof/t3/'+name,fullPage:true})}
async function select(ui,page,f){await page.getByLabel('Cari payroll',{exact:true}).fill(f.tag);await page.getByRole('button',{name:'Cari payroll',exact:true}).click();await page.locator('.cproc-receipt').filter({hasText:f.tag}).click();await ui.expect(page.getByRole('region',{name:'Pembayaran gaji',exact:true}).getByRole('button',{name:'Bayar gaji',exact:true})).toBeEnabled()}
async function payForm(ui,page,ws,f,amount){
 await ws.getByRole('button',{name:'Bayar gaji',exact:true}).click();await ws.getByLabel('Jumlah pembayaran gaji',{exact:true}).fill(amount);await ws.getByLabel('Tanggal cicilan gaji',{exact:true}).fill(f.payment_date)
 await ws.getByLabel('Cari akun cicilan gaji',{exact:true}).fill(f.cash.code);await ws.getByRole('button',{name:'Cari akun cicilan',exact:true}).click();await ws.getByRole('button',{name:f.cash.code+' · '+f.cash.name,exact:true}).click()
 await ws.getByLabel('Alasan pembayaran gaji',{exact:true}).fill('Jumlah rekening tanggal dan sisa gaji sudah diperiksa');await ws.getByLabel('Pembayaran gaji sudah diperiksa',{exact:true}).check();await ui.expect(ws.getByRole('button',{name:'Catat pembayaran gaji',exact:true})).toBeEnabled()
}
async function journey(ui,today,mobile){
 const f=fixture('prepare',{today,mobile}),user=await ui.login(mobile?'ADMIN':'OWNER',{label:'e05-installment-'+mobile,mobile,timezoneId:mobile?'America/Los_Angeles':'Asia/Jakarta'}),page=user.page,ws=page.getByRole('region',{name:'Pembayaran gaji',exact:true}),suffix=mobile?'MOBILE':'DESKTOP',screenshots=[]
 let lost=null,first=null
 const state=()=>fixture('state',{fixture:f})
 try{
  mkdirSync('cp6-proof/t3',{recursive:true});await navigate(page);await select(ui,page,f);await payForm(ui,page,ws,f,'600.00')
  await page.route('**/rest/v1/rpc/erp_cp7_save_payroll_installment_v1',async route=>{if(route.request().postDataJSON()?.p_action==='PAY'&&!lost){const native=await route.fetch();assert.equal(native.status(),200);lost={envelope:route.request().postDataJSON(),body:await native.json()};await route.abort('failed')}else await route.continue()})
  await ws.getByRole('button',{name:'Catat pembayaran gaji',exact:true}).click();await ui.expect(ws.getByRole('button',{name:'Periksa status pembayaran gaji',exact:true})).toBeEnabled();let native=state();assert.equal(native.document.paid_amount,'600.00');assert.equal(native.document.remaining_amount,'400.00');assert.equal(native.document.approved_net,'1000.00');assert.equal(native.requests.length,1)
  assert.ok(!(await page.locator('.cpay').innerText()).includes('Rp'));await capture(ui,page,`E05_UNCERTAIN_${suffix}.png`);screenshots.push(`E05_UNCERTAIN_${suffix}.png`)
  if(mobile){fixture('revoke',{});const refused=page.waitForResponse(r=>save(r)&&r.request().postDataJSON()?.p_request===lost.envelope.p_request);await ws.getByRole('button',{name:'Periksa status pembayaran gaji',exact:true}).click();assert.equal((await refused).status(),403);assert.ok(!(await page.locator('.cpay').innerText()).includes('Rp'));assert.equal(state().requests.length,1);const held=await page.evaluate(()=>Object.entries(localStorage).filter(([k])=>k.startsWith('erp.production.PAYROLL_INSTALLMENT.pending-mutation.v1:')));assert.equal(held.length,1);assert.equal(JSON.parse(held[0][1]).id,lost.envelope.p_request);await capture(ui,page,`E05_REVOKED_REPLAY_${suffix}.png`);screenshots.push(`E05_REVOKED_REPLAY_${suffix}.png`);fixture('restore',{})}
  else{await navigate(page,'• Kas & Bank');await ui.expect(page.getByRole('main',{name:'Kas dan bank dari jurnal',exact:true})).toContainText('Ada transaksi yang belum dipastikan');assert.ok(!(await page.getByRole('main',{name:'Kas dan bank dari jurnal',exact:true}).innerText()).includes('Rp'));await capture(ui,page,'E05_PENDING_CASH_DESKTOP.png');screenshots.push('E05_PENDING_CASH_DESKTOP.png')}
  await page.reload();await navigate(page);await ui.expect(ws.getByRole('button',{name:'Periksa status pembayaran gaji',exact:true})).toBeEnabled();let response=page.waitForResponse(r=>save(r)&&r.request().postDataJSON()?.p_request===lost.envelope.p_request);await ws.getByRole('button',{name:'Periksa status pembayaran gaji',exact:true}).click();let result=await response;assert.equal(result.status(),200);assert.deepEqual(result.request().postDataJSON(),lost.envelope);assert.deepEqual(await result.json(),lost.body);first=lost.body.payment_id
  await ui.expect(ws.locator('.cpay-net')).toHaveText(/Sisa gaji\s*Rp400/);await ui.expect(ws.locator('.cpay-totals > div').filter({hasText:'Sudah dibayar'})).toContainText('Rp600');await ui.expect(page.getByRole('button',{name:'Lunasi payroll',exact:true})).toHaveCount(0);native=state();assert.equal(native.requests.length,1);await capture(ui,page,`E05_PARTIAL_${suffix}.png`);screenshots.push(`E05_PARTIAL_${suffix}.png`)
  f.payment_date=today;await payForm(ui,page,ws,f,'400.00');response=page.waitForResponse(r=>save(r)&&r.request().postDataJSON()?.p_action==='PAY');await ws.getByRole('button',{name:'Catat pembayaran gaji',exact:true}).click();result=await response;assert.equal(result.status(),200);await ui.expect(ws.locator('.cpay-net')).toHaveText(/Sisa gaji\s*Rp0/);await ui.expect(ws.locator('.cpay-totals > div').filter({hasText:'Sudah dibayar'})).toContainText('Rp1.000');native=state();assert.equal(native.document.native_status,'PAID');assert.equal(native.document.approved_net,'1000.00');assert.equal(native.payments.rows.length,2);await capture(ui,page,`E05_PAID_${suffix}.png`);screenshots.push(`E05_PAID_${suffix}.png`)
  const original=native.payments.rows.find(p=>p.id===first);assert.ok(original);await ws.getByRole('button',{name:'Balikkan pembayaran '+original.journal_number,exact:true}).click();await ws.getByLabel('Alasan pembayaran gaji',{exact:true}).fill('Koreksi pembayaran asli tetap tersimpan biaya gaji tetap');await ws.getByLabel('Pembayaran gaji sudah diperiksa',{exact:true}).check();response=page.waitForResponse(r=>save(r)&&r.request().postDataJSON()?.p_action==='REVERSE_PAYMENT');await ws.getByRole('button',{name:'Balikkan pembayaran sekarang',exact:true}).click();result=await response;assert.equal(result.status(),200);await ui.expect(ws.locator('.cpay-net')).toHaveText(/Sisa gaji\s*Rp600/);await ui.expect(ws.locator('.cpay-totals > div').filter({hasText:'Sudah dibayar'})).toContainText('Rp400');native=state();const reversed=native.payments.rows.find(p=>p.id===first);assert.equal(reversed.status,'REVERSED');assert.equal(reversed.payment_date,original.payment_date);assert.equal(reversed.reversal_accounting_date,today);assert.equal(native.document.approved_net,'1000.00');assert.equal(native.document.native_status,'APPROVED');assert.equal(native.requests.length,3);await capture(ui,page,`E05_INVERSED_${suffix}.png`);screenshots.push(`E05_INVERSED_${suffix}.png`)
  return{status:'PASS',mobile,actual_Auth_native_attendance_cost1000_once:true,approved_net1000_cash600_remaining400_final400_same_payroll:true,actual_committed_HTTP200_loss_remount_same_UUID_one_effect:true,current_ADMIN_revoked_cached403_preserves_original_uncertainty:mobile,pending_financial_route_facts_retired:!mobile,individual_inverse600_reopens_remaining600_without_cost_inverse:true,original_date_and_linked_inverse_own_date_retained:true,no_mobile_horizontal_clipping:true,screenshots}
 }catch(e){writeFileSync(`cp6-proof/t3/E05_${suffix}_FAILURE.json`,JSON.stringify({error:String(e),stack:e.stack,text:await page.locator('.cpay').innerText().catch(()=>''),native:state(),lost},null,2));await page.screenshot({path:`cp6-proof/t3/E05_${suffix}_FAILURE.png`,fullPage:true}).catch(()=>{});throw e}
 finally{if(mobile)fixture('restore',{original:f.admin_pay_original});await user.context.close()}
}
export function cases(ui,today){return[['E05_BROWSER_DESKTOP_INSTALLMENTS_LOST_REPLY',()=>journey(ui,today,false)],['E05_BROWSER_MOBILE_CURRENT_AUTH_INSTALLMENTS',()=>journey(ui,today,true)]]}
