import assert from'node:assert/strict'
import{execFileSync}from'node:child_process'
import{mkdirSync,writeFileSync}from'node:fs'
import{cases as originalCases}from'./cp7_f05_analysis_browser.mjs'
import{cases as receivableCases}from'./cp7_f05_receivable_browser.mjs'
import{cases as payableCases}from'./cp7_f05_payable_browser.mjs'
const fixture=(op,p)=>JSON.parse(execFileSync('python',['../auditor/scripts/cp7_f05_analysis_browser_fixture.py',op],{input:JSON.stringify(p),cwd:'../writer',encoding:'utf8',maxBuffer:16*1024*1024}).trim())
const observed=p=>JSON.parse(execFileSync('python',['../auditor/scripts/cp7_f05_attention_browser_fixture.py','state'],{input:JSON.stringify(p),cwd:'../writer',encoding:'utf8',maxBuffer:16*1024*1024}).trim())
async function navigate(page){await page.locator('.sidebar .nav-main').filter({hasText:'Gudang'}).waitFor({state:'attached'});const menu=page.getByRole('button',{name:'Buka menu',exact:true});if(await menu.isVisible())await menu.click();const link=page.getByRole('button',{name:'• Ringkasan Barang Jadi',exact:true});if(!await link.isVisible())await page.locator('.sidebar .nav-main').filter({hasText:'Gudang'}).click();await link.click()}
async function journey(ui,today,mobile){
 fixture('prepare',{today});const user=await ui.login('OWNER',{label:'p16-attention-'+mobile,mobile,timezoneId:mobile?'America/Los_Angeles':'Asia/Jakarta'}),page=user.page,suffix=mobile?'MOBILE':'DESKTOP',panel=page.getByRole('region',{name:'Analisis ERP bersama',exact:true}),history=page.getByRole('region',{name:'Data permintaan ERP',exact:true}),shots=[]
 let lost=null,original=null
 const state=()=>observed({actor:user.user.id})
 const shot=async(name)=>{await ui.expect.poll(()=>page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);await page.screenshot({path:'cp6-proof/t3/'+name,fullPage:true});shots.push(name)}
 const post=async(action)=>{const response=page.waitForResponse(r=>r.url().endsWith('/rpc/erp_cp7_save_analysis_attention_v1'));await action();const r=await response;assert.equal(r.status(),200);return await r.json()}
 try{
  mkdirSync('cp6-proof/t3',{recursive:true});await navigate(page);const dirty=page.getByLabel('Cari barang jadi',{exact:true});await dirty.fill('P16 ISIAN GUDANG');await history.getByRole('button',{name:'Data permintaan & stok',exact:true}).click();await history.getByRole('button',{name:'Analisis, laporan & pengingat seluruh produk',exact:true}).click()
  const capture=page.waitForResponse(r=>r.url().endsWith('/rpc/erp_cp7_capture_analysis_v1'));await panel.getByRole('button',{name:'Ambil analisis ERP terbaru',exact:true}).click();const c=await capture;assert.equal(c.status(),200);original=await c.json();const count=state().analysis_count
  const a=original.analysis.actions.find(a=>a.primary_reason!=='PRODUCTION_POLICY_UNREVIEWED')??original.analysis.actions[0];assert.ok(a);const article=panel.getByRole('article',{name:'Perhatian '+a.key,exact:true})
  await panel.getByRole('tab',{name:'Pengingat',exact:true}).click();await ui.expect(article).toContainText('Belum dimuat');await panel.getByRole('button',{name:'Muat perhatian tersimpan',exact:true}).click();await ui.expect(article.getByRole('button',{name:'Sudah dibaca',exact:true})).toBeEnabled();await shot(`P16_LOADED_${suffix}.png`)
  await article.getByText('Jadwalkan pengingat pribadi ERP',{exact:true}).click();const dueDay=new Date(Date.parse(today+'T00:00:00Z')+3*86400000).toISOString().slice(0,10);await article.getByLabel('Judul pengingat',{exact:true}).fill('Cek bahan '+suffix);await article.getByLabel('Waktu pengingat · WIB',{exact:true}).fill(dueDay+'T08:30');await article.getByLabel('Catatan pengingat',{exact:true}).fill('Isian operator, belum berarti bahan tersedia')
  const before=state();await page.route('**/rest/v1/rpc/erp_cp7_save_analysis_attention_v1',async route=>{if(!lost){const r=await route.fetch();assert.equal(r.status(),200);lost={envelope:route.request().postDataJSON(),body:await r.json()};await route.abort('failed')}else await route.continue()})
  await article.getByRole('button',{name:'Simpan jadwal pengingat ERP',exact:true}).click();await ui.expect(panel.getByRole('button',{name:'Ulangi perhatian yang sama',exact:true})).toBeEnabled();assert.equal(state().manual_rows.length,before.manual_rows.length+1);await shot(`P16_UNCERTAIN_${suffix}.png`)
  await panel.getByRole('button',{name:'Tutup analisis bersama',exact:true}).click();await history.getByRole('button',{name:'Analisis, laporan & pengingat seluruh produk',exact:true}).click()
  const replay=page.waitForResponse(r=>r.url().endsWith('/rpc/erp_cp7_save_analysis_attention_v1'));await panel.getByRole('button',{name:'Ulangi perhatian yang sama',exact:true}).click();const rr=await replay;assert.equal(rr.status(),200);assert.deepEqual(rr.request().postDataJSON(),lost.envelope);const recovered=await rr.json();assert.deepEqual(recovered.request_result,lost.body.request_result);assert.deepEqual(recovered.analysis.analysis,original.analysis);assert.deepEqual(recovered.analysis.financial_source,original.financial_source);assert.equal(state().manual_rows.length,before.manual_rows.length+1)
  const manual=recovered.rows.find(r=>r.action_key===a.key).manual;assert.equal(Date.parse(manual.due_at),Date.parse(dueDay+'T08:30:00+07:00'));await ui.expect(article).toContainText('Cek bahan '+suffix);await shot(`P16_RECOVERED_${suffix}.png`)
  let e=await post(()=>article.getByRole('button',{name:'Selesai ditinjau',exact:true}).click());assert.equal(e.rows.find(r=>r.action_key===a.key).manual.status,'DONE');assert.equal(e.rows.find(r=>r.action_key===a.key).business_resolved,false);await ui.expect(article).toContainText('masih perlu diperiksa');await shot(`P16_DONE_REVIEW_${suffix}.png`)
  await post(()=>article.getByRole('button',{name:'Tinjau lagi',exact:true}).click());await article.getByLabel('Waktu tinjau ulang · WIB',{exact:true}).fill(dueDay+'T10:15');e=await post(()=>article.getByRole('button',{name:'Ingatkan lagi nanti',exact:true}).click());const row=e.rows.find(r=>r.action_key===a.key);assert.equal(Date.parse(row.attention.resume_at),Date.parse(dueDay+'T10:15:00+07:00'));assert.equal(row.manual.due_at,row.attention.resume_at);await shot(`P16_SNOOZED_${suffix}.png`)
  fixture('update_schedule',{today});await panel.getByRole('button',{name:'Muat perhatian tersimpan',exact:true}).click();await ui.expect(article).toContainText('sumber berubah; perlu analisis baru');await shot(`P16_ARCHIVE_${suffix}.png`)
  await panel.getByRole('tab',{name:'Tanya AI',exact:true}).click();await panel.getByLabel('Pertanyaan analisis ERP',{exact:true}).fill('P16 pertanyaan belum dikirim');await panel.getByRole('tab',{name:'Pengingat',exact:true}).click();await article.getByText('Jadwalkan pengingat pribadi ERP',{exact:true}).click();await article.getByLabel('Judul pengingat',{exact:true}).fill('P16 isian jadwal belum dikirim')
  fixture('deactivate',{actor:user.user.id});const denied=page.waitForResponse(r=>r.url().endsWith('/rpc/erp_cp7_get_analysis_attention_v1')),parent=page.waitForResponse(r=>r.url().endsWith('/rpc/erp_cp7_get_fg_v1'));await panel.getByRole('button',{name:'Muat perhatian tersimpan',exact:true}).click();assert.equal((await denied).status(),403);assert.equal((await parent).status(),403);await ui.expect(panel.locator('.native-analysis-result')).toHaveCount(0);await ui.expect(page.locator('.cfg-totals')).toHaveCount(0);assert.equal(await dirty.inputValue(),'P16 ISIAN GUDANG');await shot(`P16_REVOKED_${suffix}.png`)
  fixture('restore',{actor:user.user.id});await panel.getByText('Arsip analisis yang pernah dibuka',{exact:true}).click();await panel.getByRole('button',{name:'Buka arsip analisis 1',exact:true}).click();await ui.expect(article).toContainText('Belum dimuat');await article.getByText('Jadwalkan pengingat pribadi ERP',{exact:true}).click();assert.equal(await article.getByLabel('Judul pengingat',{exact:true}).inputValue(),'P16 isian jadwal belum dikirim');await panel.getByRole('tab',{name:'Tanya AI',exact:true}).click();assert.equal(await panel.getByLabel('Pertanyaan analisis ERP',{exact:true}).inputValue(),'P16 pertanyaan belum dikirim');assert.equal(state().analysis_count,count)
  return{status:'PASS',actual_Auth_Native_manual_writer_and_immutable_original:true,lost_reply_remount_exact_UUID_one_task:true,done_review_never_closes_business_source:true,WIB_task_and_snooze_under_foreign_device_timezone:true,source_changed_attention_remains_review_required:true,current403_retires_all_source_and_parent_FG_HPP:true,own_dirty_fields_question_stock_search_preserved:true,no_extra_analysis_recapture_or_external_dispatch:true,screenshots:shots}
 }catch(e){writeFileSync(`cp6-proof/t3/P16_ATTENTION_${suffix}_FAILURE.json`,JSON.stringify({error:String(e),text:await panel.innerText().catch(()=>''),lost,original},null,2));await page.screenshot({path:`cp6-proof/t3/P16_ATTENTION_${suffix}_FAILURE.png`,fullPage:true}).catch(()=>{});throw e}
 finally{fixture('restore',{actor:user.user.id});await user.context.close()}
}
export function cases(ui,today){return[...originalCases(ui,today),['P16_BROWSER_DESKTOP_NATIVE_ATTENTION',()=>journey(ui,today,false)],['P16_BROWSER_MOBILE_NATIVE_ATTENTION',()=>journey(ui,today,true)],...receivableCases(ui,today),...payableCases(ui,today)]}
