import assert from'node:assert/strict'
import{execFileSync}from'node:child_process'
import{mkdirSync,writeFileSync}from'node:fs'
const control=(file,op,p)=>JSON.parse(execFileSync('python',['../auditor/scripts/'+file,op],{input:JSON.stringify(p),cwd:'../writer',encoding:'utf8',maxBuffer:16*1024*1024}).trim())
const fixture=(op,p)=>control('cp7_f05_analysis_browser_fixture.py',op,p)
const ar=(op,p)=>control('cp7_f05_receivable_browser_fixture.py',op,p)
const historyFixture=(op,p)=>control('cp7_f05_history_browser_fixture.py',op,p)
async function navigate(page){await page.locator('.sidebar .nav-main').filter({hasText:'Gudang'}).waitFor({state:'attached'});const menu=page.getByRole('button',{name:'Buka menu',exact:true});if(await menu.isVisible())await menu.click();const link=page.getByRole('button',{name:'• Ringkasan Barang Jadi',exact:true});if(!await link.isVisible())await page.locator('.sidebar .nav-main').filter({hasText:'Gudang'}).click();await link.click()}
async function journey(ui,today,mobile){
 fixture('prepare',{today});const sale=ar('prepare',{today}),user=await ui.login('OWNER',{label:'p16-history-'+mobile,mobile,timezoneId:'America/Los_Angeles'}),page=user.page,suffix=mobile?'MOBILE':'DESKTOP',panel=page.getByRole('region',{name:'Analisis ERP bersama',exact:true}),demand=page.getByRole('region',{name:'Data permintaan ERP',exact:true}),source=panel.getByRole('region',{name:'Riwayat masalah tagihan',exact:true}),saved=source.getByRole('region',{name:'Seluruh riwayat masalah tagihan',exact:true}),article=source.getByRole('article',{name:'Catatan masalah '+sale.number,exact:true}),readRpc='**/rest/v1/rpc/erp_cp7_get_obligation_episode_history_v1',shots=[]
 let original=null,lastHistory=null
 const state=()=>historyFixture('state',{actor:user.user.id}),shot=async name=>{await ui.expect.poll(()=>page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);await page.screenshot({path:'cp6-proof/t3/'+name,fullPage:true});shots.push(name)}
 const observe=async()=>{const reply=page.waitForResponse(r=>r.url().endsWith('/rpc/erp_cp7_evaluate_obligation_episodes_v1'));await source.getByRole('button',{name:'Catat pemeriksaan piutang ERP',exact:true}).click();const r=await reply;assert.equal(r.status(),200);const e=await r.json();assert.deepEqual(e.analysis.analysis,original.analysis);assert.deepEqual(e.analysis.financial_source,original.financial_source);for(let i=0;i<400&&!await article.isVisible();i++){const next=source.getByRole('button',{name:'Catatan berikutnya',exact:true});assert.ok(await next.isEnabled(),'Current Native source missing from complete observation');await next.click()}await ui.expect(article).toBeVisible();return e.result.rows.find(x=>x.source_id===sale.sale).episode}
 const read=async(action,before=null,through=null)=>{const unchanged=state(),reply=page.waitForResponse(r=>r.url().endsWith('/rpc/erp_cp7_get_obligation_episode_history_v1'));await action();const r=await reply;assert.equal(r.status(),200);const e=await r.json();lastHistory=e;assert.deepEqual(r.request().postDataJSON(),{p_payload:{run_id:original.run_id,domain:'AR',source_id:sale.sale,before_episode:before,through_episode:through,limit:25}});assert.equal(e.read_kind,'SAVED_EPISODE_HISTORY');assert.equal(e.page_complete,true);assert.deepEqual(e.analysis.analysis,original.analysis);assert.deepEqual(e.analysis.financial_source,original.financial_source);assert.deepEqual(state(),unchanged);await ui.expect(saved).toBeVisible();return e}
 try{
  mkdirSync('cp6-proof/t3',{recursive:true});await navigate(page);const dirty=page.getByLabel('Cari barang jadi',{exact:true});await dirty.fill('P16 RIWAYAT LAMA ISIAN');await demand.getByRole('button',{name:'Data permintaan & stok',exact:true}).click();await demand.getByRole('button',{name:'Analisis, laporan & pengingat seluruh produk',exact:true}).click()
  const capture=page.waitForResponse(r=>r.url().endsWith('/rpc/erp_cp7_capture_analysis_v1'));await panel.getByRole('button',{name:'Ambil analisis ERP terbaru',exact:true}).click();const captured=await capture;assert.equal(captured.status(),200);original=await captured.json();const count=state().analysis_count;await panel.getByRole('tab',{name:'Tanya AI',exact:true}).click();await panel.getByLabel('Pertanyaan analisis ERP',{exact:true}).fill('P16 riwayat lama pertanyaan sendiri');await panel.getByRole('tab',{name:'Pengingat',exact:true}).click()
  const first=await observe();assert.equal(first.number,'1');historyFixture('repeat26',{...sale,today,actor:user.user.id,run_id:original.run_id});const latest=await observe();assert.equal(latest.number,'26');assert.notEqual(latest.id,first.id)
  let e=await read(()=>article.getByRole('button',{name:'Buka seluruh riwayat masalah',exact:true}).click());assert.equal(e.total,'26');assert.equal(e.through_episode,'26');assert.equal(e.next_before_episode,'2');assert.equal(e.rows.length,25);assert.deepEqual(e.rows.map(x=>x.episode.number),Array.from({length:25},(_,i)=>String(26-i)));assert.equal(e.rows[0].episode.id,latest.id);assert.equal(e.rows[0].episode.state,'ACTIVE');assert.ok(e.rows.slice(1).every(x=>x.episode.state==='RESOLVED'));await ui.expect(saved).toContainText('halaman ini menampilkan 25 catatan');await shot(`P16_HISTORY_LATEST_${suffix}.png`)
  e=await read(()=>saved.getByRole('button',{name:'Buka riwayat yang lebih lama',exact:true}).click(),'2','26');assert.equal(e.rows.length,1);assert.equal(e.next_before_episode,null);assert.equal(e.rows[0].episode.id,first.id);assert.equal(e.rows[0].episode.number,'1');assert.equal(e.rows[0].episode.first_observed_at,first.first_observed_at);assert.equal(e.rows[0].episode.state,'RESOLVED');await ui.expect(saved).toContainText('Sudah sampai riwayat pertama.');await ui.expect(saved).toContainText('Selesai menurut pemeriksaan ERP');await ui.expect(saved.getByRole('button',{name:'Buka riwayat yang lebih lama',exact:true})).toHaveCount(0);await shot(`P16_HISTORY_OLDEST_${suffix}.png`)
  await read(()=>saved.getByRole('button',{name:'Buka riwayat paling baru',exact:true}).click())
  let release,entered,delivered;const gate=new Promise(r=>{release=r}),ready=new Promise(r=>{entered=r}),finished=new Promise(r=>{delivered=r});await page.route(readRpc,async route=>{const response=await route.fetch();assert.equal(response.status(),200);entered();await gate;await route.fulfill({response});delivered()});await saved.getByRole('button',{name:'Buka riwayat yang lebih lama',exact:true}).click();await ready;await ui.expect(panel.locator('.native-analysis-result')).toHaveCount(0);await ui.expect(page.locator('.cfg-totals')).toHaveCount(0);await page.evaluate(()=>window.dispatchEvent(new StorageEvent('storage',{key:null})));release();await finished;await ui.expect(saved).toHaveCount(0);await ui.expect(panel.locator('.native-analysis-result')).toHaveCount(0);await page.unroute(readRpc)
  await panel.getByText('Arsip analisis yang pernah dibuka',{exact:true}).click();await panel.getByRole('button',{name:'Buka arsip analisis 1',exact:true}).click();await observe();await read(()=>article.getByRole('button',{name:'Buka seluruh riwayat masalah',exact:true}).click())
  fixture('deactivate',{actor:user.user.id});const denied=page.waitForResponse(r=>r.url().endsWith('/rpc/erp_cp7_get_obligation_episode_history_v1')),parent=page.waitForResponse(r=>r.url().endsWith('/rpc/erp_cp7_get_fg_v1'));await saved.getByRole('button',{name:'Buka riwayat yang lebih lama',exact:true}).click();assert.equal((await denied).status(),403);assert.equal((await parent).status(),403);await ui.expect(saved).toHaveCount(0);await ui.expect(panel.locator('.native-analysis-result')).toHaveCount(0);await ui.expect(page.locator('.cfg-totals')).toHaveCount(0);assert.equal(await dirty.inputValue(),'P16 RIWAYAT LAMA ISIAN');await shot(`P16_HISTORY_REVOKED_${suffix}.png`)
  fixture('restore',{actor:user.user.id});await panel.getByRole('button',{name:'Buka arsip analisis 1',exact:true}).click();await panel.getByRole('tab',{name:'Tanya AI',exact:true}).click();assert.equal(await panel.getByLabel('Pertanyaan analisis ERP',{exact:true}).inputValue(),'P16 riwayat lama pertanyaan sendiri');assert.equal(state().analysis_count,count)
  return{status:'PASS',actual_Auth_Native_history_complete26_keyset25_plus1:true,actual_Native_payment_inverse_recursions_closed_first_and_linked_latest:true,every_history_read_exact_own_Original_business_and_all_monitoring_metadata_unchanged:true,held_actual200_scope_invalidation_retires_late_history:true,current403_retires_history_parent_FG_HPP_dirty_fields_and_question_preserved:true,no_new_analysis_or_local_history_fact_cache_business_write_or_delivery:true,screenshots:shots}
 }catch(e){writeFileSync(`cp6-proof/t3/P16_HISTORY_${suffix}_FAILURE.json`,JSON.stringify({error:String(e),text:await panel.innerText().catch(()=>''),original,lastHistory},null,2));await page.screenshot({path:`cp6-proof/t3/P16_HISTORY_${suffix}_FAILURE.png`,fullPage:true}).catch(()=>{});throw e}
 finally{fixture('restore',{actor:user.user.id});await user.context.close()}
}
export function cases(ui,today){return[['P16_BROWSER_DESKTOP_NATIVE_SAVED_EPISODE_HISTORY',()=>journey(ui,today,false)],['P16_BROWSER_MOBILE_NATIVE_SAVED_EPISODE_HISTORY',()=>journey(ui,today,true)]]}
