import assert from 'node:assert/strict'
import {execFileSync} from 'node:child_process'
import {mkdirSync,writeFileSync} from 'node:fs'
import {cases as previousCases} from './cp7_f04_netting_browser.mjs'
const fixture=(op,p)=>JSON.parse(execFileSync('python',['../auditor/scripts/cp7_f05_analysis_browser_fixture.py',op],{input:JSON.stringify(p),cwd:'../writer',encoding:'utf8',maxBuffer:16*1024*1024}).trim())
async function navigate(page){await page.locator('.sidebar .nav-main').filter({hasText:'Gudang'}).waitFor({state:'attached'});const menu=page.getByRole('button',{name:'Buka menu',exact:true});if(await menu.isVisible())await menu.click();const link=page.getByRole('button',{name:'• Ringkasan Barang Jadi',exact:true});if(!await link.isVisible())await page.locator('.sidebar .nav-main').filter({hasText:'Gudang'}).click();await link.click()}
async function shot(ui,page,name){await ui.expect.poll(()=>page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);await page.screenshot({path:'cp6-proof/t3/'+name,fullPage:true})}
async function journey(ui,today,mobile){
 const f=fixture('prepare',{today}),user=await ui.login('OWNER',{label:'p14-analysis-'+mobile,mobile,timezoneId:mobile?'America/Los_Angeles':'Asia/Jakarta'}),page=user.page,suffix=mobile?'MOBILE':'DESKTOP',panel=page.getByRole('region',{name:'Analisis ERP bersama',exact:true}),history=page.getByRole('region',{name:'Data permintaan ERP',exact:true}),shots=[]
 let lost=null,original=null;const state=()=>fixture('state',{actor:user.user.id})
 try{
  mkdirSync('cp6-proof/t3',{recursive:true});await navigate(page);const dirty=page.getByLabel('Cari barang jadi',{exact:true});await dirty.fill('P14 ANALISIS ISIAN GUDANG');await history.getByRole('button',{name:'Data permintaan & stok',exact:true}).click();await history.getByRole('button',{name:'Analisis, laporan & pengingat seluruh produk',exact:true}).click();const before=state()
  await page.route('**/rest/v1/rpc/erp_cp7_capture_analysis_v1',async route=>{if(!lost){const r=await route.fetch();assert.equal(r.status(),200);lost={envelope:route.request().postDataJSON(),body:await r.json()};await route.abort('failed')}else await route.continue()})
  await panel.getByRole('button',{name:'Ambil analisis ERP terbaru',exact:true}).click();await ui.expect(panel.getByRole('button',{name:'Ulangi analisis yang sama',exact:true})).toBeEnabled();assert.equal(state().analysis_count,before.analysis_count+1);await shot(ui,page,`P14_UNCERTAIN_${suffix}.png`);shots.push(`P14_UNCERTAIN_${suffix}.png`)
  const replay=page.waitForResponse(r=>r.url().endsWith('/rpc/erp_cp7_capture_analysis_v1'));await panel.getByRole('button',{name:'Ulangi analisis yang sama',exact:true}).click();const r=await replay;assert.equal(r.status(),200);assert.deepEqual(r.request().postDataJSON(),lost.envelope);original=await r.json();assert.equal(original.run_id,lost.body.run_id);assert.deepEqual(original.analysis,lost.body.analysis);assert.equal(state().analysis_count,before.analysis_count+1)
  const x=original.analysis,target=x.recommendations.find(r=>r.target.product_id===f.product);assert.equal(target.actual_fg.value,'0');assert.equal(target.target_qty.value,'100');assert.equal(target.q_base.value,'93');assert.equal(target.q_conditional.value,'93');assert.equal(target.feasible_new.state,'UNKNOWN');assert.equal(x.financial_readiness,'BLOCKED');assert.equal(original.apply_enabled,false);assert.equal(x.fixture_kind,undefined);assert.deepEqual(state().business,before.business)
  await ui.expect(panel.locator('.native-analysis-result')).toContainText('93 PCS');const runCount=state().analysis_count;await shot(ui,page,`P14_PRODUCTION_${suffix}.png`);shots.push(`P14_PRODUCTION_${suffix}.png`)
  await panel.getByLabel('Cari hasil analisis bersama',{exact:true}).fill(original.product_labels.find(l=>l.target_key===target.target.key).sku);assert.equal(await panel.locator('tbody tr').count(),1)
  await panel.getByRole('tab',{name:'Laporan',exact:true}).click();const report=await panel.getByLabel('Isi laporan ERP',{exact:true}).innerText();assert.ok(report.includes('93 PCS'));assert.ok(report.includes(x.semantic_hash));assert.ok(original.financial_source);assert.ok(report.includes('Keuangan: '+original.financial_source.report.snapshot.data_confidence.status));assert.ok(report.includes('HPP penjualan tercatat'));assert.ok(report.includes(original.financial_source.source_hash));assert.ok(!report.includes('DATA CONTOH'));await shot(ui,page,`P15_REPORT_${suffix}.png`);shots.push(`P15_REPORT_${suffix}.png`)
  await panel.getByRole('tab',{name:'Pengingat',exact:true}).click();await ui.expect(panel.getByRole('tabpanel')).toContainText('Bahan dan batas produksi perlu diperiksa');await shot(ui,page,`P16_REMINDER_${suffix}.png`);shots.push(`P16_REMINDER_${suffix}.png`)
  await panel.getByRole('tab',{name:'Tanya AI',exact:true}).click();await panel.getByLabel('Pertanyaan analisis ERP',{exact:true}).fill('Periksa angka 93 ini dan jangan mengarang HPP');const prompt=await panel.getByLabel('Pertanyaan dan sumber ERP',{exact:true}).innerText();assert.ok(prompt.includes(report));assert.ok(prompt.includes(JSON.stringify(x)));assert.ok(prompt.includes(JSON.stringify(original.financial_source)));assert.ok(prompt.includes('Periksa angka 93 ini'));assert.equal(state().analysis_count,runCount);await shot(ui,page,`P17_PROMPT_${suffix}.png`);shots.push(`P17_PROMPT_${suffix}.png`)
  await panel.getByRole('button',{name:'Tutup analisis bersama',exact:true}).click();await history.getByRole('button',{name:'Analisis, laporan & pengingat seluruh produk',exact:true}).click();await panel.getByText('Arsip analisis yang pernah dibuka',{exact:true}).click();const reopened=page.waitForResponse(r=>r.url().endsWith('/rpc/erp_cp7_read_analysis_v1'));await panel.getByRole('button',{name:'Buka arsip analisis 1',exact:true}).click();const ar=await reopened;assert.equal(ar.status(),200);assert.deepEqual((await ar.json()).analysis,x);assert.equal(state().analysis_count,runCount);await panel.getByRole('tab',{name:'Tanya AI',exact:true}).click();await panel.getByLabel('Pertanyaan analisis ERP',{exact:true}).fill('Periksa angka 93 ini dan jangan mengarang HPP');
  fixture('update_schedule',{today});const read=page.waitForResponse(r=>r.url().endsWith('/rpc/erp_cp7_read_analysis_v1'));await panel.getByRole('button',{name:'Periksa sumber analisis',exact:true}).click();const archive=await read;assert.equal(archive.status(),200);const old=await archive.json();assert.equal(old.source_state,'ARCHIVED_STALE');assert.deepEqual(old.analysis,x);await ui.expect(panel.locator('.native-analysis-result')).toContainText('Arsip lama: sumber berubah.');assert.equal(await panel.getByLabel('Pertanyaan analisis ERP',{exact:true}).inputValue(),'Periksa angka 93 ini dan jangan mengarang HPP');await ui.expect(panel.getByRole('button',{name:'Periksa & salin pertanyaan untuk AI',exact:true})).toBeDisabled();await shot(ui,page,`P14_ARCHIVE_${suffix}.png`);shots.push(`P14_ARCHIVE_${suffix}.png`)
  fixture('deactivate',{actor:user.user.id});const denied=page.waitForResponse(r=>r.url().endsWith('/rpc/erp_cp7_read_analysis_v1')),parent=page.waitForResponse(r=>r.url().endsWith('/rpc/erp_cp7_get_fg_v1'));await panel.getByRole('button',{name:'Periksa sumber analisis',exact:true}).click();assert.equal((await denied).status(),403);assert.equal((await parent).status(),403);await ui.expect(panel.locator('.native-analysis-result')).toHaveCount(0);await ui.expect(page.locator('.cfg-totals')).toHaveCount(0);assert.equal(await dirty.inputValue(),'P14 ANALISIS ISIAN GUDANG');await shot(ui,page,`P14_REVOKED_${suffix}.png`);shots.push(`P14_REVOKED_${suffix}.png`)
  return{status:'PASS',actual_Auth_and_Native_opening8_selected7_target100_FG0_gap93:true,one_original_analysis_for_all_four_consumers:true,archive_remount_reads_same_original_from_server_under_current_auth:true,presentation_filter_and_tab_switch_do_not_recapture_or_reallocate:true,lost_reply_identical_UUID_one_immutable_run:true,report_and_prompt_keep_native_hash_values_unknowns_and_complete_original_result:true,material_unknown_native_financial_readiness_respected_no_apply:true,source_changed_archive_body_and_dirty_question_preserved:true,current403_retires_all_consumers_and_parent_FG_Hpp:true,original_stock_search_preserved:true,native_business_unchanged:true,screenshots:shots}
 }catch(e){writeFileSync(`cp6-proof/t3/P14_ANALYSIS_${suffix}_FAILURE.json`,JSON.stringify({error:String(e),text:await panel.innerText().catch(()=>''),lost,original},null,2));await page.screenshot({path:`cp6-proof/t3/P14_ANALYSIS_${suffix}_FAILURE.png`,fullPage:true}).catch(()=>{});throw e}
 finally{fixture('restore',{actor:user.user.id});await user.context.close()}
}
export function cases(ui,today){return[...previousCases(ui,today),['P14_BROWSER_DESKTOP_SHARED_ANALYSIS',()=>journey(ui,today,false)],['P14_BROWSER_MOBILE_SHARED_ANALYSIS',()=>journey(ui,today,true)]]}
