import assert from'node:assert/strict'
import{execFileSync}from'node:child_process'
import{mkdirSync,writeFileSync}from'node:fs'
const control=(file,op,p)=>JSON.parse(execFileSync('python',['../auditor/scripts/'+file,op],{input:JSON.stringify(p),cwd:'../writer',encoding:'utf8',maxBuffer:16*1024*1024}).trim())
const fixture=(op,p)=>control('cp7_f05_analysis_browser_fixture.py',op,p)
const ap=(op,p)=>control('cp7_f05_payable_browser_fixture.py',op,p)
async function navigate(page){await page.locator('.sidebar .nav-main').filter({hasText:'Gudang'}).waitFor({state:'attached'});const menu=page.getByRole('button',{name:'Buka menu',exact:true});if(await menu.isVisible())await menu.click();const link=page.getByRole('button',{name:'• Ringkasan Barang Jadi',exact:true});if(!await link.isVisible())await page.locator('.sidebar .nav-main').filter({hasText:'Gudang'}).click();await link.click()}
async function journey(ui,today,mobile){
 fixture('prepare',{today});const receipt=ap('prepare',{today}),user=await ui.login('OWNER',{label:'p16-material-ap-'+mobile,mobile,timezoneId:'America/Los_Angeles'}),page=user.page,suffix=mobile?'MOBILE':'DESKTOP',panel=page.getByRole('region',{name:'Analisis ERP bersama',exact:true}),history=page.getByRole('region',{name:'Data permintaan ERP',exact:true}),source=panel.getByRole('region',{name:'Sumber utang bahan pemasok terkini',exact:true}),article=source.getByRole('article',{name:'Utang bahan '+receipt.tag,exact:true}),shots=[]
 let original=null
 const state=()=>ap('state',{actor:user.user.id}),shot=async name=>{await ui.expect.poll(()=>page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);await page.screenshot({path:'cp6-proof/t3/'+name,fullPage:true});shots.push(name)}
 const read=async()=>{const before=state(),response=page.waitForResponse(r=>r.url().endsWith('/rpc/erp_cp7_get_analysis_payable_conditions_v1'));await source.getByRole('button',{name:'Periksa utang bahan pemasok dari ERP',exact:true}).click();const r=await response;assert.equal(r.status(),200);const e=await r.json();assert.deepEqual(e.analysis.analysis,original.analysis);assert.deepEqual(e.analysis.financial_source,original.financial_source);assert.equal(e.source.page_complete,true);assert.equal(e.source.rows.length,Number(e.source.total));assert.deepEqual(state(),before);const row=e.source.rows.find(r=>r.liability.purchase_id===receipt.receipt.purchase_id);assert.ok(row);await ui.expect(source.getByRole('navigation',{name:'Halaman utang bahan pemasok',exact:true})).toBeVisible();for(let i=0;i<200&&!await article.isVisible();i++){const next=source.getByRole('button',{name:'Utang bahan berikutnya',exact:true});assert.ok(await next.isEnabled(),'Native target receipt missing from complete AP source');await next.click()}await ui.expect(article).toBeVisible();return row}
 try{
  mkdirSync('cp6-proof/t3',{recursive:true});await navigate(page);const dirty=page.getByLabel('Cari barang jadi',{exact:true});await dirty.fill('P16 UTANG BAHAN ISIAN GUDANG');await history.getByRole('button',{name:'Data permintaan & stok',exact:true}).click();await history.getByRole('button',{name:'Analisis, laporan & pengingat seluruh produk',exact:true}).click()
  const capture=page.waitForResponse(r=>r.url().endsWith('/rpc/erp_cp7_capture_analysis_v1'));await panel.getByRole('button',{name:'Ambil analisis ERP terbaru',exact:true}).click();const captured=await capture;assert.equal(captured.status(),200);original=await captured.json();const count=state().analysis_count;await panel.getByRole('tab',{name:'Pengingat',exact:true}).click();await ui.expect(source).toContainText('Sumber utang bahan belum dimuat.');let row=await read();assert.equal(row.balance.remaining,'0.00');assert.equal(row.condition.state,'INVOICE_PENDING');assert.equal(row.condition.business_resolved,false);await ui.expect(article).toContainText('Invoice penerimaan belum lengkap.');await shot(`P16_AP_PENDING_${suffix}.png`)
  ap('finalize_pay200',{receipt,today});row=await read();assert.equal(row.balance.final_ap,'500.00');assert.equal(row.balance.paid,'200.00');assert.equal(row.balance.remaining,'300.00');assert.equal(row.condition.state,'OVERDUE');assert.equal(row.condition.business_resolved,false);await ui.expect(article).toContainText('Saldo tagihan final Rp300');await shot(`P16_AP_OPEN_${suffix}.png`)
  await panel.getByRole('button',{name:'Muat perhatian tersimpan',exact:true}).click();const action=original.analysis.actions[0];assert.ok(action);const attention=panel.getByRole('article',{name:'Perhatian '+action.key,exact:true});await ui.expect(attention.getByRole('button',{name:'Selesai ditinjau',exact:true})).toBeEnabled();const done=page.waitForResponse(r=>r.url().endsWith('/rpc/erp_cp7_save_analysis_attention_v1'));await attention.getByRole('button',{name:'Selesai ditinjau',exact:true}).click();assert.equal((await done).status(),200);row=await read();assert.equal(row.balance.remaining,'300.00');assert.equal(row.condition.business_resolved,false)
  const paid=ap('settle',{receipt,today});row=await read();assert.equal(row.balance.remaining,'0.00');assert.equal(row.condition.state,'ZERO_BALANCE');assert.equal(row.condition.business_resolved,true);await ui.expect(article).toContainText('Tagihan final tersisa nol');await shot(`P16_AP_SETTLED_${suffix}.png`)
  ap('inverse',paid);row=await read();assert.equal(row.balance.remaining,'300.00');assert.equal(row.condition.business_resolved,false);await ui.expect(article).toContainText('Saldo tagihan final Rp300');await shot(`P16_AP_INVERSE_${suffix}.png`)
  await panel.getByRole('tab',{name:'Tanya AI',exact:true}).click();await panel.getByLabel('Pertanyaan analisis ERP',{exact:true}).fill('P16 utang bahan pertanyaan belum dikirim');await panel.getByRole('tab',{name:'Pengingat',exact:true}).click();fixture('deactivate',{actor:user.user.id});const denied=page.waitForResponse(r=>r.url().endsWith('/rpc/erp_cp7_get_analysis_payable_conditions_v1')),parent=page.waitForResponse(r=>r.url().endsWith('/rpc/erp_cp7_get_fg_v1'));await source.getByRole('button',{name:'Periksa utang bahan pemasok dari ERP',exact:true}).click();assert.equal((await denied).status(),403);assert.equal((await parent).status(),403);await ui.expect(panel.locator('.native-analysis-result')).toHaveCount(0);await ui.expect(page.locator('.cfg-totals')).toHaveCount(0);assert.equal(await dirty.inputValue(),'P16 UTANG BAHAN ISIAN GUDANG');await shot(`P16_AP_REVOKED_${suffix}.png`)
  fixture('restore',{actor:user.user.id});await panel.getByText('Arsip analisis yang pernah dibuka',{exact:true}).click();await panel.getByRole('button',{name:'Buka arsip analisis 1',exact:true}).click();await panel.getByRole('tab',{name:'Tanya AI',exact:true}).click();assert.equal(await panel.getByLabel('Pertanyaan analisis ERP',{exact:true}).inputValue(),'P16 utang bahan pertanyaan belum dikirim');assert.equal(state().analysis_count,count)
  return{status:'PASS',actual_Native_GRNI_receipt_estimate500_never_paid_or_healthy_final_zero:true,actual_final_invoice500_payment200_remaining300_due_source:true,review_done_never_settles_AP:true,actual_final300_payment_resolves_and_inverse_reopens300:true,immutable_Original_ops_and_finance_current_AP_separate_read_only:true,complete_source_display_pages_no_recapture_or_fact_cache:true,current403_retires_all_source_and_parent_FG_HPP:true,dirty_question_stock_search_preserved_under_foreign_device_timezone:true,no_external_delivery_or_opening_payroll_AP_coverage_claim:true,screenshots:shots}
 }catch(e){writeFileSync(`cp6-proof/t3/P16_AP_${suffix}_FAILURE.json`,JSON.stringify({error:String(e),text:await panel.innerText().catch(()=>''),original},null,2));await page.screenshot({path:`cp6-proof/t3/P16_AP_${suffix}_FAILURE.png`,fullPage:true}).catch(()=>{});throw e}
 finally{fixture('restore',{actor:user.user.id});await user.context.close()}
}
export function cases(ui,today){return[['P16_BROWSER_DESKTOP_CURRENT_NATIVE_MATERIAL_AP',()=>journey(ui,today,false)],['P16_BROWSER_MOBILE_CURRENT_NATIVE_MATERIAL_AP',()=>journey(ui,today,true)]]}
