import assert from 'node:assert/strict'
import {execFileSync} from 'node:child_process'
import {mkdirSync,writeFileSync} from 'node:fs'
const fixture=(op,p)=>JSON.parse(execFileSync('python',['../auditor/scripts/cp7_sales_return_correction_browser_fixture.py',op],{input:JSON.stringify(p),cwd:'../writer',encoding:'utf8',maxBuffer:16*1024*1024}).trim())
const endpoint='**/rest/v1/rpc/erp_cp7_correct_sales_return_v1'
async function menu(page){const open=page.getByRole('button',{name:'Buka menu',exact:true});if(await open.isVisible())await open.click();const link=page.getByRole('button',{name:'• Retur Penjualan',exact:true});if(!await link.isVisible())await page.locator('.sidebar .nav-main').filter({hasText:'Penjualan'}).click();await link.click()}
async function observed(page,button){const pending=page.waitForResponse(r=>r.url().endsWith('/rpc/erp_cp7_correct_sales_return_v1')).then(response=>({response}),error=>({error}));await button.click();const r=await pending;if(r.error)throw r.error;return r.response}
async function journey(ui,today,mobile){
 const f=fixture('prepare',{today}),user=await ui.login(mobile?'ADMIN':'OWNER',{label:'return-correction-'+mobile,mobile,timezoneId:'America/Los_Angeles'}),page=user.page,suffix=mobile?'MOBILE':'DESKTOP',requests=[]
 const state=()=>fixture('state',{fixture:f.fixture}),panel=()=>page.getByRole('region',{name:'Retur fisik invoice',exact:true}),row=id=>panel().locator(`[data-return-id="${id}"]`),history=()=>page.getByRole('region',{name:'Pembetulan retur tercatat',exact:true}),form=()=>page.getByRole('form',{name:'Edit retur pelanggan',exact:true}),detail=()=>page.getByRole('complementary',{name:'Rincian invoice',exact:true})
 page.on('request',r=>{if(/\/rpc\/erp_cp7_(?:correct_sales_return|save_sale)_v1$/.test(r.url()))requests.push({url:r.url(),body:r.postDataJSON()})})
 async function openReturns(){await detail().getByRole('button',{name:'Retur fisik invoice',exact:true}).click();await ui.expect(panel()).toBeVisible()}
 try{
  mkdirSync('cp6-proof/t3',{recursive:true});const before=state();await menu(page);await page.getByLabel('Cari invoice',{exact:true}).fill(f.invoice.number);await page.getByRole('button',{name:'Cari invoice',exact:true}).click();await page.locator('[aria-label="Daftar invoice"] .cproc-receipt').filter({hasText:f.invoice.number}).click();await openReturns()
  await row(f.workspace.document.id).getByRole('button',{name:`Edit retur ${f.workspace.document.number}`,exact:true}).click();await ui.expect(form().getByLabel('Jumlah pembetulan retur 1',{exact:true})).toHaveValue('2');await form().getByLabel('Jumlah pembetulan retur 1',{exact:true}).fill('1');await form().getByLabel('Nilai pembetulan retur 1',{exact:true}).fill('20');await form().getByLabel('Alasan pembetulan retur',{exact:true}).fill('Jumlah barang retur diperbaiki setelah pemeriksaan fisik');await form().getByLabel('Pembetulan retur sudah diperiksa',{exact:true}).check()
  let first
  if(!mobile){let intercepted;await page.route(endpoint,async route=>{try{const r=await route.fetch();intercepted={status:r.status()};if(r.status()===200){first=await r.json();await route.abort('failed')}else await route.fulfill({response:r})}catch(error){intercepted={error:String(error)};await route.abort('failed').catch(()=>{})}})
   await form().getByRole('button',{name:'Simpan pembetulan retur',exact:true}).click();await ui.expect.poll(()=>intercepted!==undefined).toBe(true);assert.equal(intercepted.status,200,JSON.stringify(intercepted));assert.equal(state().chain.length,1);await ui.expect(page.getByRole('button',{name:'Reconcile transaksi',exact:true})).toBeVisible();const request=structuredClone(requests[0].body);await page.unroute(endpoint);await page.reload();await menu(page);const response=await observed(page,page.getByRole('button',{name:'Reconcile transaksi',exact:true}));assert.equal(response.status(),200);assert.deepEqual(await response.json(),first);assert.deepEqual(requests[1].body,request)
  }else{const response=await observed(page,form().getByRole('button',{name:'Simpan pembetulan retur',exact:true}));assert.equal(response.status(),200);first=await response.json()}
  await ui.expect(detail()).toContainText('Sisa pembayaran Rp60');const after=state();assert.equal(after.original.status,'REVERSED');assert.equal(after.original.items[0].qty_pcs,'2');assert.equal(after.current.items[0].qty_pcs,'1');assert.equal(after.current.items[0].refund_amount,'20.00');assert.equal(after.current.physical_at,f.workspace.document.physical_at);assert.match(after.current.physical_at,/123456/);assert.equal(after.available,before.available-1);assert.equal(after.original_physical_input_unchanged,true);assert.equal(after.original_sale_input_unchanged,true)
  await openReturns();await ui.expect(row(first.return_id)).toHaveAttribute('data-source-selected','true');await row(first.return_id).getByRole('button',{name:`Lihat perubahan retur ${after.current.number}`,exact:true}).click();await ui.expect(history().getByRole('region',{name:'Isi retur sebelum pembetulan',exact:true})).toContainText('Rp40')
  await history().getByRole('button',{name:`Buka retur sebelum pembetulan ${f.workspace.document.number}`,exact:true}).click();await ui.expect(row(f.workspace.document.id)).toHaveAttribute('data-source-selected','true');await row(f.workspace.document.id).getByRole('button',{name:`Lihat perubahan retur ${f.workspace.document.number}`,exact:true}).click();await history().getByRole('button',{name:`Buka retur pengganti ${after.current.number}`,exact:true}).click();await ui.expect(row(first.return_id)).toHaveAttribute('data-source-selected','true')
  await row(first.return_id).getByRole('button',{name:`Lihat perubahan retur ${after.current.number}`,exact:true}).click();await history().getByRole('button',{name:'Pulihkan isi retur sebelum pembetulan',exact:true}).click();await ui.expect(form().getByLabel('Jumlah pembetulan retur 1',{exact:true})).toHaveValue('2');await ui.expect(form().getByLabel('Nilai pembetulan retur 1',{exact:true})).toHaveValue('40.00');await form().getByLabel('Alasan pembetulan retur',{exact:true}).fill('Isi retur awal dipulihkan setelah pemeriksaan ulang');await form().getByLabel('Pembetulan retur sudah diperiksa',{exact:true}).check()
  const response=await observed(page,form().getByRole('button',{name:'Simpan pembetulan retur',exact:true}));assert.equal(response.status(),200);const second=await response.json();await ui.expect(detail()).toContainText('Sisa pembayaran Rp40');const final=state();assert.equal(final.chain.length,2);assert.equal(final.current.id,second.return_id);assert.equal(final.current.items[0].qty_pcs,'2');assert.equal(final.current.items[0].refund_amount,'40.00');assert.equal(final.current.physical_at,f.workspace.document.physical_at);assert.equal(final.available,before.available);assert.deepEqual(final.positions,before.positions);assert.deepEqual(final.accounts,before.accounts);assert.equal(final.original_physical_input_unchanged,true);assert.equal(final.original_sale_input_unchanged,true);assert.equal(requests.length,mobile?2:3);assert.equal(requests.filter(r=>r.url.endsWith('/erp_cp7_save_sale_v1')).length,0)
  await openReturns();await ui.expect(row(second.return_id)).toHaveAttribute('data-source-selected','true');await row(second.return_id).getByRole('button',{name:`Lihat perubahan retur ${final.current.number}`,exact:true}).click();await ui.expect(history()).toContainText('Rp20');await ui.expect.poll(()=>page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);await page.screenshot({path:`cp6-proof/t3/CP7_RETURN_CORRECTION_${suffix}.png`,fullPage:true})
  return{status:'PASS',mobile,actual_Auth_original2_PCS40_new1_PCS20_restore2_PCS40:true,one_atomic_backend_command_each:true,actual_lost_committed_reply_exact_UUID_recovery:!mobile,actual_exact_old_and_replacement_source_focus:true,immutable_two_link_history:true,Native_microseconds_original_inputs_preserved_and_stock_accounts_restored:true,screenshot:`CP7_RETURN_CORRECTION_${suffix}.png`}
 }catch(error){writeFileSync(`cp6-proof/t3/CP7_RETURN_CORRECTION_${suffix}_FAILURE.json`,JSON.stringify({error:String(error),stack:error.stack,text:await page.locator('main').innerText().catch(()=>''),state:state(),requests},null,2));await page.screenshot({path:`cp6-proof/t3/CP7_RETURN_CORRECTION_${suffix}_FAILURE.png`,fullPage:true}).catch(()=>{});throw error}
 finally{await page.unroute(endpoint).catch(()=>{});await user.context.close()}
}
export function cases(ui,today){return[['CP7_RETURN_CORRECTION_BROWSER_DESKTOP',()=>journey(ui,today,false)],['CP7_RETURN_CORRECTION_BROWSER_MOBILE',()=>journey(ui,today,true)]]}
