import assert from'node:assert/strict'
import{execFileSync}from'node:child_process'
import{mkdirSync,writeFileSync}from'node:fs'
const fixture=(op,p)=>JSON.parse(execFileSync('python',['../auditor/scripts/cp7_f05_other_browser_fixture.py',op],{input:JSON.stringify(p),cwd:'../writer',encoding:'utf8',maxBuffer:16*1024*1024}).trim())
async function navigate(page){await page.locator('.sidebar .nav-main').filter({hasText:'Gudang'}).waitFor({state:'attached'});const menu=page.getByRole('button',{name:'Buka menu',exact:true});if(await menu.isVisible())await menu.click();const link=page.getByRole('button',{name:'• Ringkasan Barang Jadi',exact:true});if(!await link.isVisible())await page.locator('.sidebar .nav-main').filter({hasText:'Gudang'}).click();await link.click()}
async function journey(ui,today,mobile){
 const native=fixture('prepare',{today}),user=await ui.login('OWNER',{label:'p15-obligation-report-'+mobile,mobile,timezoneId:'America/Los_Angeles'}),page=user.page,suffix=mobile?'MOBILE':'DESKTOP'
 const panel=page.getByRole('region',{name:'Analisis ERP bersama',exact:true}),reports=panel.getByRole('region',{name:'Laporan ERP tersimpan',exact:true}),appendix=reports.getByRole('region',{name:'Lampiran tagihan laporan ERP',exact:true}),history=page.getByRole('region',{name:'Data permintaan ERP',exact:true}),shots=[]
 let original=null,base=null,preview=null,one=null,lost=null,routeError=null
 const shot=async name=>{await ui.expect.poll(()=>page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);await page.screenshot({path:'cp6-proof/t3/'+name,fullPage:true});shots.push(name)}
 try{
  mkdirSync('cp6-proof/t3',{recursive:true});await navigate(page);const dirty=page.getByLabel('Cari barang jadi',{exact:true});await dirty.fill('P15 LAMPIRAN ISIAN GUDANG');await history.getByRole('button',{name:'Data permintaan & stok',exact:true}).click();await history.getByRole('button',{name:'Analisis, laporan & pengingat seluruh produk',exact:true}).click()
  const capture=page.waitForResponse(r=>r.url().endsWith('/rpc/erp_cp7_capture_analysis_v1'));await panel.getByRole('button',{name:'Ambil analisis ERP terbaru',exact:true}).click();const c=await capture;assert.equal(c.status(),200);original=await c.json();await panel.getByRole('tab',{name:'Laporan',exact:true}).click()
  await reports.getByLabel('Jenis laporan tersimpan',{exact:true}).selectOption('PERIOD');await reports.getByLabel('Judul laporan tersimpan',{exact:true}).fill('Laporan dasar untuk lampiran');await reports.getByLabel('Alasan laporan tersimpan',{exact:true}).fill('Sumber Native ditinjau');await reports.getByLabel('Laporan sudah ditinjau',{exact:true}).check()
  const savingBase=page.waitForResponse(r=>r.url().endsWith('/rpc/erp_cp7_publish_report_v1'));await reports.getByRole('button',{name:'Simpan laporan yang ditinjau',exact:true}).click();const saved=await savingBase;assert.equal(saved.status(),200);base=(await saved.json()).document
  await appendix.getByLabel('Judul lampiran tagihan',{exact:true}).fill('Lampiran tagihan Native');await appendix.getByLabel('Alasan lampiran tagihan',{exact:true}).fill('Tanggal dan angka yang diketahui sekarang ditinjau')
  const checking=page.waitForResponse(r=>r.url().endsWith('/rpc/erp_cp7_get_obligation_report_preview_v1'));await appendix.getByRole('button',{name:'Periksa tagihan untuk laporan yang dibuka',exact:true}).click();const checked=await checking;assert.equal(checked.status(),200);preview=await checked.json();assert.deepEqual(preview.source.analysis.analysis,original.analysis);assert.deepEqual(preview.base_report.period_query,base.period_query)
  await ui.expect(appendix.getByLabel('Pratinjau lampiran tagihan',{exact:true})).toContainText('9007199254740993.01 IDR');await ui.expect(appendix.getByLabel('Pratinjau lampiran tagihan',{exact:true})).toContainText('jatuh tempo tercatat Belum diketahui');await ui.expect(appendix.getByLabel('Pratinjau lampiran tagihan',{exact:true})).toContainText('Jangan menjumlahkan baris ini sebagai total utang');await shot('P15_OBLIGATION_REPORT_PREVIEW_'+suffix+'.png')
  await appendix.getByLabel('Lampiran tagihan sudah ditinjau',{exact:true}).check()
  await page.route('**/rest/v1/rpc/erp_cp7_publish_obligation_report_v1',async route=>{try{if(!lost){const r=await route.fetch();assert.equal(r.status(),200);lost={payload:route.request().postDataJSON(),body:await r.json()};await route.abort('failed')}else await route.continue()}catch(error){routeError=error;await route.abort('failed').catch(()=>{})}})
  const failed=page.waitForEvent('requestfailed',{predicate:r=>r.url().endsWith('/rpc/erp_cp7_publish_obligation_report_v1'),timeout:60000});await appendix.getByRole('button',{name:'Simpan lampiran tagihan yang ditinjau',exact:true}).click();await failed;if(routeError)throw routeError;assert.ok(lost);await ui.expect(appendix.getByRole('button',{name:'Periksa hasil lampiran tersimpan',exact:true})).toBeEnabled()
  const recovering=page.waitForResponse(r=>r.url().endsWith('/rpc/erp_cp7_get_obligation_report_request_v1'));await appendix.getByRole('button',{name:'Periksa hasil lampiran tersimpan',exact:true}).click();const recovered=await recovering;assert.equal(recovered.status(),200);assert.deepEqual(recovered.request().postDataJSON(),lost.payload);one=(await recovered.json()).document;assert.equal(one.body,lost.body.document.body);assert.equal(one.base_report.body,base.body);await ui.expect(appendix.getByLabel('Teks lampiran tagihan tersimpan',{exact:true})).toHaveText(one.body);await shot('P15_OBLIGATION_REPORT_RECOVERED_'+suffix+'.png')
  fixture('partial',{payroll:native.payroll});await appendix.getByLabel('Judul lampiran tagihan',{exact:true}).fill('Judul belum dikirim');await appendix.getByLabel('Alasan lampiran tagihan',{exact:true}).fill('Alasan belum dikirim')
  const oldRead=page.waitForResponse(r=>r.url().endsWith('/rpc/erp_cp7_read_obligation_report_v1'));await appendix.getByRole('button',{name:'Periksa & salin lampiran tagihan',exact:true}).click();const old=await oldRead;assert.equal(old.status(),200);const archived=await old.json();assert.equal(archived.source_state,'ARCHIVED_STALE');assert.equal(archived.body,one.body);assert.deepEqual(archived.source,one.source);await ui.expect(appendix.getByLabel('Teks lampiran tagihan tersimpan',{exact:true})).toHaveText(one.body);assert.equal(await appendix.getByLabel('Judul lampiran tagihan',{exact:true}).inputValue(),'Judul belum dikirim');await shot('P15_OBLIGATION_REPORT_ARCHIVE_'+suffix+'.png')
  fixture('deactivate',{actor:user.user.id});const denied=page.waitForResponse(r=>r.url().endsWith('/rpc/erp_cp7_read_obligation_report_v1')),parent=page.waitForResponse(r=>r.url().endsWith('/rpc/erp_cp7_get_fg_v1'));await appendix.getByRole('button',{name:'Periksa & salin lampiran tagihan',exact:true}).click();assert.equal((await denied).status(),403);assert.equal((await parent).status(),403);await ui.expect(appendix.getByLabel('Teks lampiran tagihan tersimpan',{exact:true})).toHaveCount(0);await ui.expect(appendix.getByLabel('Salinan manual lampiran tagihan',{exact:true})).toHaveCount(0);await ui.expect(panel.locator('.native-analysis-result')).toHaveCount(0);await ui.expect(page.locator('.cfg-totals')).toHaveCount(0);assert.equal(await dirty.inputValue(),'P15 LAMPIRAN ISIAN GUDANG');assert.equal(await appendix.getByLabel('Alasan lampiran tagihan',{exact:true}).inputValue(),'Alasan belum dikirim');await shot('P15_OBLIGATION_REPORT_CURRENT_AUTH_'+suffix+'.png')
  return{status:'PASS',real_Auth_Native_publication_current_obligation_snapshot_exact_large_cent_and_unknown_due:true,lost_committed_reply_identical_UUID_recovery_one_archive:true,actual_partial_payment_preserves_old_body_and_snapshot_current_stale_mark:true,current403_retires_body_clipboard_Original_and_parent_FG_HPP:true,dirty_operator_and_stock_fields_preserved_under_foreign_device_timezone:true,screenshots:shots}
 }catch(e){try{const diagnostic=JSON.parse(execFileSync('python',['../auditor/scripts/cp7_native_read_profile.py'],{input:JSON.stringify({actor:user.user.id,today}),cwd:'../writer',encoding:'utf8',timeout:30000,maxBuffer:1024*1024}).trim());writeFileSync('cp6-proof/t3/P15_OBLIGATION_REPORT_'+suffix+'_READ_PROFILE.json',JSON.stringify(diagnostic,null,2))}catch{};writeFileSync('cp6-proof/t3/P15_OBLIGATION_REPORT_'+suffix+'_FAILURE.json',JSON.stringify({error:String(e),text:await panel.innerText().catch(()=>''),original,base,preview,one,lost},null,2));await page.screenshot({path:'cp6-proof/t3/P15_OBLIGATION_REPORT_'+suffix+'_FAILURE.png',fullPage:true}).catch(()=>{});throw e}
 finally{await page.unrouteAll({behavior:'wait'});fixture('restore',{actor:user.user.id});await user.context.close()}
}
export function cases(ui,today){return[['P15_OBLIGATION_REPORT_BROWSER_DESKTOP',()=>journey(ui,today,false)],['P15_OBLIGATION_REPORT_BROWSER_MOBILE',()=>journey(ui,today,true)]]}
