import assert from 'node:assert/strict'
import {execFileSync} from 'node:child_process'
import {mkdirSync,writeFileSync} from 'node:fs'
import {cases as historyCases} from './cp7_f04_history_browser.mjs'
const fixture=(op,p)=>JSON.parse(execFileSync('python',['../auditor/scripts/cp7_f04_model_browser_fixture.py',op],{input:JSON.stringify(p),cwd:'../writer',encoding:'utf8',maxBuffer:16*1024*1024}).trim())
async function navigate(page){await page.locator('.sidebar .nav-main').filter({hasText:'Gudang'}).waitFor({state:'attached'});const menu=page.getByRole('button',{name:'Buka menu',exact:true});if(await menu.isVisible())await menu.click();const link=page.getByRole('button',{name:'• Ringkasan Barang Jadi',exact:true});if(!await link.isVisible())await page.locator('.sidebar .nav-main').filter({hasText:'Gudang'}).click();await link.click()}
async function response(page,name,action){const[request]=await Promise.all([page.waitForRequest(r=>r.method()==='POST'&&r.url().endsWith('/rpc/'+name)),action()]);const result=await request.response();assert.ok(result,'The new Native request must receive its own response');return result}
async function journey(ui,today,mobile){
 const f=fixture('prepare',{today}),user=await ui.login('OWNER',{label:'p07-native-model-'+mobile,mobile,timezoneId:'America/Los_Angeles'}),page=user.page,suffix=mobile?'MOBILE':'DESKTOP',demand=page.getByRole('region',{name:'Data permintaan ERP',exact:true}),panel=page.getByRole('region',{name:'Evaluasi ramalan ERP',exact:true}),shots=[]
 const state=()=>fixture('state',{actor:user.user.id}),shot=async name=>{await ui.expect.poll(()=>page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);await page.screenshot({path:'cp6-proof/t3/'+name,fullPage:true});shots.push(name)}
 let original=null,lost=null,sku=null
 async function open(){await navigate(page);await demand.getByRole('button',{name:'Data permintaan & stok',exact:true}).click();const from=new Date(Date.parse(today+'T00:00:00Z')-12*86400000).toISOString().slice(0,10);await demand.getByLabel('Permintaan dari tanggal',{exact:true}).fill(from);const r=await response(page,'erp_cp7_capture_demand_history_v1',()=>demand.getByRole('button',{name:'Muat data permintaan',exact:true}).click());assert.equal(r.status(),200);const history=await r.json();sku=history.current_stock.find(x=>x.root_id===f.product).sku;await demand.getByLabel('Cari data permintaan',{exact:true}).fill(sku);await demand.getByRole('button',{name:'Bandingkan ramalan '+sku,exact:true}).click()}
 try{
  mkdirSync('cp6-proof/t3',{recursive:true});await open();const dirty=page.getByLabel('Cari barang jadi',{exact:true});await dirty.fill('P07 ISIAN GUDANG TETAP');assert.equal(state().model_rows,0);assert.equal(await panel.getByLabel('Jumlah hari ramalan',{exact:true}).inputValue(),'');await panel.getByLabel('Jumlah hari ramalan',{exact:true}).fill('1')
  const before=state();await page.route('**/rest/v1/rpc/erp_cp7_capture_model_evaluation_v1',async route=>{if(!lost){const r=await route.fetch();assert.equal(r.status(),200);lost={envelope:route.request().postDataJSON(),body:await r.json()};await route.abort('failed')}else await route.continue()})
  await panel.getByRole('button',{name:'Bandingkan model ERP',exact:true}).click();await ui.expect(panel.getByRole('button',{name:'Ulangi evaluasi yang sama',exact:true})).toBeEnabled();assert.equal(state().model_rows,1);assert.equal(state().business_sha256,before.business_sha256);await shot(`P07_MODEL_UNCERTAIN_${suffix}.png`)
  await page.reload();await open();const replay=await response(page,'erp_cp7_capture_model_evaluation_v1',()=>panel.getByRole('button',{name:'Ulangi evaluasi yang sama',exact:true}).click());assert.equal(replay.status(),200);assert.deepEqual(replay.request().postDataJSON(),lost.envelope);original=await replay.json();assert.deepEqual(original,lost.body);assert.equal(state().model_rows,1);assert.equal(await panel.getByLabel('Jumlah hari ramalan',{exact:true}).inputValue(),'1');await ui.expect(panel).toContainText('Aturan model baru tersedia setelah periode pembanding.');await ui.expect(panel).toContainText('Model terpilih: Rata-rata.');assert.equal(original.automatic_activation,false);assert.equal(original.apply_allowed,false);assert.equal(original.forecast,null);await shot(`P07_MODEL_FALLBACK_${suffix}.png`)
  await dirty.fill('P07 ISIAN GUDANG TETAP');fixture('post',{fixture:f});const archive=await response(page,'erp_cp7_read_model_evaluation_v1',()=>panel.getByRole('button',{name:'Periksa arsip evaluasi',exact:true}).click());assert.equal(archive.status(),200);const old=await archive.json();assert.equal(old.source_state,'ARCHIVED_STALE');assert.deepEqual({...old,source_state:original.source_state},original);await ui.expect(panel).toContainText('Arsip evaluasi: sumber sudah berubah.');assert.equal(state().model_rows,1);await shot(`P07_MODEL_ARCHIVE_${suffix}.png`)
  fixture('deactivate',{actor:user.user.id});const[denied,parent]=await Promise.all([page.waitForRequest(r=>r.method()==='POST'&&r.url().endsWith('/rpc/erp_cp7_read_model_evaluation_v1')).then(r=>r.response()),page.waitForRequest(r=>r.method()==='POST'&&r.url().endsWith('/rpc/erp_cp7_get_fg_v1')).then(r=>r.response()),panel.getByRole('button',{name:'Periksa arsip evaluasi',exact:true}).click()]);assert.ok(denied);assert.ok(parent);assert.equal(denied.status(),403);assert.equal(parent.status(),403);await ui.expect(panel.locator('.native-model-result')).toHaveCount(0);await ui.expect(page.locator('.cfg-totals')).toHaveCount(0);assert.equal(await dirty.inputValue(),'P07 ISIAN GUDANG TETAP');assert.equal(await panel.getByLabel('Jumlah hari ramalan',{exact:true}).inputValue(),'1');await shot(`P07_MODEL_REVOKED_${suffix}.png`)
  return{status:'PASS',actual_Auth_own_Native_snapshot_prospective_registry_fallback:true,no_fake_historical_training_or_public_promotion:true,committed_reply_loss_reload_exact_UUID_one_evaluation:true,actual_Native_sale_changes_source_not_frozen_model_result:true,current403_retires_model_parent_FG_HPP_dirty_fields_preserved:true,desktop_mobile_and_foreign_timezone:true,no_business_writer_apply_or_implicit_model_activation:true,screenshots:shots}
 }catch(e){writeFileSync(`cp6-proof/t3/P07_MODEL_${suffix}_FAILURE.json`,JSON.stringify({error:String(e),text:(await panel.innerText().catch(()=>'' )).slice(0,16000),lost,original},null,2));await page.screenshot({path:`cp6-proof/t3/P07_MODEL_${suffix}_FAILURE.png`,fullPage:true}).catch(()=>{});throw e}
 finally{fixture('restore',{actor:user.user.id});await user.context.close()}
}
export function cases(ui,today){return[...historyCases(ui,today),['P07_BROWSER_DESKTOP_NATIVE_MODEL',()=>journey(ui,today,false)],['P07_BROWSER_MOBILE_NATIVE_MODEL',()=>journey(ui,today,true)]]}
