import assert from 'node:assert/strict'
import {execFileSync} from 'node:child_process'
import {mkdirSync,writeFileSync} from 'node:fs'
const fixture=(op,p)=>JSON.parse(execFileSync('python',['../auditor/scripts/cp7_supplier_payment_correction_browser_fixture.py',op],{input:JSON.stringify(p),cwd:'../writer',encoding:'utf8',maxBuffer:16*1024*1024}).trim())
const endpoint='**/rest/v1/rpc/erp_cp7_correct_supplier_payment_v1'
async function menu(page){const open=page.getByRole('button',{name:'Buka menu',exact:true});if(await open.isVisible())await open.click();const link=page.getByRole('button',{name:'• Jurnal & Transaksi Lain',exact:true});if(!await link.isVisible())await page.locator('.sidebar .nav-main').filter({hasText:'Keuangan'}).click();await link.click()}
async function procurementMenu(page){const open=page.getByRole('button',{name:'Buka menu',exact:true});if(await open.isVisible())await open.click();const link=page.getByRole('button',{name:'• Pembelian & Penerimaan',exact:true});if(!await link.isVisible())await page.locator('.sidebar .nav-main').filter({hasText:'Gudang'}).click();await link.click()}
async function observed(page,button){const pending=page.waitForResponse(r=>r.url().endsWith('/rpc/erp_cp7_correct_supplier_payment_v1'));await button.click();return pending}
async function journey(ui,today,mobile){
 const f=fixture('prepare',{today}),user=await ui.login(mobile?'ADMIN':'OWNER',{label:'supplier-correction-'+mobile,mobile,timezoneId:'America/Los_Angeles'}),page=user.page,suffix=mobile?'MOBILE':'DESKTOP',requests=[]
 const state=()=>fixture('state',{fixture:f.fixture}),panel=()=>page.getByRole('region',{name:'Pembayaran supplier',exact:true}),row=id=>panel().locator(`[data-supplier-payment-id="${id}"]`),history=()=>page.getByRole('region',{name:'Koreksi pembayaran supplier tercatat',exact:true}),form=()=>page.getByRole('form',{name:'Edit pembayaran supplier',exact:true})
 page.on('request',r=>{if(/\/rpc\/erp_cp7_(?:correct_supplier_payment|reverse_supplier_payment)_v1$/.test(r.url()))requests.push({url:r.url(),body:r.postDataJSON()})})
 async function original(){await menu(page);const journal=page.getByRole('main',{name:'Jurnal keuangan dari buku',exact:true});await journal.getByLabel('Periode jurnal dari',{exact:true}).fill(f.payment.journal.economic_date);await journal.getByLabel('Periode jurnal sampai',{exact:true}).fill(today);await journal.getByLabel('Cari sumber jurnal',{exact:true}).fill(f.payment.journal.number);await journal.getByRole('button',{name:'Tampilkan jurnal',exact:true}).click();await journal.locator(`[data-journal-id="${f.payment.journal.id}"]`).click();await journal.getByRole('button',{name:'Buka transaksi asal',exact:true}).click();await ui.expect(row(f.payment.id)).toHaveAttribute('data-source-focus','true')}
 try{
  mkdirSync('cp6-proof/t3',{recursive:true});await original();await row(f.payment.id).getByRole('button',{name:`Edit pembayaran supplier ${f.payment.number}`,exact:true}).click();await ui.expect(form().getByLabel('Nominal koreksi pembayaran supplier',{exact:true})).toHaveValue('30.01')
  await form().getByLabel('Nominal koreksi pembayaran supplier',{exact:true}).fill('20.01');await form().getByLabel('Alasan koreksi pembayaran supplier',{exact:true}).fill('Jumlah pembayaran supplier diperbaiki sesudah pemeriksaan lapangan');await form().getByLabel('Koreksi pembayaran supplier sudah diperiksa',{exact:true}).check()
  let first
  if(!mobile){let intercepted;await page.route(endpoint,async route=>{try{const r=await route.fetch();intercepted={status:r.status()};if(r.status()===200){first=await r.json();await route.abort('failed')}else await route.fulfill({response:r})}catch(error){intercepted={error:String(error)};await route.abort('failed').catch(()=>{})}})
   await form().getByRole('button',{name:'Simpan koreksi pembayaran supplier',exact:true}).click();await ui.expect.poll(()=>intercepted!==undefined).toBe(true);assert.equal(intercepted.status,200,JSON.stringify(intercepted));await ui.expect(panel().getByRole('button',{name:'Periksa status pembatalan supplier',exact:true})).toBeEnabled();assert.equal(state().chain.length,1);const request=structuredClone(requests[0].body);await page.unroute(endpoint);await page.reload();await procurementMenu(page);const response=await observed(page,panel().getByRole('button',{name:'Periksa status pembatalan supplier',exact:true}));assert.equal(response.status(),200);assert.deepEqual(await response.json(),first);assert.deepEqual(requests[1].body,request)
  }else{const response=await observed(page,form().getByRole('button',{name:'Simpan koreksi pembayaran supplier',exact:true}));assert.equal(response.status(),200);first=await response.json()}
  await ui.expect(panel()).toContainText('Rp979,99');const after=state();assert.equal(after.original.amount,'30.01');assert.equal(after.original.status,'REVERSED');assert.equal(after.current.amount,'20.01');assert.equal(after.current.payment_date,f.payment.payment_date);assert.match(after.current.payment_date,/123456/);assert.equal(after.cash_balance,'-20.01');assert.equal(after.stock_HPP_unchanged,true);assert.equal(after.original_all_non_lifecycle_fields_unchanged,true)
  await row(first.payment_id).getByRole('button',{name:`Lihat perubahan pembayaran supplier ${after.current.number}`,exact:true}).click();await ui.expect(history().getByRole('region',{name:'Pembayaran supplier sebelum koreksi',exact:true})).toContainText(f.payment.number)
  await history().getByRole('button',{name:'Buka pembayaran supplier sebelum koreksi',exact:true}).click();await ui.expect(row(f.payment.id)).toHaveAttribute('data-source-focus','true');await row(f.payment.id).getByRole('button',{name:`Lihat perubahan pembayaran supplier ${f.payment.number}`,exact:true}).click();await history().getByRole('button',{name:'Buka pembayaran supplier pengganti',exact:true}).click();await ui.expect(row(first.payment_id)).toHaveAttribute('data-source-focus','true')
  await row(first.payment_id).getByRole('button',{name:`Lihat perubahan pembayaran supplier ${after.current.number}`,exact:true}).click();await history().getByRole('button',{name:'Pulihkan isi pembayaran supplier sebelum koreksi',exact:true}).click();await ui.expect(form().getByLabel('Nominal koreksi pembayaran supplier',{exact:true})).toHaveValue('30.01');await form().getByLabel('Alasan koreksi pembayaran supplier',{exact:true}).fill('Isi pembayaran asal dipulihkan sesudah pemeriksaan ulang');await form().getByLabel('Koreksi pembayaran supplier sudah diperiksa',{exact:true}).check()
  const response=await observed(page,form().getByRole('button',{name:'Simpan koreksi pembayaran supplier',exact:true}));assert.equal(response.status(),200);const second=await response.json();await ui.expect(panel()).toContainText('Rp969,99');const final=state();assert.equal(final.chain.length,2);assert.equal(final.current.id,second.payment_id);assert.equal(final.current.amount,'30.01');assert.equal(final.cash_balance,'-30.01');assert.equal(final.current.payment_date,f.payment.payment_date);assert.equal(final.stock_HPP_unchanged,true);assert.equal(final.original_all_non_lifecycle_fields_unchanged,true);assert.equal(requests.length,mobile?2:3);assert.equal(requests.filter(r=>r.url.endsWith('/erp_cp7_reverse_supplier_payment_v1')).length,0)
  await row(second.payment_id).getByRole('button',{name:`Lihat perubahan pembayaran supplier ${final.current.number}`,exact:true}).click();await ui.expect(history()).toContainText('Rp20,01');await ui.expect.poll(()=>page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);await page.screenshot({path:`cp6-proof/t3/CP7_SUPPLIER_PAYMENT_CORRECTION_${suffix}.png`,fullPage:true})
  return{status:'PASS',mobile,actual_Auth_original30_01_new20_01_restore30_01:true,one_atomic_backend_command_each:true,actual_lost_committed_reply_exact_UUID_recovery:!mobile,actual_exact_original_replacement_source_focus:true,immutable_two_link_history:true,Native_microseconds_complete_original_and_stock_HPP_preserved:true,screenshot:`CP7_SUPPLIER_PAYMENT_CORRECTION_${suffix}.png`}
 }catch(error){writeFileSync(`cp6-proof/t3/CP7_SUPPLIER_PAYMENT_CORRECTION_${suffix}_FAILURE.json`,JSON.stringify({error:String(error),stack:error.stack,text:await page.locator('main').innerText().catch(()=>''),state:state(),requests},null,2));await page.screenshot({path:`cp6-proof/t3/CP7_SUPPLIER_PAYMENT_CORRECTION_${suffix}_FAILURE.png`,fullPage:true}).catch(()=>{});throw error}
 finally{await page.unroute(endpoint).catch(()=>{});await user.context.close()}
}
export function cases(ui,today){return[['CP7_SUPPLIER_PAYMENT_CORRECTION_BROWSER_DESKTOP',()=>journey(ui,today,false)],['CP7_SUPPLIER_PAYMENT_CORRECTION_BROWSER_MOBILE',()=>journey(ui,today,true)]]}
