import assert from'node:assert/strict'
import{execFileSync}from'node:child_process'
import{mkdirSync,writeFileSync}from'node:fs'
const control=(file,op,p)=>JSON.parse(execFileSync('python',['../auditor/scripts/'+file,op],{input:JSON.stringify(p),cwd:'../writer',encoding:'utf8',maxBuffer:16*1024*1024}).trim())
const fixture=(op,p)=>control('cp7_f05_analysis_browser_fixture.py',op,p)
const ar=(op,p)=>control('cp7_f05_receivable_browser_fixture.py',op,p)
async function navigate(page){await page.locator('.sidebar .nav-main').filter({hasText:'Gudang'}).waitFor({state:'attached'});const menu=page.getByRole('button',{name:'Buka menu',exact:true});if(await menu.isVisible())await menu.click();const link=page.getByRole('button',{name:'• Ringkasan Barang Jadi',exact:true});if(!await link.isVisible())await page.locator('.sidebar .nav-main').filter({hasText:'Gudang'}).click();await link.click()}
async function journey(ui,today,mobile){
 fixture('prepare',{today});const sale=ar('prepare',{today}),user=await ui.login('OWNER',{label:'p16-ar-source-'+mobile,mobile,timezoneId:'America/Los_Angeles'}),page=user.page,suffix=mobile?'MOBILE':'DESKTOP',panel=page.getByRole('region',{name:'Analisis ERP bersama',exact:true}),history=page.getByRole('region',{name:'Data permintaan ERP',exact:true}),source=panel.getByRole('region',{name:'Sumber piutang pelanggan terkini',exact:true}),invoice=source.getByRole('article',{name:'Piutang '+sale.number,exact:true}),shots=[]
 let original=null
 const state=()=>ar('state',{actor:user.user.id})
 const shot=async name=>{await ui.expect.poll(()=>page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);await page.screenshot({path:'cp6-proof/t3/'+name,fullPage:true});shots.push(name)}
 const read=async()=>{const before=state(),response=page.waitForResponse(r=>r.url().endsWith('/rpc/erp_cp7_get_analysis_receivable_conditions_v1'));await source.getByRole('button',{name:'Periksa piutang pelanggan dari ERP',exact:true}).click();const r=await response;assert.equal(r.status(),200);const e=await r.json();assert.deepEqual(e.analysis.analysis,original.analysis);assert.deepEqual(e.analysis.financial_source,original.financial_source);assert.equal(e.source.page_complete,true);assert.equal(e.source.pages.flatMap(p=>p.page.rows).length,Number(e.source.total));assert.deepEqual(state(),before);const row=e.source.pages.flatMap(p=>p.page.rows).find(r=>r.id===sale.sale),condition=e.source.conditions.find(c=>c.source_id===sale.sale);assert.ok(row&&condition);await ui.expect(source.getByRole('navigation',{name:'Halaman piutang pelanggan',exact:true})).toBeVisible();for(let i=0;i<200&&!await invoice.isVisible();i++){const next=source.getByRole('button',{name:'Piutang berikutnya',exact:true});assert.ok(await next.isEnabled(),'Native target document missing from complete source');await next.click()}await ui.expect(invoice).toBeVisible();return{row,condition,e}}
 try{
  mkdirSync('cp6-proof/t3',{recursive:true});await navigate(page);const dirty=page.getByLabel('Cari barang jadi',{exact:true});await dirty.fill('P16 PIUTANG ISIAN GUDANG');await history.getByRole('button',{name:'Data permintaan & stok',exact:true}).click();await history.getByRole('button',{name:'Analisis, laporan & pengingat seluruh produk',exact:true}).click()
  const capture=page.waitForResponse(r=>r.url().endsWith('/rpc/erp_cp7_capture_analysis_v1'));await panel.getByRole('checkbox',{name:'Sertakan angka keuangan (menunggu buku besar)',exact:true}).check();await panel.getByRole('button',{name:'Ambil analisis ERP terbaru',exact:true}).click();const captured=await capture;assert.equal(captured.status(),200);original=await captured.json();const count=state().analysis_count
  await panel.getByRole('tab',{name:'Pengingat',exact:true}).click();await ui.expect(source).toContainText('Sumber piutang belum dimuat.');let current=await read();assert.equal(current.row.financial.gross_total,'500.00');assert.equal(current.row.financial.paid_total,'200.00');assert.equal(current.row.financial.open_balance,'300.00');assert.equal(current.row.due_date,null);assert.equal(current.condition.state,'MISSING_DUE_DATE');assert.equal(current.condition.business_resolved,false);await ui.expect(invoice).toContainText('Sisa tagihan Rp300');await shot(`P16_AR_OPEN_${suffix}.png`)
  await panel.getByRole('button',{name:'Muat perhatian tersimpan',exact:true}).click();const action=original.analysis.actions[0];assert.ok(action);const attention=panel.getByRole('article',{name:'Perhatian '+action.key,exact:true});await ui.expect(attention.getByRole('button',{name:'Selesai ditinjau',exact:true})).toBeEnabled();const done=page.waitForResponse(r=>r.url().endsWith('/rpc/erp_cp7_save_analysis_attention_v1'));await attention.getByRole('button',{name:'Selesai ditinjau',exact:true}).click();assert.equal((await done).status(),200);current=await read();assert.equal(current.row.financial.open_balance,'300.00');assert.equal(current.condition.business_resolved,false)
  const paid=ar('settle',{...sale,today});current=await read();assert.equal(current.row.financial.open_balance,'0.00');assert.equal(current.condition.state,'ZERO_BALANCE');assert.equal(current.condition.business_resolved,true);await ui.expect(invoice).toContainText('Tagihan tersisa nol');await shot(`P16_AR_SETTLED_${suffix}.png`)
  ar('inverse',paid);current=await read();assert.equal(current.row.financial.open_balance,'300.00');assert.equal(current.condition.state,'MISSING_DUE_DATE');assert.equal(current.condition.business_resolved,false);await ui.expect(invoice).toContainText('Sisa tagihan Rp300');await shot(`P16_AR_INVERSE_${suffix}.png`)
  await panel.getByRole('tab',{name:'Tanya AI',exact:true}).click();await panel.getByLabel('Pertanyaan analisis ERP',{exact:true}).fill('P16 piutang pertanyaan belum dikirim');await panel.getByRole('tab',{name:'Pengingat',exact:true}).click();fixture('deactivate',{actor:user.user.id});const denied=page.waitForResponse(r=>r.url().endsWith('/rpc/erp_cp7_get_analysis_receivable_conditions_v1')),parent=page.waitForResponse(r=>r.url().endsWith('/rpc/erp_cp7_get_fg_v1'));await source.getByRole('button',{name:'Periksa piutang pelanggan dari ERP',exact:true}).click();assert.equal((await denied).status(),403);assert.equal((await parent).status(),403);await ui.expect(panel.locator('.native-analysis-result')).toHaveCount(0);await ui.expect(page.locator('.cfg-totals')).toHaveCount(0);assert.equal(await dirty.inputValue(),'P16 PIUTANG ISIAN GUDANG');await shot(`P16_AR_REVOKED_${suffix}.png`)
  fixture('restore',{actor:user.user.id});await panel.getByText('Arsip analisis yang pernah dibuka',{exact:true}).click();await panel.getByRole('button',{name:'Buka arsip analisis 1',exact:true}).click();await panel.getByRole('tab',{name:'Tanya AI',exact:true}).click();assert.equal(await panel.getByLabel('Pertanyaan analisis ERP',{exact:true}).inputValue(),'P16 piutang pertanyaan belum dikirim');assert.equal(state().analysis_count,count)
  return{status:'PASS',actual_Native_invoice500_payment200_remaining300:true,review_done_never_settles_AR:true,actual_Native_final300_payment_resolves_and_inverse_reopens:true,missing_Native_due_date_never_invented:true,original_operational_and_financial_analysis_immutable:true,current_AR_source_complete_read_only_and_display_pagination:true,current403_retires_all_source_and_parent_FG_HPP:true,dirty_question_stock_search_preserved_under_foreign_device_timezone:true,no_reanalysis_local_fact_cache_or_external_delivery:true,screenshots:shots}
 }catch(e){writeFileSync(`cp6-proof/t3/P16_AR_${suffix}_FAILURE.json`,JSON.stringify({error:String(e),text:await panel.innerText().catch(()=>''),original},null,2));await page.screenshot({path:`cp6-proof/t3/P16_AR_${suffix}_FAILURE.png`,fullPage:true}).catch(()=>{});throw e}
 finally{fixture('restore',{actor:user.user.id});await user.context.close()}
}
export function cases(ui,today){return[['P16_BROWSER_DESKTOP_CURRENT_NATIVE_AR',()=>journey(ui,today,false)],['P16_BROWSER_MOBILE_CURRENT_NATIVE_AR',()=>journey(ui,today,true)]]}
