import assert from 'node:assert/strict'
import {execFileSync} from 'node:child_process'
import {mkdirSync,writeFileSync} from 'node:fs'
const fixture=(op,p)=>JSON.parse(execFileSync('python',['../auditor/scripts/cp7_fabric_recipe_browser_fixture.py',op],{input:JSON.stringify(p),cwd:'../writer',encoding:'utf8',maxBuffer:16*1024*1024}).trim())
async function navigate(page){await page.locator('.sidebar .nav-main').filter({hasText:'Gudang'}).waitFor({state:'attached'});const menu=page.getByRole('button',{name:'Buka menu',exact:true});if(await menu.isVisible())await menu.click();const link=page.getByRole('button',{name:'• Ringkasan Barang Jadi',exact:true});if(!await link.isVisible())await page.locator('.sidebar .nav-main').filter({hasText:'Gudang'}).click();await link.click()}
async function journey(ui,today,mobile){
 const user=await ui.login('OWNER',{label:'p08-fabric-'+mobile,mobile,timezoneId:mobile?'America/Los_Angeles':'Asia/Jakarta'}),page=user.page,suffix=mobile?'MOBILE':'DESKTOP',f=fixture('prepare',{today,actor:user.user.id})
 const panel=page.getByRole('region',{name:'Analisis ERP bersama',exact:true}),history=page.getByRole('region',{name:'Data permintaan ERP',exact:true}),form=panel.getByRole('region',{name:'Review pemakaian kain',exact:true}),materials=panel.getByRole('region',{name:'Kebutuhan bahan dari BOM ERP',exact:true}),shots=[]
 const state=()=>fixture('state',{actor:user.user.id});let lost=null,original=null,fresh=null,firstOriginal=null,rejection=null
 async function open(){await navigate(page);await history.getByRole('button',{name:'Data permintaan & stok',exact:true}).click();await history.getByRole('button',{name:'Analisis, laporan & pengingat seluruh produk',exact:true}).click()}
 async function shot(name){await ui.expect.poll(()=>page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);await page.screenshot({path:'cp6-proof/t3/'+name,fullPage:true});shots.push(name)}
 async function capture(){const pending=page.waitForResponse(r=>r.url().endsWith('/rpc/erp_cp7_capture_analysis_v1'));await panel.getByRole('button',{name:'Ambil analisis ERP terbaru',exact:true}).click();const response=await pending;assert.equal(response.status(),200);return response.json()}
 function row(e){const m=e.analysis.material_needs.find(m=>m.target_key===f.target&&(m.material_key??'').startsWith('FABRIC_'));assert.ok(m);for(const key of['installed_proven','unused_allocated_proven','additional_external']){assert.equal(m[key].state,'UNKNOWN');assert.equal(m[key].value,undefined)}return m}
 try{
  mkdirSync('cp6-proof/t3',{recursive:true});await open();original=await capture();assert.equal(original.analysis.recommendations.find(r=>r.target.key===f.target).q_conditional.value,'85');assert.equal(row(original).gross.state,'UNKNOWN');const before=state()
  await form.getByLabel('Produk dan ukuran resep kain',{exact:true}).selectOption(f.target);await form.getByLabel('Cari bahan kain ERP',{exact:true}).fill(f.material.sku)
  const loaded=page.waitForResponse(r=>r.url().endsWith('/rpc/erp_cp7_get_fabric_recipe_v1'));await form.getByRole('button',{name:'Baca bahan dan versi resep kain',exact:true}).click();const w=await loaded;assert.equal(w.status(),200);assert.deepEqual((await w.json()).analysis.analysis,original.analysis)
  assert.equal(await form.getByLabel('Pemakaian kain per PCS',{exact:true}).inputValue(),'');assert.equal(await form.getByLabel('Pola resep kain',{exact:true}).inputValue(),'');assert.equal(await form.getByLabel('Mulai berlaku resep kain WIB',{exact:true}).inputValue(),'')
  await form.getByLabel('Bahan kain yang direview',{exact:true}).selectOption(f.material.id);await form.getByLabel('Pemakaian kain per PCS',{exact:true}).fill(f.selected_rate);await form.getByLabel('Mulai berlaku resep kain WIB',{exact:true}).fill(f.rejected_from_wib);await form.getByLabel('Alasan review resep kain',{exact:true}).fill('P08 explicit Native fixture rate2; not factory recipe or installation');await form.getByLabel('Konfirmasi review resep kain',{exact:true}).check()
  const rejected=page.waitForResponse(r=>r.url().endsWith('/rpc/erp_cp7_save_fabric_recipe_v1'));await form.getByRole('button',{name:'Simpan review resep kain',exact:true}).click();const refused=await rejected;const body=await refused.json();assert.equal(body.code,'P0001');assert.equal(body.message,'CP7_FABRIC_BACKDATE_LIMIT');rejection={args:refused.request().postDataJSON(),status:refused.status(),body}
  await ui.expect(form.getByRole('button',{name:'Ulangi resep kain yang sama',exact:true})).toHaveCount(0);await ui.expect(panel.getByRole('button',{name:'Ambil analisis ERP terbaru',exact:true})).toBeEnabled();const noCommit=state();assert.equal(noCommit.recipes,before.recipes);assert.equal(noCommit.commands,before.commands);assert.deepEqual(noCommit.business,before.business)
  firstOriginal=original;original=await capture();assert.equal(row(original).gross.state,'UNKNOWN');await form.getByLabel('Produk dan ukuran resep kain',{exact:true}).selectOption(f.target);const refreshed=page.waitForResponse(r=>r.url().endsWith('/rpc/erp_cp7_get_fabric_recipe_v1'));await form.getByRole('button',{name:'Baca bahan dan versi resep kain',exact:true}).click();assert.equal((await refreshed).status(),200)
  await form.getByLabel('Bahan kain yang direview',{exact:true}).selectOption(f.material.id);await form.getByLabel('Pemakaian kain per PCS',{exact:true}).fill(f.selected_rate);await form.getByLabel('Mulai berlaku resep kain WIB',{exact:true}).fill(f.from_wib);await form.getByLabel('Konfirmasi review resep kain',{exact:true}).check();await shot(`P08_FABRIC_REVIEW_${suffix}.png`)
  await page.route('**/rest/v1/rpc/erp_cp7_save_fabric_recipe_v1',async route=>{if(!lost){const r=await route.fetch();assert.equal(r.status(),200);lost={args:route.request().postDataJSON(),outcome:await r.json()};await route.abort('failed')}else await route.continue()})
  await form.getByRole('button',{name:'Simpan review resep kain',exact:true}).click();await ui.expect(form.getByRole('button',{name:'Ulangi resep kain yang sama',exact:true})).toBeEnabled();assert.ok(lost);assert.equal(lost.args.p_payload.config.pattern_id,null)
  const committed=state();assert.equal(committed.recipes,before.recipes+1);assert.equal(committed.commands,before.commands+1);assert.deepEqual(committed.business,before.business);await ui.expect(panel.getByRole('button',{name:'Ambil analisis ERP terbaru',exact:true})).toBeDisabled();await shot(`P08_FABRIC_LOST_REPLY_${suffix}.png`)
  await page.reload();await open();const retry=page.waitForResponse(r=>r.url().endsWith('/rpc/erp_cp7_save_fabric_recipe_v1'));await form.getByRole('button',{name:'Ulangi resep kain yang sama',exact:true}).click();const replay=await retry;assert.equal(replay.status(),200);assert.deepEqual(replay.request().postDataJSON(),lost.args);assert.deepEqual(await replay.json(),lost.outcome);assert.equal(state().recipes,committed.recipes);assert.equal(state().commands,committed.commands)
  fresh=await capture();const m=row(fresh);assert.equal(m.gross.state,'ASSUMED');assert.equal(Number(m.gross.value),170);assert.equal(m.gross.unit,f.material.unit);assert.ok(m.gross.assumption_ids.includes(lost.outcome.recipe_id));assert.equal(fresh.analysis.recommendations.find(r=>r.target.key===f.target).feasible_new.state,'UNKNOWN');assert.notEqual(fresh.analysis.snapshot.source_hash,original.analysis.snapshot.source_hash)
  const targetLabel=fresh.product_labels.find(l=>l.target_key===f.target).sku;await panel.getByLabel('Cari hasil analisis bersama',{exact:true}).fill(targetLabel);await ui.expect(materials).toContainText('Kebutuhan kain');await ui.expect(materials).toContainText('170');await shot(`P08_FABRIC_GROSS170_${suffix}.png`)
  const count=state().analyses;await panel.getByRole('tab',{name:'Laporan',exact:true}).click();const report=await panel.getByLabel('Isi laporan ERP',{exact:true}).innerText();assert.ok(report.includes('CP7_FABRIC_RECIPE'));assert.ok(report.includes('170'));assert.ok(report.includes(lost.outcome.recipe_id))
  await panel.getByRole('tab',{name:'Tanya AI',exact:true}).click();const prompt=await panel.getByLabel('Pertanyaan dan sumber ERP',{exact:true}).innerText();assert.ok(prompt.includes('CP7_FABRIC_RECIPE'));assert.ok(prompt.includes(lost.outcome.recipe_id));assert.equal(state().analyses,count);assert.deepEqual(state().business,before.business)
  fixture('deactivate',{actor:user.user.id});const denied=page.waitForResponse(r=>r.url().endsWith('/rpc/erp_cp7_read_analysis_v1'));await panel.getByRole('button',{name:'Periksa sumber analisis',exact:true}).click();assert.equal((await denied).status(),403);await ui.expect(panel.locator('.native-analysis-result')).toHaveCount(0);await ui.expect(materials).toHaveCount(0);await shot(`P08_FABRIC_CURRENT403_${suffix}.png`)
  return{status:'PASS',actual_Auth_HTTP_Native_catalog_selected_rate2_gap85_gross170:true,no_auto_rate_pattern_or_effective_date:true,optional_pattern_left_null:true,definitive_Native_no_commit_rejection_releases_fence_before_fresh_review:true,actual_committed_lost_reply_reload_same_UUID_one_recipe_one_command:true,full_Native_business_boundary_unchanged_by_recipe_write:true,one_fresh_Original_shared_production_report_AI:true,installation_allocated_unused_external_and_feasible_remain_UNKNOWN:true,current403_retires_material_and_parent:true,screenshots:shots,complete_first_original:firstOriginal,complete_refused_request_and_response:rejection,complete_original:original,complete_fresh:fresh,complete_lost_request_and_outcome:lost}
 }catch(e){writeFileSync(`cp6-proof/t3/P08_FABRIC_${suffix}_FAILURE.json`,JSON.stringify({error:String(e),text:await panel.innerText().catch(()=>''),lost,original,fresh,firstOriginal,rejection},null,2));await page.screenshot({path:`cp6-proof/t3/P08_FABRIC_${suffix}_FAILURE.png`,fullPage:true}).catch(()=>{});throw e}
 finally{fixture('restore',{actor:user.user.id});await user.context.close()}
}
export function cases(ui,today){return[['P08_FABRIC_BROWSER_DESKTOP',()=>journey(ui,today,false)],['P08_FABRIC_BROWSER_MOBILE',()=>journey(ui,today,true)]]}
