import assert from'node:assert/strict'
import{execFileSync}from'node:child_process'
import{mkdirSync,writeFileSync}from'node:fs'
const control=(file,op,p)=>JSON.parse(execFileSync('python',['../auditor/scripts/'+file,op],{input:JSON.stringify(p),cwd:'../writer',encoding:'utf8',maxBuffer:16*1024*1024}).trim())
const fixture=(op,p)=>control('cp7_f05_analysis_browser_fixture.py',op,p)
const ar=(op,p)=>control('cp7_f05_receivable_browser_fixture.py',op,p)
async function navigate(page){await page.locator('.sidebar .nav-main').filter({hasText:'Gudang'}).waitFor({state:'attached'});const menu=page.getByRole('button',{name:'Buka menu',exact:true});if(await menu.isVisible())await menu.click();const link=page.getByRole('button',{name:'• Ringkasan Barang Jadi',exact:true});if(!await link.isVisible())await page.locator('.sidebar .nav-main').filter({hasText:'Gudang'}).click();await link.click()}
async function journey(ui,today,mobile){
 fixture('prepare',{today});const sale=ar('prepare',{today}),user=await ui.login('OWNER',{label:'p16-episodes-'+mobile,mobile,timezoneId:'America/Los_Angeles'}),page=user.page,suffix=mobile?'MOBILE':'DESKTOP',panel=page.getByRole('region',{name:'Analisis ERP bersama',exact:true}),history=page.getByRole('region',{name:'Data permintaan ERP',exact:true}),source=panel.getByRole('region',{name:'Riwayat masalah tagihan',exact:true}),article=source.getByRole('article',{name:'Catatan masalah '+sale.number,exact:true}),shots=[]
 let original=null,lastSourceResponse=null
 const state=()=>ar('state',{actor:user.user.id}),shot=async name=>{await ui.expect.poll(()=>page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);await page.screenshot({path:'cp6-proof/t3/'+name,fullPage:true});shots.push(name)}
 const observe=async()=>{const before=state(),reply=page.waitForResponse(r=>r.url().endsWith('/rpc/erp_cp7_evaluate_obligation_episodes_v1'));await source.getByRole('button',{name:'Catat pemeriksaan piutang ERP',exact:true}).click();const r=await reply;assert.equal(r.status(),200);const e=await r.json();lastSourceResponse=e;assert.deepEqual(e.analysis.analysis,original.analysis);assert.deepEqual(e.analysis.financial_source,original.financial_source);assert.equal(e.read_kind,'SAVED_OBSERVATION');assert.equal(e.result.source_status,'COMPLETE');assert.equal(e.result.rows.filter(x=>x.condition_state!=='SOURCE_UNKNOWN').length,Number(e.result.source_total));assert.deepEqual(state(),before);const row=e.result.rows.find(x=>x.source_id===sale.sale);assert.ok(row);await ui.expect(source.getByRole('navigation',{name:'Halaman catatan pemeriksaan tagihan',exact:true})).toBeVisible();for(let i=0;i<400&&!await article.isVisible();i++){const next=source.getByRole('button',{name:'Catatan berikutnya',exact:true});assert.ok(await next.isEnabled(),'Target Native episode missing from complete observation');await next.click()}await ui.expect(article).toBeVisible();return row}
 try{
  mkdirSync('cp6-proof/t3',{recursive:true});await navigate(page);const dirty=page.getByLabel('Cari barang jadi',{exact:true});await dirty.fill('P16 RIWAYAT ISIAN GUDANG');await history.getByRole('button',{name:'Data permintaan & stok',exact:true}).click();await history.getByRole('button',{name:'Analisis, laporan & pengingat seluruh produk',exact:true}).click()
  const capture=page.waitForResponse(r=>r.url().endsWith('/rpc/erp_cp7_capture_analysis_v1'));await panel.getByRole('checkbox',{name:'Sertakan angka keuangan (menunggu buku besar)',exact:true}).check();await panel.getByRole('button',{name:'Ambil analisis ERP terbaru',exact:true}).click();const captured=await capture;assert.equal(captured.status(),200);original=await captured.json();const count=state().analysis_count;await panel.getByRole('tab',{name:'Pengingat',exact:true}).click();await ui.expect(source.getByRole('region',{name:'Catatan pemeriksaan tagihan',exact:true})).toHaveCount(0)
  let row=await observe();const first=row.episode;assert.equal(row.transition,'OPENED');assert.equal(first.state,'ACTIVE');assert.equal(row.business_resolved,false);await ui.expect(article).toContainText('Masalah masih terbuka');await shot(`P16_EP_OPEN_${suffix}.png`)
  row=await observe();assert.equal(row.episode.id,first.id);assert.equal(row.episode.number,'1');assert.equal(row.episode.first_observed_at,first.first_observed_at)
  const paid=ar('settle',{...sale,today});row=await observe();assert.equal(row.transition,'RESOLVED');assert.equal(row.episode.id,first.id);assert.equal(row.business_resolved,true);await ui.expect(article).toContainText('Selesai menurut pemeriksaan ERP');await shot(`P16_EP_RESOLVED_${suffix}.png`)
  ar('inverse',paid);row=await observe();assert.equal(row.transition,'REOPENED_NEW_EPISODE');assert.notEqual(row.episode.id,first.id);assert.equal(row.episode.number,'2');assert.equal(row.episode.previous_episode_id,first.id);assert.equal(row.business_resolved,false);await ui.expect(article).toContainText('Masalah muncul kembali');await shot(`P16_EP_REOPENED_${suffix}.png`)
  await panel.getByRole('tab',{name:'Tanya AI',exact:true}).click();await panel.getByLabel('Pertanyaan analisis ERP',{exact:true}).fill('P16 riwayat pertanyaan belum dikirim');await panel.getByRole('tab',{name:'Pengingat',exact:true}).click();fixture('deactivate',{actor:user.user.id});const denied=page.waitForResponse(r=>r.url().endsWith('/rpc/erp_cp7_evaluate_obligation_episodes_v1')),parent=page.waitForResponse(r=>r.url().endsWith('/rpc/erp_cp7_get_fg_v1'));await source.getByRole('button',{name:'Catat pemeriksaan piutang ERP',exact:true}).click();assert.equal((await denied).status(),403);assert.equal((await parent).status(),403);await ui.expect(panel.locator('.native-analysis-result')).toHaveCount(0);await ui.expect(page.locator('.cfg-totals')).toHaveCount(0);assert.equal(await dirty.inputValue(),'P16 RIWAYAT ISIAN GUDANG');await ui.expect(panel.getByRole('button',{name:'Periksa hasil pemeriksaan tagihan',exact:true})).toBeVisible();await shot(`P16_EP_REVOKED_${suffix}.png`)
  fixture('restore',{actor:user.user.id});const lookup=page.waitForResponse(r=>r.url().endsWith('/rpc/erp_cp7_get_obligation_episode_request_v1'));await panel.getByRole('button',{name:'Periksa hasil pemeriksaan tagihan',exact:true}).click();const sealed=await lookup;assert.equal(sealed.status(),200);assert.equal((await sealed.json()).result.status,'NOT_COMMITTED');await ui.expect(panel.getByText('Server memastikan pemeriksaan ini belum tersimpan. Permintaan lama sudah ditutup; pemeriksaan baru dapat dimulai.',{exact:true})).toBeVisible();await panel.getByRole('tab',{name:'Tanya AI',exact:true}).click();assert.equal(await panel.getByLabel('Pertanyaan analisis ERP',{exact:true}).inputValue(),'P16 riwayat pertanyaan belum dikirim');assert.equal(state().analysis_count,count)
  return{status:'PASS',actual_Native_AR500_paid200_remaining300_stable_business_episode:true,repeat_evaluation_preserves_identity_and_first_seen:true,actual300_payment_resolves_and_inverse_new_linked_episode:true,Original_operational_and_financial_body_immutable:true,explicit_metadata_write_never_writes_ERP_business_or_recaptures:true,current403_retires_source_parent_FG_HPP_dirty_fields_and_stable_intent_preserved:true,current_authority_absent_resolution_seals_failed_intent:true,no_local_money_cache_or_external_delivery:true,screenshots:shots}
 }catch(e){writeFileSync(`cp6-proof/t3/P16_EP_${suffix}_FAILURE.json`,JSON.stringify({error:String(e),text:await panel.innerText().catch(()=>''),original,lastSourceResponse},null,2));await page.screenshot({path:`cp6-proof/t3/P16_EP_${suffix}_FAILURE.png`,fullPage:true}).catch(()=>{});throw e}
 finally{fixture('restore',{actor:user.user.id});await user.context.close()}
}
export function cases(ui,today){return[['P16_BROWSER_DESKTOP_NATIVE_OBLIGATION_EPISODES',()=>journey(ui,today,false)],['P16_BROWSER_MOBILE_NATIVE_OBLIGATION_EPISODES',()=>journey(ui,today,true)]]}
