import assert from 'node:assert/strict'
import {execFileSync} from 'node:child_process'
import {mkdirSync,writeFileSync} from 'node:fs'
const fixture=(op,p)=>JSON.parse(execFileSync('python',['../auditor/scripts/cp7_sales_chain_browser_fixture.py',op],{input:JSON.stringify(p),cwd:'../writer',encoding:'utf8',maxBuffer:16*1024*1024}).trim())
const endpoint='**/rest/v1/rpc/erp_cp7_reverse_sales_chain_v1'
async function menu(page){const open=page.getByRole('button',{name:'Buka menu',exact:true});if(await open.isVisible())await open.click();const link=page.getByRole('button',{name:'• Penjualan & Invoice',exact:true});if(!await link.isVisible())await page.locator('.sidebar .nav-main').filter({hasText:'Penjualan'}).click();await link.click()}
async function observed(page,button){const pending=page.waitForResponse(r=>r.url().endsWith('/rpc/erp_cp7_reverse_sales_chain_v1')).then(response=>({response}),error=>({error}));await button.click();const r=await pending;if(r.error)throw r.error;return r.response}
async function journey(ui,today,mobile){
 const f=fixture('prepare',{today}),user=await ui.login(mobile?'ADMIN':'OWNER',{label:'sales-chain-'+mobile,mobile,timezoneId:'America/Los_Angeles'}),page=user.page,suffix=mobile?'MOBILE':'DESKTOP',requests=[]
 const state=()=>fixture('state',{fixture:f.fixture}),panel=()=>page.getByRole('region',{name:`Pembatalan atomik rantai ${f.invoice.number}`,exact:true}),detail=()=>page.getByRole('complementary',{name:'Rincian invoice',exact:true})
 page.on('request',r=>{if(/\/rpc\/erp_cp7_(?:reverse_sales_chain|save_sale)_v1$/.test(r.url()))requests.push({url:r.url(),body:r.postDataJSON()})})
 try{
  mkdirSync('cp6-proof/t3',{recursive:true});const before=state();await menu(page);await page.getByLabel('Cari invoice',{exact:true}).fill(f.invoice.number);await page.getByRole('button',{name:'Cari invoice',exact:true}).click();await page.locator('[aria-label="Daftar invoice"] .cproc-receipt').filter({hasText:f.invoice.number}).click()
  await detail().getByRole('button',{name:'Periksa pembatalan rantai',exact:true}).click();await ui.expect(panel()).toBeVisible();await ui.expect(panel().getByRole('list',{name:'Urutan pembatalan lengkap',exact:true}).locator('li')).toHaveCount(3)
  await ui.expect(panel()).toContainText(f.workspace.source.payments[0].number);await ui.expect(panel()).toContainText(f.workspace.source.returns[0].number);assert.equal(requests.length,0);assert.deepEqual(state(),before)
  await panel().getByLabel('Alasan pembatalan rantai',{exact:true}).fill('Seluruh pembayaran retur invoice dan barang sudah diperiksa');await panel().getByLabel('Seluruh rantai sudah diperiksa',{exact:true}).check();let first
  if(!mobile){let intercepted;await page.route(endpoint,async route=>{try{const r=await route.fetch();intercepted={status:r.status()};if(r.status()===200){first=await r.json();await route.abort('failed')}else await route.fulfill({response:r})}catch(error){intercepted={error:String(error)};await route.abort('failed').catch(()=>{})}})
   await panel().getByRole('button',{name:'Batalkan rantai sekaligus',exact:true}).click();await ui.expect.poll(()=>intercepted!==undefined).toBe(true);assert.equal(intercepted.status,200,JSON.stringify(intercepted));assert.equal(state().history.length,1);await ui.expect(page.getByRole('button',{name:'Reconcile transaksi',exact:true})).toBeVisible();const request=structuredClone(requests[0].body)
   await page.unroute(endpoint);await page.reload();await menu(page);const response=await observed(page,page.getByRole('button',{name:'Reconcile transaksi',exact:true}));assert.equal(response.status(),200);assert.deepEqual(await response.json(),first);assert.deepEqual(requests[1].body,request)
  }else{const response=await observed(page,panel().getByRole('button',{name:'Batalkan rantai sekaligus',exact:true}));assert.equal(response.status(),200);first=await response.json()}
  await ui.expect(detail()).toContainText('Penjualan dibatalkan');const after=state();assert.equal(after.invoice.status,'REVERSED');assert.equal(after.invoice.financial.open_balance,null);assert.equal(after.available,10);assert.deepEqual(after.accounts,f.fixture.before_sale);assert.equal(after.original_facts_unchanged,true);assert.equal(after.history.length,1);assert.deepEqual(after.history[0].steps,first.steps)
  assert.equal(after.payments.length,1);assert.equal(after.returns.length,1);assert.equal(after.payments[0].status,'REVERSED');assert.equal(after.returns[0].status,'REVERSED');assert.equal(requests.length,mobile?1:2);assert.equal(requests.filter(r=>r.url.endsWith('/erp_cp7_save_sale_v1')).length,0)
  assert.deepEqual(requests[0].body.p_payload.payment_ids,f.workspace.source.payments.map(p=>p.id));assert.deepEqual(requests[0].body.p_payload.return_ids,f.workspace.source.returns.map(r=>r.id));assert.equal(requests[0].body.p_expected,f.invoice.row_version)
  await ui.expect.poll(()=>page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);await page.screenshot({path:`cp6-proof/t3/CP7_SALES_CHAIN_${suffix}.png`,fullPage:true})
  return{status:'PASS',mobile,actual_Auth_one_Native_payment_return_invoice_atomic_chain:true,one_outer_backend_write:true,actual_lost_committed_reply_exact_UUID_recovery:!mobile,original366_day_microsecond_inputs_unchanged:true,Native_stock10_and_GL_neutral:true,immutable_reviewed_source_and_all_steps:true,screenshot:`CP7_SALES_CHAIN_${suffix}.png`}
 }catch(error){writeFileSync(`cp6-proof/t3/CP7_SALES_CHAIN_${suffix}_FAILURE.json`,JSON.stringify({error:String(error),stack:error.stack,text:await page.locator('main').innerText().catch(()=>''),state:state(),requests},null,2));await page.screenshot({path:`cp6-proof/t3/CP7_SALES_CHAIN_${suffix}_FAILURE.png`,fullPage:true}).catch(()=>{});throw error}
 finally{await page.unroute(endpoint).catch(()=>{});await user.context.close()}
}
export function cases(ui,today){return[['CP7_SALES_CHAIN_BROWSER_DESKTOP',()=>journey(ui,today,false)],['CP7_SALES_CHAIN_BROWSER_MOBILE',()=>journey(ui,today,true)]]}
