import assert from 'node:assert/strict'
import {execFileSync} from 'node:child_process'
import {mkdirSync,writeFileSync} from 'node:fs'
import {cases as previous,openCutting} from './cp7_cutting_yield_browser.mjs'
const fixture=(op,p)=>JSON.parse(execFileSync('python',['../auditor/scripts/cp7_f04_history_browser_fixture.py',op],{input:JSON.stringify(p),cwd:'../writer',encoding:'utf8',maxBuffer:16*1024*1024}).trim())
async function capture(ui,page,name){mkdirSync('cp6-proof/t3',{recursive:true});await ui.expect.poll(()=>page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);await page.evaluate(()=>scrollTo(0,0));await page.screenshot({path:'cp6-proof/t3/'+name,fullPage:true})}
async function journey(ui,today,mobile){
 const user=await ui.login('OWNER',{label:'native-cut-input-'+mobile,mobile,timezoneId:mobile?'America/Los_Angeles':'Asia/Jakarta'}),page=user.page,f=fixture('cut_prepare',{today}),suffix=mobile?'MOBILE':'DESKTOP',screenshots=[]
 const panel=page.getByRole('region',{name:'Rencana bahan sebelum potong',exact:true}),state=()=>fixture('cut_input_state',{fixture:f,actor:user.user.id});let lost=null
 try{
  await openCutting(ui,page,mobile)
  await page.getByLabel('Cari draft Potongan',{exact:true}).fill(f.group_number);const searched=page.waitForResponse(r=>r.url().endsWith('/rpc/erp_get_cutting_workspace_v2')&&r.request().postDataJSON().p_draft_query===f.group_number);await page.getByRole('button',{name:'Cari draft',exact:true}).click();assert.equal((await searched).status(),200)
  await page.locator('.ccut-drafts button').filter({hasText:f.group_number}).click();const notes=page.getByLabel('Catatan',{exact:true});await notes.fill('CATATAN OPERATOR TETAP ADA');const before=state();assert.equal(Number(before.raw_qty),100)
  await panel.getByRole('button',{name:'Muat rencana potong',exact:true}).click();await ui.expect(panel.getByLabel('Nama susunan pola',{exact:true})).toBeEnabled();assert.equal(await notes.inputValue(),'CATATAN OPERATOR TETAP ADA');assert.equal(state().native_hash,before.native_hash)
  await panel.getByLabel('Nama susunan pola',{exact:true}).fill('Susunan terperiksa');for(const [name,value]of [['Merek kain','MEREK TERPERIKSA'],['Pabrik kain','PABRIK TERPERIKSA'],['Jenis kain','JENIS TERPERIKSA'],['Revisi spesifikasi','1']])await panel.getByLabel(new RegExp('^'+name+' ·')).fill(value)
  const mix=panel.getByLabel(/^Jumlah gambar ukuran /);assert.equal(await mix.count(),1);await mix.fill('3');const width=panel.getByLabel(/^Lebar tercatat \(cm\) ·/);assert.equal(await width.inputValue(),'');if(mobile)await width.fill('175.250')
  await panel.getByLabel('Saya sudah memeriksa bahan dan susunan ukuran.',{exact:true}).check()
  await page.route('**/rest/v1/rpc/erp_cp7_record_cutting_inputs_v1',async route=>{if(!lost){const reply=await route.fetch();assert.equal(reply.status(),200);lost={envelope:route.request().postDataJSON(),body:await reply.json()};await route.abort('failed')}else await route.continue()})
  await panel.getByRole('button',{name:'Catat rencana potong',exact:true}).click();await ui.expect(panel.getByRole('button',{name:'Pulihkan rencana potong',exact:true})).toBeEnabled();const committed=state();assert.equal(committed.own_plans,1);assert.equal(committed.own_requests,1);assert.equal(committed.native_hash,before.native_hash);assert.equal(await notes.inputValue(),'CATATAN OPERATOR TETAP ADA');assert.equal(lost.body.result.record.values.rolls[0].width_cm,mobile?'175.250':null);assert.equal(lost.body.current.preknown_before_physical,false)
  await capture(ui,page,`CUT_INPUT_UNCERTAIN_${suffix}.png`);screenshots.push(`CUT_INPUT_UNCERTAIN_${suffix}.png`)
  const posted=page.waitForResponse(r=>r.url().endsWith('/rpc/erp_save_cutting_group_before_sewing_v2'));await page.getByRole('button',{name:'Post ke WIP Potongan',exact:true}).click();assert.equal((await posted).status(),200);await ui.expect(page.locator('.ccut-message.success')).toContainText('terposting. Form lama ditutup');const after=state();assert.equal(Number(after.raw_qty),40);assert.equal(Number(after.raw_value),400);assert.equal(Number(after.cut_pcs),60)
  await page.reload();await openCutting(ui,page,mobile);await ui.expect(panel.getByRole('button',{name:'Pulihkan rencana potong',exact:true})).toBeEnabled();const recovery=page.waitForResponse(r=>r.url().endsWith('/rpc/erp_cp7_get_cutting_input_request_v1'));await panel.getByRole('button',{name:'Pulihkan rencana potong',exact:true}).click();const recovered=await recovery;assert.equal(recovered.status(),200);assert.deepEqual(recovered.request().postDataJSON(),lost.envelope);const body=await recovered.json();assert.deepEqual(body.result,lost.body.result);assert.equal(body.current.group.posted,true);assert.equal(body.current.preknown_before_physical,false);assert.equal(body.current.model_qualified,false)
  await ui.expect(panel.locator('[data-cutting-input-record]')).toContainText('MEREK TERPERIKSA');await ui.expect(panel).toContainText('setelah waktu potong');await ui.expect(panel).toContainText(mobile?'lebar 175.250 cm':'lebar belum dicatat');assert.equal(state().own_plans,1);assert.equal(state().own_requests,1);assert.equal(state().native_hash,after.native_hash)
  await capture(ui,page,`CUT_INPUT_RECOVERED_${suffix}.png`);screenshots.push(`CUT_INPUT_RECOVERED_${suffix}.png`)
  fixture('deactivate',{actor:user.user.id});const denied=page.waitForResponse(r=>r.url().endsWith('/rpc/erp_cp7_get_cutting_input_workspace_v1'));await panel.getByRole('button',{name:'Periksa sumber rencana',exact:true}).click();assert.equal((await denied).status(),403);await ui.expect(panel.locator('[data-cutting-input-record]')).toHaveCount(0);assert.equal(state().native_hash,after.native_hash)
  await capture(ui,page,`CUT_INPUT_CURRENT_AUTH_${suffix}.png`);screenshots.push(`CUT_INPUT_CURRENT_AUTH_${suffix}.png`)
  return{status:'PASS',actual_Native_draft_private_metadata_then_POST60_raw100_to40_value1000_to400:true,Native_dirty_form_and_every_economic_fact_unchanged_by_metadata:true,exact_UUID_payload_and_immutable_result_recovery_after_reload_and_posted_draft_removal:true,real_knowledge_clock_after_old_cut_date_not_imputed_as_preknown:true,Native_pattern_roll_size_unit_and_explicit_operator_family_bound:true,optional_width_null_or_exact_175_250_no_default:true,current403_retires_all_input_source_facts:true,screenshots}
 }catch(e){writeFileSync(`cp6-proof/t3/CUT_INPUT_${suffix}_FAILURE.json`,JSON.stringify({error:String(e),text:await panel.innerText().catch(()=>''),lost},null,2));await page.screenshot({path:`cp6-proof/t3/CUT_INPUT_${suffix}_FAILURE.png`,fullPage:true}).catch(()=>{});throw e}
 finally{fixture('restore',{actor:user.user.id});await user.context.close()}
}
export function cases(ui,today){return previous(ui,today).concat([['CUT_INPUT_BROWSER_DESKTOP',()=>journey(ui,today,false)],['CUT_INPUT_BROWSER_MOBILE',()=>journey(ui,today,true)]])}
