alter function cp7_wip.fields(jsonb,text[]) owner to cp7_capture;
alter function cp7_wip.key(jsonb) owner to cp7_capture;
alter function cp7_wip.pcs(jsonb) owner to cp7_capture;
alter function cp7_wip.refs(jsonb) owner to cp7_capture;
alter function cp7_wip.reconcile(jsonb) owner to cp7_capture;
alter function cp7_wip.match_target(jsonb,jsonb) owner to cp7_capture;
alter function cp7_wip.check_allocations(jsonb,jsonb) owner to cp7_capture;
alter function cp7_wip.project_yield(jsonb,jsonb) owner to cp7_capture;
alter function cp7_wip.remaining_eta(timestamptz,timestamptz,jsonb) owner to cp7_capture;
revoke all on all functions in schema cp7_wip from public,anon,authenticated,service_role;
alter function cp7_wip.capture_cutting_sources(uuid[]) owner to cp7_capture;
alter function cp7_wip.capture_cutting_sources(uuid[],timestamptz) owner to cp7_capture;
alter function cp7_wip.transition(jsonb,text,text,text,text,numeric,jsonb) owner to cp7_capture;
alter function cp7_wip.ref(text,text,text) owner to cp7_capture;
alter function cp7_wip.redispatch_valid(jsonb) owner to cp7_capture;
alter function cp7_wip.normalize_cutting(jsonb) owner to cp7_capture;
alter function cp7_wip.settle_bs(jsonb,jsonb,jsonb,timestamptz) owner to cp7_capture;
alter function cp7_wip.serve(uuid) owner to cp7_capture;
alter function cp7_wip.capture(uuid[],uuid) owner to cp7_capture;
alter function cp7_wip.capture_other_sources(uuid[],uuid[],timestamptz) owner to cp7_capture;
alter function cp7_wip.normalize_other(jsonb) owner to cp7_capture;
alter function cp7_wip.production_scope(jsonb) owner to cp7_capture;
alter function cp7_wip.capture_production_sources(jsonb) owner to cp7_capture;
alter function cp7_wip.normalize_production(jsonb) owner to cp7_capture;
alter function cp7_wip.capture_production(jsonb,uuid) owner to cp7_capture;
alter function cp7_wip.serve_production(uuid) owner to cp7_capture;
alter function public.erp_cp7_capture_production_wip_v1(jsonb,uuid) owner to cp7_capture;
alter function public.erp_cp7_read_production_wip_v1(uuid) owner to cp7_capture;
alter function public.erp_cp7_capture_cutting_wip_v1(uuid[],uuid) owner to cp7_capture;
alter function public.erp_cp7_read_cutting_wip_v1(uuid) owner to cp7_capture;
revoke all on all functions in schema cp7_wip from public,anon,authenticated,service_role;
revoke all on function public.erp_cp7_capture_cutting_wip_v1(uuid[],uuid),public.erp_cp7_read_cutting_wip_v1(uuid) from public,anon,service_role;
grant execute on function public.erp_cp7_capture_cutting_wip_v1(uuid[],uuid),public.erp_cp7_read_cutting_wip_v1(uuid) to authenticated;
revoke all on function public.erp_cp7_capture_production_wip_v1(jsonb,uuid),public.erp_cp7_read_production_wip_v1(uuid) from public,anon,service_role;
grant execute on function public.erp_cp7_capture_production_wip_v1(jsonb,uuid),public.erp_cp7_read_production_wip_v1(uuid) to authenticated;
