-- Pre-use N to exact M. Run through reviewed maintenance admission controller.
begin;
set local lock_timeout='10s';set local statement_timeout='240s';set local timezone='UTC';
lock table erp.schema_migrations,supabase_migrations.schema_migrations in share row exclusive mode;
lock table erp.app_users in access exclusive mode;
lock table erp.idempotency_requests in share row exclusive mode;
select pg_advisory_xact_lock(hashtextextended('FG_HPP_SALES_V2620C',0));
lock table erp.products,erp.audit_logs,erp.journal_entries,erp.journal_lines,erp.account_daily_balances,erp.sales_headers,erp.sales_items,erp.sale_stock_allocations,erp.sales_returns,erp.sales_return_items,erp.sales_payments,erp.fg_lots,erp.fg_stock_movements,erp.fg_inventory_balances,erp.hpp_versions,erp.product_conversions,erp.product_conversion_allocations,erp.laundry_deliveries,erp.laundry_delivery_lines,erp.laundry_receipts,erp.laundry_failed_wash_attempts,erp.wip_stage_events,erp.cp6_v2620g_rollback_capsule,erp.cp6_v2620h_rollback_capsule,erp.cp6_v2620i_rollback_capsule,erp.sales_payment_posting_facts,erp.sales_payment_reversal_facts,erp.cp6_v2620j_rollback_capsule,erp.cp6_v2620k_rollback_capsule,erp.accounting_period_control,erp.accounting_account_mappings,erp.cash_accounts,erp.chart_accounts,erp.laundry_claims,erp.laundry_vendors,erp.cp6_v2620l_rollback_capsule,erp.opening_balance_headers,erp.opening_balance_items,erp.opening_subledger_balances,erp.opening_subledger_settlements,erp.opening_financial_corrections,erp.supplier_payments,erp.material_purchase_headers,erp.material_purchase_items,erp.material_supplier_invoices,erp.material_supplier_invoice_lines,erp.material_supplier_returns,erp.material_supplier_return_items,erp.material_purchase_cost_corrections,erp.material_purchase_cost_correction_items,erp.material_stock_movements,erp.material_rolls,erp.cost_recalc_queue,erp.cost_adjustments,erp.suppliers,erp.materials,erp.cp6_v2620m_rollback_capsule,erp.material_cost_history,erp.material_cost_revaluation_state,erp.material_cost_revaluation_events,erp.material_cost_checkpoints in share row exclusive mode;
lock table erp.supplier_cent_posting_facts,erp.cp6_v2620n_rollback_capsule in access exclusive mode;
do $restore_guard$
declare r record;c record;v_table text;v_hash text;v_expected jsonb;
begin
 if (select count(*) from supabase_migrations.schema_migrations where name='erp_v2_6_20n_cp6_supplier_cent_lifecycle')<>1 or not exists(select 1 from supabase_migrations.schema_migrations where version='20260911124328' and name='erp_v2_6_20n_cp6_supplier_cent_lifecycle' and encode(extensions.digest(convert_to(array_to_string(statements,E'\n'),'UTF8'),'sha256'),'hex') in('4b351432f4ddd8781f42c3c194b78fc575257e3a5fd60753e310c9928590b21e','3cccb407130c862d66bfb7ee74eb00a3be98121c1892cc646901a9ca2d62d273')) or exists(select 1 from supabase_migrations.schema_migrations where version>'20260911124328') then raise exception 'N_ROLLBACK_PLATFORM_IDENTITY_OR_SUCCESSOR';end if;
 if not exists(select 1 from erp.schema_migrations where version='v2.6.20m') or not exists(select 1 from erp.schema_migrations where version='v2.6.20n') or (select count(*) from erp.cp6_v2620n_rollback_capsule)<>7 then raise exception 'N_ROLLBACK_MARKER_CAPSULE';end if;
 for r in select * from(values
('erp.post_material_purchase_cost_correction(uuid)','9542acde669945e633d5929cb5b441a2119b8f3bf9a69919ae46725d598e8ba9','5839dee0ab9db69ebabf5f08894b5c6603c851c1d55aa9eff30a12dd0331dff9',array['authenticated=X/postgres','postgres=X/postgres']::text[]),
('erp.post_material_supplier_invoice(uuid)','65ae76bce50952c2ced64ad7ec25c1039a1e3086048e5ea39eae71ec4c8b7d69','da4ce12c6f41625933511e6fd59246c2410b80ce02ddf865c489803070f7b8b0',array['postgres=X/postgres','service_role=X/postgres']::text[]),
('erp.post_material_supplier_return(uuid)','f5f6603b258eeda0b34a10f06a301b94c488525dfddfe0863e5ded8f56244ad1','b4ac34b5df0e35f0cf1afe85d4a92e0b369922f91d0ce9eb4e2589a71367d607',array['postgres=X/postgres','service_role=X/postgres']::text[]),
('erp.reverse_material_purchase_cost_correction(uuid,text)','dc17e41110f001f6f16d18d065745dc8e85bb9e58ef28e162522976da45c4a6f','9913ee82901495aa850712c29d21ab8a8b96a5d71c29fca20fb0844b1af1dddd',array['authenticated=X/postgres','postgres=X/postgres']::text[]),
('erp.reverse_material_supplier_invoice(uuid,text)','76ee31ad50c747b5a9f5730a5a3e81ba79c1685f57f716ac211197f11aa7080e','b4b10a9021e4360a25327656217fac0ed8a171748c215af2291ed00539684cb2',array['postgres=X/postgres','service_role=X/postgres']::text[]),
('erp.reverse_material_supplier_return(uuid,text)','ac2504b1f04d5eaf8bf63b13ce945adf17fda0104ac6e4f6c44ac831c255706b','5659d9755c81ae4134a494d1ebd0aaaec29ed82b75a5a32bdfd6d048e6ebaca3',array['postgres=X/postgres','service_role=X/postgres']::text[]),
('erp.run_v267_financial_truth_checks()','efde954275e89f01793f405e2b000c6c599bae0be731869802f288994dd154fa','f50decac0d38f9ddc2cfc5a28af53607fb8c1cf38cde5a65f13b38ec748a6fda',array['authenticated=X/postgres','postgres=X/postgres','service_role=X/postgres']::text[])
 ) expected(identity,predecessor_sha256,installed_sha256,acl) loop
 select * into c from erp.cp6_v2620n_rollback_capsule where object_regidentity=r.identity;
 if c.object_regidentity is null or c.definition_sha256 is distinct from r.predecessor_sha256 or encode(extensions.digest(convert_to(c.object_definition,'UTF8'),'sha256'),'hex') is distinct from r.predecessor_sha256 or c.installed_definition_sha256 is distinct from r.installed_sha256 or c.owner_snapshot is distinct from 'postgres' or c.acl_snapshot is distinct from r.acl or encode(extensions.digest(convert_to(pg_get_functiondef(to_regprocedure(r.identity)),'UTF8'),'sha256'),'hex') is distinct from r.installed_sha256 or (select pg_get_userbyid(proowner) from pg_proc where oid=to_regprocedure(r.identity)) is distinct from 'postgres' or (select array(select a::text from unnest(proacl) a order by a::text) from pg_proc where oid=to_regprocedure(r.identity)) is distinct from r.acl then raise exception 'N_TRUSTED_PREDECESSOR_PIN_MISMATCH';end if;
 end loop;
 for r in select * from(values
('erp._cp6_apply_supplier_cent_event(text,uuid,date,text,jsonb,boolean)','390fc3fae9bf59cf35fbc699f988521b3bde572e266937fdce99e0854c1756a3',array['postgres=X/postgres']::text[]),
('erp._cp6_supplier_cent_ledger(uuid[])','43572de7870afb9050d5af24a05ff6f5b91063d9a46de2cf6616f1f1edb0e49c',array['postgres=X/postgres']::text[]),
('erp._cp6_supplier_cent_state(uuid[])','19d43e3e32d94c6aaaf0acbb1f6e55946701fa10b9f53df7a990ea9375fad191',array['postgres=X/postgres']::text[])) expected(identity,installed_sha256,acl) loop
 if encode(extensions.digest(convert_to(pg_get_functiondef(to_regprocedure(r.identity)),'UTF8'),'sha256'),'hex') is distinct from r.installed_sha256 or (select pg_get_userbyid(proowner) from pg_proc where oid=to_regprocedure(r.identity)) is distinct from 'postgres' or (select array(select a::text from unnest(proacl) a order by a::text) from pg_proc where oid=to_regprocedure(r.identity)) is distinct from r.acl then raise exception 'N_EXTRA_FUNCTION_OWNER_ACL_MISMATCH';end if;
end loop;
if not exists(select 1 from pg_class where oid='erp.supplier_cent_posting_facts'::regclass and relrowsecurity and relowner='postgres'::regrole) or exists(select 1 from information_schema.role_table_grants where table_schema='erp' and table_name='supplier_cent_posting_facts' and grantee in('PUBLIC','anon','authenticated','service_role')) or (select count(*) from pg_trigger where tgrelid='erp.supplier_cent_posting_facts'::regclass and not tgisinternal and tgenabled='O' and tgfoid='erp.guard_sales_payment_fact_append_only()'::regprocedure and tgname in('trg_supplier_cent_fact_append_only','trg_supplier_cent_fact_no_truncate'))<>2 then raise exception 'N_CENT_FACT_SECURITY_MISMATCH';end if;
if encode(extensions.digest(convert_to(pg_get_functiondef('erp.guard_sales_payment_fact_append_only()'::regprocedure),'UTF8'),'sha256'),'hex') is distinct from '2011da553bc46c6106ba4c638c0f695da4bb2c1855bd1518b42df8215cf81cf5' or (select pg_get_userbyid(proowner) from pg_proc where oid='erp.guard_sales_payment_fact_append_only()'::regprocedure) is distinct from 'postgres' or (select array(select a::text from unnest(proacl) a order by a::text) from pg_proc where oid='erp.guard_sales_payment_fact_append_only()'::regprocedure) is distinct from array['postgres=X/postgres']::text[] then raise exception 'N_INHERITED_FACT_GUARD_MISMATCH';end if;

 select boundary_snapshot into v_expected from erp.cp6_v2620n_rollback_capsule limit 1;
 if v_expected is null or (select count(*) from jsonb_object_keys(v_expected))<>64 or exists(select 1 from erp.cp6_v2620n_rollback_capsule where boundary_snapshot is distinct from v_expected) then raise exception 'N_BOUNDARY_SNAPSHOT_MISMATCH';end if;
 foreach v_table in array array['app_users','idempotency_requests','products','audit_logs','journal_entries','journal_lines','account_daily_balances','sales_headers','sales_items','sale_stock_allocations','sales_returns','sales_return_items','sales_payments','fg_lots','fg_stock_movements','fg_inventory_balances','hpp_versions','product_conversions','product_conversion_allocations','laundry_deliveries','laundry_delivery_lines','laundry_receipts','laundry_failed_wash_attempts','wip_stage_events','cp6_v2620g_rollback_capsule','cp6_v2620h_rollback_capsule','cp6_v2620i_rollback_capsule','sales_payment_posting_facts','sales_payment_reversal_facts','cp6_v2620j_rollback_capsule','cp6_v2620k_rollback_capsule','accounting_period_control','accounting_account_mappings','cash_accounts','chart_accounts','laundry_claims','laundry_vendors','cp6_v2620l_rollback_capsule','opening_balance_headers','opening_balance_items','opening_subledger_balances','opening_subledger_settlements','opening_financial_corrections','supplier_payments','material_purchase_headers','material_purchase_items','material_supplier_invoices','material_supplier_invoice_lines','material_supplier_returns','material_supplier_return_items','material_purchase_cost_corrections','material_purchase_cost_correction_items','material_stock_movements','material_rolls','cost_recalc_queue','cost_adjustments','suppliers','materials','cp6_v2620m_rollback_capsule','supplier_cent_posting_facts','material_cost_history','material_cost_revaluation_state','material_cost_revaluation_events','material_cost_checkpoints']::text[] loop
 execute format($sql$select encode(extensions.digest(convert_to(coalesce(string_agg(row_hash,',' order by row_hash),''),'UTF8'),'sha256'),'hex') from(select encode(extensions.digest(convert_to(to_jsonb(t)::text,'UTF8'),'sha256'),'hex') row_hash from erp.%I t) rows$sql$,v_table) into v_hash;
 if v_hash is distinct from v_expected->>v_table then raise exception 'N_POST_USE_ROLLBACK_REFUSED';end if;
 end loop;
 for r in select * from erp.cp6_v2620n_rollback_capsule order by object_regidentity loop execute r.object_definition;end loop;
end
$restore_guard$;
drop function erp._cp6_apply_supplier_cent_event(text,uuid,date,text,jsonb,boolean);
drop function erp._cp6_supplier_cent_ledger(uuid[]);
drop function erp._cp6_supplier_cent_state(uuid[]);
drop table erp.supplier_cent_posting_facts;
delete from erp.schema_migrations where version='v2.6.20n';
delete from supabase_migrations.schema_migrations where version='20260911124328' and name='erp_v2_6_20n_cp6_supplier_cent_lifecycle';
drop table erp.cp6_v2620n_rollback_capsule;
commit;
