// @vitest-environment jsdom
import {act} from 'react'
import {createRoot,type Root} from 'react-dom/client'
import {afterEach,beforeEach,describe,expect,it,vi} from 'vitest'
import AttendanceEntryEditor,{type AttendanceSelection} from './AttendanceEntryEditor'
import {parseAttendanceEntry,parseAttendanceOutcome,type AttendanceEntry} from './attendanceEntryContract'
import type {useProductionMutation} from './useProductionMutation'
import type {Json} from './types/database.preconnect'
const cid='11111111-1111-4111-8111-111111111111',pid='22222222-2222-4222-8222-222222222222',day='2026-09-29',token='a'.repeat(32),uuid=(n:number)=>`33333333-3333-4333-8333-${String(n).padStart(12,'0')}`
const h={id:pid,contractor_id:cid,number:'ABS-TEST',period_start:day,period_end:day,pay_date:day,status:'DRAFT',correction_of_id:null,notes:null,row_version:'9007199254740993',record_count:'101',consuming_payroll_count:'0'}
function matrix(offset=0,count=101,recorded=true,status='DRAFT'):AttendanceEntry{
 const rows=Array.from({length:Math.min(100,count-offset)},(_,j)=>{const n=offset+j+1,id=uuid(n);return {id:id+':'+day,worker_id:id,worker_name:'Pekerja '+n,worker_code:null,pay_scheme:'DAILY',date:day,eligible:true,required:true,daily_rate:'100.123456',record:recorded?{id:uuid(n+1000),mark:'PRESENT',paid_fraction:'1.0000',notes:null,lifecycle:status,supersedes_id:null,row_version:'9007199254740993'}:null}})
 return parseAttendanceEntry({contract_version:'cp7.attendance-entry.v1',date_from:day,date_to:day,source_token:token,contractor:{id:cid,name:'Mandor matrix',active_now:true,attendance_required:true},period:recorded?{...h,status,record_count:String(count)}:null,page:{rows,total:String(count),offset,limit:100,next_offset:offset+rows.length<count?offset+rows.length:null}})
}
let root:Root,container:HTMLDivElement
const read=vi.fn(),preview=vi.fn(),commit=vi.fn(),invalidate=vi.fn(),cancel=vi.fn()
const recovery={beginRead:()=>({}),finishRead:()=>true,isReadCurrent:()=>true,invalidate,writerLocked:false,busy:false} as unknown as ReturnType<typeof useProductionMutation>
beforeEach(()=>{Object.assign(globalThis,{IS_REACT_ACT_ENVIRONMENT:true});vi.clearAllMocks();container=document.createElement('div');document.body.append(container);root=createRoot(container);read.mockImplementation(async(q:{offset:number})=>matrix(q.offset));preview.mockImplementation(async(p:{contractor_id:string;source_token:string;document:{period_id?:string;attendance:unknown[]}})=>({contract_version:'cp7.attendance-preview.v1',kind:'READ_ONLY_PREVIEW',contractor_id:p.contractor_id,period_id:p.document.period_id??null,source_token:p.source_token,line_count:String(p.document.attendance.length),paid_day_equivalent:'100.5000',estimated_amount:'10062.4073280000'.replace(/0000$/,'')}))})
afterEach(async()=>{await act(async()=>root.unmount());container.remove()})
async function flush(){await act(async()=>{await new Promise(r=>setTimeout(r,0))})}
async function mount(selection:AttendanceSelection={mode:'EDIT',contractor:cid,from:day,to:day,period:h}){await act(async()=>root.render(<AttendanceEntryEditor selection={selection} recovery={recovery} read={read} preview={preview} commit={commit} cancel={cancel}/>));await flush()}
async function input(label:string,value:string){const el=container.querySelector(`[aria-label="${label}"]`) as HTMLInputElement|HTMLTextAreaElement|HTMLSelectElement;expect(el).not.toBeNull();await act(async()=>{const proto=el.tagName==='TEXTAREA'?HTMLTextAreaElement.prototype:el.tagName==='SELECT'?HTMLSelectElement.prototype:HTMLInputElement.prototype;Object.getOwnPropertyDescriptor(proto,'value')!.set!.call(el,value);el.dispatchEvent(new Event(el.tagName==='SELECT'?'change':'input',{bubbles:true}))});await flush()}
function button(name:string){return [...container.querySelectorAll('button')].find(b=>b.textContent===name)!}
async function click(name:string){await act(async()=>button(name).click());await flush()}
describe('complete attendance matrix editing',()=>{
 it('loads every page before editing and retains unseen draft records in a save snapshot',async()=>{await mount();expect(read.mock.calls.map(([q])=>q.offset)).toEqual([0,100]);expect(container.querySelectorAll('.catt-cell')).toHaveLength(20);expect(container.textContent).toContain('101 sel pekerja/tanggal dimuat lengkap');await input('Kehadiran Pekerja 1 '+day,'HALF_DAY');await input('Alasan tindakan absensi','Seluruh periode telah diperiksa');expect(button('Simpan draft absensi').disabled).toBe(true);await click('Pratinjau hitungan absensi');expect(container.textContent).toContain('Perkiraan upah Rp10.062,407328');await click('Simpan draft absensi');expect(commit).toHaveBeenCalledOnce();const [action,p,version]=commit.mock.calls[0];expect(action).toBe('SAVE');expect(version).toBe('9007199254740993');expect(p.document.attendance).toHaveLength(101);expect(p.document.attendance[0]).toMatchObject({status:'HALF_DAY',paid_fraction:'0.5000'});expect(p.document.attendance[100]).toMatchObject({worker_id:uuid(101),status:'PRESENT',paid_fraction:'1.0000'})})
 it('keeps empty cells unrecorded and invalidates the native preview when a mark changes',async()=>{read.mockImplementation(async()=>matrix(0,2,false));await mount({mode:'CREATE',contractor:cid,from:day,to:day,period:null});expect(container.textContent).toContain('2 sel wajib belum dicatat');await input('Nomor periode absensi','ABS-NEW');await input('Alasan tindakan absensi','Draft baru belum lengkap');await click('Pratinjau hitungan absensi');expect(preview.mock.calls[0][0].document.attendance).toEqual([]);expect(button('Simpan draft absensi').disabled).toBe(false);await input('Kehadiran Pekerja 1 '+day,'ABSENT');expect(button('Simpan draft absensi').disabled).toBe(true);expect(container.textContent).not.toContain('Perkiraan upah');await click('Pratinjau hitungan absensi');expect(preview.mock.calls[1][0].document.attendance).toEqual([{worker_id:uuid(1),attendance_date:day,status:'ABSENT',paid_fraction:'0.0000',notes:null}])})
 it('retires all rows when another source revision appears on a later page',async()=>{read.mockImplementation(async(q:{offset:number})=>({...matrix(q.offset),source_token:q.offset?'b'.repeat(32):token}));await mount();expect(container.textContent).toContain('berubah saat dimuat');expect(container.querySelectorAll('.catt-cell')).toHaveLength(0);expect(container.textContent).not.toContain('Rp');expect(commit).not.toHaveBeenCalled()})
 it('retires rates and locks writing if native preview fails',async()=>{await mount();await input('Alasan tindakan absensi','Periode telah diperiksa');preview.mockRejectedValueOnce({code:'42501',message:'Current access revoked'});await click('Pratinjau hitungan absensi');expect(container.querySelectorAll('.catt-cell')).toHaveLength(0);expect(container.textContent).not.toContain('Rp');expect(invalidate).toHaveBeenCalledOnce();expect(commit).not.toHaveBeenCalled()})
 it('retains exact source lineage for every row in a correction with a new period identity',async()=>{const period={...h,status:'POSTED',record_count:'2'};read.mockImplementation(async()=>matrix(0,2,true,'POSTED'));await mount({mode:'CORRECT',contractor:cid,from:day,to:day,period});await input('Kehadiran Pekerja 1 '+day,'ABSENT');await input('Alasan tindakan absensi','Koreksi seluruh catatan asal');await click('Pratinjau hitungan absensi');await click('Simpan draft absensi');const [,p,v]=commit.mock.calls[0];expect(v).toBeNull();expect(p.document.period_id).toBeUndefined();expect(p.document.correction_of_period_id).toBe(pid);expect(p.document.attendance.map((x:{supersedes_attendance_record_id:string})=>x.supersedes_attendance_record_id)).toEqual([uuid(1001),uuid(1002)])})
 it('requires review before posting and sends the native period version without numeric conversion',async()=>{read.mockImplementation(async()=>matrix(0,2));await mount({mode:'POST',contractor:cid,from:day,to:day,period:{...h,record_count:'2'}});await input('Alasan tindakan absensi','Catatan lengkap siap diposting');expect(button('Posting absensi sekarang').disabled).toBe(true);await act(async()=>(container.querySelector('[aria-label="Absensi sudah diperiksa"]') as HTMLInputElement).click());await click('Posting absensi sekarang');expect(preview).not.toHaveBeenCalled();expect(commit).toHaveBeenCalledWith('POST',{contractor_id:cid,date_from:day,date_to:day,source_token:token,document:{period_id:pid,reason:'Catatan lengkap siap diposting'}},'9007199254740993')})
 it('rejects a different period, status, request or unchanged version in a committed response',()=>{const payload:Json={document:{contractor_id:cid,date_from:day,date_to:day,source_token:token,document:{period_id:pid}},expected_version:h.row_version},r={contract_version:'cp7.attendance-outcome.v1',kind:'COMMITTED_OUTCOME',action:'POST',request_id:cid,period_id:pid,contractor_id:cid,row_version:'9007199254740994',status:'POSTED',source_token:token};expect(parseAttendanceOutcome(r,cid,'POST',payload).row_version).toBe('9007199254740994');for(const bad of [{period_id:cid},{status:'DRAFT'},{request_id:pid},{row_version:h.row_version}])expect(()=>parseAttendanceOutcome({...r,...bad},cid,'POST',payload)).toThrow()})
})
