const bsrActiveKey='erp.prototypePage'
const bsrPageId='bs-rework'
type BsComponent={name:string;doneBefore:boolean;rate:number}
type BsCase={id:string;po:string;brand:string;sku:string;size:string;qty:number;category:'BS'|'CU';stage:string;source:string;responsible:string;components:BsComponent[]}
const bsCases:BsCase[]=[
{id:'BS-260827-014',po:'PO-260812-031',brand:'Vivo',sku:'73002',size:'31',qty:1,category:'BS',stage:'QC',source:'Jahitan samping',responsible:'Mandor Asep',components:[{name:'Jahit samping',doneBefore:true,rate:1800},{name:'Obras',doneBefore:true,rate:900},{name:'Bartack',doneBefore:false,rate:750}]},
{id:'CU-260827-008',po:'PO-260812-031',brand:'Vivo',sku:'73002',size:'32',qty:1,category:'CU',stage:'Laundry',source:'Warna belum sesuai',responsible:'Laundry Sumber Warna',components:[]},
{id:'BS-260826-010',po:'PO-260812-028',brand:'Vivo',sku:'73001',size:'29',qty:2,category:'BS',stage:'QC',source:'Zipper miring',responsible:'Mandor Dedi',components:[{name:'Pasang zipper',doneBefore:true,rate:2400},{name:'Top stitch',doneBefore:false,rate:1100},{name:'Finishing',doneBefore:false,rate:700}]},
]
const payrollCandidates=[
{id:'RW-PAY-011',caseId:'BS-260826-010',mandor:'Mandor Dedi',component:'Top stitch',qty:2,amount:2200,group:'unassigned'},
{id:'RW-PAY-012',caseId:'BS-260826-010',mandor:'Mandor Dedi',component:'Finishing',qty:2,amount:1400,group:'note-31'},
{id:'RW-PAY-013',caseId:'BS-260827-014',mandor:'Mandor Asep',component:'Bartack',qty:1,amount:750,group:'note-28'},
]
function bsrMoney(v:number){return new Intl.NumberFormat('id-ID',{style:'currency',currency:'IDR',maximumFractionDigits:0}).format(v)}
function bsrSetText(root:HTMLElement|Document,sel:string,text:string){const n=root.querySelector<HTMLElement>(sel);if(n)n.textContent=text}
function bsrTop(active=true){const top=document.querySelector<HTMLElement>('.top-title');const s=top?.querySelector<HTMLElement>('strong');const sub=top?.querySelector<HTMLElement>('span');if(!s||!sub)return;if(active){s.textContent='Barang BS & Rework';sub.textContent='Pilih treatment, cek entitlement, lalu kelompokkan nota'}else{s.textContent='Modul ERP';sub.textContent='Cepat, jelas, dan aman buat operasional'}}
function bsrGeneric(root:HTMLElement){root.className='panel placeholder';root.removeAttribute('data-bsr-ready');root.innerHTML='<div class="placeholder-icon">◇</div><h2>Fondasinya sudah disiapkan.</h2><p>Modul ini berikutnya akan mengikuti flow bisnis yang sama: informasi penting terlihat sebelum user menekan tombol yang mengubah uang atau stok.</p>'}
function bsrUnmount(){const root=document.querySelector<HTMLElement>('.bsr-root');if(root)bsrGeneric(root);bsrTop(false)}
function bsrCaseRow(c:BsCase,index:number){return `<button type="button" class="bsr-case-row ${index===0?'active':''}" data-bsr-case="${index}"><span class="bsr-case-kind ${c.category==='CU'?'cu':''}">${c.category==='CU'?'CU · Cuci Ulang':'BS'}</span><div><strong>${c.id}</strong><small>${c.po} · ${c.brand} ${c.sku} · size ${c.size}</small></div><div><span>QTY</span><strong>${c.qty} pcs</strong></div><div><span>SUMBER</span><strong>${c.stage}</strong><small>${c.source}</small></div><b>›</b></button>`}
function bsrComponentRows(c:BsCase){if(c.category==='CU')return `<div class="bsr-cu-route"><span>JALUR OTOMATIS</span><strong>Cuci ulang → Laundry</strong><small>Tidak membuat upah rework mandor. Biaya mengikuti jalur laundry/vendor.</small></div>`;return c.components.map((component,i)=>`<label class="bsr-component ${component.doneBefore?'paid-before':''}"><input type="checkbox" data-bsr-component="${i}" ${component.doneBefore?'disabled':''}/><div><strong>${component.name}</strong><small>${component.doneBefore?'Sudah completed/payable sebelumnya · tidak dibayar ulang':'Belum completed sebelum BS · eligible bila benar-benar dikerjakan'}</small></div><span>${bsrMoney(component.rate)} / pcs</span></label>`).join('')}
function bsrPayrollCard(item:typeof payrollCandidates[number]){return `<article class="bsr-pay-card" draggable="true" data-pay-id="${item.id}"><div class="bsr-drag">⠿</div><div><strong>${item.caseId} · ${item.component}</strong><small>${item.mandor} · ${item.qty} pcs</small></div><b>${bsrMoney(item.amount)}</b><select data-bsr-move aria-label="Pindah nota"><option value="unassigned" ${item.group==='unassigned'?'selected':''}>Belum dipilih</option><option value="note-28" ${item.group==='note-28'?'selected':''}>Nota 28 Agu</option><option value="note-31" ${item.group==='note-31'?'selected':''}>Nota 31 Agu</option></select></article>`}
function bsrBoard(root:HTMLElement){const groups:{id:string;title:string;sub:string}[]=[{id:'unassigned',title:'Belum dipilih',sub:'Tarik ke nota pembayaran'},{id:'note-28',title:'Nota 28 Agu',sub:'Batch pembayaran lebih dulu'},{id:'note-31',title:'Nota 31 Agu',sub:'Batch pembayaran berikutnya'}];const board=root.querySelector<HTMLElement>('[data-bsr-board]');if(!board)return;board.innerHTML=groups.map((g)=>{const items=payrollCandidates.filter((i)=>i.group===g.id);const total=items.reduce((s,i)=>s+i.amount,0);return `<section class="bsr-pay-column" data-drop-group="${g.id}"><div class="bsr-pay-head"><div><strong>${g.title}</strong><small>${g.sub}</small></div><b>${bsrMoney(total)}</b></div><div class="bsr-pay-list">${items.map(bsrPayrollCard).join('')||'<div class="bsr-pay-empty">Drop di sini</div>'}</div></section>`}).join('')}
function bsrRenderDetail(root:HTMLElement,index:number){const c=bsCases[index]??bsCases[0];root.querySelectorAll<HTMLElement>('[data-bsr-case]').forEach((n)=>n.classList.toggle('active',Number(n.dataset.bsrCase)===index));bsrSetText(root,'[data-bsr-id]',c.id);bsrSetText(root,'[data-bsr-product]',`${c.brand} ${c.sku} · size ${c.size}`);bsrSetText(root,'[data-bsr-source]',`${c.stage} · ${c.source}`);bsrSetText(root,'[data-bsr-responsible]',c.responsible);bsrSetText(root,'[data-bsr-qty]',`${c.qty} pcs`);const treatment=root.querySelector<HTMLElement>('[data-bsr-treatment]');if(treatment){treatment.innerHTML=c.category==='CU'?'<button class="bsr-treatment active" data-treatment="laundry"><strong>Cuci ulang</strong><small>Kembali ke laundry</small></button>':'<button class="bsr-treatment active" data-treatment="sewing"><strong>Bikin bagus</strong><small>Rework ke mandor</small></button><button class="bsr-treatment" data-treatment="laundry"><strong>Cuci ulang</strong><small>Rework ke laundry</small></button><button class="bsr-treatment" data-treatment="scrap"><strong>Scrap / selesai BS</strong><small>Tidak kembali jadi Good</small></button>'}const components=root.querySelector<HTMLElement>('[data-bsr-components]');if(components)components.innerHTML=bsrComponentRows(c);const add=root.querySelector<HTMLButtonElement>('[data-bsr-add-payroll]');if(add){add.hidden=c.category==='CU';add.disabled=true;add.textContent='Tambahkan eligible ke antrian nota'}}
function bsrRender(root:HTMLElement){if(root.dataset.bsrReady==='true')return;root.dataset.bsrReady='true';root.className='bsr-root';root.innerHTML=`<section class="hero-copy compact bsr-hero"><div class="eyebrow">PRODUKSI · BS · REWORK</div><h1>Barang BS & Rework</h1><p>BS baru diputuskan treatment-nya di sini. Cuci Ulang tetap kategori BS tetapi jalurnya Laundry. Rework mandor hanya menambah upah untuk komponen yang memang baru dikerjakan dan belum pernah payable.</p></section><section class="bsr-layout"><div class="panel bsr-list"><div class="bsr-section-head"><div><span>01</span><div><strong>Kasus terbuka</strong><small>BS dan Cuci Ulang dari finishing.</small></div></div><b>${bsCases.length} kasus</b></div><div class="bsr-case-list">${bsCases.map(bsrCaseRow).join('')}</div></div><div class="panel bsr-detail"><div class="bsr-section-head"><div><span>02</span><div><strong>Pilih treatment</strong><small>Keputusan dibuat per kasus BS.</small></div></div><span class="bsr-pill">SIMULASI</span></div><div class="bsr-case-title"><div><span data-bsr-id>—</span><strong data-bsr-product>—</strong><small data-bsr-source>—</small></div><div><span>QTY</span><strong data-bsr-qty>—</strong><small data-bsr-responsible>—</small></div></div><div class="bsr-treatment-grid" data-bsr-treatment></div><div class="bsr-component-head"><div><strong>Komponen kerja rework</strong><small>Centang yang benar-benar dikerjakan. Yang sudah payable sebelumnya terkunci.</small></div></div><div class="bsr-components" data-bsr-components></div><div class="bsr-entitlement-note"><strong>Aturan payroll</strong><span>Komponen yang sudah completed/payable sebelum BS tidak mendapat entitlement kedua. Hanya komponen baru yang performed dan eligible yang masuk kandidat payroll.</span></div><button type="button" class="primary-btn bsr-add-payroll" data-bsr-add-payroll>Tambahkan eligible ke antrian nota</button></div></section><section class="panel bsr-payroll"><div class="bsr-section-head"><div><span>03</span><div><strong>Antrian upah rework → nota pembayaran</strong><small>Drag kartu ke nota yang lu mau. Ini pengelompokan nota; settlement payroll final tetap bisa digabung per mandor/periode.</small></div></div><span class="bsr-drag-hint">DRAG DESKTOP · PILIH DROPDOWN DI HP</span></div><div class="bsr-board" data-bsr-board></div></section><div class="bsr-toast" data-bsr-toast hidden></div>`;bsrBoard(root);bsrRenderDetail(root,0);bsrBind(root)}
function bsrBind(root:HTMLElement){root.addEventListener('click',(event)=>{const target=event.target as Element|null;const caseBtn=target?.closest<HTMLButtonElement>('[data-bsr-case]');if(caseBtn)bsrRenderDetail(root,Number(caseBtn.dataset.bsrCase));const treatment=target?.closest<HTMLButtonElement>('[data-treatment]');if(treatment){root.querySelectorAll('[data-treatment]').forEach((n)=>n.classList.remove('active'));treatment.classList.add('active')}if(target?.closest('[data-bsr-add-payroll]')){const button=target.closest<HTMLButtonElement>('[data-bsr-add-payroll]');if(button&&!button.disabled){const toast=root.querySelector<HTMLElement>('[data-bsr-toast]');if(toast){toast.hidden=false;toast.textContent='Simulasi: komponen eligible masuk antrian nota payroll. Backend belum berubah.';setTimeout(()=>toast.hidden=true,2600)}}}});root.addEventListener('change',(event)=>{const target=event.target as HTMLInputElement|HTMLSelectElement|null;if(!target)return;if(target.matches('[data-bsr-component]')){const any=Array.from(root.querySelectorAll<HTMLInputElement>('[data-bsr-component]:checked')).length>0;const add=root.querySelector<HTMLButtonElement>('[data-bsr-add-payroll]');if(add)add.disabled=!any}if(target.matches('[data-bsr-move]')){const card=target.closest<HTMLElement>('[data-pay-id]');const item=payrollCandidates.find((x)=>x.id===card?.dataset.payId);if(item){item.group=(target as HTMLSelectElement).value;bsrBoard(root)}}});let dragging='';root.addEventListener('dragstart',(event)=>{const card=(event.target as Element|null)?.closest<HTMLElement>('[data-pay-id]');if(!card)return;dragging=card.dataset.payId??'';card.classList.add('dragging')});root.addEventListener('dragend',(event)=>{(event.target as Element|null)?.closest<HTMLElement>('[data-pay-id]')?.classList.remove('dragging');root.querySelectorAll('.is-drop-target').forEach((n)=>n.classList.remove('is-drop-target'));dragging=''});root.addEventListener('dragover',(event)=>{const column=(event.target as Element|null)?.closest<HTMLElement>('[data-drop-group]');if(!column||!dragging)return;event.preventDefault();column.classList.add('is-drop-target')});root.addEventListener('dragleave',(event)=>{(event.target as Element|null)?.closest<HTMLElement>('[data-drop-group]')?.classList.remove('is-drop-target')});root.addEventListener('drop',(event)=>{const column=(event.target as Element|null)?.closest<HTMLElement>('[data-drop-group]');if(!column||!dragging)return;event.preventDefault();const item=payrollCandidates.find((x)=>x.id===dragging);if(item){item.group=column.dataset.dropGroup??'unassigned';bsrBoard(root)}dragging=''})}
function bsrMount(){if(sessionStorage.getItem(bsrActiveKey)!==bsrPageId)return;const placeholder=document.querySelector<HTMLElement>('.placeholder');if(!placeholder)return;bsrTop(true);bsrRender(placeholder)}
document.addEventListener('click',(event)=>{const target=event.target as Element|null;const submenu=target?.closest('.submenu button') as HTMLButtonElement|null;if(submenu){const label=submenu.textContent?.replace(/^•\s*/,'').trim()??'';if(label==='Barang BS & Rework')sessionStorage.setItem(bsrActiveKey,bsrPageId);else if(sessionStorage.getItem(bsrActiveKey)===bsrPageId){sessionStorage.removeItem(bsrActiveKey);bsrUnmount()}}const main=target?.closest('.nav-main');if(main&&!submenu&&sessionStorage.getItem(bsrActiveKey)===bsrPageId){sessionStorage.removeItem(bsrActiveKey);bsrUnmount()}},true)
const bsrObserver=new MutationObserver(bsrMount);bsrObserver.observe(document.documentElement,{childList:true,subtree:true});queueMicrotask(bsrMount)
