// @vitest-environment jsdom
// Explicit synthetic source DTOs exercise the real shared recovery hook.
// These DOM controls do not claim actual Native or independent qualification.
import {act} from 'react'
import {createRoot,type Root} from 'react-dom/client'
import {afterEach,beforeEach,describe,expect,it,vi} from 'vitest'
import ConnectedSupplierCreditPage from './ConnectedSupplierCreditPage'
import {recoveryIdentity} from '../tests/fixtures/productionRecovery'
import {readProductionRecovery} from './productionRecovery'
const auth=vi.hoisted(()=>({current:null as unknown}))
const client=vi.hoisted(()=>({rpc:vi.fn()}))
vi.mock('./auth/AuthProvider',()=>({useAuth:()=>auth.current}))
vi.mock('./lib/supabase',()=>({getUatSupabaseClient:()=>client}))
let root:Root,container:HTMLDivElement
const supplier='11111111-1111-4111-8111-111111111111',source='22222222-2222-4222-8222-222222222222',target='33333333-3333-4333-8333-333333333333',ret='44444444-4444-4444-8444-444444444444'
const version='a'.repeat(64)
function dto(selected:string|null=null){return {supplier_id:selected,page:1,total:1,can_manage:true,suppliers:[{id:supplier,code:'SUP-SOURCE',name:'Supplier source'}],purchases:[{id:source,number:'PURCHASE-ORIGINAL',date:'2026-09-20',final_ap:'80.00',paid:'0.00',remaining:'80.00',credit_delta:'-20.00',payment_status:'UNPAID'},{id:target,number:'PURCHASE-TARGET',date:'2026-09-21',final_ap:'100.00',paid:'0.00',remaining:'100.00',credit_delta:'0.00',payment_status:'UNPAID'}],credits:[{return_id:ret,return_number:'SOURCE-RETURN',supplier_id:supplier,source_purchase_id:source,purchase_number:'PURCHASE-ORIGINAL',credit:'20.00',original_purchase_credit:'20.00',version,allocations:[] as {purchase_id:string,amount:string}[],events:[]}]}}
beforeEach(()=>{Object.assign(globalThis,{IS_REACT_ACT_ENVIRONMENT:true});localStorage.clear();client.rpc.mockReset();auth.current={...structuredClone(recoveryIdentity),identity:{...structuredClone(recoveryIdentity.identity),permissions:['finance.ap.view','finance.ap.pay']}};Object.defineProperty(navigator,'locks',{configurable:true,value:{request:async(_name:string,_options:unknown,fn:(lock:unknown)=>Promise<unknown>)=>fn({})}});container=document.createElement('div');document.body.append(container);root=createRoot(container)})
afterEach(async()=>{await act(async()=>root.unmount());container.remove();localStorage.clear();Reflect.deleteProperty(navigator,'locks');vi.restoreAllMocks()})
async function flush(){await act(async()=>{await new Promise(r=>setTimeout(r,0))})}
async function mount(){await act(async()=>root.render(<ConnectedSupplierCreditPage onLaundry={()=>{}}/>));await flush()}
async function change(label:string,value:string){const input=container.querySelector<HTMLInputElement|HTMLSelectElement>(`[aria-label="${label}"]`);if(!input)throw Error('Missing '+label);await act(async()=>{Object.getOwnPropertyDescriptor(input instanceof HTMLSelectElement?HTMLSelectElement.prototype:HTMLInputElement.prototype,'value')!.set!.call(input,value);input.dispatchEvent(new Event('input',{bubbles:true}));input.dispatchEvent(new Event('change',{bubbles:true}))});await flush()}
function button(label:string){const b=[...container.querySelectorAll('button')].find(b=>b.getAttribute('aria-label')===label||b.textContent?.trim()===label);if(!b)throw Error('Missing '+label);return b}
async function click(label:string){await act(async()=>button(label).click());await flush()}
async function review(){await change('Supplier kredit',supplier);await click('Atur alokasi SOURCE-RETURN');await change('Kredit untuk PURCHASE-TARGET','12.00');await change('Alasan pengalihan kredit','Catatan operator sendiri')}
function server(){const s={lost:false,effects:0},cache=new Map<string,unknown>();client.rpc.mockImplementation(async(name:string,args:Record<string,unknown>)=>{if(name==='erp_get_supplier_credit_v1'){const f=args.p_filters as {supplier_id?:string};return {data:dto(f.supplier_id??null),error:null}};const payload=args.p_payload as Record<string,unknown>,id=String(args.p_client_request_id);if(!cache.has(id)){s.effects++;cache.set(id,{request_id:id,return_id:payload.return_id,source_purchase_id:payload.source_purchase_id,version:'b'.repeat(64)})}return s.lost?{data:null,error:{status:503,message:'Lost reply'}}:{data:cache.get(id),error:null}});return s}
const writes=()=>client.rpc.mock.calls.filter(([name])=>name==='erp_save_supplier_credit_v1')
describe('supplier-credit factual retirement and exact recovery',()=>{
 it('renders a consistent signed Native-source balance without converting it to an unsigned operator amount',async()=>{client.rpc.mockImplementation(async(_name:string,args:Record<string,unknown>)=>{const f=args.p_filters as {supplier_id?:string},w=dto(f.supplier_id??null);Object.assign(w.purchases[0],{final_ap:'60.00',paid:'100.00',remaining:'-40.00'});return {data:w,error:null}});await mount();expect(container.textContent).toContain('PURCHASE-ORIGINAL');expect(container.textContent).toContain('−Rp40,00');await change('Supplier kredit',supplier);await click('Atur alokasi SOURCE-RETURN');expect(button('Simpan alokasi kredit').disabled).toBe(true)})
 it('retires current denied facts and preserves operator fields for an explicit authorized read',async()=>{server();await mount();await review();client.rpc.mockResolvedValueOnce({data:null,error:{code:'42501',status:403,message:'CURRENT_SUPPLIER_DENIED'}});await click('Muat ulang kredit supplier');expect(container.textContent).not.toContain('PURCHASE-ORIGINAL');expect(container.querySelector('[aria-label="Alasan pengalihan kredit"]')).toBeNull();await click('Muat ulang kredit supplier');expect(container.querySelector<HTMLInputElement>('[aria-label="Alasan pengalihan kredit"]')?.value).toBe('Catatan operator sendiri');expect(container.querySelector<HTMLInputElement>('[aria-label="Kredit untuk PURCHASE-TARGET"]')?.value).toBe('12.00');expect(container.querySelector<HTMLInputElement>('input[type=checkbox]')?.checked).toBe(false);expect(writes()).toHaveLength(0)})
 it('retires currently displayed Native names when another tab changes shared recovery',async()=>{server();await mount();await review();await act(async()=>window.dispatchEvent(new StorageEvent('storage',{key:null})));await flush();expect(container.textContent).not.toContain('PURCHASE-ORIGINAL');expect(container.textContent).not.toContain('SOURCE-RETURN');await click('Muat ulang kredit supplier');expect(container.querySelector<HTMLInputElement>('[aria-label="Alasan pengalihan kredit"]')?.value).toBe('Catatan operator sendiri');expect(writes()).toHaveLength(0)})
 it('never paints a held response after the shared recovery generation retires',async()=>{server();await mount();let release:(value:unknown)=>void=()=>{};client.rpc.mockImplementationOnce(()=>new Promise(r=>release=r));await click('Muat ulang kredit supplier');const held=dto();held.purchases[0].number='OBSOLETE-HELD-PURCHASE';await act(async()=>window.dispatchEvent(new StorageEvent('storage',{key:null})));await act(async()=>release({data:held,error:null}));await flush();expect(container.textContent).not.toContain('OBSOLETE-HELD-PURCHASE');expect(container.textContent).not.toContain('PURCHASE-ORIGINAL')})
 it('replays the exact committed allocation UUID and payload after a full remount, with one effect',async()=>{const s=server();await mount();await review();await act(async()=>container.querySelector<HTMLInputElement>('input[type=checkbox]')!.click());s.lost=true;await click('Simpan alokasi kredit');const sent=structuredClone(writes()[0][1]);expect(readProductionRecovery('disposable:actor-1').pending.SUPPLIER_CREDIT?.id).toBe(sent.p_client_request_id);expect(container.textContent).not.toContain('PURCHASE-ORIGINAL');await act(async()=>root.unmount());root=createRoot(container);await mount();s.lost=false;await click('Reconcile transaksi');expect(writes()).toHaveLength(2);expect(writes()[1][1]).toEqual(sent);expect(s.effects).toBe(1);expect(readProductionRecovery('disposable:actor-1').pending.SUPPLIER_CREDIT).toBeUndefined()})
 it('does not enable saving negative or excessive-precision operator credit amounts',async()=>{server();await mount();await review();for(const amount of ['-1.00','1.001','21.00']){await change('Kredit untuk PURCHASE-TARGET',amount);await act(async()=>container.querySelector<HTMLInputElement>('input[type=checkbox]')!.click());expect(button('Simpan alokasi kredit').disabled).toBe(true)}expect(writes()).toHaveLength(0)})
})
