// @vitest-environment jsdom
import { act } from 'react'
import { createRoot, type Root } from 'react-dom/client'
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest'
import ConnectedFgStockPage from './ConnectedFgStockPage'
import { parseFgWorkspace, parseFgLedger } from './fgContract'
import { recoveryIdentity } from '../tests/fixtures/productionRecovery'
const state=vi.hoisted(()=>({auth:null as unknown}))
const client=vi.hoisted(()=>({rpc:vi.fn()}))
vi.mock('./auth/AuthProvider',()=>({useAuth:()=>state.auth}))
vi.mock('./lib/supabase',()=>({getUatSupabaseClient:()=>client}))
const id='11111111-1111-4111-8111-111111111111',lot='22222222-2222-4222-8222-222222222222',at='2026-09-29T03:00:00Z'
const position={product_id:id,product_sku:'SKU-PHYSICAL',commercial_sku:'LUNA',product_name:'Celana denim',size_code:'M',brand_name:'Vivo',lot_id:lot,lot_number:'LOT-01',location_id:id,location_name:'Gudang FG',quality_grade:'GRADE_A'}
const totals={physical_qty:'10',reserved_qty:'4',available_qty:'6',quality:'KNOWN'},page=(rows:unknown[])=>({rows,total:String(rows.length),offset:0,limit:25,next_offset:null})
function stock(finance=true){return {contract_version:'cp7.fg-workspace.v1',purpose:'SUMMARY',read_at:at,knowledge:'CURRENT',quantity_basis:'PHYSICAL_EQUALS_AVAILABLE_PLUS_ACTIVE_RESERVATION',financial_captured:finance,capabilities:{card:true},unit_code:'PCS',totals,page:page([{...position,...totals,last_movement_at:at,...(finance?{valuation:{state:'UNKNOWN',hpp_version_id:null,hpp_version:null,cost_state:null,calculated_at:null,unit_cost:null,value:null,basis:'CURRENT_RESTATED_LOT_VALUE'}}:{})}])}}
function ledger(finance=true){return {contract_version:'cp7.fg-ledger.v1',purpose:'CARD',read_at:at,knowledge:'CURRENT',financial_captured:finance,position,balances:totals,balance_basis:'COMPLETE_CHRONOLOGICAL_PREFIX_BEFORE_SEARCH_AND_PAGE',page:page([{id,physical_at:at,recorded_at:at,movement_type:'SALE_RESERVE',source_type:'SALE_ITEM',source_id:id,reversal_of_id:null,customer_name:'Toko A',notes:null,book_order:'9007199254740993',commercial_sku_at_transaction:'OLD-LUNA',qty_signed:'-4',reservation_delta:'4',physical_delta:'0',available_balance:'6',reserved_balance:'4',physical_balance:'10',...(finance?{valuation:{state:'UNKNOWN',unit_cost:null,basis:'CURRENT_RESTATED_MOVEMENT_SNAPSHOT'}}:{})}])}}
let root:Root,container:HTMLDivElement
beforeEach(()=>{Object.assign(globalThis,{IS_REACT_ACT_ENVIRONMENT:true});localStorage.clear();client.rpc.mockReset();const a=structuredClone(recoveryIdentity);a.identity.permissions.push('warehouse.fg.view','warehouse.stock.view','finance.hpp.view');state.auth=a;Object.defineProperty(navigator,'locks',{configurable:true,value:{request:async(_n:string,_o:unknown,fn:(l:unknown)=>Promise<unknown>)=>fn({})}});container=document.createElement('div');document.body.append(container);root=createRoot(container)})
afterEach(async()=>{await act(async()=>root.unmount());container.remove();localStorage.clear();Reflect.deleteProperty(navigator,'locks');vi.restoreAllMocks()})
async function flush(){await act(async()=>{await new Promise(r=>setTimeout(r,0))})}
async function mount(){await act(async()=>root.render(<ConnectedFgStockPage/>));await flush()}
async function click(label:string){const b=[...container.querySelectorAll('button')].find(x=>x.textContent===label);if(!b)throw Error(label);await act(async()=>b.click());await flush()}
function server(finance=true){client.rpc.mockImplementation(async(name:string)=>({data:name==='erp_cp7_get_fg_v1'?stock(finance):ledger(finance),error:null}))}
describe('FG current stock and complete ledger boundary',()=>{
  it('binds all four selected stock keys and shows historical identity without another stock calculation',async()=>{server();await mount();expect(container.textContent).toContain('10 PCS');expect(container.textContent).toContain('Biaya belum lengkap');expect(container.textContent).not.toContain('Rp0');await click('Lihat mutasi LUNA · M');const sent=client.rpc.mock.calls.find(([n])=>n==='erp_cp7_get_fg_ledger_v1')![1].p_query;expect(sent).toMatchObject({product_id:id,lot_id:lot,location_id:id,quality_grade:'GRADE_A',offset:0});expect(container.textContent).toContain('OLD-LUNA');expect(container.textContent).toContain('Dicadangkan untuk penjualan');expect(client.rpc.mock.calls.every(([name])=>name.startsWith('erp_cp7_get_'))).toBe(true)})
  it('rejects a ledger from another lot before showing its movements',async()=>{server();const handler=client.rpc.getMockImplementation()!;client.rpc.mockImplementation(async(name:string)=>{const r=await handler(name);if(name==='erp_cp7_get_fg_ledger_v1')r.data.position={...position,lot_id:id};return r});await mount();await click('Lihat mutasi LUNA · M');expect(container.textContent).toContain('Pilihan barang atau halaman berubah');expect(container.textContent).not.toContain('OLD-LUNA')})
  it('rejects monetary fields in operations responses and displays no hidden amount',async()=>{const a=state.auth as typeof recoveryIdentity;a.identity.permissions=a.identity.permissions.filter(p=>p!=='finance.hpp.view');server(false);await mount();expect(container.textContent).not.toContain('Rp');expect(()=>parseFgWorkspace(stock(true),false,'SUMMARY')).toThrow();const wrong=ledger(false);Object.assign(wrong.page.rows[0] as object,{recorded_unit_hpp:'100'});expect(()=>parseFgLedger(wrong,false,'CARD')).toThrow()})
  it('refuses partial pages and inconsistent reservation totals while keeping large quantities exact',()=>{const w=stock();expect(()=>parseFgWorkspace({...w,page:{...w.page,total:'2'}},true,'SUMMARY')).toThrow();expect(()=>parseFgWorkspace({...w,totals:{...totals,physical_qty:'11'}},true,'SUMMARY')).toThrow();const big={physical_qty:'9007199254740993',reserved_qty:'1',available_qty:'9007199254740992',quality:'KNOWN'};expect(parseFgWorkspace({...w,totals:big},true,'SUMMARY').totals.physical_qty).toBe('9007199254740993');const l=ledger();Object.assign(l.page.rows[0] as object,{book_order:'-9007199254740993'});expect(parseFgLedger(l,true,'CARD').page.rows[0].book_order).toBe('-9007199254740993');expect(parseFgLedger(l,true,'CARD').page.rows[0].physical_balance).toBe('10');expect(()=>parseFgLedger({...l,knowledge:'AS_KNOWN'},true,'CARD')).toThrow()})
  it('clears old stock after a denied reload',async()=>{server();await mount();client.rpc.mockResolvedValue({data:null,error:{status:403,message:'Hak akses berubah'}});await click('Muat ulang stok');expect(container.textContent).not.toContain('LOT-01');expect(container.querySelector('[role="alert"]')).toBeTruthy()})
})
