import type {Json} from './types/database.preconnect'
export type FinanceDates={from:string;to:string;as_of:string}
export const positionFields=['assets','cash','customer_ar','material_inventory','wip_inventory','fg_inventory','liabilities','supplier_final_ap','grni_estimated_liability','recorded_equity','current_earnings','liabilities_plus_equity','balance_difference'] as const
export const performanceMoney=['sales_revenue_gl','cogs_gl','gross_profit','other_income','operating_and_other_expense','net_profit','gross_sales_before_discount','line_discounts','posted_sales_returns','operational_net_sales','sales_revenue_bridge_delta'] as const
export type FinanceBlocker={family:string;code:string;severity:'CRITICAL'|'POLICY'|'RECALC'|'INFO';scope:'AS_OF'|'CURRENT_STATE'|'WINDOW';impact_date:string|null;reference:Json;reason:string}
export type FilingRow={id:string;closed_through:string;previous_closed_through:string|null;filed_at:string;reason:string;filed_status:'READY'}
export type FinanceReport={contract_version:'cp7.finance-report.v1';captured_at:string;knowledge_basis:'CURRENT_RECORDED_KNOWLEDGE';historical_knowledge:'NOT_RECONSTRUCTED';snapshot:{basis:{period_from:string;period_to:string;balance_sheet_as_of:string;supplier_exposure_basis:string;performance_lifecycle_basis:string;performance_reconciliation_basis:string;quality_event_basis:string;laundry_outstanding_basis:string};financial_position:Record<typeof positionFields[number],string>;performance:Record<typeof performanceMoney[number],string>&{gross_margin_pct:string|null;net_margin_pct:string|null;sales_revenue_reconciled:boolean};quality:Record<string,string|null>;supplier_exposure:Record<string,string>;data_confidence:{status:'BLOCKED'|'RECALC_PENDING'|'READY';critical_issue_count:string;warning_issue_count:string;pending_cost_recalc_count:string;failed_checks:Array<{check_name:string;severity:'WARNING'|'CRITICAL';issue_count:string;details:string;family?:string;scope?:string;impact_date?:string|null;reference?:Json}>;engine:'PERIOD_READINESS_V1';as_of:string;window_from:string|null;closed_through:string|null;blockers:FinanceBlocker[];info:FinanceBlocker[];filing:null|{filing_id:string;closed_through:string;previous_closed_through:string|null;filed_at:string;filed_status:'READY'};changed_since_filing:boolean}};close_preflight:null|{engine:'PERIOD_READINESS_V1';through:string;window_from:string|null;status:'BLOCKED'|'RECALC_PENDING'|'READY';blocker_count:string;critical_count:string;policy_count:string;recalc_count:string;blockers:FinanceBlocker[];info:FinanceBlocker[];closed_through:string|null;date_allowed:boolean};filings:{rows:FilingRow[];total:string;offset:number;limit:number;next_offset:number|null};filing:null|Omit<FilingRow,'filed_status'>&{basis:'IMMUTABLE_AS_FILED_GL_BALANCES';readiness:Json;gl_balances:Record<string,string>;source_hash:string}}
const fail=():never=>{throw Error('Laporan keuangan belum lengkap atau basis tanggal berubah. Muat ulang laporan.')}
const text=(v:unknown):v is string=>typeof v==='string'
const uuid=(v:unknown)=>text(v)&&/^[a-f0-9]{8}-[a-f0-9]{4}-[1-8][a-f0-9]{3}-[89ab][a-f0-9]{3}-[a-f0-9]{12}$/i.test(v)
const whole=(v:unknown):v is string=>text(v)&&/^(0|[1-9][0-9]{0,20})$/.test(v)
const decimal=(v:unknown,scale=2):v is string=>text(v)&&new RegExp(`^-?(0|[1-9][0-9]{0,40})(\\.[0-9]{1,${scale}})?$`).test(v)
export const financeDate=(v:unknown):v is string=>text(v)&&/^\d{4}-\d{2}-\d{2}$/.test(v)&&Number.isFinite(Date.parse(v+'T00:00:00Z'))&&new Date(v+'T00:00:00Z').toISOString().slice(0,10)===v
const nullableDate=(v:unknown)=>v===null||financeDate(v)
const timestamp=(v:unknown)=>text(v)&&/^\d{4}-\d{2}-\d{2}T/.test(v)&&Number.isFinite(Date.parse(v))
function closed(v:unknown,keys:readonly string[],optional:readonly string[]=[]){if(!v||typeof v!=='object'||Array.isArray(v))return fail();const r=v as Record<string,unknown>;if(keys.some(k=>!(k in r))||Object.keys(r).some(k=>!keys.includes(k)&&!optional.includes(k)))fail();return r}
// Numeric source values must already be strings before JS parses the RPC body.
function exactJson(v:unknown,depth=0):boolean{if(depth>24)return false;if(v===null||typeof v==='boolean'||text(v))return true;if(Array.isArray(v))return v.every(x=>exactJson(x,depth+1));return !!v&&typeof v==='object'&&Object.values(v).every(x=>exactJson(x,depth+1))}
function blockers(v:unknown,info=false){if(!Array.isArray(v))return fail();for(const b of v){const x=closed(b,['family','code','severity','scope','impact_date','reference','reason']);if(![x.family,x.code,x.reason].every(text)||!['CRITICAL','POLICY','RECALC','INFO'].includes(String(x.severity))||(x.severity==='INFO')!==info||!['AS_OF','CURRENT_STATE','WINDOW'].includes(String(x.scope))||!nullableDate(x.impact_date)||!exactJson(x.reference))fail()}return v as FinanceBlocker[]}
function readiness(v:unknown,extra:string[]=[],optional:string[]=[]){const r=closed(v,['engine','through','window_from','status','blocker_count','critical_count','policy_count','recalc_count','blockers','info',...extra],optional);if(r.engine!=='PERIOD_READINESS_V1'||!financeDate(r.through)||!nullableDate(r.window_from)||![r.blocker_count,r.critical_count,r.policy_count,r.recalc_count].every(whole))return fail();const b=blockers(r.blockers);blockers(r.info,true);for(const [severity,key]of[['CRITICAL','critical_count'],['POLICY','policy_count'],['RECALC','recalc_count']])if(BigInt(String(r[key]))!==BigInt(b.filter(x=>x.severity===severity).length))fail();if(BigInt(String(r.blocker_count))!==BigInt(b.length)||r.status!==(BigInt(String(r.critical_count))+BigInt(String(r.policy_count))>0n?'BLOCKED':BigInt(String(r.recalc_count))>0n?'RECALC_PENDING':'READY'))fail();return r}
function filingMeta(r:Record<string,unknown>,key='id'){if(!uuid(r[key])||!financeDate(r.closed_through)||!nullableDate(r.previous_closed_through)||r.previous_closed_through!==null&&String(r.previous_closed_through)>=r.closed_through||!timestamp(r.filed_at))fail()}
export function parseFinanceReport(v:unknown,dates:FinanceDates,filingId:string|null=null,offset=0,canPreflight=false):FinanceReport{
 const r=closed(v,['contract_version','captured_at','knowledge_basis','historical_knowledge','snapshot','close_preflight','filings','filing']);if(r.contract_version!=='cp7.finance-report.v1'||!timestamp(r.captured_at)||r.knowledge_basis!=='CURRENT_RECORDED_KNOWLEDGE'||r.historical_knowledge!=='NOT_RECONSTRUCTED')fail()
 const s=closed(r.snapshot,['basis','financial_position','performance','quality','supplier_exposure','data_confidence']),basis=closed(s.basis,['period_from','period_to','balance_sheet_as_of','supplier_exposure_basis','performance_lifecycle_basis','performance_reconciliation_basis','quality_event_basis','laundry_outstanding_basis'])
 if(![dates.from,dates.to,dates.as_of].every(financeDate)||dates.from>dates.to||dates.to>dates.as_of||basis.period_from!==dates.from||basis.period_to!==dates.to||basis.balance_sheet_as_of!==dates.as_of||basis.supplier_exposure_basis!=='CURRENT_OPERATIONAL_STATE'||basis.performance_lifecycle_basis!=='SIGNED_JOURNAL_LIFECYCLE_EVENTS_IN_POSTING_PERIOD'||basis.performance_reconciliation_basis!=='OPERATIONAL_NET_SALES_MINUS_SALES_REVENUE_GL'||basis.quality_event_basis!=='CURRENT_OPERATIONAL_STATE_WITH_EVENT_DATE_CUTOFF'||basis.laundry_outstanding_basis!=='IMMUTABLE_WIP_STAGE_EVENT_NET_AS_OF_BALANCE_DATE')fail()
 const position=closed(s.financial_position,positionFields);if(!Object.values(position).every(x=>decimal(x)))fail()
 const performance=closed(s.performance,[...performanceMoney,'gross_margin_pct','net_margin_pct','sales_revenue_reconciled']);if(!performanceMoney.every(k=>decimal(performance[k]))||![performance.gross_margin_pct,performance.net_margin_pct].every(x=>x===null||decimal(x,4))||typeof performance.sales_revenue_reconciled!=='boolean')fail()
 const quality=closed(s.quality,['qc_good_pcs','qc_bs_pcs','qc_defect_rate_pct','laundry_good_received_pcs','laundry_bs_pcs','laundry_bs_rate_on_resolved_receipts_pct','laundry_outstanding_pcs','legacy_receipt_stuck_pcs','legacy_receipt_missing_pcs']);for(const[k,x]of Object.entries(quality))if(k.endsWith('_pct')?x!==null&&!decimal(x,4):!whole(x))fail()
 const exposure=closed(s.supplier_exposure,['unfinalized_receipt_count','oldest_unfinalized_days','open_final_ap_document_count','overdue_final_ap_amount']);for(const[k,x]of Object.entries(exposure))if(k==='overdue_final_ap_amount'?!decimal(x):!whole(x))fail()
 const c=closed(s.data_confidence,['status','critical_issue_count','warning_issue_count','pending_cost_recalc_count','failed_checks','engine','as_of','window_from','closed_through','blockers','info','filing','changed_since_filing']);if(![c.critical_issue_count,c.warning_issue_count,c.pending_cost_recalc_count].every(whole)||c.engine!=='PERIOD_READINESS_V1'||c.as_of!==dates.as_of||!nullableDate(c.window_from)||!nullableDate(c.closed_through)||typeof c.changed_since_filing!=='boolean'||!Array.isArray(c.failed_checks))return fail()
 if(c.status!==(BigInt(String(c.critical_issue_count))>0n?'BLOCKED':BigInt(String(c.pending_cost_recalc_count))>0n?'RECALC_PENDING':'READY'))fail();blockers(c.blockers);blockers(c.info,true)
 for(const value of c.failed_checks){const x=closed(value,['check_name','severity','issue_count','details'],['family','scope','impact_date','reference']);if(!text(x.check_name)||!text(x.details)||!['WARNING','CRITICAL'].includes(String(x.severity))||!whole(x.issue_count)||!exactJson(x))fail()}
 const nativeBlockers=c.blockers as FinanceBlocker[],criticalChecks=c.failed_checks.reduce((sum,x)=>sum+(x.severity==='CRITICAL'?BigInt(x.issue_count):0n),0n)
 if(BigInt(String(c.critical_issue_count))!==criticalChecks||BigInt(String(c.critical_issue_count))<BigInt(nativeBlockers.filter(x=>x.severity==='CRITICAL'||x.severity==='POLICY').length)||BigInt(String(c.pending_cost_recalc_count))!==BigInt(nativeBlockers.filter(x=>x.severity==='RECALC').length))fail()
 if(c.filing!==null){const f=closed(c.filing,['filing_id','closed_through','previous_closed_through','filed_at','filed_status']);filingMeta(f,'filing_id');if(f.filed_status!=='READY')fail()}else if(c.changed_since_filing)fail()
 if(canPreflight){const p=readiness(r.close_preflight,['closed_through','date_allowed']);if(p.through!==dates.as_of||!nullableDate(p.closed_through)||typeof p.date_allowed!=='boolean')fail()}else if(r.close_preflight!==null)fail()
 const page=closed(r.filings,['rows','total','offset','limit','next_offset']);if(!Array.isArray(page.rows)||page.rows.length>25||!whole(page.total)||page.offset!==offset||page.limit!==25)return fail();const end=BigInt(offset+page.rows.length),total=BigInt(page.total);if(page.rows.length&&end>total||end<total&&(!page.rows.length||page.next_offset!==Number(end))||end>=total&&page.next_offset!==null)fail();const ids=new Set();for(const value of page.rows){const f=closed(value,['id','closed_through','previous_closed_through','filed_at','reason','filed_status']);filingMeta(f);if(ids.has(f.id)||!text(f.reason)||f.filed_status!=='READY')fail();ids.add(f.id)}
 if(filingId===null){if(r.filing!==null)fail()}else{const f=closed(r.filing,['id','closed_through','previous_closed_through','filed_at','reason','basis','readiness','gl_balances','source_hash']);filingMeta(f);if(f.id!==filingId||f.closed_through!==dates.as_of||!text(f.reason)||f.basis!=='IMMUTABLE_AS_FILED_GL_BALANCES'||!text(f.source_hash)||!/^[a-f0-9]{32}$/.test(f.source_hash)||!f.gl_balances||typeof f.gl_balances!=='object'||Array.isArray(f.gl_balances)||!Object.values(f.gl_balances).every(x=>decimal(x)))fail();const original=readiness(f.readiness,[],['booked_after_filed_period']);if(original.through!==f.closed_through||original.status!=='READY'||original.booked_after_filed_period!==undefined&&(!Array.isArray(original.booked_after_filed_period)||!original.booked_after_filed_period.every(uuid)))fail()}
 return r as unknown as FinanceReport
}
