import {useEffect,useMemo,useRef,useState} from 'react'
import {useAuth} from './auth/AuthProvider'
import {getUatSupabaseClient} from './lib/supabase'
import {normalizeClientError} from './lib/clientError'
import {formatReceiptDecimal} from './procurementContract'
import {formatCp6WibDateTime} from './cp6BusinessTime'
import {parseNativeModelEvaluation,readModelRequest,persistModelRequest,clearModelRequest,modelRequestKey,type NativeModelEvaluation,type NativeModelQuery} from './nativeModelEvaluation'
type Props={historyRunId:string;targetKey:string;onSourceReadStart:()=>void;onSourceReadEnd:()=>void;onClose:()=>void}
const reasons:Record<string,string>={INSUFFICIENT_CHRONOLOGICAL_HISTORY:'Riwayat belum cukup untuk tiga putaran pembanding dan satu periode uji terakhir.',REGISTRY_NOT_KNOWN_BEFORE_VALIDATION:'Aturan model baru tersedia setelah periode pembanding. Hasil lama belum dapat dipakai untuk membuktikan kemenangan model.',HISTORICAL_NATIVE_KNOWLEDGE_INSUFFICIENT:'Snapshot ERP yang sudah diketahui pada waktu keputusan belum cukup. Data yang baru dibaca sekarang tidak dianggap sudah diketahui dulu.',BASELINE_RETAINED_BY_PAIRED_PROMOTION_GUARDS:'Model pembanding belum melewati syarat perbaikan kesalahan, bias, dan kesalahan seluruh periode.',COMPLETE_VALIDATION_RECOMMENDATION_REQUIRES_REVIEW:'Model pembanding memenuhi syarat teknis. Rekomendasi ini masih perlu ditinjau.'}
const names:Record<string,string>={'mean-1':'Rata-rata','naive-1':'Nilai terakhir','moving-mean-7-1':'Rata-rata 7 hari','ses-half-1':'Pemulusan sederhana','holt-damped-1':'Tren teredam','seasonal-7-1':'Pola 7 hari','sba-half-1':'Permintaan jarang · SBA','tsb-half-1':'Permintaan jarang · TSB'}
export default function NativeModelEvaluationPanel(props:Props){const{runtime,identity}=useAuth();if(runtime.mode!=='DISPOSABLE_TEST'||identity.status!=='AUTHORIZED'||!['master.product.view','production.wip.view','warehouse.stock.view','sales.invoice.view'].every(p=>identity.permissions.includes(p)))return null;return<Workspace {...props} key={`${runtime.projectRef}:${identity.profile.id}:${identity.profile.rowVersion}:${identity.profile.roleRowVersion}:${identity.permissions.join('|')}`}/>}
function Workspace({historyRunId,targetKey,onSourceReadStart,onSourceReadEnd,onClose}:Props){
 const{runtime,identity}=useAuth();if(runtime.mode!=='DISPOSABLE_TEST'||identity.status!=='AUTHORIZED')throw Error('Sesi evaluasi belum siap.')
 const client=useMemo(()=>getUatSupabaseClient(runtime),[runtime]),scope=runtime.projectRef+':'+identity.profile.id,actor=identity.profile.authUserId,sequence=useRef(0),active=useRef(false)
 const[recovery,setRecovery]=useState(()=>readModelRequest(scope)),[horizon,setHorizon]=useState(recovery.pending?.q.horizon_days??''),[data,setData]=useState<NativeModelEvaluation|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState('')
 const begin=()=>{const n=++sequence.current;active.current=true;setData(null);setError('');setBusy(true);onSourceReadStart();return n}
 const end=(n:number)=>{if(n===sequence.current){active.current=false;setBusy(false);onSourceReadEnd()}}
 useEffect(()=>()=>{++sequence.current;if(active.current){active.current=false;onSourceReadEnd()}},[onSourceReadEnd])
 useEffect(()=>{const listener=(e:StorageEvent)=>{if(e.key===null||e.key===modelRequestKey(scope)){++sequence.current;const wasActive=active.current;active.current=false;setData(null);setBusy(false);setRecovery(readModelRequest(scope));if(!wasActive)onSourceReadStart();onSourceReadEnd()}};addEventListener('storage',listener);return()=>removeEventListener('storage',listener)},[scope,onSourceReadStart,onSourceReadEnd])
 useEffect(()=>{++sequence.current;setData(null);setError('');if(active.current){active.current=false;setBusy(false);onSourceReadEnd()}},[historyRunId,targetKey,onSourceReadEnd])
 const load=async(retry=false)=>{const n=begin();try{
  const held=readModelRequest(scope);if(held.error)throw Error(held.error);if(retry&&!held.pending)throw Error('Permintaan evaluasi tersimpan tidak tersedia.');if(!retry&&held.pending)throw Error('Ulangi evaluasi tersimpan terlebih dahulu.')
  const q:NativeModelQuery={history_run_id:historyRunId,target_key:targetKey,horizon_days:horizon},r=retry?held.pending!:{id:crypto.randomUUID(),q};if(!retry)persistModelRequest(scope,r);setRecovery(readModelRequest(scope))
  const reply=await client.rpc('erp_cp7_capture_model_evaluation_v1',{p_query:r.q,p_request:r.id});if(n!==sequence.current)return;if(reply.error)throw reply.error
  const result=parseNativeModelEvaluation(reply.data,r.q,actor);if(result.requestId!==r.id)throw Error('Permintaan evaluasi server berubah.');clearModelRequest(scope,r.id);setRecovery(readModelRequest(scope));setData(result)
 }catch(e){if(n===sequence.current)setError(normalizeClientError(e).message)}finally{end(n)}}
 const check=async()=>{if(!data)return;const old=data,n=begin();try{const reply=await client.rpc('erp_cp7_read_model_evaluation_v1',{p_run:old.runId});if(n!==sequence.current)return;if(reply.error)throw reply.error;const result=parseNativeModelEvaluation(reply.data,{history_run_id:old.historyRunId,target_key:old.targetKey,horizon_days:String(old.horizon)},actor);if(result.runId!==old.runId||result.requestId!==old.requestId||result.sourceHash!==old.sourceHash||result.selected!==old.selected)throw Error('Arsip evaluasi server berubah.');setData(result)}catch(e){if(n===sequence.current)setError(normalizeClientError(e).message)}finally{end(n)}}
 const blocked=busy||Boolean(recovery.pending||recovery.error),number=(x:string|null)=>x===null?'Belum diketahui':formatReceiptDecimal(x)
 return<section className="native-analysis panel" aria-label="Evaluasi ramalan ERP"><header><div><h2>Bandingkan ramalan</h2><p>Model dibandingkan memakai snapshot yang sudah diketahui pada waktu keputusan. Riwayat stok habis dan data belum diketahui tidak dianggap nol.</p></div><button disabled={busy} onClick={onClose}>Tutup evaluasi ramalan</button></header>
  <form onSubmit={e=>{e.preventDefault();void load()}}><label>Jumlah hari ramalan<input aria-label="Jumlah hari ramalan" type="number" min="1" max="90" step="1" value={horizon} required disabled={blocked} onChange={e=>{setData(null);setHorizon(e.target.value)}}/></label><button disabled={blocked||!/^([1-9]|[1-8][0-9]|90)$/.test(horizon)}>Bandingkan model ERP</button></form>
  {busy?<p role="status">Memeriksa histori, model, dan izin ERP…</p>:null}{error||recovery.error?<p role="alert">{error||recovery.error}</p>:null}{recovery.pending?<div role="status"><p>Hasil evaluasi sebelumnya belum dipastikan. Permintaan yang sama dipertahankan.</p><button disabled={busy} onClick={()=>void load(true)}>Ulangi evaluasi yang sama</button></div>:null}
  {data?<div className="native-model-result"><h3>{data.sku} · {data.name}</h3><p>{data.state==='UNCHANGED'?'Sumber sesuai saat diperiksa.':'Arsip evaluasi: sumber sudah berubah.'} Riwayat {data.from} sampai {data.through}; diketahui {formatCp6WibDateTime(data.knownAt)}.</p><p>{reasons[data.reason]??'Bukti model belum lengkap; periksa sumber ERP.'}</p><p>Model terpilih: {names[data.selected]}. Rata-rata dasar pada hari tersedia: {number(data.mean)} PCS/hari.</p><p>Aturan teknis tersedia sejak {formatCp6WibDateTime(data.registryAt)}. Periode uji terakhir ditampilkan terpisah dan tidak memilih model.</p><button disabled={busy} onClick={()=>void check()}>Periksa arsip evaluasi</button>
   {data.scores.length?<div className="responsive-table"><table><thead><tr><th>Model</th><th>Putaran lengkap</th><th>Kesalahan rata-rata</th><th>Bias</th><th>Kesalahan periode</th><th>Uji terakhir</th></tr></thead><tbody>{data.scores.map(s=><tr key={s.id}><td>{names[s.id]}</td><td data-label="Putaran lengkap">{s.complete}/{s.requested}</td><td data-label="Kesalahan rata-rata">{number(s.mae)}</td><td data-label="Bias">{number(s.bias)}</td><td data-label="Kesalahan periode">{number(s.tail)}</td><td data-label="Uji terakhir">{number(s.holdoutMae)}</td></tr>)}</tbody></table></div>:null}
   <p>{data.forecasts?`Ramalan ${data.horizon} hari: ${data.forecasts.map(x=>formatReceiptDecimal(x)).join('; ')} PCS.`:'Ramalan baru belum terbukti oleh histori yang lengkap.'}</p><p>Evaluasi ini tidak mengubah target, menyimpan pesanan, atau menerapkan produksi.</p>
  </div>:null}
 </section>
}
