// @vitest-environment jsdom
import {act,useRef,useState} from 'react'
import {createRoot,type Root} from 'react-dom/client'
import {beforeEach,afterEach,it,expect,vi} from 'vitest'
import NativeReminderPolicyPanel from './NativeReminderPolicyPanel'
import {parseNativeAnalysis,type NativeAnalysis} from './nativeAnalysis'
import {readReminderPolicyRequest,type ReminderPolicyRequest} from './nativeReminderPolicy'
import {reminderPolicyFixture,reminderPolicyRow} from '../tests/fixtures/nativeReminderPolicy'
import original from '../tests/fixtures/nativeAnalysisStandin.json'
import {recoveryIdentity} from '../tests/fixtures/productionRecovery'
import type {NativeDemandQuery} from './nativeDemandHistory'
const state=vi.hoisted(()=>({auth:null as unknown}))
const client=vi.hoisted(()=>({rpc:vi.fn()}))
vi.mock('./auth/AuthProvider',()=>({useAuth:()=>state.auth}));vi.mock('./lib/supabase',()=>({getUatSupabaseClient:()=>client}))
const q=original.query as NativeDemandQuery,access={ownerReports:false,preflight:false},actor=original.analysis.scope.actor_scope_id,scope='analysis:cp6-disposable:actor-1'
let container:HTMLDivElement,root:Root
function Host(){const seq=useRef(0),[generation,setGeneration]=useState(0),[context,setContext]=useState<NativeAnalysis|null>(()=>parseNativeAnalysis(original,q,actor,access));return <NativeReminderPolicyPanel context={context} generation={generation} blocked={false} access={access} onReadStart={()=>{const n=++seq.current;setGeneration(n);setContext(null);return n}} isReadCurrent={n=>seq.current===n} onReadEnd={()=>{}} onAnalysis={(a,n)=>{if(seq.current===n)setContext(a)}} requireClear={()=>{}}/>}
beforeEach(()=>{Object.assign(globalThis,{IS_REACT_ACT_ENVIRONMENT:true});localStorage.clear();client.rpc.mockReset();const a=structuredClone(recoveryIdentity);Object.assign(a.runtime,{mode:'DISPOSABLE_TEST',projectRef:'cp6-disposable'});Object.assign(a.identity.profile,{authUserId:actor});a.identity.permissions.push('master.product.view','production.wip.view','warehouse.stock.view','sales.invoice.view');state.auth=a;Object.defineProperty(navigator,'locks',{configurable:true,value:{request:async(_n:string,_o:unknown,fn:(lock:object)=>unknown)=>fn({})}});container=document.createElement('div');document.body.append(container);root=createRoot(container)})
afterEach(async()=>{await act(async()=>root.unmount());container.remove();localStorage.clear();vi.restoreAllMocks()})
const render=async()=>act(async()=>root.render(<Host/>))
async function click(label:string){const b=[...container.querySelectorAll('button')].find(b=>b.textContent===label)!;expect(b).toBeTruthy();await act(async()=>b.click())}
async function fill(label:string,value:string){const f=container.querySelector<HTMLInputElement|HTMLTextAreaElement|HTMLSelectElement>(`[aria-label="${label}"]`)!;await act(async()=>{const proto=f instanceof HTMLSelectElement?HTMLSelectElement.prototype:f instanceof HTMLTextAreaElement?HTMLTextAreaElement.prototype:HTMLInputElement.prototype;Object.getOwnPropertyDescriptor(proto,'value')!.set!.call(f,value);f.dispatchEvent(new Event(f instanceof HTMLSelectElement?'change':'input',{bubbles:true}))})}
const review=async()=>act(async()=>container.querySelector<HTMLInputElement>('[aria-label="Pengaturan pengingat sudah ditinjau"]')!.click())
it('performs no automatic read and sends blank fields as null only after explicit review',async()=>{client.rpc.mockImplementation(async(name:string,args:{p_request:string})=>{if(name==='erp_cp7_get_reminder_policy_v1')return{data:reminderPolicyFixture(),error:null};const r=readReminderPolicyRequest(scope).pending!;expect(r.id).toBe(args.p_request);expect(r.payload.config).toMatchObject({enabled:null,threshold_value:null,cooldown_minutes:null,quiet:{enabled:null}});return{data:reminderPolicyFixture(original,[reminderPolicyRow(r)],r),error:null}});await render();expect(client.rpc).not.toHaveBeenCalled();await click('Muat pengaturan pengingat');expect(container.querySelector<HTMLInputElement>('[aria-label="Batas pengingat"]')?.value).toBe('');await fill('Alasan perubahan pengingat','Belum ada keputusan nilai');await review();await click('Simpan versi pengaturan pengingat');expect(readReminderPolicyRequest(scope).pending).toBeNull();expect(container.textContent).toContain('Status: belum diatur')})
it('retains an exact committed intent after lost response and recovers it after remount without another version',async()=>{let held:ReminderPolicyRequest|null=null;client.rpc.mockImplementation(async(name:string)=>{if(name==='erp_cp7_get_reminder_policy_v1')return{data:reminderPolicyFixture(),error:null};const r=readReminderPolicyRequest(scope).pending!;if(name==='erp_cp7_save_reminder_policy_v1'){held=r;throw Error('Lost committed reply')}return{data:reminderPolicyFixture(original,[reminderPolicyRow(r)],r),error:null}});await render();await click('Muat pengaturan pengingat');await fill('Status aturan','false');await fill('Batas pengingat','0');await fill('Jeda pengingat dalam menit','0');await fill('Waktu tenang','false');await fill('Alasan perubahan pengingat','Dimatikan oleh pemilik');await review();await click('Simpan versi pengaturan pengingat');expect(held).toBeTruthy();expect(readReminderPolicyRequest(scope).pending).toEqual(held);await act(async()=>root.unmount());root=createRoot(container);await render();await click('Pastikan hasil pengaturan di server');expect(client.rpc.mock.calls.at(-1)![1]).toEqual(client.rpc.mock.calls[1][1]);expect(readReminderPolicyRequest(scope).pending).toBeNull();expect(container.textContent).toContain('Status: dimatikan');expect(container.querySelector<HTMLSelectElement>('[aria-label="Status aturan"]')?.value).toBe('')})
it('retires saved facts during a held read and current403 while keeping unsent operator values',async()=>{client.rpc.mockResolvedValue({data:reminderPolicyFixture(),error:null});await render();await click('Muat pengaturan pengingat');await fill('Batas pengingat','15');await fill('Alasan perubahan pengingat','Isian belum disimpan');let finish!:(v:unknown)=>void;client.rpc.mockImplementation(()=>new Promise(resolve=>{finish=resolve}));await click('Muat pengaturan pengingat');expect(container.textContent).not.toContain('Pengaturan diperiksa');await act(async()=>finish({data:null,error:{code:'42501',message:'Current access denied'}}));expect(container.textContent).not.toContain('Pengaturan diperiksa');expect(client.rpc).toHaveBeenCalledTimes(2)})
