import {useEffect,useMemo,useRef,useState} from 'react'
import {useAuth} from './auth/AuthProvider'
import {getUatSupabaseClient} from './lib/supabase'
import {normalizeClientError} from './lib/clientError'
import {formatCp6WibDateTime} from './cp6BusinessTime'
import {assertSameAnalysis,type NativeAnalysis,type AnalysisFinanceAccess} from './nativeAnalysis'
import {productionLockManager,productionLockName,readProductionRecovery,hasProductionPending} from './productionRecovery'
import {formatFact} from './cp7/workspace'
import {reminderRuleIds,reminderRuleLabels,type ReminderRule} from './nativeReminderPolicy'
import {parseRuleSource,parseRuleObservations,parseLocalWorkspace,parseLocalCommand,readRuleRequest,persistRuleRequest,clearRuleRequest,ruleRequestKey,ruleConditionLabels,ruleEligibilityLabels,localClaimLabels,type RuleSource,type RuleObservationResult,type RuleRequest,type LocalWorkspace,type LocalClaim} from './nativeRuleSource'

type Props={context:NativeAnalysis|null;generation:number;blocked:boolean;access:AnalysisFinanceAccess;onReadStart:()=>number;isReadCurrent:(n:number)=>boolean;onReadEnd:(n:number)=>void;onAnalysis:(a:NativeAnalysis,n:number)=>void;requireClear:()=>void}
type Facts={generation:number;source:RuleSource|null;observations:RuleObservationResult|null;local:LocalWorkspace|null}
const emptyFacts:Facts={generation:-1,source:null,observations:null,local:null}
export default function NativeRuleSourcePanel(props:Props){
 const{runtime,identity}=useAuth()
 if(runtime.mode!=='DISPOSABLE_TEST'||identity.status!=='AUTHORIZED'||!['OWNER','ADMIN','STAFF'].includes(identity.profile.role)||!['master.product.view','production.wip.view','warehouse.stock.view','sales.invoice.view'].every(p=>identity.permissions.includes(p)))return null
 return <Conditions {...props} projectRef={runtime.projectRef} profileId={identity.profile.id} actor={identity.profile.authUserId} manage={['OWNER','ADMIN'].includes(identity.profile.role)&&identity.permissions.includes('master.product.manage')} ar={identity.permissions.includes('finance.ar.view')} ap={identity.permissions.includes('finance.ap.view')}/>
}
function Conditions(props:Props&{projectRef:string;profileId:string;actor:string;manage:boolean;ar:boolean;ap:boolean}){
 const{runtime}=useAuth();if(runtime.mode!=='DISPOSABLE_TEST')throw Error('Sesi pemeriksaan kondisi belum siap.')
 const client=useMemo(()=>getUatSupabaseClient(runtime),[runtime]),scope='analysis:'+props.projectRef+':'+props.profileId,productionScope='erp:'+props.projectRef+':'+props.profileId,rights={ar:props.ar,ap:props.ap}
 const mounted=useRef(true),active=useRef<number|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState(''),[facts,setFacts]=useState<Facts>(emptyFacts),[recovery,setRecovery]=useState(()=>readRuleRequest(scope))
 const[label,setLabel]=useState(''),[enabled,setEnabled]=useState(''),[selectedRules,setSelectedRules]=useState<ReminderRule[]>([]),[bindingReason,setBindingReason]=useState(''),[reviewed,setReviewed]=useState(false),[selectedKey,setSelectedKey]=useState(''),[resolutionReason,setResolutionReason]=useState(''),[resolutionOutcome,setResolutionOutcome]=useState(''),[resolutionReviewed,setResolutionReviewed]=useState(false),[page,setPage]=useState(0)
 useEffect(()=>{mounted.current=true;return()=>{mounted.current=false}},[])
 useEffect(()=>{const listener=(e:StorageEvent)=>{if(e.key===null||e.key===ruleRequestKey(scope)){setRecovery(readRuleRequest(scope));setFacts(emptyFacts);setReviewed(false);setResolutionReviewed(false)}};addEventListener('storage',listener);return()=>removeEventListener('storage',listener)},[scope])
 const current=(n:number)=>mounted.current&&props.isReadCurrent(n),data=facts.generation===props.generation?facts:null,source=data?.source,blocked=props.blocked||busy||Boolean(recovery.error||recovery.pending),eligible=source?.rows.filter(r=>r.eligibility==='LOCAL_PREVIEW_ELIGIBLE')??[],binding=data?.local?.binding
 const perform=async(fn:(n:number)=>Promise<void>)=>{if(active.current!==null)return;const n=props.onReadStart();active.current=n;setBusy(true);setFacts(emptyFacts);setReviewed(false);setResolutionReviewed(false);setError('');setMessage('');try{await fn(n)}catch(e){if(current(n))setError(normalizeClientError(e).message)}finally{if(mounted.current){setBusy(false);setRecovery(readRuleRequest(scope))}if(active.current===n)active.current=null;props.onReadEnd(n)}}
 const load=(local=false)=>{const original=props.context;void perform(async n=>{props.requireClear();if(!original)throw Error('Muat analisis ERP terlebih dahulu.');const r=local?await client.rpc('erp_cp7_get_local_reminders_v1',{p_run:original.runId}):await client.rpc('erp_cp7_get_rule_conditions_v1',{p_run:original.runId});if(!current(n))return;if(r.error)throw r.error;const workspace=local?await parseLocalWorkspace(r.data,original.query,props.actor,props.access,rights):null,source=workspace?.source??parseRuleSource(r.data,original.query,props.actor,props.access,rights);if(!current(n))return;assertSameAnalysis(original,source.analysis);setFacts({generation:n,source,observations:null,local:workspace});setPage(0);props.onAnalysis(source.analysis,n)})}
 const send=(request:RuleRequest,lookup=false)=>void perform(async n=>{
  props.requireClear();const manager=productionLockManager();if(!manager)throw Error('Pencatatan pemeriksaan membutuhkan pengunci tab. Sumber masih dapat dibaca.')
  await manager.request(productionLockName(productionScope),{mode:'exclusive',ifAvailable:true},async lock=>{
   if(!lock)throw Error('Ada transaksi ERP di tab lain. Tunggu selesai.');if(!current(n))return;const shared=readProductionRecovery(productionScope);if(shared.corrupted||!lookup&&hasProductionPending(shared))throw Error('Pastikan hasil transaksi ERP yang tertunda terlebih dahulu.')
   persistRuleRequest(scope,request);setRecovery(readRuleRequest(scope));const args={p_payload:request.payload,p_request:request.id}
   const r=request.operation==='EPISODES'?(lookup?await client.rpc('erp_cp7_get_rule_episode_request_v1',args):await client.rpc('erp_cp7_evaluate_rule_episodes_v1',args)):lookup?await client.rpc('erp_cp7_get_local_reminder_request_v1',{...args,p_operation:request.operation}):request.operation==='BINDING'?await client.rpc('erp_cp7_save_local_binding_v1',args):request.operation==='PREVIEW'?await client.rpc('erp_cp7_claim_local_preview_v1',args):request.operation==='OUTCOME'?await client.rpc('erp_cp7_finish_local_preview_v1',args):await client.rpc('erp_cp7_resolve_local_preview_v1',args)
   if(!current(n))return;if(r.error)throw r.error
   const observations=request.operation==='EPISODES'?parseRuleObservations(r.data,request,props.actor,props.access,rights):null,command=observations?null:await parseLocalCommand(r.data,request,props.actor,props.access,rights),source=observations?.source??command!.workspace.source
   if(!current(n))return;clearRuleRequest(scope,request.id);setRecovery(readRuleRequest(scope));setFacts({generation:n,source,observations,local:command?.workspace??null});props.onAnalysis(source.analysis,n);setMessage((observations?.status??command?.status)==='COMMITTED'?'Catatan tersimpan. Status bisnis tetap mengikuti sumber ERP.':'Permintaan lama belum tersimpan dan sudah ditutup. Periksa sumber sebelum mencoba lagi.')
  })
 })
 const action=(operation:RuleRequest['operation'],payload:RuleRequest['payload'])=>{try{props.requireClear();const held=readRuleRequest(scope);if(held.error||held.pending)throw Error(held.error??'Pastikan hasil permintaan lokal yang tertunda.');if(!props.context||!source)throw Error('Periksa sumber terlebih dahulu.');send({id:crypto.randomUUID(),query:props.context.query,operation,payload:{run_id:props.context.runId,...payload}})}catch(e){setError(normalizeClientError(e).message)}}
 const retry=(lookup:boolean)=>{try{const held=readRuleRequest(scope);setRecovery(held);if(!held.pending)throw Error(held.error??'Permintaan lokal tidak tersedia.');send(held.pending,lookup)}catch(e){setError(normalizeClientError(e).message)}}
 const saveBinding=()=>{if(!reviewed||!['true','false'].includes(enabled)||!label.trim()||!bindingReason.trim()||!selectedRules.length)return;action('BINDING',{expected_revision:binding?.revision??'0',enabled:enabled==='true',label,environment:'LOCAL_TEST_SINK',rules:selectedRules,reason:bindingReason})}
 const finish=(claim:LocalClaim,outcome:'LOCAL_CAPTURE'|'UNKNOWN')=>action('OUTCOME',{claim_id:claim.id,fence:claim.fence,outcome})
 const resolve=(claim:LocalClaim)=>{if(!resolutionReviewed||!resolutionReason.trim()||!['CAPTURE_CONFIRMED','NOT_CAPTURED_CONFIRMED'].includes(resolutionOutcome))return;action('RESOLUTION',{claim_id:claim.id,fence:claim.fence,outcome:resolutionOutcome,reason:resolutionReason})}
 return <section aria-label="Kondisi masalah dan pratinjau lokal"><h3>Kondisi yang perlu ditangani</h3><p>Sudah dibaca, selesai ditinjau, dan hasil pesan adalah catatan terpisah. Masalah selesai hanya ketika sumber ERP membuktikannya.</p>
  <button disabled={blocked||!props.context}onClick={()=>load()}>Periksa kondisi masalah ERP</button>{props.manage?<button disabled={blocked||!props.context}onClick={()=>load(true)}>Muat pratinjau lokal tersimpan</button>:null}
  {error?<p role="alert">{error}</p>:null}{recovery.error?<p role="alert">{recovery.error}</p>:null}{message?<p role="status">{message}</p>:null}
  {recovery.pending?<aside><p>Hasil pencatatan belum diketahui. Permintaan yang sama dipertahankan.</p><button disabled={props.blocked||busy}onClick={()=>retry(false)}>Ulangi permintaan kondisi yang sama</button><button disabled={props.blocked||busy}onClick={()=>retry(true)}>Pastikan hasil kondisi di server</button></aside>:null}
  {source?<><p>Kondisi diperiksa {formatCp6WibDateTime(source.readAt)} · {source.rows.length} kondisi.</p><p>Piutang awal, utang awal, gaji, aksesori dan laundry belum tercakup dalam daftar ini.</p><button disabled={blocked}onClick={()=>action('EPISODES',{source_hash:source.hash})}>Catat pemeriksaan kondisi ERP</button>
   {source.rows.slice(page*25,(page+1)*25).map(r=><article key={r.key}aria-label={`Kondisi ${r.key}`}><h4>{reminderRuleLabels[r.rule_id]} · {r.label}</h4><p>{ruleConditionLabels[r.state]}. {formatFact(r.value)}</p><p>{ruleEligibilityLabels[r.eligibility]}. {r.policy_timing.next_at?'Dapat diperiksa lagi '+formatCp6WibDateTime(r.policy_timing.next_at)+'.':''}</p><p>{r.business_resolved?'Sumber membuktikan selesai.':'Belum ada bukti sumber bahwa masalah ini selesai.'}</p>{r.production_state==='PAUSED'||r.production_state==='STOPPED'?<p>Produksi ditunda atau dihentikan; kebutuhan tercatat tetap dipertahankan.</p>:null}<details><summary>Dasar pemeriksaan kondisi</summary><p>{r.reason} · {r.source_hash}</p><p>{r.policy_binding.policy?'Mengikuti versi aturan '+r.policy_binding.policy.revision+'.':'Aturan belum diatur.'}</p></details></article>)}
   <nav aria-label="Halaman kondisi masalah"><button disabled={blocked||page===0}onClick={()=>setPage(p=>p-1)}>Kondisi sebelumnya</button><span>Halaman {page+1} dari {Math.max(1,Math.ceil(source.rows.length/25))}</span><button disabled={blocked||(page+1)*25>=source.rows.length}onClick={()=>setPage(p=>p+1)}>Kondisi berikutnya</button></nav>
   {data?.observations?<section aria-label="Catatan pemeriksaan kondisi"><h4>Catatan pemeriksaan kondisi</h4>{data.observations.freshness==='HISTORICAL_SOURCE_CHANGED'?<p>Catatan ini memakai sumber sebelumnya. Sumber terkini ditampilkan pada daftar kondisi.</p>:null}{data.observations.rows.filter(r=>r.episode).map(r=><p key={r.condition.key}>{r.condition.label} · kejadian {r.episode!.number} · {r.episode!.state==='RESOLVED'?'sumber membuktikan selesai':'masih terbuka'} · pertama dicatat {formatCp6WibDateTime(r.episode!.first_observed_at)}. {r.episode!.freshness==='UNKNOWN'?'Data kini belum pasti; umur masalah tetap dipertahankan.':''}</p>)}</section>:null}
  </>:null}
  {props.manage?<><h4>Pratinjau lokal</h4><p>Pratinjau ini dicatat di aplikasi uji. Belum ada penerima, pengiriman keluar, atau penjadwalan otomatis.</p>
   {data?.local?<><p>{binding?'Tujuan lokal: '+binding.label+' · versi '+binding.revision+' · '+(binding.enabled?'aktif':'dimatikan')+'.':'Belum ada tujuan pratinjau lokal.'}</p><fieldset disabled={blocked}><legend>Tujuan pratinjau yang ditinjau</legend><label>Nama tujuan lokal<input aria-label="Nama tujuan lokal"maxLength={120}value={label}onChange={e=>{setLabel(e.target.value);setReviewed(false)}}/></label><label>Status tujuan lokal<select aria-label="Status tujuan lokal"value={enabled}onChange={e=>{setEnabled(e.target.value);setReviewed(false)}}><option value="">Pilih status</option><option value="true">Aktif</option><option value="false">Dimatikan</option></select></label>
    {reminderRuleIds.filter(r=>r==='AR_DUE'?props.ar:r==='AP_DUE'?props.ap:true).map(r=><label key={r}><input aria-label={`Tujuan lokal ${reminderRuleLabels[r]}`}type="checkbox"checked={selectedRules.includes(r)}onChange={e=>{setSelectedRules(s=>e.target.checked?[...s,r]:s.filter(x=>x!==r));setReviewed(false)}}/>{reminderRuleLabels[r]}</label>)}
    <label>Alasan tujuan lokal<textarea aria-label="Alasan tujuan lokal"maxLength={1000}value={bindingReason}onChange={e=>{setBindingReason(e.target.value);setReviewed(false)}}/></label><label><input aria-label="Tujuan lokal sudah ditinjau"type="checkbox"checked={reviewed}onChange={e=>setReviewed(e.target.checked)}/>Tujuan dan aturan sudah saya tinjau.</label><button disabled={!reviewed||!enabled||!label.trim()||!bindingReason.trim()||!selectedRules.length}onClick={saveBinding}>Simpan versi tujuan lokal</button></fieldset>
    <label>Kondisi untuk pratinjau<select aria-label="Kondisi untuk pratinjau"value={selectedKey}disabled={blocked}onChange={e=>setSelectedKey(e.target.value)}><option value="">Pilih kondisi yang sudah diperiksa</option>{eligible.map(r=><option key={r.key}value={r.key}>{reminderRuleLabels[r.rule_id]} · {r.label}</option>)}</select></label><button disabled={blocked||!binding?.enabled||!eligible.some(r=>r.key===selectedKey&&binding.rules.includes(r.rule_id))}onClick={()=>action('PREVIEW',{condition_key:selectedKey,source_hash:source!.hash,binding_id:binding!.id})}>Buat pratinjau lokal</button>
    {data.local.claims.map(c=><article key={c.id}aria-label={`Pratinjau lokal ${c.id}`}><h5>{source!.rows.find(r=>r.key===c.condition_key)?.label}</h5><p>{localClaimLabels[c.status]}. Pesan belum dikirim keluar.</p>{c.body?<pre aria-label="Isi pratinjau lokal">{c.body}</pre>:<p>Isi sumber lama tidak ditampilkan sebagai pratinjau terkini.</p>}{c.status==='CLAIMED'?<><button disabled={blocked}onClick={()=>finish(c,'LOCAL_CAPTURE')}>Catat hasil pratinjau lokal</button><button disabled={blocked}onClick={()=>finish(c,'UNKNOWN')}>Hasil pratinjau belum pasti</button></>:null}{c.status==='UNKNOWN'&&!c.resolution?<fieldset disabled={blocked}><legend>Pastikan hasil lokal secara manual</legend><p>Permintaan baru ditahan sampai hasil ini dipastikan. Catatan lama tetap utuh.</p><label>Hasil pemeriksaan manual<select aria-label="Hasil pemeriksaan manual"value={resolutionOutcome}onChange={e=>{setResolutionOutcome(e.target.value);setResolutionReviewed(false)}}><option value="">Pilih hasil yang sudah diperiksa</option><option value="CAPTURE_CONFIRMED">Pratinjau sudah tercatat</option><option value="NOT_CAPTURED_CONFIRMED">Pratinjau belum tercatat</option></select></label><label>Alasan pemeriksaan manual<textarea aria-label="Alasan pemeriksaan manual"maxLength={1000}value={resolutionReason}onChange={e=>{setResolutionReason(e.target.value);setResolutionReviewed(false)}}/></label><label><input aria-label="Hasil lokal sudah diperiksa"type="checkbox"checked={resolutionReviewed}onChange={e=>setResolutionReviewed(e.target.checked)}/>Saya sudah memeriksa hasil lokal dan alasannya.</label><button disabled={!resolutionReviewed||!resolutionOutcome||!resolutionReason.trim()}onClick={()=>resolve(c)}>Simpan kepastian hasil lokal</button></fieldset>:null}{c.resolution?<p>Hasil dipastikan secara manual: {c.resolution.outcome==='CAPTURE_CONFIRMED'?'sudah tercatat':'belum tercatat'}. Alasan: {c.resolution.reason}. Kejadian lama tetap {localClaimLabels[c.status].toLowerCase()}.</p>:null}</article>)}
   </>:null}
  </>:null}
 </section>
}
