// @vitest-environment jsdom
import {it,expect,beforeEach} from 'vitest'
import {parsePlanOptions,planPayload,parsePlanSaved,parsePlanPreview,validatePlanCommit,readPlanPointer,rememberPlanPointer,planPointerKey} from './nativePlanDraft'
import * as f from '../tests/fixtures/nativePlan'
const form={orderId:f.order,patternId:f.pattern,locationId:f.location,cutAt:'2026-10-01T08:00',notes:'Own note',reason:'Reviewed Native draft only',reviewed:true,rolls:[{id:f.roll,issued:'1',consumed:'0.5',remaining:'0.5',pcs:'60'}]}
it('preserves need100 capacity60 selected60 as distinct server values; without a yield the unresolved gap is unknown, never 100% yield',()=>{const o=parsePlanOptions(f.options(),f.actor,f.context),s=parsePlanSaved(f.saved(),f.actor,f.draft),p=parsePlanPreview(f.preview(),f.actor,s);expect([o.needed,o.capacity,p.selected,p.unresolved,p.expectedGood,p.yield.basis,p.cutLimit]).toEqual(['100','60','60',null,null,'UNKNOWN','100'])
 // The old 100%-yield arithmetic is refused under an unknown yield.
 for(const mutate of [(x:ReturnType<typeof f.preview>)=>{x.unresolved_pcs='40'},(x:ReturnType<typeof f.preview>)=>{x.expected_good_pcs='60'},(x:ReturnType<typeof f.preview>)=>{x.cut_limit_pcs='101'}]){const x=f.preview();mutate(x);expect(()=>parsePlanPreview(x,f.actor,s)).toThrow()}})
it('PL-5 A: a reviewed planner estimate 9/10 caps the cut at 112 for need 100 and states the good pieces',()=>{const s=parsePlanSaved(f.saved(),f.actor,f.draft),x=f.preview();Object.assign(x,{new_start_yield:{...x.new_start_yield,basis:'PLAN_ESTIMATE_REVIEWED',numerator:'9',denominator:'10',assumption_id:'PLAN_NEW_START_YIELD'},cut_limit_pcs:'112',cut_limit_basis:'NEED_AT_STATED_YIELD',expected_good_pcs:'54',unresolved_pcs:'46',rounding_extra_pcs:'0'})
 const p=parsePlanPreview(x,f.actor,s);expect([p.yield.basis,p.cutLimit,p.expectedGood,p.unresolved]).toEqual(['PLAN_ESTIMATE_REVIEWED','112','54','46'])
 for(const mutate of [(z:typeof x)=>{z.cut_limit_pcs='111'},(z:typeof x)=>{z.expected_good_pcs='60'},(z:typeof x)=>{z.unresolved_pcs='40'},(z:typeof x)=>{z.new_start_yield.assumption_id=null},(z:typeof x)=>{z.new_start_yield.numerator='11'},(z:typeof x)=>{z.new_start_yield.basis='HISTORY_NATIVE'}]){const z=structuredClone(x);mutate(z);expect(()=>parsePlanPreview(z,f.actor,s)).toThrow()}
 const y=structuredClone(x);Object.assign(y,{selected_new_pcs:'112',expected_good_pcs:'100',unresolved_pcs:'0',rounding_extra_pcs:'0',free_capacity_pcs:'120'});expect(parsePlanPreview(y,f.actor,s).unresolved).toBe('0')
 const over=structuredClone(y);over.selected_new_pcs='113';Object.assign(over,{expected_good_pcs:'101',rounding_extra_pcs:'1'});expect(()=>parsePlanPreview(over,f.actor,s)).toThrow()})
it('keeps physical stock10 and linked draft6 separate from future-plan remainder4 without reserving stock',()=>{
 const o=f.options();Object.assign(o.rolls[0],{available:'10',linked_native_draft_qty:'6',free_for_new_plan:'4'})
 const p=parsePlanOptions(o,f.actor,f.context);expect([p.rolls[0].available,p.rolls[0].planned,p.rolls[0].free]).toEqual(['10','6','4'])
 const v=f.preview();Object.assign(v.material_rows[0],{native_available:'10',linked_native_draft_qty:'6',free_for_new_plan:'4'})
 const r=parsePlanPreview(v,f.actor,parsePlanSaved(f.saved(),f.actor,f.draft));expect([r.materials[0].available,r.materials[0].planned,r.materials[0].free]).toEqual(['10','6','4'])
})
it('rejects missing or contradictory pool receipts and preserves tiny exact residuals',()=>{
 const o=f.options();Object.assign(o.rolls[0],{available:'10.000001',linked_native_draft_qty:'10',free_for_new_plan:'0.000001'})
 expect(parsePlanOptions(o,f.actor,f.context).rolls[0].free).toBe('0.000001')
 o.rolls[0].free_for_new_plan='10.000001';expect(()=>parsePlanOptions(o,f.actor,f.context)).toThrow()
 Object.assign(o.rolls[0],{linked_native_draft_qty:undefined});expect(()=>parsePlanOptions(o,f.actor,f.context)).toThrow()
})
it.each(['actor_scope_id','run_id','target_key','source_hash'])('rejects another %s before adopting choices',(key)=>{const o=f.options();Object.assign(o,{[key]:key==='source_hash'?'c'.repeat(64):f.order});expect(()=>parsePlanOptions(o,f.actor,f.context)).toThrow()})
it('keeps absent capacities unknown and legitimate zero distinct',()=>{const o=f.options();Object.assign(o,{needed_pcs:null,capacity_pcs:'0',production_state:null});const p=parsePlanOptions(o,f.actor,f.context);expect(p.needed).toBeNull();expect(p.capacity).toBe('0');expect(p.state).toBeNull();expect(()=>planPayload(p,form,'2026-10-01T08:00:00Z',null)).toThrow()})
it('rejects a truncated page or another Native model instead of admitting a partial choice list',()=>{const o=f.options();o.page.po_total='2';expect(()=>parsePlanOptions(o,f.actor,f.context)).toThrow();const wrong=f.options();wrong.orders[0].model_id=f.roll;expect(()=>parsePlanOptions(wrong,f.actor,f.context)).toThrow()})
it('constructs only an explicitly reviewed Native draft composition, with exact size and no POST/reservation authority',()=>{const p=planPayload(parsePlanOptions(f.options(),f.actor,f.context),form,'2026-10-01T08:00:00Z',null);expect(p.cutting.size_slots).toEqual([{slot_no:'1',size_id:f.size,drawing_no:'1'}]);expect(p.cutting).not.toHaveProperty('action');expect(p).not.toHaveProperty('reservation');expect(p.reviewed_assumption_ids).toEqual(['selected-calendar']);expect(()=>planPayload(parsePlanOptions(f.options(),f.actor,f.context),{...form,reviewed:false},'2026-10-01T08:00:00Z',null)).toThrow()})
it('rejects counterfeit installed/reserved material or another preview version',()=>{const s=parsePlanSaved(f.saved(),f.actor,f.draft),p=f.preview();p.material_rows[0].basis='INSTALLED';expect(()=>parsePlanPreview(p,f.actor,s)).toThrow();const changed=f.preview();changed.revision='2';expect(()=>parsePlanPreview(changed,f.actor,s)).toThrow()})
it('binds success to the exact saved UUID, input run, target, actor and non-posting state',()=>{const e={action:'SAVE_DRAFT',payload:{run_id:f.run,target_key:f.context.targetKey,source_hash:f.sourceHash},id:f.order,createdAt:'2026-10-01T08:00:00Z',expectedVersion:null,fingerprint:'synthetic'};expect(validatePlanCommit(f.saveOutcome(e.id),e,f.actor).id).toBe(f.draft);const bad=f.saveOutcome(f.roll);expect(()=>validatePlanCommit(bad,e,f.actor)).toThrow();const foreign=f.saveOutcome(e.id);foreign.actor_scope_id=f.roll;expect(()=>validatePlanCommit(foreign,e,f.actor)).toThrow()})
beforeEach(()=>localStorage.clear())
it('stores only an opaque draft pointer and keeps corrupt prior evidence',()=>{rememberPlanPointer('scope',f.draft);expect(localStorage.getItem(planPointerKey('scope'))).toBe(JSON.stringify({id:f.draft}));localStorage.setItem(planPointerKey('scope'),'broken');expect(readPlanPointer('scope').error).not.toBe('');expect(()=>rememberPlanPointer('scope',f.order)).toThrow();expect(localStorage.getItem(planPointerKey('scope'))).toBe('broken')})
