import {useCallback,useEffect,useMemo,useRef,useState} from 'react'
import {useAuth} from './auth/AuthProvider'
import {getUatSupabaseClient} from './lib/supabase'
import {normalizeClientError} from './lib/clientError'
import {useProductionMutation} from './useProductionMutation'
import ProductionRecoveryNotice from './ProductionRecoveryNotice'
import {formatReceiptDecimal} from './procurementContract'
import {cp6WibPhysicalTimeToIso} from './cp6BusinessTime'
import {observeProductionRecovery,type ProductionEnvelope} from './productionRecovery'
import {planOptionsQuery,parsePlanOptions,planPayload,validatePlanCommit,parsePlanSaved,parsePlanPreview,readPlanPointer,rememberPlanPointer,planPointerKey,type PlanContext,type PlanOptions,type PlanForm,type PlanSaved,type PlanPreview} from './nativePlanDraft'
import {parsePlanActual,planActualLabels,planActualValue,planActualStage,type PlanActual} from './nativePlanActual'
import './native-plan-draft.css'
const required=['master.product.view','production.wip.view','warehouse.stock.view','sales.invoice.view','production.cutting.view']
type Props={context:PlanContext;onSourceReadStart:()=>void;onSourceReadEnd:()=>void;onClose:()=>void}
const empty:PlanForm={orderId:'',patternId:'',locationId:'',cutAt:'',notes:'',reason:'',reviewed:false,rolls:[]}
export default function NativePlanDraftPanel(props:Props){const{runtime,identity}=useAuth();if(runtime.mode!=='DISPOSABLE_TEST'||identity.status!=='AUTHORIZED'||!required.every(p=>identity.permissions.includes(p)))return null;return<Workspace {...props} key={`${runtime.projectRef}:${identity.profile.id}:${identity.profile.rowVersion}:${identity.profile.roleRowVersion}:${identity.permissions.join('|')}`}/>}
function Workspace({context,onSourceReadStart,onSourceReadEnd,onClose}:Props){
 const{runtime,identity}=useAuth();if(runtime.mode!=='DISPOSABLE_TEST'||identity.status!=='AUTHORIZED')throw Error('Sesi rencana belum siap.')
 const client=useMemo(()=>getUatSupabaseClient(runtime),[runtime]),mutation=useProductionMutation('PLAN_APPLY'),actor=identity.profile.authUserId,scope=runtime.projectRef+':'+identity.profile.id,seq=useRef(0),active=useRef(false)
 const[form,setForm]=useState<PlanForm>(()=>structuredClone(empty)),[options,setOptions]=useState<PlanOptions|null>(null),[saved,setSaved]=useState<PlanSaved|null>(null),[preview,setPreview]=useState<PlanPreview|null>(null)
 const[actual,setActual]=useState<PlanActual|null>(null)
 const[pointer,setPointer]=useState(()=>readPlanPointer(scope)),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[poQuery,setPoQuery]=useState(''),[rollQuery,setRollQuery]=useState(''),[reviewApply,setReviewApply]=useState(false),[applyReason,setApplyReason]=useState(''),[dirty,setDirty]=useState(true)
 const current=useRef({context,form,saved});current.current={context,form,saved}
 const retireFacts=useCallback(()=>{setOptions(null);setPreview(null);setActual(null);setReviewApply(false)},[])
 const invalidate=useCallback(()=>{++seq.current;const wasActive=active.current;active.current=false;setBusy(false);retireFacts();setSaved(null);if(!wasActive)onSourceReadStart();onSourceReadEnd()},[retireFacts,onSourceReadStart,onSourceReadEnd])
 useEffect(()=>()=>{++seq.current;if(active.current){active.current=false;onSourceReadEnd()}},[onSourceReadEnd])
 useEffect(()=>{++seq.current;if(active.current){active.current=false;onSourceReadEnd()}setBusy(false);setSaved(null);retireFacts();setDirty(true)},[context.runId,context.targetKey,context.sourceHash,retireFacts,onSourceReadEnd])
 useEffect(()=>observeProductionRecovery(scope,invalidate),[scope,invalidate])
 useEffect(()=>{const listener=(e:StorageEvent)=>{if(e.key===null||e.key===planPointerKey(scope)){invalidate();setPointer(readPlanPointer(scope))}};addEventListener('storage',listener);return()=>removeEventListener('storage',listener)},[scope,invalidate])
 const begin=()=>{const n=++seq.current;active.current=true;setBusy(true);retireFacts();setError('');onSourceReadStart();return n}
 const end=(n:number)=>{if(n===seq.current){active.current=false;setBusy(false);onSourceReadEnd()}}
 const load=async(poOffset=0,rollOffset=0,patternOffset=0)=>{const n=begin(),ticket=mutation.beginRead();try{
  if(pointer.error)throw Error(pointer.error)
  const c=current.current.context,r=await client.rpc('erp_cp7_get_plan_options_v1',{p_query:planOptionsQuery(c,current.current.form.locationId,poQuery,rollQuery,poOffset,rollOffset,patternOffset)});if(n!==seq.current||!mutation.isReadCurrent(ticket))return false;if(r.error)throw r.error
  setOptions(parsePlanOptions(r.data,actor,c));return mutation.finishRead(ticket)
 }catch(e){if(n===seq.current){setSaved(null);setError(normalizeClientError(e).message)};return false}finally{end(n)}}
 const loadSaved=async()=>{const n=begin(),ticket=mutation.beginRead();try{const held=readPlanPointer(scope);setPointer(held);if(held.error||!held.id)throw Error(held.error||'Belum ada penunjuk rencana tersimpan.');const r=await client.rpc('erp_cp7_read_plan_draft_v1',{p_draft:held.id});if(n!==seq.current||!mutation.isReadCurrent(ticket))return false;if(r.error)throw r.error;const s=parsePlanSaved(r.data,actor,held.id);setSaved(s);setDirty(s.runId!==context.runId||s.targetKey!==context.targetKey||s.sourceHash!==context.sourceHash);return mutation.finishRead(ticket)}catch(e){if(n===seq.current){setSaved(null);setError(normalizeClientError(e).message)};return false}finally{end(n)}}
 const inspect=async()=>{if(!saved)return;const held=saved,n=begin(),ticket=mutation.beginRead();try{const r=await client.rpc('erp_cp7_preview_plan_action_v1',{p_draft:held.id});if(n!==seq.current||!mutation.isReadCurrent(ticket))return;if(r.error)throw r.error;setPreview(parsePlanPreview(r.data,actor,held));mutation.finishRead(ticket)}catch(e){if(n===seq.current){setSaved(null);setError(normalizeClientError(e).message)}}finally{end(n)}}
 const compareActual=async()=>{if(!saved)return;const held=saved,n=begin(),ticket=mutation.beginRead();try{const r=await client.rpc('erp_cp7_read_plan_actual_v1',{p_draft:held.id});if(n!==seq.current||!mutation.isReadCurrent(ticket))return;if(r.error)throw r.error;setActual(parsePlanActual(r.data,actor,held));mutation.finishRead(ticket)}catch(e){if(n===seq.current){setSaved(null);setError(normalizeClientError(e).message)}}finally{end(n)}}
 const send=(e:ProductionEnvelope)=>e.action==='SAVE_DRAFT'?client.rpc('erp_cp7_save_plan_draft_v1',{p_payload:e.payload,p_request:e.id}):client.rpc('erp_cp7_apply_plan_action_v1',{p_payload:e.payload,p_request:e.id})
 const handlers={send,validate:(v:unknown,e:ProductionEnvelope)=>{validatePlanCommit(v,e,actor)},retire:(v:unknown,e:ProductionEnvelope)=>{const s=validatePlanCommit(v,e,actor);rememberPlanPointer(scope,s.id);setPointer(readPlanPointer(scope));setSaved(s);setDirty(false);retireFacts();setNotice(e.action==='APPLY'?`${s.native?.number??'Draf Potongan'} tersimpan di ERP. Buka Buat Potongan untuk melanjutkan setelah pekerjaan fisik diperiksa.`:'Rencana tersimpan. Periksa pratinjau terbaru sebelum membuat draf Potongan.');setReviewApply(false)},reload:loadSaved}
 const save=async()=>{if(!options||mutation.writerLocked||!canCreate)return;setError('');try{const at=cp6WibPhysicalTimeToIso(form.cutAt);if(!at)throw Error('Isi waktu pencatatan draf WIB yang sah.');const payload=planPayload(options,form,at,saved?.state==='SAVED'?saved:null);await mutation.run('SAVE_DRAFT',payload,saved?Number(saved.revision):null,handlers)}catch(e){setError(normalizeClientError(e).message)}}
 const apply=async()=>{if(!saved||!preview||!reviewApply||!applyReason.trim()||dirty||mutation.writerLocked||!canCreate)return;setError('');await mutation.run('APPLY',{draft_id:saved.id,expected_revision:saved.revision,explicit_review:true,reason:applyReason.trim()},Number(saved.revision),handlers)}
 const edit=(p:Partial<PlanForm>)=>{setForm(f=>({...f,...p}));setDirty(true);setPreview(null);setReviewApply(false);setNotice('')}
 const editRoll=(id:string,p:Partial<PlanForm['rolls'][number]>)=>edit({rolls:form.rolls.map(x=>x.id===id?{...x,...p}:x)})
 const canCreate=identity.permissions.includes('production.cutting.create'),blocked=busy||mutation.busy||mutation.externalMutationBlocked||mutation.corruptedEnvelope
 const close=()=>{if(active.current){++seq.current;active.current=false;onSourceReadEnd()}onClose()}
 const page=(kind:'po'|'roll'|'pattern',direction:1|-1)=>{if(!options)return;const p=options.page;void load(kind==='po'?Math.max(0,p.poOffset+direction*p.limit):p.poOffset,kind==='roll'?Math.max(0,p.rollOffset+direction*p.limit):p.rollOffset,kind==='pattern'?Math.max(0,p.patternOffset+direction*p.limit):p.patternOffset)}
 return<section aria-label="Rencana Potongan ERP" className="native-plan-controls"><header><h3>Rencana Potongan</h3><button onClick={close}>Tutup rencana Potongan</button></header><p>Rencana dan draf tidak mengurangi stok. Periksa pola, roll, perkiraan hasil, dan asumsi sebelum membuat draf Potongan.</p>
  {error?<p role="alert">{error}</p>:null}{notice?<p role="status">{notice}</p>:null}<ProductionRecoveryNotice className="native-plan-recovery" recovery={mutation} onReconcile={()=>mutation.reconcile(handlers)}/>
  <div className="native-analysis-actions"><button disabled={blocked||Boolean(mutation.pending)||Boolean(pointer.error)} onClick={()=>void load()}>Muat pilihan Potongan dari ERP</button><button disabled={blocked||Boolean(mutation.pending)||!pointer.id||Boolean(pointer.error)} onClick={()=>void loadSaved()}>Muat rencana tersimpan</button><button disabled={blocked||Boolean(mutation.pending)||!saved||saved.state!=='SAVED'||dirty} onClick={()=>void inspect()}>Periksa pratinjau rencana</button></div>
  {options?<div className="native-plan-result"><p><strong>{options.sku} · {options.name}</strong>. Kebutuhan setelah pembagian: {options.needed===null?'belum diketahui':formatReceiptDecimal(options.needed)+' PCS'}. Kapasitas bebas pilihan: {options.capacity===null?'belum diketahui':formatReceiptDecimal(options.capacity)+' PCS'}.</p><p>Hasil ini memakai asumsi yang dipilih. Pilihan roll menunjukkan stok di lokasi saat diperiksa; belum dialokasikan atau terpasang.</p></div>:null}
  <fieldset disabled={blocked||Boolean(mutation.pending)||!canCreate}><legend>Isian rencana</legend><label>Gudang bahan rencana<select aria-label="Gudang bahan rencana" value={form.locationId} onChange={e=>edit({locationId:e.target.value,rolls:[]})}><option value="">Pilih lalu muat pilihan terbaru</option>{options?.locations.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label>
   <label>Cari PO rencana<input aria-label="Cari PO rencana" value={poQuery} onChange={e=>setPoQuery(e.target.value)}/></label><label>PO rencana<select aria-label="PO rencana" value={form.orderId} onChange={e=>edit({orderId:e.target.value})}><option value="">Pilih PO dengan model yang sama</option>{options?.orders.map(x=><option key={x.id} value={x.id}>{x.number}</option>)}</select></label>
   <label>Pola rencana<select aria-label="Pola rencana" value={form.patternId} onChange={e=>edit({patternId:e.target.value})}><option value="">Pilih pola yang diperiksa</option>{options?.patterns.map(x=><option key={x.id} value={x.id}>{x.code} · {x.revision} · {x.name}</option>)}</select></label><label>Waktu pencatatan draf · WIB<input aria-label="Waktu pencatatan draf WIB" type="datetime-local" step="1" value={form.cutAt} onChange={e=>edit({cutAt:e.target.value})}/></label>
   <label>Cari roll rencana<input aria-label="Cari roll rencana" value={rollQuery} onChange={e=>setRollQuery(e.target.value)}/></label>{options?.rolls.map(r=><article key={r.id}><p>{r.number} · {r.materialName} · tersedia {formatReceiptDecimal(r.available)} {r.unit}.</p>{form.rolls.some(x=>x.id===r.id)?null:<button type="button" onClick={()=>edit({rolls:[...form.rolls,{id:r.id,issued:'',consumed:'',remaining:'',pcs:''}]})}>Pilih roll {r.number}</button>}</article>)}
   {form.rolls.map((r,i)=><article key={r.id}><h4>Roll pilihan {i+1}</h4><label>Jumlah keluar<input aria-label={`Keluar roll rencana ${i+1}`} inputMode="decimal" value={r.issued} onChange={e=>editRoll(r.id,{issued:e.target.value})}/></label><label>Perkiraan terpakai<input aria-label={`Terpakai roll rencana ${i+1}`} inputMode="decimal" value={r.consumed} onChange={e=>editRoll(r.id,{consumed:e.target.value})}/></label><label>Perkiraan sisa<input aria-label={`Sisa roll rencana ${i+1}`} inputMode="decimal" value={r.remaining} onChange={e=>editRoll(r.id,{remaining:e.target.value})}/></label><label>Perkiraan hasil size terpilih (PCS)<input aria-label={`Hasil roll rencana ${i+1}`} inputMode="numeric" value={r.pcs} onChange={e=>editRoll(r.id,{pcs:e.target.value})}/></label><button type="button" onClick={()=>edit({rolls:form.rolls.filter(x=>x.id!==r.id)})}>Hapus roll pilihan {i+1}</button></article>)}
   <label>Catatan rencana<textarea aria-label="Catatan rencana Potongan" value={form.notes} onChange={e=>edit({notes:e.target.value})}/></label><label>Alasan rencana<textarea aria-label="Alasan rencana Potongan" maxLength={1000} value={form.reason} onChange={e=>edit({reason:e.target.value})}/></label>{options?<ul>{options.assumptions.map(a=><li key={a.id}>{a.label}</li>)}</ul>:null}<label><input aria-label="Asumsi dan komposisi rencana sudah diperiksa" type="checkbox" checked={form.reviewed} onChange={e=>edit({reviewed:e.target.checked})}/>Saya sudah memeriksa asumsi, pola, size, roll, dan perkiraan hasil.</label><button disabled={!options||!form.reviewed||mutation.writerLocked||options.state!=='ACTIVE'||options.needed===null||options.capacity===null||!dirty} onClick={()=>void save()}>Simpan rencana Potongan</button>
  </fieldset>
  {options?<nav aria-label="Halaman pilihan rencana">{(['po','pattern','roll']as const).map(k=>{const p=options.page,off=k==='po'?p.poOffset:k==='pattern'?p.patternOffset:p.rollOffset,total=k==='po'?p.poTotal:k==='pattern'?p.patternTotal:p.rollTotal;return<span key={k}><button disabled={blocked||off===0} onClick={()=>page(k,-1)}>{k==='po'?'PO':k==='pattern'?'Pola':'Roll'} sebelumnya</button><span>{off+1} · total {total}</span><button disabled={blocked||BigInt(off+p.limit)>=BigInt(total)} onClick={()=>page(k,1)}>{k==='po'?'PO':k==='pattern'?'Pola':'Roll'} berikutnya</button></span>})}</nav>:null}
  {saved?<p>Rencana versi {saved.revision} · {saved.state==='SAVED'?'tersimpan':saved.state==='NATIVE_DRAFT_CREATED'?'draf Potongan sudah dibuat':saved.state==='NATIVE_MATERIAL_POSTED'?'bahan sudah diposting di ERP':'draf Potongan sudah dihapus'}. {saved.native?.number??''}</p>:null}
  <button disabled={blocked||Boolean(mutation.pending)||!saved||Boolean(pointer.error)} onClick={()=>void compareActual()}>Bandingkan rencana dengan hasil produksi</button>
  {actual?<div className="native-plan-result" aria-label="Perbandingan rencana dan hasil produksi"><h4>Rencana dan hasil produksi</h4><p>Rencana tersimpan: {actual.planned} PCS. Angka rencana adalah perkiraan yang diperiksa operator.</p><p>Hasil ERP diperiksa pada {actual.capturedAt}. {actual.nativeGroup?`Kelompok ${actual.nativeGroup.number}.`:'Belum ada kelompok produksi yang terbukti.'}</p><p>{actual.state==='NOT_STARTED'?'Draf belum menjadi produksi fisik.':actual.state==='COMPLETE'?'Jumlah dari kelompok dan size yang terhubung berhasil dicocokkan.':'Sumber hasil produksi belum lengkap; jumlah yang belum terbukti tetap belum diketahui.'}</p>{actual.originalState==='ARCHIVED_STALE'?<p>Sumber rencana lama sudah berubah. Perbandingan ini tetap memakai versi rencana tersimpan dan hasil ERP yang baru diperiksa.</p>:null}<dl>{(Object.keys(planActualLabels)as (keyof typeof planActualLabels)[]).map(k=><div key={k}><dt>{planActualLabels[k]}</dt><dd>{planActualValue(actual.facts[k])}</dd></div>)}<div><dt>Sisa menuju jumlah rencana</dt><dd>{planActualValue(actual.remaining)}</dd></div></dl><p>FG di sini menunjukkan hasil produksi kelompok ini, bukan stok gudang yang tersedia sekarang. Pengeluaran bahan belum membuktikan bahan terpasang.</p>{actual.positions.length?<table><caption>Posisi dari kelompok dan size rencana</caption><thead><tr><th>Posisi</th><th>Jumlah</th><th>Produk fisik</th></tr></thead><tbody>{actual.positions.map(p=><tr key={p.key}><td>{planActualStage(p.stage)}</td><td>{p.quantity} PCS</td><td>{p.rootId??'Belum menjadi FG yang terbukti'}</td></tr>)}</tbody></table>:null}</div>:null}
  {preview?<div className="native-plan-result"><h4>Pratinjau yang diperiksa</h4><p>Kebutuhan {formatReceiptDecimal(preview.needed)} PCS; pilihan {formatReceiptDecimal(preview.selected)} PCS; kapasitas bebas {formatReceiptDecimal(preview.capacity)} PCS; belum tertutup {formatReceiptDecimal(preview.unresolved)} PCS.</p><p>Tidak ada stok yang direservasi. Hasil akan membuat draf Potongan, lalu operator melanjutkan di Buat Potongan.</p><label>Alasan membuat draf Potongan<textarea aria-label="Alasan membuat draf Potongan" maxLength={1000} value={applyReason} disabled={blocked} onChange={e=>setApplyReason(e.target.value)}/></label><label><input aria-label="Pratinjau sudah diperiksa untuk membuat draf" type="checkbox" checked={reviewApply} disabled={blocked} onChange={e=>setReviewApply(e.target.checked)}/>Saya sudah memeriksa pratinjau dan akan membuat satu draf Potongan.</label><button disabled={blocked||!reviewApply||!applyReason.trim()||dirty||mutation.writerLocked||!canCreate} onClick={()=>void apply()}>Buat draf Potongan di ERP</button></div>:null}
 </section>
}
