// @vitest-environment jsdom
import {reportCrypto,reportBodyDigest} from '../tests/fixtures/reportCrypto.mjs'
import {beforeEach,afterEach,it,expect,vi} from 'vitest'
import fixture from '../tests/fixtures/nativeAnalysisStandin.json'
import {parseNativeReport,parseReportCommand,parseReportComparison,assertSameReport,readReportRequest,persistReportRequest,clearReportRequest,reportRequestKey,parseReportIndex,type ReportRequest} from './nativeAnalysisReports'
import type {NativeDemandQuery} from './nativeDemandHistory'
const actor=fixture.analysis.scope.actor_scope_id,access={ownerReports:false,preflight:false},id='00000000-0000-4000-8000-000000000011',key='00000000-0000-4000-8000-000000000012'
function raw(){const e=structuredClone(fixture),body='Laporan uji parser. Sumber '+e.analysis.snapshot.source_hash;return{contract_version:'cp7.report-publication.v1',actor_scope_id:actor,id,series_id:'00000000-0000-4000-8000-000000000013',revision:'1',run_id:e.run_id,request_id:key,kind:'PERIOD',period_query:e.query,title:'Laporan uji parser',reason:'Kontrak stand-in, bukan bukti Native',template_version:'native-report-1',body,body_sha256:reportBodyDigest(body),source_hash:e.analysis.snapshot.source_hash,semantic_hash:e.analysis.semantic_hash,published_at:'2026-10-01T00:00:00.000001+00:00',is_latest:true,source_state:e.source_state,analysis:e,production_go:false}}
function request():ReportRequest{const d=raw();return{id:key,query:d.period_query as NativeDemandQuery,payload:{run_id:d.run_id,source_hash:d.source_hash,semantic_hash:d.semantic_hash,kind:'PERIOD',series_id:null,expected_revision:null,title:d.title,reason:d.reason,explicit_review:true}}}
beforeEach(()=>{localStorage.clear();vi.stubGlobal('crypto',reportCrypto)})
afterEach(()=>vi.unstubAllGlobals())
it('checks the complete UTF8 body digest and Original actor/source before returning protected content',async()=>{const d=raw(),parsed=await parseNativeReport(d,actor,access);expect(parsed.body).toBe(d.body);for(const change of[{body:d.body+' changed'},{actor_scope_id:key},{source_hash:'0'.repeat(64)},{semantic_hash:'0'.repeat(64)},{production_go:true},{analysis:{...d.analysis,apply_enabled:true}}])await expect(parseNativeReport({...d,...change},actor,access)).rejects.toThrow()})
it('accepts SourceChanged archives with exactly the old Original and body, and detects rewritten publications',async()=>{const d=raw(),original=await parseNativeReport(d,actor,access),old={...d,source_state:'ARCHIVED_STALE',is_latest:false,analysis:{...d.analysis,source_state:'ARCHIVED_STALE'}};assertSameReport(original,await parseNativeReport(old,actor,access));old.body+=' changed';old.body_sha256=reportBodyDigest(old.body);expect(()=>assertSameReport(original,{...original,body:old.body,bodyHash:old.body_sha256})).toThrow()})
it('accepts only the exact committed request and revision, or a sealed negative with no document',async()=>{const d=raw(),r=request(),c={contract_version:'cp7.report-command.v1',request_id:key,status:'COMMITTED',document:d,analysis:d.analysis,production_go:false};expect((await parseReportCommand(c,r,actor,access)).document?.id).toBe(id);await expect(parseReportCommand({...c,request_id:id},r,actor,access)).rejects.toThrow();await expect(parseReportCommand({...c,document:{...d,title:'Other title'}},r,actor,access)).rejects.toThrow();const negative={...c,status:'CLOSED_UNCOMMITTED',document:null};expect((await parseReportCommand(negative,r,actor,access)).document).toBeNull();await expect(parseReportCommand({...negative,document:d},r,actor,access)).rejects.toThrow()})
it('keeps one exact pending UUID and payload; corrupt or inaccessible storage remains blocked',()=>{const scope='analysis:standin:actor',r=request();persistReportRequest(scope,r);expect(readReportRequest(scope).pending).toEqual(r);persistReportRequest(scope,r);expect(()=>persistReportRequest(scope,{...r,payload:{...r.payload,title:'Changed'}})).toThrow();expect(()=>clearReportRequest(scope,{...r,id})).toThrow();clearReportRequest(scope,r);expect(readReportRequest(scope).pending).toBeNull();localStorage.setItem(reportRequestKey(scope),'{bad');expect(readReportRequest(scope).error).toBeTruthy();expect(()=>persistReportRequest(scope,r)).toThrow();expect(localStorage.getItem(reportRequestKey(scope))).toBe('{bad')})
it('rejects archived fact or secret fields in the request and index; exact decimal counts remain strings',()=>{const r=request();expect(()=>persistReportRequest('s',{...r,financial_source:{cash:'100'}} as ReportRequest)).toThrow();const d=raw(),row={id:d.id,series_id:d.series_id,revision:d.revision,run_id:d.run_id,kind:d.kind,title:d.title,period_query:d.period_query,published_at:d.published_at,body_sha256:d.body_sha256},index={contract_version:'cp7.report-index.v1',actor_scope_id:actor,rows:[row],total:'9007199254740993',next_before_id:null,page_complete:true,production_go:false};expect(parseReportIndex(index,actor,25).total).toBe(index.total);for(const change of[{page_complete:false},{actor_scope_id:key},{rows:[{...row,body:d.body}]},{total:'9223372036854775808'}])expect(()=>parseReportIndex({...index,...change},actor,25)).toThrow()})
it('requires every Native metric exactly once and keeps UNKNOWN separate from known zero',async()=>{const d=raw(),rows=d.analysis.analysis.metrics.map(m=>({metric_id:m.metric_id,version:m.version,scope_kind:m.scope_kind,scope_key:m.scope_key,knowledge_mode:m.knowledge_mode,before:m,after:m,difference:m.value.state==='UNKNOWN'?{state:'UNKNOWN',unit:m.value.unit,reason:'ONE_OR_BOTH_VALUES_UNKNOWN'}:{state:m.value.state,unit:m.value.unit,value:'0'}})),c={contract_version:'cp7.report-comparison.v1',actor_scope_id:actor,before:d,after:d,rows,comparison_basis:'AFTER_MINUS_BEFORE_NATIVE_METRICS_MATCHED_VERSION_SCOPE_UNIT_KNOWLEDGE',production_go:false};expect((await parseReportComparison(c,actor,access,id,id)).rows).toHaveLength(rows.length);await expect(parseReportComparison({...c,rows:[]},actor,access,id,id)).rejects.toThrow();await expect(parseReportComparison({...c,rows:[...rows,rows[0]]},actor,access,id,id)).rejects.toThrow();const changed=structuredClone(rows);changed[0].difference={state:'KNOWN',unit:changed[0].difference.unit,value:'1'};await expect(parseReportComparison({...c,rows:changed},actor,access,id,id)).rejects.toThrow()})
