import {parseNativeAnalysis,type NativeAnalysis,type AnalysisFinanceAccess} from './nativeAnalysis'
import {parseReminderPolicyRow,reminderRuleIds,reminderRuleLabels,type ReminderRule,type ReminderPolicyRow} from './nativeReminderPolicy'
import type {NativeDemandQuery} from './nativeDemandHistory'
import type {FactValue} from './cp7/contract'
import {financeDate} from './financeReportContract'

export type RuleRights={ar:boolean;ap:boolean}
export type RuleCondition={key:string;rule_id:ReminderRule;target_key:string|null;source_id:string;material_key:string|null;source_hash:string;state:'ACTIVE'|'RESOLVED'|'NO_CURRENT_GAP'|'DATA_REVIEW'|'SOURCE_CHANGED';reason:string;value:FactValue;production_state:string|null;business_resolved:boolean;scope:string;label:string;policy_binding:{rule_id:ReminderRule;target_key:string|null;basis:'MISSING'|'GLOBAL'|'EXACT_TARGET';policy:ReminderPolicyRow|null};policy_timing:{status:string;ready:boolean;checked_at:string;next_at:string|null;meaning:'LOCAL_PREVIEW_ELIGIBILITY_ONLY_NOT_DELIVERY_OR_BUSINESS_RESOLUTION'};eligibility:string;delivery_sent:false;eligibility_meaning:'LOCAL_PREVIEW_ONLY_NOT_BUSINESS_RESOLUTION'}
export type RuleSource={analysis:NativeAnalysis;policyRows:ReminderPolicyRow[];rows:RuleCondition[];hash:string;readAt:string;coverage:Record<string,string>}
export type RuleEpisode={id:string;number:string;previous_id:string|null;state:'ACTIVE'|'RESOLVED';freshness:'KNOWN'|'ASSUMED'|'UNKNOWN';first_observed_at:string;last_observed_at:string;resolved_at:string|null}
export type RuleObservation={condition:RuleCondition;episode:RuleEpisode|null;transition:string}
export type RuleObservationResult={source:RuleSource;status:'COMMITTED'|'NOT_COMMITTED';rows:RuleObservation[];freshness:'CURRENT_SOURCE'|'HISTORICAL_SOURCE_CHANGED'}
export type LocalBinding={id:string;revision:string;previous_id:string|null;enabled:boolean;label:string;environment:'LOCAL_TEST_SINK';rules:ReminderRule[];reason:string;created_at:string}
export type LocalClaim={id:string;run_id:string;status:'CLAIMED'|'LOCAL_SINK_CAPTURED'|'SUPPRESSED'|'UNKNOWN';occurrence_key:string;binding_id:string;environment:'LOCAL_TEST_SINK';condition_key:string;rule_id:ReminderRule;episode_id:string;policy_id:string;source_hash:string;body_sha256:string;body:string|null;fence:string;created_at:string;finished_at:string|null;reason:string|null;resolution:{id:string;outcome:'CAPTURE_CONFIRMED'|'NOT_CAPTURED_CONFIRMED';reason:string;created_at:string}|null}
export type LocalWorkspace={source:RuleSource;binding:LocalBinding|null;claims:LocalClaim[]}
export type RuleRequest={id:string;query:NativeDemandQuery;operation:'EPISODES'|'BINDING'|'PREVIEW'|'OUTCOME'|'RESOLUTION';payload:Record<string,string|boolean|ReminderRule[]>}
export const ruleRequestKey=(scope:string)=>'erp.cp7.rule-local-request.v1:'+scope
export const ruleConditionLabels={ACTIVE:'Masih perlu ditangani',RESOLVED:'Sumber membuktikan selesai',NO_CURRENT_GAP:'Tidak ada peringatan pada skenario ini',DATA_REVIEW:'Data perlu diperiksa',SOURCE_CHANGED:'Analisis perlu diperbarui'}
export const localClaimLabels={CLAIMED:'Pratinjau belum dipastikan',LOCAL_SINK_CAPTURED:'Tercatat di pratinjau lokal',SUPPRESSED:'Ditahan karena sumber atau pengaturan berubah',UNKNOWN:'Hasil lokal belum pasti'}
export const ruleEligibilityLabels:Record<string,string>={SOURCE_REVIEW_REQUIRED:'Lengkapi atau perbarui sumber',NO_CURRENT_ALERT:'Tidak ada peringatan saat ini',UNCONFIGURED:'Pengaturan belum lengkap',DISABLED:'Aturan dimatikan',CLOCK_CONFLICT:'Waktu perlu diperiksa',QUIET:'Masih dalam waktu tenang',COOLDOWN:'Masih dalam jeda pengingat',UNIT_REVIEW_REQUIRED:'Satuan perlu disamakan',BELOW_SELECTED_THRESHOLD:'Di bawah batas yang dipilih',LOCAL_PREVIEW_ELIGIBLE:'Bisa ditinjau secara lokal'}
const fail=():never=>{throw Error('Kondisi masalah atau pratinjau lokal belum sesuai sumber dan hak akses ERP.')}
const closed=(v:unknown,keys:string[])=>{if(!v||typeof v!=='object'||Array.isArray(v)||Object.keys(v).sort().join('|')!==[...keys].sort().join('|'))return fail();return v as Record<string,unknown>}
const uuid=(v:unknown):v is string=>typeof v==='string'&&/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/.test(v)
const hash=(v:unknown):v is string=>typeof v==='string'&&/^[0-9a-f]{64}$/.test(v)
const uint=(v:unknown):v is string=>typeof v==='string'&&/^(0|[1-9][0-9]{0,18})$/.test(v)&&BigInt(v)<=9223372036854775807n
const stamp=(v:unknown):v is string=>typeof v==='string'&&financeDate(v.slice(0,10))&&/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(?:\.\d{1,6})?(?:Z|[+-]\d{2}:\d{2})$/.test(v)&&Number(v.slice(11,13))<24&&Number(v.slice(14,16))<60&&Number(v.slice(17,19))<60&&Number.isFinite(Date.parse(v))
const canonical=(v:unknown):string=>JSON.stringify(v===null||typeof v!=='object'?v:Array.isArray(v)?v.map(x=>JSON.parse(canonical(x))):Object.fromEntries(Object.entries(v).sort(([a],[b])=>a.localeCompare(b)).map(([k,x])=>[k,JSON.parse(canonical(x))])))
const rules=(rights:RuleRights):ReminderRule[]=>reminderRuleIds.filter(r=>r==='AR_DUE'?rights.ar:r==='AP_DUE'?rights.ap:true)
const compare=(a:string,b:string)=>{if(!/^\d+(\.\d+)?$/.test(a)||!/^\d+(\.\d+)?$/.test(b)||a.length>80||b.length>80)fail();const[ai,af='']=a.split('.'),[bi,bf='']=b.split('.'),n=Math.max(af.length,bf.length),x=BigInt(ai+af.padEnd(n,'0')),y=BigInt(bi+bf.padEnd(n,'0'));return x<y?-1:x>y?1:0}
function condition(v:unknown,analysis:NativeAnalysis,policies:ReminderPolicyRow[],rights:RuleRights,historical=false):RuleCondition{
 const r=closed(v,['key','rule_id','target_key','source_id','material_key','source_hash','state','reason','value','production_state','business_resolved','scope','label','policy_binding','policy_timing','eligibility','delivery_sent','eligibility_meaning'])
 if(!rules(rights).includes(r.rule_id as ReminderRule)||typeof r.key!=='string'||!r.key||!uuid(r.source_id)||!hash(r.source_hash)||!Object.hasOwn(ruleConditionLabels,String(r.state))||typeof r.reason!=='string'||!r.reason||typeof r.scope!=='string'||!r.scope||typeof r.label!=='string'||!r.label.trim()||r.delivery_sent!==false||r.eligibility_meaning!=='LOCAL_PREVIEW_ONLY_NOT_BUSINESS_RESOLUTION'||!Object.hasOwn(ruleEligibilityLabels,String(r.eligibility))||typeof r.business_resolved!=='boolean')fail()
 const rule=r.rule_id as ReminderRule,target=r.target_key as string|null
 if(['PRODUCTION_GAP','ACCESSORY_NEED'].includes(rule)?typeof target!=='string'||!analysis.labels.some(l=>l.key===target)||target.split(':')[0]!==r.source_id:target!==null)fail()
 if(rule==='PRODUCTION_GAP'?(r.key!=='PRODUCTION_GAP:'+target||r.material_key!==null||!['ACTIVE','PAUSED','STOPPED'].includes(String(r.production_state))):r.production_state!==null)fail()
 if(rule==='ACCESSORY_NEED'?(r.material_key!==null&&typeof r.material_key!=='string'||r.key!=='ACCESSORY_NEED:'+target+':'+(r.material_key??'UNKNOWN_BOM')):r.material_key!==null)fail()
 if(rule==='AR_DUE'&&r.key!=='AR_DUE:'+r.source_id||rule==='AP_DUE'&&r.key!=='AP_DUE:MATERIAL:'+r.source_id)fail()
 const value=r.value as FactValue
 if(rule==='PRODUCTION_GAP'){const original=analysis.analysis.recommendations.find(x=>x.target.key===target)!;if(canonical(value)!==canonical(original.q_conditional)||r.production_state!==original.production_state)fail()}
 else if(rule==='ACCESSORY_NEED'){const original=analysis.analysis.material_needs.find(x=>x.target_key===target&&x.material_key===r.material_key);if(!original||canonical(value)!==canonical(original.additional_external))fail()}
 else{const f=closed(value,['state','unit','refs',...((value as {state?:string})?.state==='KNOWN'?['value']:['reason'])]);if(!['KNOWN','UNKNOWN'].includes(String(f.state))||f.unit!=='DAY'||!Array.isArray(f.refs)||f.refs.length!==1||f.state==='UNKNOWN'&&(typeof f.reason!=='string'||!f.reason))fail();const ref=closed((f.refs as unknown[])[0],['kind','id','revision']);if(ref.kind!==(rule==='AR_DUE'?'ACCEPTED_P11_NATIVE_SALE':'ACCEPTED_BF_NATIVE_MATERIAL_PAYABLE')||ref.id!==r.source_id||!uint(ref.revision)||ref.revision==='0'||f.state==='KNOWN'&&(!uint(f.value)||BigInt(f.value)>3652059n))fail()}
 const known=value.state==='KNOWN'||value.state==='ASSUMED',num=known&&'value'in value?value.value:null
 if(['PRODUCTION_GAP','ACCESSORY_NEED'].includes(rule)){
  const state=!known?'DATA_REVIEW':compare(num!,'0')>0?'ACTIVE':value.state==='ASSUMED'?'NO_CURRENT_GAP':'RESOLVED'
  if(historical?r.state!=='SOURCE_CHANGED'&&r.state!==state:r.state!==(analysis.state!=='UNCHANGED'?'SOURCE_CHANGED':state))fail()
  if(r.business_resolved!==(r.state==='RESOLVED'))fail()
 }else if(r.business_resolved!==(r.state==='RESOLVED')||r.state==='SOURCE_CHANGED')fail()
 const b=closed(r.policy_binding,['rule_id','target_key','basis','policy']),exact=policies.find(p=>p.rule_id===rule&&p.scope_kind==='TARGET'&&p.scope_key===target),chosen=historical?(b.policy===null?null:parseReminderPolicyRow(b.policy,rules(rights),new Set(analysis.labels.map(l=>l.key)))):exact??policies.find(p=>p.rule_id===rule&&p.scope_kind==='GLOBAL')??null
 if(b.rule_id!==rule||b.target_key!==target||b.basis!==(chosen?(chosen.scope_kind==='TARGET'?'EXACT_TARGET':'GLOBAL'):'MISSING')||chosen&&(chosen.rule_id!==rule||chosen.scope_kind==='TARGET'&&chosen.scope_key!==target)||!historical&&canonical(b.policy)!==canonical(chosen))fail()
 const t=closed(r.policy_timing,['status','ready','checked_at','next_at','meaning'])
 if(!['UNCONFIGURED','DISABLED','CLOCK_CONFLICT','QUIET','COOLDOWN','READY'].includes(String(t.status))||t.ready!==(t.status==='READY')||!stamp(t.checked_at)||t.meaning!=='LOCAL_PREVIEW_ELIGIBILITY_ONLY_NOT_DELIVERY_OR_BUSINESS_RESOLUTION'||t.next_at!==null&&!stamp(t.next_at)||['QUIET','COOLDOWN'].includes(String(t.status))&&t.next_at===null)fail()
 if(r.eligibility==='LOCAL_PREVIEW_ELIGIBLE'&&(r.state!=='ACTIVE'||!known||t.status!=='READY'||!chosen||chosen.config.enabled!==true||chosen.config.threshold_unit!==value.unit||chosen.config.threshold_value===null||compare(num!,chosen.config.threshold_value)<0))fail()
 if(['DATA_REVIEW','SOURCE_CHANGED'].includes(String(r.state))&&r.eligibility!=='SOURCE_REVIEW_REQUIRED'||r.state!=='ACTIVE'&&!['DATA_REVIEW','SOURCE_CHANGED'].includes(String(r.state))&&r.eligibility!=='NO_CURRENT_ALERT')fail()
 return structuredClone(r) as RuleCondition
}
export function parseRuleSource(v:unknown,q:NativeDemandQuery,actor:string,finance:AnalysisFinanceAccess,rights:RuleRights):RuleSource{
 const e=closed(v,['contract_version','actor_scope_id','analysis','policy_rows','rows','page_complete','total','coverage','source_hash','read_at','external_delivery_enabled','full_family_acceptance','meaning'])
 if(e.contract_version!=='cp7.native-rule-conditions.v1'||e.actor_scope_id!==actor||e.page_complete!==true||e.external_delivery_enabled!==false||e.full_family_acceptance!==false||e.meaning!=='CURRENT_SOURCE_CONDITION_SEPARATE_FROM_ATTENTION_DELIVERY_AND_ORIGINAL'||!hash(e.source_hash)||!stamp(e.read_at)||!uint(e.total)||BigInt(e.total)>15000n||!Array.isArray(e.rows)||e.rows.length!==Number(e.total)||!Array.isArray(e.policy_rows)||e.policy_rows.length>4000)fail()
 const analysis=parseNativeAnalysis(e.analysis,q,actor,finance),targets=new Set(analysis.labels.map(l=>l.key)),policies=(e.policy_rows as unknown[]).map(r=>parseReminderPolicyRow(r,rules(rights),targets));if(new Set(policies.map(r=>JSON.stringify([r.rule_id,r.scope_kind,r.scope_key]))).size!==policies.length)fail()
 const coverage=closed(e.coverage,['production','accessory','sales_ar','material_ap','opening_ar','opening_ap','payroll_ap','accessory_ap','laundry_ap'])
 if(coverage.production!=='COMPLETE_AUTHORIZED_ORIGINAL'||coverage.accessory!=='COMPLETE_AUTHORIZED_ORIGINAL_UNKNOWN_INSTALLATION_RETAINED'||coverage.sales_ar!==(rights.ar?'COMPLETE_NATIVE_DOCUMENT_SCOPE':'EXCLUDED_BY_CURRENT_RIGHTS')||coverage.material_ap!==(rights.ap?'COMPLETE_NATIVE_DOCUMENT_SCOPE':'EXCLUDED_BY_CURRENT_RIGHTS')||['opening_ar','opening_ap','payroll_ap','accessory_ap','laundry_ap'].some(k=>coverage[k]!=='NOT_COMPOSED'))fail()
 const rows=(e.rows as unknown[]).map(r=>condition(r,analysis,policies,rights));if(new Set(rows.map(r=>r.key)).size!==rows.length||rows.filter(r=>r.rule_id==='PRODUCTION_GAP').length!==analysis.analysis.recommendations.length||rows.filter(r=>r.rule_id==='ACCESSORY_NEED').length!==analysis.analysis.material_needs.length)fail()
 return{analysis,policyRows:policies,rows,hash:e.source_hash as string,readAt:e.read_at as string,coverage:coverage as Record<string,string>}
}
export function parseRuleObservations(v:unknown,r:RuleRequest,actor:string,finance:AnalysisFinanceAccess,rights:RuleRights):RuleObservationResult{
 const e=closed(v,['contract_version','actor_scope_id','source','result','result_freshness','external_delivery_enabled','business_DML']),res=closed(e.result,['request_id','status','source_hash','rows'])
 if(e.contract_version!=='cp7.native-rule-observations.v1'||e.actor_scope_id!==actor||e.external_delivery_enabled!==false||e.business_DML!==false||r.operation!=='EPISODES'||res.request_id!==r.id||res.source_hash!==r.payload.source_hash||!['COMMITTED','NOT_COMMITTED'].includes(String(res.status))||!Array.isArray(res.rows)||res.rows.length>15000)fail()
 const source=parseRuleSource(e.source,r.query,actor,finance,rights);if(source.analysis.runId!==r.payload.run_id||e.result_freshness!==(source.hash===res.source_hash?'CURRENT_SOURCE':'HISTORICAL_SOURCE_CHANGED')||res.status==='NOT_COMMITTED'&&(res.rows as unknown[]).length)fail()
 const seen=new Set<string>(),rows=(res.rows as unknown[]).map(raw=>{const o=closed(raw,['condition','episode','transition']),c=condition(o.condition,source.analysis,source.policyRows,rights,e.result_freshness!=='CURRENT_SOURCE')
  if(seen.has(c.key)||!['OBSERVED_NO_ACTIVE_EPISODE','OPENED','REOPENED_NEW_EPISODE','RESOLVED','UNKNOWN_RETAINED','SCENARIO_NO_ALERT_EPISODE_RETAINED','ACTIVE_RETAINED'].includes(String(o.transition)))fail();seen.add(c.key)
  let ep:RuleEpisode|null=null
  if(o.episode!==null){const x=closed(o.episode,['id','number','previous_id','state','freshness','first_observed_at','last_observed_at','resolved_at']);if(!uuid(x.id)||!uint(x.number)||x.number==='0'||!['ACTIVE','RESOLVED'].includes(String(x.state))||!['KNOWN','ASSUMED','UNKNOWN'].includes(String(x.freshness))||x.previous_id!==null&&(!uuid(x.previous_id)||x.previous_id===x.id)||(x.number==='1')!==(x.previous_id===null)||!stamp(x.first_observed_at)||!stamp(x.last_observed_at)||Date.parse(x.first_observed_at)>Date.parse(x.last_observed_at)||Date.parse(x.last_observed_at)>Date.parse(source.readAt)||(x.state==='ACTIVE'?x.resolved_at!==null:!stamp(x.resolved_at)||x.resolved_at!==x.last_observed_at))fail();if(x.state==='RESOLVED'&&(!c.business_resolved||x.freshness!=='KNOWN'||c.state!=='RESOLVED'))fail();ep=structuredClone(x) as RuleEpisode}
  if(c.state==='ACTIVE'&&!ep||o.transition==='RESOLVED'&&ep?.state!=='RESOLVED'||['UNKNOWN_RETAINED','SCENARIO_NO_ALERT_EPISODE_RETAINED'].includes(String(o.transition))&&ep?.state!=='ACTIVE'||o.transition==='UNKNOWN_RETAINED'&&ep?.freshness!=='UNKNOWN')fail()
  return{condition:c,episode:ep,transition:o.transition as string}
 });if(res.status==='COMMITTED'&&e.result_freshness==='CURRENT_SOURCE'&&rows.length!==source.rows.length)fail()
 return{source,status:res.status as RuleObservationResult['status'],rows,freshness:e.result_freshness as RuleObservationResult['freshness']}
}
export const localPreviewBody=(r:RuleCondition)=>['PRATINJAU LOKAL — BELUM DIKIRIM',reminderRuleLabels[r.rule_id],r.label,('value'in r.value?r.value.value:'Belum diketahui')+' '+r.value.unit,r.value.state==='ASSUMED'?'Berdasarkan skenario yang dipilih.':'Berdasarkan sumber ERP yang diperiksa.','Ini pratinjau lokal. Masalah tetap diperiksa dari transaksi ERP.'].join('\n')
export async function parseLocalWorkspace(v:unknown,q:NativeDemandQuery,actor:string,finance:AnalysisFinanceAccess,rights:RuleRights):Promise<LocalWorkspace>{
 const e=closed(v,['contract_version','actor_scope_id','source','binding','claims','page_complete','total','external_delivery_enabled','scheduler_enabled','sent'])
 if(e.contract_version!=='cp7.native-local-workspace.v1'||e.actor_scope_id!==actor||e.external_delivery_enabled!==false||e.scheduler_enabled!==false||e.sent!==false||e.page_complete!==true||!uint(e.total)||BigInt(e.total)>4000n||!Array.isArray(e.claims)||e.claims.length!==Number(e.total))fail()
 const source=parseRuleSource(e.source,q,actor,finance,rights);let binding:LocalBinding|null=null
 if(e.binding!==null){const b=closed(e.binding,['id','revision','previous_id','enabled','label','environment','rules','reason','created_at']);if(!uuid(b.id)||!uint(b.revision)||b.revision==='0'||(b.revision==='1')!==(b.previous_id===null)||b.previous_id!==null&&(!uuid(b.previous_id)||b.previous_id===b.id)||typeof b.enabled!=='boolean'||typeof b.label!=='string'||!b.label.trim()||b.label.length>120||b.environment!=='LOCAL_TEST_SINK'||!Array.isArray(b.rules)||!b.rules.length||b.rules.length>4||b.rules.some(r=>!rules(rights).includes(r))||new Set(b.rules).size!==b.rules.length||typeof b.reason!=='string'||!b.reason.trim()||b.reason.length>1000||!stamp(b.created_at))fail();binding=structuredClone(b) as LocalBinding}
 const ids=new Set<string>(),occurrences=new Set<string>(),claims=(e.claims as unknown[]).map(raw=>{const c=closed(raw,['id','run_id','status','occurrence_key','binding_id','environment','condition_key','rule_id','episode_id','policy_id','source_hash','body_sha256','body','fence','created_at','finished_at','reason','resolution']);if(!uuid(c.id)||!uuid(c.run_id)||!uuid(c.binding_id)||!uuid(c.episode_id)||!uuid(c.policy_id)||!uuid(c.fence)||!hash(c.occurrence_key)||!hash(c.source_hash)||!hash(c.body_sha256)||!Object.hasOwn(localClaimLabels,String(c.status))||c.environment!=='LOCAL_TEST_SINK'||!source.rows.some(r=>r.key===c.condition_key&&r.rule_id===c.rule_id)||!stamp(c.created_at)||c.finished_at!==null&&(!stamp(c.finished_at)||Date.parse(c.finished_at)<Date.parse(c.created_at))||c.status==='CLAIMED'&&(c.finished_at!==null||c.reason!==null)||c.status!=='CLAIMED'&&(c.finished_at===null||typeof c.reason!=='string'||!c.reason)||c.body!==null&&(typeof c.body!=='string'||!c.body.startsWith('PRATINJAU LOKAL — BELUM DIKIRIM')||c.source_hash!==source.hash||c.status==='SUPPRESSED')||ids.has(c.id)||occurrences.has(JSON.stringify([c.binding_id,c.occurrence_key])))fail();if(c.body!==null&&c.body!==localPreviewBody(source.rows.find(r=>r.key===c.condition_key)!))fail();ids.add(c.id as string);occurrences.add(JSON.stringify([c.binding_id,c.occurrence_key]));if(c.resolution!==null){const x=closed(c.resolution,['id','outcome','reason','created_at']);if(!uuid(x.id)||c.status!=='UNKNOWN'||!['CAPTURE_CONFIRMED','NOT_CAPTURED_CONFIRMED'].includes(String(x.outcome))||typeof x.reason!=='string'||!x.reason.trim()||x.reason.length>1000||!stamp(x.created_at)||Date.parse(x.created_at)<Date.parse(c.finished_at as string))fail()}return structuredClone(c) as LocalClaim})
 await Promise.all(claims.filter(c=>c.body!==null).map(async c=>{const bytes=new TextEncoder().encode(c.body!);if(bytes.byteLength>8000000)fail();const digest=Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',bytes)),x=>x.toString(16).padStart(2,'0')).join('');if(digest!==c.body_sha256)fail()}))
 return{source,binding,claims}
}
export async function parseLocalCommand(v:unknown,r:RuleRequest,actor:string,finance:AnalysisFinanceAccess,rights:RuleRights):Promise<{workspace:LocalWorkspace;status:'COMMITTED'|'NOT_COMMITTED'}>{
 const e=closed(v,['contract_version','actor_scope_id','operation','workspace','result']);if(e.contract_version!=='cp7.native-local-command.v1'||e.actor_scope_id!==actor||e.operation!==r.operation||r.operation==='EPISODES')fail()
 const workspace=await parseLocalWorkspace(e.workspace,r.query,actor,finance,rights);if(workspace.source.analysis.runId!==r.payload.run_id)fail()
 const res=closed(e.result,['request_id','status',...(r.operation==='BINDING'?['binding_id','revision']:r.operation==='PREVIEW'?['claim_id','fence']:r.operation==='OUTCOME'?['claim_id','local_status']:['claim_id','resolution_id'])]);if(res.request_id!==r.id||!['COMMITTED','NOT_COMMITTED'].includes(String(res.status)))fail()
 if(r.operation==='BINDING'){if(res.status==='NOT_COMMITTED'?(res.binding_id!==null||res.revision!==null):!uuid(res.binding_id)||!uint(res.revision)||BigInt(res.revision)!==BigInt(r.payload.expected_revision as string)+1n||!workspace.binding||BigInt(workspace.binding.revision)<BigInt(res.revision)||workspace.binding.revision===res.revision&&(workspace.binding.id!==res.binding_id||workspace.binding.enabled!==r.payload.enabled||workspace.binding.label!==r.payload.label||canonical(workspace.binding.rules)!==canonical(r.payload.rules)||workspace.binding.reason!==r.payload.reason))fail()}
 else if(res.status==='NOT_COMMITTED'){if(r.operation==='PREVIEW'?(res.claim_id!==null||res.fence!==null):res.claim_id!==r.payload.claim_id||(r.operation==='OUTCOME'?res.local_status:res.resolution_id)!==null)fail()}
 else{const claim=workspace.claims.find(c=>c.id===res.claim_id);if(!claim)return fail();if(r.operation==='PREVIEW'?(res.fence!==claim.fence||claim.condition_key!==r.payload.condition_key||claim.binding_id!==r.payload.binding_id):claim.id!==r.payload.claim_id||claim.fence!==r.payload.fence)fail();if(r.operation==='OUTCOME'&&(!Object.hasOwn(localClaimLabels,String(res.local_status))||res.local_status==='CLAIMED'||res.local_status!==claim.status)||r.operation==='RESOLUTION'&&(!claim.resolution||res.resolution_id!==claim.resolution.id||claim.resolution.outcome!==r.payload.outcome||claim.resolution.reason!==r.payload.reason))fail()}
 return{workspace,status:res.status as 'COMMITTED'|'NOT_COMMITTED'}
}
function validRequest(v:unknown):v is RuleRequest{try{const r=closed(v,['id','query','operation','payload']),q=closed(r.query,['from_date','through_date','group_mode']);if(!uuid(r.id)||!financeDate(q.from_date)||!financeDate(q.through_date)||q.from_date>q.through_date||!['AS_SOLD','RESTATED'].includes(String(q.group_mode))||JSON.stringify(v).length>12000)return false;const op=r.operation,p=closed(r.payload,op==='EPISODES'?['run_id','source_hash']:op==='BINDING'?['run_id','expected_revision','enabled','label','environment','rules','reason']:op==='PREVIEW'?['run_id','condition_key','source_hash','binding_id']:op==='OUTCOME'?['run_id','claim_id','fence','outcome']:op==='RESOLUTION'?['run_id','claim_id','fence','outcome','reason']:[]);if(!uuid(p.run_id))return false;if(op==='EPISODES')return hash(p.source_hash);if(op==='PREVIEW')return hash(p.source_hash)&&uuid(p.binding_id)&&typeof p.condition_key==='string'&&p.condition_key.length>0&&p.condition_key.length<=250;if(op==='OUTCOME'||op==='RESOLUTION')return uuid(p.claim_id)&&uuid(p.fence)&&(op==='OUTCOME'?['LOCAL_CAPTURE','UNKNOWN'].includes(String(p.outcome)):['CAPTURE_CONFIRMED','NOT_CAPTURED_CONFIRMED'].includes(String(p.outcome))&&typeof p.reason==='string'&&p.reason.trim().length>0&&p.reason.length<=1000);return op==='BINDING'&&uint(p.expected_revision)&&BigInt(p.expected_revision)<9223372036854775807n&&typeof p.enabled==='boolean'&&p.environment==='LOCAL_TEST_SINK'&&typeof p.label==='string'&&p.label.trim().length>0&&p.label.length<=120&&typeof p.reason==='string'&&p.reason.trim().length>0&&p.reason.length<=1000&&Array.isArray(p.rules)&&p.rules.length>0&&p.rules.length<=4&&p.rules.every(r=>reminderRuleIds.includes(r))&&new Set(p.rules).size===p.rules.length}catch{return false}}
export function readRuleRequest(scope:string):{pending:RuleRequest|null;error:string|null}{try{const raw=localStorage.getItem(ruleRequestKey(scope));if(raw===null)return{pending:null,error:null};const r=JSON.parse(raw);if(!validRequest(r))throw Error();return{pending:r,error:null}}catch{return{pending:null,error:'Permintaan kondisi atau pratinjau lokal belum bisa dibaca. Isinya dipertahankan.'}}}
export function persistRuleRequest(scope:string,r:RuleRequest){if(!validRequest(r))fail();const held=readRuleRequest(scope);if(held.error||held.pending&&canonical(held.pending)!==canonical(r))throw Error('Pastikan hasil permintaan lokal yang tertunda.');localStorage.setItem(ruleRequestKey(scope),JSON.stringify(r));if(canonical(readRuleRequest(scope).pending)!==canonical(r))throw Error('Permintaan lokal belum tersimpan.')}
export function clearRuleRequest(scope:string,id:string){const held=readRuleRequest(scope);if(held.error||held.pending?.id!==id)throw Error('Permintaan lokal berubah.');localStorage.removeItem(ruleRequestKey(scope));if(localStorage.getItem(ruleRequestKey(scope))!==null)throw Error('Permintaan lokal belum bisa dibersihkan.')}
