export type CuttingFamily={brand:string;mill:string;variant:string;spec_revision:string}
export type CuttingInputPayload={group_id:string;expected_group_version:string;expected_input_version:string|null;marker_key:string;planned_mix:{size_id:string;drawings:string}[];roll_inputs:{roll_id:string;family:CuttingFamily;width_cm:string|null}[];explicit_review:true}
export type CuttingInputIntent={id:string;payload:CuttingInputPayload}
type Anchor={group_id:string;po_id:string;pattern_id:string;pattern_revision:string;rolls:{roll_id:string;material_id:string;unit:string}[];size_ids:string[]}
type Group={id:string;po_id:string;version:string;physical_at:string;posted:boolean;pattern_id:string|null;pattern_revision:string|null}
type InputRecord={id:string;actor_scope_id:string;group_id:string;request_id:string;version:string;previous_id:string|null;known_at:string;native_anchor:Anchor;original_native_group:Group;values:{rolls:{roll_id:string;material_id:string;context:{family:CuttingFamily;pattern_id:string;pattern_revision:string;marker_key:string;unit:string;planned_mix:CuttingInputPayload['planned_mix']};width_cm:string|null;width_basis:'UNKNOWN'|'OPERATOR_RECORDED_NOT_INFERRED'}[];planned_mix:CuttingInputPayload['planned_mix'];provenance:string;output_mix_is_not_preknown_planned_mix:true;automatic_activation:false;business_write:false;production_go:false}}
export type CuttingInputWorkspace={contract_version:string;actor_scope_id:string;requested_group_id:string;size_labels:Record<string,string>;roll_labels:Record<string,string>;group:Group|null;anchor:Anchor|null;record:InputRecord|null;record_matches_native_identity:boolean;preknown_before_physical:boolean;can_record:boolean;model_qualified:false;automatic_activation:false;business_write:false;production_go:false}
const fail=():never=>{throw Error('Rencana potong tidak lengkap atau tidak cocok dengan sumber. Muat ulang.')}
const obj=(v:unknown)=>v&&typeof v==='object'&&!Array.isArray(v)?v as Record<string,unknown>:fail()
const closed=(v:unknown,keys:string[])=>{const r=obj(v);if(Object.keys(r).length!==keys.length||keys.some(k=>!(k in r)))fail();return r}
const text=(v:unknown)=>typeof v==='string'&&v.trim().length>0&&v.length<=200?v:fail()
const id=(v:unknown)=>typeof v==='string'&&/^[0-9a-f]{8}(-[0-9a-f]{4}){3}-[0-9a-f]{12}$/.test(v)?v:fail()
const version=(v:unknown)=>typeof v==='string'&&/^[1-9][0-9]{0,18}$/.test(v)&&BigInt(v)<=9223372036854775807n?v:fail()
const decimal=(v:unknown)=>typeof v==='string'&&v.length<=200&&/^[0-9]+(\.[0-9]+)?$/.test(v)&&/[1-9]/.test(v)?v:fail()
const time=(v:unknown)=>typeof v==='string'&&/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(\.\d{1,6})?(Z|[+-]\d{2}:\d{2})$/.test(v)&&Number.isFinite(Date.parse(v))?v:fail()
function ticks(v:string){time(v);const fraction=/\.(\d{1,6})/.exec(v)?.[1]??'';return BigInt(Date.parse(v))*1000n+BigInt(fraction.padEnd(6,'0').slice(3))}
function labels(v:unknown){const r=obj(v);if(Object.keys(r).length>1000)fail();return Object.fromEntries(Object.entries(r).map(([k,v])=>[id(k),text(v)]))}
const bool=(v:unknown)=>typeof v==='boolean'?v:fail()
const list=(v:unknown)=>Array.isArray(v)&&v.length>0&&v.length<=1000?v:fail()
function unique<T>(rows:T[],key:(r:T)=>string){if(new Set(rows.map(key)).size!==rows.length)fail();return rows}
function family(v:unknown):CuttingFamily{const r=closed(v,['brand','mill','variant','spec_revision']);return{brand:text(r.brand),mill:text(r.mill),variant:text(r.variant),spec_revision:text(r.spec_revision)}}
function mix(v:unknown){return unique(list(v).map(x=>{const r=closed(x,['size_id','drawings']);const n=version(r.drawings);if(BigInt(n)>2147483647n)fail();return{size_id:id(r.size_id),drawings:n}}),x=>x.size_id)}
function normalizedMix(v:CuttingInputPayload['planned_mix']){const gcd=(a:bigint,b:bigint):bigint=>b===0n?a:gcd(b,a%b);const divisor=v.reduce((n,x)=>gcd(n,BigInt(x.drawings)),0n);return v.map(x=>({size_id:x.size_id,drawings:(BigInt(x.drawings)/divisor).toString()})).sort((a,b)=>a.size_id.localeCompare(b.size_id))}
function group(v:unknown):Group{const r=closed(v,['id','po_id','version','physical_at','posted','pattern_id','pattern_revision']);return{id:id(r.id),po_id:id(r.po_id),version:version(r.version),physical_at:time(r.physical_at),posted:bool(r.posted),pattern_id:r.pattern_id===null?null:id(r.pattern_id),pattern_revision:r.pattern_revision===null?null:text(r.pattern_revision)}}
function anchor(v:unknown):Anchor{const r=closed(v,['group_id','po_id','pattern_id','pattern_revision','rolls','size_ids']);return{group_id:id(r.group_id),po_id:id(r.po_id),pattern_id:id(r.pattern_id),pattern_revision:text(r.pattern_revision),rolls:unique(list(r.rolls).map(x=>{const row=closed(x,['roll_id','material_id','unit']);return{roll_id:id(row.roll_id),material_id:id(row.material_id),unit:text(row.unit)}}),x=>x.roll_id),size_ids:unique(list(r.size_ids).map(id),x=>x)}}
function record(v:unknown):InputRecord{
 const r=closed(v,['id','actor_scope_id','group_id','request_id','version','previous_id','known_at','values','native_anchor','original_native_group']),a=anchor(r.native_anchor),g=group(r.original_native_group),val=closed(r.values,['rolls','planned_mix','provenance','output_mix_is_not_preknown_planned_mix','automatic_activation','business_write','production_go'])
 if(val.provenance!=='EXPLICIT_OPERATOR_INPUT_BOUND_TO_NATIVE_IDENTITIES'||val.output_mix_is_not_preknown_planned_mix!==true||val.automatic_activation!==false||val.business_write!==false||val.production_go!==false||id(r.group_id)!==a.group_id||g.id!==a.group_id||g.po_id!==a.po_id)fail()
 const planned_mix=mix(val.planned_mix),rolls=unique(list(val.rolls).map(x=>{const row=closed(x,['roll_id','material_id','context','width_cm','width_basis']),c=closed(row.context,['family','pattern_id','pattern_revision','marker_key','unit','planned_mix']),native=a.rolls.find(y=>y.roll_id===row.roll_id),cm=row.width_cm===null?null:decimal(row.width_cm)
  if(!native||row.material_id!==native.material_id||c.unit!==native.unit||c.pattern_id!==a.pattern_id||c.pattern_revision!==a.pattern_revision||JSON.stringify(mix(c.planned_mix))!==JSON.stringify(planned_mix)||row.width_basis!==(cm===null?'UNKNOWN':'OPERATOR_RECORDED_NOT_INFERRED'))fail()
  return{roll_id:id(row.roll_id),material_id:id(row.material_id),context:{family:family(c.family),pattern_id:id(c.pattern_id),pattern_revision:text(c.pattern_revision),marker_key:text(c.marker_key),unit:text(c.unit),planned_mix},width_cm:cm,width_basis:row.width_basis as 'UNKNOWN'|'OPERATOR_RECORDED_NOT_INFERRED'}
 }),x=>x.roll_id)
 if(rolls.length!==a.rolls.length||planned_mix.some(x=>!a.size_ids.includes(x.size_id)))fail()
 return{id:id(r.id),actor_scope_id:id(r.actor_scope_id),group_id:id(r.group_id),request_id:id(r.request_id),version:version(r.version),previous_id:r.previous_id===null?null:id(r.previous_id),known_at:time(r.known_at),native_anchor:a,original_native_group:g,values:{rolls,planned_mix,provenance:text(val.provenance),output_mix_is_not_preknown_planned_mix:true,automatic_activation:false,business_write:false,production_go:false}}
}
export function parseCuttingInputWorkspace(value:unknown,groupId:string):CuttingInputWorkspace{
 const v=closed(value,['contract_version','actor_scope_id','requested_group_id','size_labels','roll_labels','group','anchor','record','record_matches_native_identity','preknown_before_physical','can_record','model_qualified','automatic_activation','business_write','production_go'])
 if(v.contract_version!=='cp7.native-cutting-input-workspace.v1'||v.model_qualified!==false||v.automatic_activation!==false||v.business_write!==false||v.production_go!==false)fail()
 const size_labels=labels(v.size_labels),roll_labels=labels(v.roll_labels),actor=id(v.actor_scope_id),g=v.group===null?null:group(v.group),a=v.anchor===null?null:anchor(v.anchor),r=v.record===null?null:record(v.record)
 if(a&&(Object.keys(size_labels).length!==a.size_ids.length||a.size_ids.some(s=>!size_labels[s])||Object.keys(roll_labels).length!==a.rolls.length||a.rolls.some(r=>!roll_labels[r.roll_id]))||!g&&(Object.keys(size_labels).length>0||Object.keys(roll_labels).length>0)||id(v.requested_group_id)!==id(groupId)||v.preknown_before_physical!==Boolean(r&&g&&ticks(r.known_at)<ticks(g.physical_at))||v.record_matches_native_identity!==Boolean(r&&a&&JSON.stringify(r.native_anchor)===JSON.stringify(a))||g&&g.id!==groupId||a&&(!g||a.group_id!==g.id||a.po_id!==g.po_id||a.pattern_id!==g.pattern_id||a.pattern_revision!==g.pattern_revision)||r&&(r.group_id!==groupId||r.actor_scope_id!==actor)||v.can_record===true&&(!g||!a))fail()
 return{contract_version:text(v.contract_version),actor_scope_id:actor,requested_group_id:groupId,size_labels,roll_labels,group:g,anchor:a,record:r,record_matches_native_identity:bool(v.record_matches_native_identity),preknown_before_physical:bool(v.preknown_before_physical),can_record:bool(v.can_record),model_qualified:false,automatic_activation:false,business_write:false,production_go:false}
}
export function parseCuttingInputCommand(value:unknown,intent:CuttingInputIntent){
 const v=closed(value,['contract_version','result','current','business_write','automatic_activation','production_go']),r=closed(v.result,['status','request_id','record'])
 if(v.contract_version!=='cp7.native-cutting-input-command.v1'||v.business_write!==false||v.automatic_activation!==false||v.production_go!==false||r.request_id!==intent.id||!['COMMITTED','NOT_COMMITTED'].includes(String(r.status)))fail()
 const current=parseCuttingInputWorkspace(v.current,intent.payload.group_id),saved=r.record===null?null:record(r.record)
 if((r.status==='COMMITTED')!==Boolean(saved)||saved&&(saved.request_id!==intent.id||saved.actor_scope_id!==current.actor_scope_id||saved.group_id!==intent.payload.group_id||saved.original_native_group.version!==intent.payload.expected_group_version||saved.version!==(BigInt(intent.payload.expected_input_version??'0')+1n).toString()||Boolean(saved.previous_id)!==Boolean(intent.payload.expected_input_version)||JSON.stringify(saved.values.planned_mix)!==JSON.stringify(normalizedMix(intent.payload.planned_mix))||saved.values.rolls.length!==intent.payload.roll_inputs.length||saved.values.rolls.some(roll=>{const p=intent.payload.roll_inputs.find(x=>x.roll_id===roll.roll_id);return !p||roll.context.marker_key!==intent.payload.marker_key||roll.width_cm!==p.width_cm||JSON.stringify(roll.context.family)!==JSON.stringify(p.family)})))fail()
 return{current,result:{status:r.status as 'COMMITTED'|'NOT_COMMITTED',record:saved}}
}
export function validateCuttingInputPayload(v:unknown):CuttingInputPayload{
 const r=closed(v,['group_id','expected_group_version','expected_input_version','marker_key','planned_mix','roll_inputs','explicit_review']);if(r.explicit_review!==true)fail()
 return{group_id:id(r.group_id),expected_group_version:version(r.expected_group_version),expected_input_version:r.expected_input_version===null?null:version(r.expected_input_version),marker_key:text(r.marker_key),planned_mix:mix(r.planned_mix),roll_inputs:unique(list(r.roll_inputs).map(x=>{const row=closed(x,['roll_id','family','width_cm']);return{roll_id:id(row.roll_id),family:family(row.family),width_cm:row.width_cm===null?null:decimal(row.width_cm)}}),x=>x.roll_id),explicit_review:true}
}
export const cuttingInputKey=(scope:string)=>'erp.cp7.cutting-input-intent.v1:'+scope
export function heldCuttingInput(scope:string):{pending:CuttingInputIntent|null;error:string}{try{const raw=localStorage.getItem(cuttingInputKey(scope));if(raw===null)return{pending:null,error:''};const r=closed(JSON.parse(raw),['id','payload']);return{pending:{id:id(r.id),payload:validateCuttingInputPayload(r.payload)},error:''}}catch{return{pending:null,error:'Catatan rencana belum dapat dipulihkan. Periksa penyimpanan sebelum menyimpan lagi.'}}}
export function holdCuttingInput(scope:string,r:CuttingInputIntent){const held=heldCuttingInput(scope);if(held.pending||held.error)throw Error('Pulihkan rencana tersimpan terlebih dahulu.');id(r.id);validateCuttingInputPayload(r.payload);const raw=JSON.stringify(r);localStorage.setItem(cuttingInputKey(scope),raw);if(localStorage.getItem(cuttingInputKey(scope))!==raw)throw Error('Catatan belum tersimpan; permintaan ditahan.')}
export function releaseCuttingInput(scope:string,r:CuttingInputIntent){const held=heldCuttingInput(scope);if(held.error||held.pending?.id!==r.id||JSON.stringify(held.pending.payload)!==JSON.stringify(r.payload))throw Error('Catatan permintaan berubah.');localStorage.removeItem(cuttingInputKey(scope));if(localStorage.getItem(cuttingInputKey(scope))!==null)throw Error('Catatan pemulihan belum selesai.')}
