// @vitest-environment jsdom
import {act,useRef,useState} from 'react'
import {createRoot,type Root} from 'react-dom/client'
import {beforeEach,afterEach,it,expect,vi} from 'vitest'
import NativeRuleSourcePanel from './NativeRuleSourcePanel'
import {parseNativeAnalysis,type NativeAnalysis} from './nativeAnalysis'
import {readRuleRequest,type RuleRequest} from './nativeRuleSource'
import {ruleSourceFixture,localWorkspaceFixture,localBindingCommandFixture,ruleFixtureActor} from '../tests/fixtures/nativeRuleSource'
import original from '../tests/fixtures/nativeAnalysisStandin.json'
import {recoveryIdentity} from '../tests/fixtures/productionRecovery'
import type {NativeDemandQuery} from './nativeDemandHistory'
const state=vi.hoisted(()=>({auth:null as unknown}))
const client=vi.hoisted(()=>({rpc:vi.fn()}))
vi.mock('./auth/AuthProvider',()=>({useAuth:()=>state.auth}));vi.mock('./lib/supabase',()=>({getUatSupabaseClient:()=>client}))
const q=original.query as NativeDemandQuery,access={ownerReports:false,preflight:false},scope='analysis:cp6-disposable:actor-1'
let container:HTMLDivElement,root:Root
function Host(){const seq=useRef(0),[generation,setGeneration]=useState(0),[context,setContext]=useState<NativeAnalysis|null>(()=>parseNativeAnalysis(original,q,ruleFixtureActor,access));return <><button onClick={()=>setContext(parseNativeAnalysis(original,q,ruleFixtureActor,access))}>Restore test Original</button><NativeRuleSourcePanel context={context} generation={generation} blocked={false} access={access} onReadStart={()=>{const n=++seq.current;setGeneration(n);setContext(null);return n}} isReadCurrent={n=>seq.current===n} onReadEnd={()=>{}} onAnalysis={(a,n)=>{if(seq.current===n)setContext(a)}} requireClear={()=>{}}/></>}
beforeEach(()=>{Object.assign(globalThis,{IS_REACT_ACT_ENVIRONMENT:true});localStorage.clear();client.rpc.mockReset();const a=structuredClone(recoveryIdentity);Object.assign(a.runtime,{mode:'DISPOSABLE_TEST',projectRef:'cp6-disposable'});Object.assign(a.identity.profile,{authUserId:ruleFixtureActor,role:'OWNER'});a.identity.permissions.push('master.product.view','production.wip.view','warehouse.stock.view','sales.invoice.view','master.product.manage','finance.ar.view','finance.ap.view');state.auth=a;Object.defineProperty(navigator,'locks',{configurable:true,value:{request:async(_n:string,_o:unknown,fn:(lock:object)=>unknown)=>fn({})}});container=document.createElement('div');document.body.append(container);root=createRoot(container)})
afterEach(async()=>{await act(async()=>root.unmount());container.remove();localStorage.clear();vi.restoreAllMocks()})
const render=async()=>act(async()=>root.render(<Host/>))
async function click(label:string){const b=[...container.querySelectorAll('button')].find(b=>b.textContent===label)!;expect(b).toBeTruthy();await act(async()=>b.click())}
async function fill(label:string,value:string){const f=container.querySelector<HTMLInputElement|HTMLTextAreaElement|HTMLSelectElement>(`[aria-label="${label}"]`)!;expect(f).toBeTruthy();await act(async()=>{const proto=f instanceof HTMLSelectElement?HTMLSelectElement.prototype:f instanceof HTMLTextAreaElement?HTMLTextAreaElement.prototype:HTMLInputElement.prototype;Object.getOwnPropertyDescriptor(proto,'value')!.set!.call(f,value);f.dispatchEvent(new Event(f instanceof HTMLSelectElement?'change':'input',{bubbles:true}))})}
async function check(label:string){await act(async()=>container.querySelector<HTMLInputElement>(`[aria-label="${label}"]`)!.click())}
it('loads source only on explicit request, keeps unknown supply unresolved, and creates no implicit local binding',async()=>{client.rpc.mockResolvedValue({data:ruleSourceFixture(),error:null});await render();expect(client.rpc).not.toHaveBeenCalled();await click('Periksa kondisi masalah ERP');expect(container.textContent).toContain('Tidak ada peringatan pada skenario ini');expect(container.textContent).toContain('Belum ada bukti sumber bahwa masalah ini selesai.');expect(container.textContent).toContain('Data perlu diperiksa');expect(client.rpc).toHaveBeenCalledTimes(1);expect(readRuleRequest(scope).pending).toBeNull()})
it('preserves exact intent after a lost local binding commit and resolves it after remount without another write',async()=>{let saved:RuleRequest|null=null;client.rpc.mockImplementation(async(name:string)=>{if(name==='erp_cp7_get_local_reminders_v1')return{data:localWorkspaceFixture(),error:null};const r=readRuleRequest(scope).pending!;if(name==='erp_cp7_save_local_binding_v1'){saved=r;throw Error('Lost commit response')}return{data:localBindingCommandFixture(r),error:null}});await render();await click('Muat pratinjau lokal tersimpan');await fill('Nama tujuan lokal','Pemeriksaan lokal saya');await fill('Status tujuan lokal','true');await check('Tujuan lokal Piutang jatuh tempo');await fill('Alasan tujuan lokal','Tujuan kontrak lokal ditinjau');await check('Tujuan lokal sudah ditinjau');await click('Simpan versi tujuan lokal');expect(saved).toBeTruthy();expect(readRuleRequest(scope).pending).toEqual(saved);await act(async()=>root.unmount());root=createRoot(container);await render();await click('Pastikan hasil kondisi di server');expect(client.rpc.mock.calls.at(-1)![1]).toMatchObject(client.rpc.mock.calls[1][1]);expect(client.rpc.mock.calls.at(-1)![1].p_operation).toBe('BINDING');expect(readRuleRequest(scope).pending).toBeNull();expect(container.textContent).toContain('Tujuan lokal: Pemeriksaan lokal saya · versi 1 · aktif.');expect(container.querySelector<HTMLInputElement>('[aria-label="Nama tujuan lokal"]')?.value).toBe('');expect(client.rpc.mock.calls.filter(c=>c[0]==='erp_cp7_save_local_binding_v1')).toHaveLength(1)})
it('retires all source/local facts during held current403 and restores unsent input only after a new authorized read',async()=>{client.rpc.mockResolvedValue({data:localWorkspaceFixture(),error:null});await render();await click('Muat pratinjau lokal tersimpan');await fill('Nama tujuan lokal','Isian lokal belum disimpan');await fill('Alasan tujuan lokal','Alasan operator tetap');let finish!:(r:unknown)=>void;client.rpc.mockImplementation(()=>new Promise(resolve=>{finish=resolve}));await click('Muat pratinjau lokal tersimpan');expect(container.textContent).not.toContain('Kondisi diperiksa');expect(container.textContent).not.toContain('Belum ada tujuan pratinjau lokal.');await act(async()=>finish({data:null,error:{code:'42501',message:'Current access denied'}}));expect(container.textContent).not.toContain('Kondisi diperiksa');client.rpc.mockResolvedValue({data:localWorkspaceFixture(),error:null});await click('Restore test Original');await click('Muat pratinjau lokal tersimpan');expect(container.querySelector<HTMLInputElement>('[aria-label="Nama tujuan lokal"]')?.value).toBe('Isian lokal belum disimpan');expect(container.querySelector<HTMLTextAreaElement>('[aria-label="Alasan tujuan lokal"]')?.value).toBe('Alasan operator tetap')})
