// @vitest-environment jsdom
import{describe,it,expect,beforeEach}from'vitest'
import{parseNativeObligationObservation as parse,readObligationRequest,persistObligationRequest,clearObligationRequest,obligationRequestKey,type ObligationRequest}from'./nativeObligationEpisodes'
import{nativeEpisodeFixture as fixture}from'../tests/fixtures/nativeObligationEpisodes'
import original from'../tests/fixtures/nativeAnalysisStandin.json'
import type{NativeDemandQuery}from'./nativeDemandHistory'
const q=original.query as NativeDemandQuery,actor=original.analysis.scope.actor_scope_id,finance={ownerReports:false,preflight:false},read=(e=fixture())=>parse(e,q,actor,finance,'AR',true)
describe('Native saved obligation observations and stable command recovery',()=>{
 beforeEach(()=>localStorage.clear())
 it('keeps exact source revisions and deep-owned immutable Original/episode observations, separate from live balances',()=>{const e=fixture(),x=read(e);expect(x.rows[0].source_revision).toBe('9007199254740993');expect(x.analysis.analysis).toEqual(original.analysis);expect(x.rows[0].episode?.id).toBe(e.result.rows[0].episode.id);e.result.rows[0].episode.state='RESOLVED';expect(x.rows[0].episode?.state).toBe('ACTIVE');expect(JSON.stringify(x.rows)).not.toContain('remaining')})
 it('accepts actual source resolution and linked recurrence while refusing a healthy/closed unknown observation',()=>{const e=fixture(),r=e.result.rows[0];Object.assign(r,{condition_state:'ZERO_BALANCE',business_resolved:true,reason:'NATIVE_ZERO_AND_REQUIRED_INVOICE_COVERAGE',transition:'RESOLVED'});Object.assign(r.episode,{state:'RESOLVED',closed_at:e.result.observed_at});expect(read(e).rows[0].episode?.state).toBe('RESOLVED');Object.assign(r,{condition_state:'OVERDUE',business_resolved:false,reason:'NATIVE_CONDITION_REQUIRES_REVIEW',transition:'REOPENED_NEW_EPISODE'});Object.assign(r.episode,{id:'00000000-0000-4000-8000-000000000902',number:'2',previous_episode_id:'00000000-0000-4000-8000-000000000901',state:'ACTIVE',closed_at:null});expect(read(e).rows[0].episode?.previous_episode_id).toBe('00000000-0000-4000-8000-000000000901');r.freshness='UNKNOWN';expect(()=>read(e)).toThrow()})
 it('preserves active age and last-known time for partial and missing Native sources',()=>{const e=fixture(),r=e.result.rows[0];Object.assign(e.result,{source_status:'INCOMPLETE',source_hash:null,as_of:null,source_read_at:null,source_total:null});Object.assign(r,{condition_state:'SOURCE_UNKNOWN',freshness:'UNKNOWN',reason:'SOURCE_INCOMPLETE',native_source_hash:null,transition:'DATA_UNKNOWN'});r.episode.freshness='UNKNOWN';expect(read(e).rows[0].episode?.last_known_observed_at).toBe(r.episode.first_observed_at);r.business_resolved=true;expect(()=>read(e)).toThrow();r.business_resolved=false;Object.assign(e.result,{source_status:'COMPLETE',source_hash:'a'.repeat(64),as_of:'2026-10-01',source_read_at:'2026-10-01T00:00:00+00:00',source_total:'0'});r.reason='MISSING_FROM_COMPLETE_SOURCE';expect(read(e).rows[0].episode?.state).toBe('ACTIVE')})
 it('requires current actor/domain authority, complete Native count/clock, unique source and linked episode identity',()=>{const changes:((e:ReturnType<typeof fixture>)=>void)[]=[e=>{e.actor_scope_id='foreign'},e=>{e.result.domain='MATERIAL_AP'},e=>{e.result.source_total='2'},e=>{e.result.rows.push(structuredClone(e.result.rows[0]));e.result.source_total='2'},e=>{e.result.as_of='2026-09-30'},e=>{e.result.rows[0].episode.previous_episode_id=e.result.rows[0].episode.id},e=>{e.result.rows[0].episode.number='2'}];for(const change of changes){const e=fixture();change(e);expect(()=>read(e)).toThrow()}expect(()=>parse(fixture(),q,actor,finance,'AR',false)).toThrow()})
 it('stores only a verified stable intent; changed/corrupt envelopes remain blocked and absent resolution contains no observations',()=>{const r:ObligationRequest={id:fixture().result.request_id,query:q,semanticHash:original.analysis.semantic_hash,payload:{run_id:original.run_id,domain:'AR'}};persistObligationRequest('own',r);persistObligationRequest('own',r);expect(readObligationRequest('own').pending).toEqual(r);expect(localStorage.getItem(obligationRequestKey('own'))).not.toContain('episode');expect(()=>persistObligationRequest('own',{...r,id:'00000000-0000-4000-8000-000000000802'})).toThrow();clearObligationRequest('own',r.id);localStorage.setItem(obligationRequestKey('own'),'broken');expect(readObligationRequest('own').error).toBeTruthy();expect(localStorage.getItem(obligationRequestKey('own'))).toBe('broken');const e=fixture();Object.assign(e.result,{status:'NOT_COMMITTED',source_status:'NOT_EVALUATED',source_hash:null,as_of:null,source_read_at:null,observed_at:null,source_total:null,rows:[]});expect(read(e).status).toBe('NOT_COMMITTED')})
})
