// @vitest-environment jsdom
import {afterEach,it,expect} from 'vitest'
import original from '../tests/fixtures/nativeAnalysisStandin.json'
import {emptyReminderConfig,reminderPolicyFixture,reminderPolicyRow} from '../tests/fixtures/nativeReminderPolicy'
import {parseNativeReminderPolicy,parseReminderPolicyConfig,persistReminderPolicyRequest,readReminderPolicyRequest,clearReminderPolicyRequest,reminderPolicyRequestKey,type ReminderPolicyRequest} from './nativeReminderPolicy'
import type {NativeDemandQuery} from './nativeDemandHistory'
const actor=original.analysis.scope.actor_scope_id,q=original.query as NativeDemandQuery,access={ownerReports:false,preflight:false},scope='policy-test'
const intent=():ReminderPolicyRequest=>({id:'00000000-0000-4000-8000-000000000031',query:q,payload:{run_id:original.run_id,rule_id:'PRODUCTION_GAP',scope_kind:'GLOBAL',scope_key:'*',expected_revision:'0',config:structuredClone(emptyReminderConfig),reason:'Keputusan contoh kontrak'}})
afterEach(()=>localStorage.clear())
it('retains blank, explicit zero and disabled values independently through a committed source-bound receipt',()=>{for(const enabled of [null,true,false]){const r=intent();r.payload.config.enabled=enabled;r.payload.config.threshold_value=enabled===null?null:'0';r.payload.config.cooldown_minutes=enabled===null?null:'0';r.payload.config.quiet.enabled=enabled===null?null:false;const parsed=parseNativeReminderPolicy(reminderPolicyFixture(original,[reminderPolicyRow(r)],r),q,actor,access,r);expect(parsed.rows[0].config).toEqual(r.payload.config);expect(parsed.analysis.analysis).toEqual(original.analysis)}})
it('rejects a committed receipt with absent, older, conflicting or changed settings while allowing exact old replay after a successor',()=>{const r=intent(),row=reminderPolicyRow(r),wire=reminderPolicyFixture(original,[row],r);const absent={...wire,rows:[],total:'0'};expect(()=>parseNativeReminderPolicy(absent,q,actor,access,r)).toThrow();const changed=structuredClone(wire);changed.rows[0].config.enabled=false;expect(()=>parseNativeReminderPolicy(changed,q,actor,access,r)).toThrow();const conflict=structuredClone(wire);conflict.rows[0].policy_id='00000000-0000-4000-8000-000000000099';expect(()=>parseNativeReminderPolicy(conflict,q,actor,access,r)).toThrow();const newer=structuredClone(wire);newer.rows[0]={...row,revision:'2',previous_id:row.policy_id,policy_id:'00000000-0000-4000-8000-000000000099',config:{...row.config,enabled:false}};expect(parseNativeReminderPolicy(newer,q,actor,access,r).result?.revision).toBe('1')})
it('accepts the same configuration under PostgreSQL JSON key ordering and refuses foreign, truncated or duplicate scopes',()=>{const r=intent(),row=reminderPolicyRow(r),wire=reminderPolicyFixture(original,[row],r);row.config={quiet:row.config.quiet,cooldown_minutes:null,threshold_unit:'PCS',threshold_value:null,enabled:null};wire.rows=[row];expect(parseNativeReminderPolicy(wire,q,actor,access,r).result?.status).toBe('COMMITTED');expect(()=>parseNativeReminderPolicy({...wire,actor_scope_id:'foreign'},q,actor,access,r)).toThrow();expect(()=>parseNativeReminderPolicy({...wire,page_complete:false},q,actor,access,r)).toThrow();expect(()=>parseNativeReminderPolicy({...wire,rows:[row,row],total:'2'},q,actor,access,r)).toThrow()})
it('requires explicit units and unambiguous quiet intervals without converting missing fields or fractional overdue days',()=>{expect(()=>parseReminderPolicyConfig({...emptyReminderConfig,threshold_value:'0',threshold_unit:null},'PRODUCTION_GAP')).toThrow();expect(()=>parseReminderPolicyConfig({...emptyReminderConfig,threshold_value:'1.5',threshold_unit:'DAY'},'AR_DUE')).toThrow();expect(()=>parseReminderPolicyConfig({...emptyReminderConfig,quiet:{enabled:true,starts_at:'22:00',ends_at:'22:00',timezone:'Asia/Jakarta'}},'PRODUCTION_GAP')).toThrow();expect(parseReminderPolicyConfig({...emptyReminderConfig,quiet:{enabled:true,starts_at:'22:00',ends_at:'06:00',timezone:'Asia/Jakarta'}},'PRODUCTION_GAP').quiet.ends_at).toBe('06:00')})
it('persists only exact actor-scoped intent, fences replacement and never silently clears corrupt recovery',()=>{const r=intent();persistReminderPolicyRequest(scope,r);expect(readReminderPolicyRequest(scope).pending).toEqual(r);expect(localStorage.getItem(reminderPolicyRequestKey(scope))).not.toContain('financial_source');expect(()=>persistReminderPolicyRequest(scope,{...r,id:'00000000-0000-4000-8000-000000000032'})).toThrow();expect(()=>clearReminderPolicyRequest(scope,'different')).toThrow();clearReminderPolicyRequest(scope,r.id);expect(readReminderPolicyRequest(scope).pending).toBeNull();localStorage.setItem(reminderPolicyRequestKey(scope),'{broken');expect(readReminderPolicyRequest(scope).error).toBeTruthy();expect(()=>persistReminderPolicyRequest(scope,r)).toThrow();expect(localStorage.getItem(reminderPolicyRequestKey(scope))).toBe('{broken')})
