// @vitest-environment jsdom
import {beforeEach,it,expect} from 'vitest'
import original from '../tests/fixtures/nativeAnalysisStandin.json'
import {fabricAnalysisFixture,fabricConfig,fabricWorkspaceFixture,fabricOutcomeFixture} from '../tests/fixtures/nativeFabricRecipe'
import {parseFabricConfig,parseFabricWorkspace,checkFabricOutcome,persistFabricRequest,readFabricRequest,clearFabricRequest,fabricRequestKey,type FabricRequest} from './nativeFabricRecipe'
import {parseNativeAnalysis,analysisPrompt,analysisReport} from './nativeAnalysis'
import {fabricRecipeId,fabricMaterialId} from '../tests/fixtures/nativeFabricRecipe'
import type {NativeDemandQuery} from './nativeDemandHistory'
const q=original.query as NativeDemandQuery,actor=original.analysis.scope.actor_scope_id,target=original.analysis.recommendations[0].target.key,access={ownerReports:false,preflight:false}
const request=():FabricRequest=>({id:'00000000-0000-4000-8000-00000000f010',payload:{run_id:original.run_id,target_key:target,source_hash:original.analysis.snapshot.source_hash,expected_revision:'0',config:structuredClone(fabricConfig),reason:'Explicit receiver fixture review'}})
beforeEach(()=>localStorage.clear())
it('binds the workspace to the complete same global analysis and honest material/pattern pages',()=>{const w=parseFabricWorkspace(fabricWorkspaceFixture(),q,actor,target,access);expect(w.analysis.runId).toBe(original.run_id);expect(w.patterns[0].revision).toBe('R1');expect(w.materials[0].unit).toBe('M')})
it('rejects truncated, duplicate, foreign, stale or promoted metadata pages',()=>{for(const change of[(w:ReturnType<typeof fabricWorkspaceFixture>)=>{w.materials=[]},(w:ReturnType<typeof fabricWorkspaceFixture>)=>{w.materials.push(structuredClone(w.materials[0]))},(w:ReturnType<typeof fabricWorkspaceFixture>)=>{w.actor_scope_id='foreign'},(w:ReturnType<typeof fabricWorkspaceFixture>)=>{w.analysis.source_state='ARCHIVED_STALE'},(w:ReturnType<typeof fabricWorkspaceFixture>)=>{w.production_go=true}]){const w=fabricWorkspaceFixture();change(w);expect(()=>parseFabricWorkspace(w,q,actor,target,access)).toThrow()}})
it('keeps micro decimals and an optional pattern, while refusing zero, mixed types and an invalid effective window',()=>{expect(parseFabricConfig({...fabricConfig,qty_per_good_pcs:'0.000001',pattern_id:null,pattern_hash:null}).qty_per_good_pcs).toBe('0.000001');for(const change of[{qty_per_good_pcs:'0'},{qty_per_good_pcs:'-1'},{qty_per_good_pcs:2},{effective_to:fabricConfig.effective_from},{pattern_id:null},{effective_from:'2026-02-30T00:00:00Z'}])expect(()=>parseFabricConfig({...fabricConfig,...change})).toThrow()})
it('preserves the fabric rate as an assumption in shared report and AI, without installation or feasibility credit',()=>{const x=fabricAnalysisFixture(),a=parseNativeAnalysis(x,q,actor);expect(a.analysis.material_needs.at(-1)?.gross.state).toBe('ASSUMED');expect(analysisReport(a)).toContain('Kain fixture');expect(analysisPrompt(a,'Periksa kain')).toContain('CP7_FABRIC_RECIPE');expect(a.analysis.recommendations[0].feasible_new.state).toBe('UNKNOWN')})
it('refuses Native fabric proof invented from a recipe or an unreferenced rate',()=>{for(const change of[(x:ReturnType<typeof fabricAnalysisFixture>)=>{const m=x.analysis.material_needs.at(-1)!;m.installed_proven={state:'KNOWN',value:'60',unit:'M',refs:m.gross.refs}},(x:ReturnType<typeof fabricAnalysisFixture>)=>{const m=x.analysis.material_needs.at(-1)!;m.gross={state:'KNOWN',value:'186',unit:'M',refs:m.gross.refs}},(x:ReturnType<typeof fabricAnalysisFixture>)=>{x.analysis.material_needs.at(-1)!.gross.refs=[]},(x:ReturnType<typeof fabricAnalysisFixture>)=>{x.analysis.assumptions=x.analysis.assumptions.filter(a=>a.id!==fabricRecipeId)}]){const x=fabricAnalysisFixture();change(x);expect(()=>parseNativeAnalysis(x,q,actor)).toThrow()}})
it('persists one exact request, survives reload and rejects overwrite, foreign receipt or wrong clearing',()=>{const r=request();persistFabricRequest('fixture',r);expect(readFabricRequest('fixture').pending).toEqual(r);expect(()=>persistFabricRequest('fixture',r)).toThrow();checkFabricOutcome(fabricOutcomeFixture(r),r,actor);expect(()=>checkFabricOutcome({...fabricOutcomeFixture(r),revision:'2'},r,actor)).toThrow();expect(()=>clearFabricRequest('fixture','foreign')).toThrow();clearFabricRequest('fixture',r.id);expect(readFabricRequest('fixture').pending).toBeNull()})
it('fails closed on corrupted pending storage across the next attempt',()=>{localStorage.setItem(fabricRequestKey('fixture'),'broken');expect(readFabricRequest('fixture').error).toBeTruthy();expect(()=>persistFabricRequest('fixture',request())).toThrow();expect(localStorage.getItem(fabricRequestKey('fixture'))).toBe('broken')})
const physical=(x:ReturnType<typeof fabricAnalysisFixture>,installed='0',unused='10',external='176')=>{const m=x.analysis.material_needs.at(-1)!,refs=m.gross.refs,ids=[fabricRecipeId]
 m.installed_proven={state:'ASSUMED',value:installed,unit:'M',refs,assumption_ids:ids};m.unused_allocated_proven={state:'ASSUMED',value:unused,unit:'M',refs:[...refs,{kind:'CP7_FABRIC_FREE_STOCK',id:fabricMaterialId,revision:'e'.repeat(64)}],assumption_ids:ids}
 m.additional_external={state:'ASSUMED',value:external,unit:'M',refs,assumption_ids:ids};return x}
it('accepts P08 physical facts only within the shared kernel arithmetic: installed0, allocated10, external176 of gross186',()=>{const a=parseNativeAnalysis(physical(fabricAnalysisFixture()),q,actor,access);const m=a.analysis.material_needs.at(-1)!;expect([m.installed_proven,m.unused_allocated_proven,m.additional_external].map(f=>'value'in f?f.value:null)).toEqual(['0','10','176']);expect(analysisPrompt(a,'Periksa kain')).toContain('CP7_FABRIC_FREE_STOCK')})
it('refuses physical fabric facts beyond the kernel: installed nonzero, negative allocation, external above remaining, external without allocation, unassumed external',()=>{for(const change of[(x:ReturnType<typeof fabricAnalysisFixture>)=>physical(x,'5','10','171'),(x:ReturnType<typeof fabricAnalysisFixture>)=>physical(x,'0','-1','176'),(x:ReturnType<typeof fabricAnalysisFixture>)=>physical(x,'0','10','177'),(x:ReturnType<typeof fabricAnalysisFixture>)=>{physical(x);const m=x.analysis.material_needs.at(-1)!;m.unused_allocated_proven={state:'UNKNOWN',unit:'M',reason:'FABRIC_LINKED_DRAFT_NOT_ELIGIBLE',refs:m.gross.refs}},(x:ReturnType<typeof fabricAnalysisFixture>)=>{physical(x);const m=x.analysis.material_needs.at(-1)!;m.additional_external={state:'KNOWN',value:'176',unit:'M',refs:m.gross.refs}},(x:ReturnType<typeof fabricAnalysisFixture>)=>{physical(x);const m=x.analysis.material_needs.at(-1)!;m.gross={state:'UNKNOWN',unit:'M',reason:'SOURCE_INPUT_NOT_PROVEN',refs:m.gross.refs}}]){const x=fabricAnalysisFixture();change(x);expect(()=>parseNativeAnalysis(x,q,actor,access)).toThrow()}})
it('cites the physical fact sources in the shared report, and keeps rows without them unchanged',()=>{const plain=analysisReport(parseNativeAnalysis(fabricAnalysisFixture(),q,actor,access)),physicalReport=analysisReport(parseNativeAnalysis(physical(fabricAnalysisFixture()),q,actor,access));expect(plain).not.toContain('CP7_FABRIC_FREE_STOCK');expect(physicalReport).toContain(`CP7_FABRIC_FREE_STOCK/${fabricMaterialId}@${'e'.repeat(64)}`);expect(physicalReport).toContain('tambahan eksternal 176 M · asumsi');expect(physicalReport.split('CP7_FABRIC_RECIPE/').length).toBe(plain.split('CP7_FABRIC_RECIPE/').length)})
