// @vitest-environment jsdom
import {beforeEach,it,expect} from 'vitest'
import {parseNativeSupply,parseScheduleWorkspace,parseNativeNetting,schedulePayload,checkScheduleOutcome,persistScheduleRequest,readScheduleRequest,clearScheduleRequest,scheduleRequestKey,instantToWibInput,wibInputToInstant} from './nativeProductionPlanning'
import {supplyWire,workspaceWire,nettingWire,scheduleConfig,scheduleOutcome,planningQuery,workKey} from '../tests/fixtures/nativeProductionPlanning'
import {demandRequest} from '../tests/fixtures/nativeDemandHistory'
beforeEach(()=>localStorage.clear())
it('retains physical quantities, customer work, selected good, signed shortage and capacity as separate server values',()=>{const s=parseNativeSupply(supplyWire(),planningQuery),w=parseScheduleWorkspace(workspaceWire(),s),n=parseNativeNetting(nettingWire(),planningQuery);expect(s.positions.map(x=>[x.remaining,x.eligible])).toEqual([['8',true],['8',false]]);expect(w.requirements[1].targets).toEqual([]);expect(n.rows[0]).toMatchObject({available:'76',rawGap:'24',directed:'7',baseGap:'17',conditionalGap:'17'});expect(n.capacity).toBe('15');expect(n.positions).toHaveLength(2)})
it('preserves unknown yield, shared time and global allocation as unknown values',()=>{const n=parseNativeNetting(nettingWire(demandRequest,true),planningQuery);expect(n.rows[0].baseGap).toBeNull();expect(n.rows[0].directed).toBeNull();expect(n.rows[0].conditionalGap).toBeNull();expect(n.capacity).toBeNull();expect(n.etas.every(x=>x.at===null)).toBe(true)})
it('reads the PL-8 v2 supply contract and runs archived as v1, never another version',()=>{const v1=supplyWire();v1.contract_version='cp7.native-supply.v1';expect(parseNativeSupply(v1,planningQuery).positions).toHaveLength(2);const v3=supplyWire();v3.contract_version='cp7.native-supply.v3';expect(()=>parseNativeSupply(v3,planningQuery)).toThrow()})
it('accepts the native timing kernel UTC offset serialization while keeping selected metadata UTC-Z only',()=>{const n=nettingWire();n.schedule_run_result.etas[0].result.eta='2026-10-01T01:45:00.123456+00:00';expect(parseNativeNetting(n,planningQuery).etas[0].at).toBe('2026-10-01T01:45:00.123456+00:00');const s=parseNativeSupply(supplyWire(),planningQuery),w=parseScheduleWorkspace(workspaceWire(),s),c=structuredClone(scheduleConfig);c.through_at='2026-10-02T12:00:00.123456+00:00';expect(()=>schedulePayload(w,c,'explicit')).toThrow()})
it.each(['run','hash','qty','ownership','candidate','version'])('refuses misbound schedule guidance: %s',kind=>{const s=parseNativeSupply(supplyWire(),planningQuery),w=workspaceWire();if(kind==='run')w.source_run=demandRequest;if(kind==='hash')w.source_hash='a'.repeat(64);if(kind==='qty')w.position_requirements[0].remaining_pcs='9';if(kind==='ownership')w.position_requirements[1].eligible_company_wip=true;if(kind==='candidate')w.position_requirements[0].target_candidates[0].target_key='wrong';if(kind==='version'){w.revision='1'}expect(()=>parseScheduleWorkspace(w,s)).toThrow()})
it.each(['query','target','available','net','conditional','apply','duplicate','customer','eta'])('refuses inconsistent netting receiver: %s',kind=>{const w=nettingWire();if(kind==='query')w.schedule_run_result.supply_run_result.baseline_run_result.history_run_result.history.from_date='2026-09-28';if(kind==='target')w.rows[0].target_key='wrong';if(kind==='available')w.rows[0].available_fg_pcs='77';if(kind==='net')w.rows[0].net.inputs.target_key='wrong';if(kind==='conditional'){w.allocation.status='UNKNOWN'}if(kind==='apply')w.apply_enabled=true;if(kind==='duplicate')w.rows.push(structuredClone(w.rows[0]));if(kind==='customer')w.schedule_run_result.wip.positions[1].eligible_company_wip=true;if(kind==='eta')w.schedule_run_result.etas[0].result.eta='wrong';expect(()=>parseNativeNetting(w,planningQuery)).toThrow()})
it('keeps original metadata revision and exact microsecond timestamps for retry despite newer source',()=>{const s=parseNativeSupply(supplyWire(),planningQuery),w=parseScheduleWorkspace(workspaceWire(),s),request={id:demandRequest,payload:schedulePayload(w,scheduleConfig,'explicit review')};persistScheduleRequest('actor-project',request);expect(readScheduleRequest('actor-project').pending).toEqual(request);expect(()=>persistScheduleRequest('actor-project',request)).toThrow();expect(()=>clearScheduleRequest('actor-project',crypto.randomUUID())).toThrow();checkScheduleOutcome(scheduleOutcome(request.id),request);clearScheduleRequest('actor-project',request.id);expect(readScheduleRequest('actor-project').pending).toBeNull()})
it('refuses new saves against a stale source and preserves corrupt pending state',()=>{const s=parseNativeSupply(supplyWire(),planningQuery),raw=workspaceWire();raw.current_source_hash='f'.repeat(64);raw.source_state='ARCHIVED_STALE';const w=parseScheduleWorkspace(raw,s);expect(()=>schedulePayload(w,scheduleConfig,'review')).toThrow();localStorage.setItem(scheduleRequestKey('actor'),'broken');expect(readScheduleRequest('actor').error).not.toBe('');expect(localStorage.getItem(scheduleRequestKey('actor'))).toBe('broken')})
it('converts WIB independently of computer timezone while preserving an unchanged original microsecond wire value',()=>{const original='2026-10-01T01:00:00.123456Z';expect(instantToWibInput(original)).toBe('2026-10-01T08:00:00');expect(wibInputToInstant('2026-10-01T08:00',original)).toBe(original);expect(wibInputToInstant('2026-10-01T08:01')).toBe('2026-10-01T01:01:00.000Z');expect(()=>wibInputToInstant('2026-02-30T10:00')).toThrow();expect(()=>wibInputToInstant('')).toThrow();expect(workKey).toBeTruthy()})
