import {it,expect}from'vitest'
import {parsePlanActual,planActualValue}from'./nativePlanActual'
import {parsePlanSaved}from'./nativePlanDraft'
import * as f from'../tests/fixtures/nativePlan'
const saved=()=>parsePlanSaved({...f.saved(),state:'NATIVE_DRAFT_CREATED',native_intent:{id:f.order,cutting_group_id:f.pattern,group_number:'SYNTHETIC-CUT',material_issue_posted:false}},f.actor,f.draft)
it('validates the conserved linked receipt, explicit old-plan source, and exact FG identity',()=>{const a=parsePlanActual(f.actual(),f.actor,saved());expect(a.planned).toBe('60');expect(a.facts.matched_fg_pcs).toMatchObject({state:'KNOWN',value:'1'});expect(a.remaining).toMatchObject({state:'KNOWN',value:'59'});expect(a.originalState).toBe('ARCHIVED_STALE');expect(a.positions[0].quantity).toBe('59')})
it('keeps missing source UNKNOWN without a zero or partial positions fallback',()=>{const wire=structuredClone(f.actual())as unknown as Record<string,unknown>,a=wire.actual as Record<string,unknown>,unknown={state:'UNKNOWN',unit:'PCS',reason:'LINKED_NATIVE_GROUP_MISSING',refs:[]};a.state='UNKNOWN';a.reason='LINKED_NATIVE_GROUP_MISSING';a.native_group=null;a.positions=[];a.facts=Object.fromEntries(Object.keys(a.facts as object).map(k=>[k,unknown]));wire.remaining_to_plan_pcs=unknown;const result=parsePlanActual(wire,f.actor,saved());expect(planActualValue(result.remaining)).toBe('Belum diketahui');expect(result.remaining).not.toHaveProperty('value');(a.facts as Record<string,unknown>).matched_fg_pcs={...unknown,value:'0'};expect(()=>parsePlanActual(wire,f.actor,saved())).toThrow()})
it('rejects a conserved group total that disguises other roots, sizes or position quantities',()=>{for(const mutate of[(x:ReturnType<typeof f.actual>)=>{x.actual.positions[1].fg_identity!.root_id=f.order},(x:ReturnType<typeof f.actual>)=>{x.actual.positions[1].size_id=f.order},(x:ReturnType<typeof f.actual>)=>{x.actual.positions[0].remaining_pcs='60'},(x:ReturnType<typeof f.actual>)=>{x.remaining_to_plan_pcs.value='0'}]){const x=f.actual();mutate(x);expect(()=>parsePlanActual(x,f.actor,saved())).toThrow()}})
it('binds own immutable draft and intent and rejects nested financial or undeclared facts',()=>{for(const change of[{actor_scope_id:f.order},{draft_id:f.order},{native_intent_id:f.roll},{original_source_hash:'e'.repeat(64)},{production_go:true},{amount:'100'}])expect(()=>parsePlanActual({...f.actual(),...change},f.actor,saved())).toThrow();const x=f.actual();Object.assign(x.actual.native_group,{hpp:'100'});expect(()=>parsePlanActual(x,f.actor,saved())).toThrow()})
