// @vitest-environment jsdom
import {it,expect,beforeEach} from 'vitest'
import {parsePlanOptions,planPayload,parsePlanSaved,parsePlanPreview,validatePlanCommit,readPlanPointer,rememberPlanPointer,planPointerKey} from './nativePlanDraft'
import * as f from '../tests/fixtures/nativePlan'
const form={orderId:f.order,patternId:f.pattern,locationId:f.location,cutAt:'2026-10-01T08:00',notes:'Own note',reason:'Reviewed Native draft only',reviewed:true,rolls:[{id:f.roll,issued:'1',consumed:'0.5',remaining:'0.5',pcs:'60'}]}
it('preserves need100 capacity60 selected60 unresolved40 as distinct server values',()=>{const o=parsePlanOptions(f.options(),f.actor,f.context),s=parsePlanSaved(f.saved(),f.actor,f.draft),p=parsePlanPreview(f.preview(),f.actor,s);expect([o.needed,o.capacity,p.selected,p.unresolved]).toEqual(['100','60','60','40'])})
it.each(['actor_scope_id','run_id','target_key','source_hash'])('rejects another %s before adopting choices',(key)=>{const o=f.options();Object.assign(o,{[key]:key==='source_hash'?'c'.repeat(64):f.order});expect(()=>parsePlanOptions(o,f.actor,f.context)).toThrow()})
it('keeps absent capacities unknown and legitimate zero distinct',()=>{const o=f.options();Object.assign(o,{needed_pcs:null,capacity_pcs:'0',production_state:null});const p=parsePlanOptions(o,f.actor,f.context);expect(p.needed).toBeNull();expect(p.capacity).toBe('0');expect(p.state).toBeNull();expect(()=>planPayload(p,form,'2026-10-01T08:00:00Z',null)).toThrow()})
it('rejects a truncated page or another Native model instead of admitting a partial choice list',()=>{const o=f.options();o.page.po_total='2';expect(()=>parsePlanOptions(o,f.actor,f.context)).toThrow();const wrong=f.options();wrong.orders[0].model_id=f.roll;expect(()=>parsePlanOptions(wrong,f.actor,f.context)).toThrow()})
it('constructs only an explicitly reviewed Native draft composition, with exact size and no POST/reservation authority',()=>{const p=planPayload(parsePlanOptions(f.options(),f.actor,f.context),form,'2026-10-01T08:00:00Z',null);expect(p.cutting.size_slots).toEqual([{slot_no:'1',size_id:f.size,drawing_no:'1'}]);expect(p.cutting).not.toHaveProperty('action');expect(p).not.toHaveProperty('reservation');expect(p.reviewed_assumption_ids).toEqual(['selected-calendar']);expect(()=>planPayload(parsePlanOptions(f.options(),f.actor,f.context),{...form,reviewed:false},'2026-10-01T08:00:00Z',null)).toThrow()})
it('rejects counterfeit installed/reserved material or another preview version',()=>{const s=parsePlanSaved(f.saved(),f.actor,f.draft),p=f.preview();p.material_rows[0].basis='INSTALLED';expect(()=>parsePlanPreview(p,f.actor,s)).toThrow();const changed=f.preview();changed.revision='2';expect(()=>parsePlanPreview(changed,f.actor,s)).toThrow()})
it('binds success to the exact saved UUID, input run, target, actor and non-posting state',()=>{const e={action:'SAVE_DRAFT',payload:{run_id:f.run,target_key:f.context.targetKey,source_hash:f.sourceHash},id:f.order,createdAt:'2026-10-01T08:00:00Z',expectedVersion:null,fingerprint:'synthetic'};expect(validatePlanCommit(f.saveOutcome(e.id),e,f.actor).id).toBe(f.draft);const bad=f.saveOutcome(f.roll);expect(()=>validatePlanCommit(bad,e,f.actor)).toThrow();const foreign=f.saveOutcome(e.id);foreign.actor_scope_id=f.roll;expect(()=>validatePlanCommit(foreign,e,f.actor)).toThrow()})
beforeEach(()=>localStorage.clear())
it('stores only an opaque draft pointer and keeps corrupt prior evidence',()=>{rememberPlanPointer('scope',f.draft);expect(localStorage.getItem(planPointerKey('scope'))).toBe(JSON.stringify({id:f.draft}));localStorage.setItem(planPointerKey('scope'),'broken');expect(readPlanPointer('scope').error).not.toBe('');expect(()=>rememberPlanPointer('scope',f.order)).toThrow();expect(localStorage.getItem(planPointerKey('scope'))).toBe('broken')})
