import {describe,it,expect}from'vitest'
import {parseNativePayableConditions as parse}from'./nativePayableConditions'
import {nativePayableFixture as fixture}from'../tests/fixtures/nativePayableConditions'
import original from'../tests/fixtures/nativeAnalysisStandin.json'
import type {NativeDemandQuery}from'./nativeDemandHistory'
const q=original.query as NativeDemandQuery,actor=original.analysis.scope.actor_scope_id,finance={ownerReports:false,preflight:false}
const read=(e=fixture())=>parse(e,q,actor,finance,true)
type Row=ReturnType<typeof fixture>['source']['rows'][number]
// A settled or credit receipt: the rule does not apply and the recorded due stays.
const settled=(r:Row)=>{r.due_basis='NATIVE_POSTED_INVOICE_EARLIEST';Object.assign(r.due_rule,{payments_applied:r.balance!.paid,outcome:'NOT_APPLICABLE',open_portion:null})}
const invoice=(n:number,due:string|null,amount:string)=>({kind:'POSTED_INVOICE',invoice_id:'00000000-0000-4000-8000-00000000040'+n,invoice_number:'INV-'+n,invoice_date:'2026-09-0'+n,due_date:due,amount})
describe('Current accepted Native material AP source, separate from Original',()=>{
 it('copies exact Native BF balance and current due source while preserving original and deep ownership',()=>{const e=fixture(),x=read(e);expect(x.analysis.analysis).toEqual(original.analysis);expect(x.rows[0].balance?.remaining).toBe('300.00');expect(x.rows[0].liability.row_version).toBe('9007199254740993');expect(x.rows[0].condition.business_resolved).toBe(false);e.source.rows[0].balance!.remaining='0.00';expect(x.rows[0].balance?.remaining).toBe('300.00')})
 it('preserves twelve-place Native quantity-price products and comparisons without rounding',()=>{const e=fixture(),r=e.source.rows[0];r.liability.receipt_estimate_amount='500.000000000000';r.liability.final_ap_amount='500.000000000000';r.liability.grni_estimated_amount='0.000000000000';r.liability.total_liability_amount='500.000000000000';r.liability.final_ap_outstanding='300.000000000000';r.invoice_coverage[0].capacity='20.000000000000';r.invoice_coverage[0].invoiced_qty='20.000000000000';expect(read(e).rows[0].liability.final_ap_outstanding).toBe('300.000000000000');Object.assign(r.balance!,{paid:'500.00',remaining:'0.00'});settled(r);r.invoice_coverage[0].invoiced_qty='19.999999999999';Object.assign(r.condition,{state:'INVOICE_PENDING',invoice_pending:true,business_resolved:false});expect(read(e).rows[0].condition.business_resolved).toBe(false)})
 it('keeps zero-estimate uninvoiced physical receipts unresolved',()=>{const e=fixture(),r=e.source.rows[0];Object.assign(r.balance!,{paid:'500.00',remaining:'0.00'});settled(r);r.invoice_coverage[0].invoiced_qty='0.000000';r.invoice_coverage[0].price_state='ESTIMATED';r.invoice_coverage[0].invoice_match_state='UNMATCHED';Object.assign(r.condition,{state:'INVOICE_PENDING',invoice_pending:true,business_resolved:false});expect(read(e).rows[0].condition.state).toBe('INVOICE_PENDING');r.condition.state='ZERO_BALANCE';r.condition.business_resolved=true;expect(()=>read(e)).toThrow()})
 it('resolves only Native zero without pending invoice and keeps native negative credit distinct from zero',()=>{const e=fixture(),r=e.source.rows[0];Object.assign(r.balance!,{paid:'500.00',remaining:'0.00'});settled(r);Object.assign(r.condition,{state:'ZERO_BALANCE',business_resolved:true});expect(read(e).rows[0].condition.business_resolved).toBe(true);Object.assign(r.balance!,{final_ap:'60.00',paid:'100.00',remaining:'-40.00'});settled(r);Object.assign(r.condition,{state:'CREDIT_REVIEW',business_resolved:false});expect(read(e).rows[0].balance?.remaining).toBe('-40.00');r.balance!.remaining='0.00';expect(()=>read(e)).toThrow()})
 it('without a payable portion keeps the recorded due, then the Native header fallback; missing or impossible dates stay refused or unknown',()=>{const e=fixture(),r=e.source.rows[0];r.liability.earliest_due_date=null;r.receipt_due_date='2026-10-01';r.due_date='2026-10-01';r.due_basis='NATIVE_RECEIPT_HEADER';Object.assign(r.due_rule,{recorded_due_date:'2026-10-01',recorded_due_basis:'NATIVE_RECEIPT_HEADER',portions:[],outcome:'NOT_APPLICABLE',open_portion:null});r.condition.state='DUE_TODAY';expect(read(e).rows[0].due_date).toBe('2026-10-01');r.receipt_due_date=null;r.due_date=null;r.due_basis='MISSING';Object.assign(r.due_rule,{recorded_due_date:null,recorded_due_basis:'MISSING'});r.condition.state='MISSING_DUE_DATE';expect(read(e).rows[0].condition.business_resolved).toBe(false);r.due_date='2026-02-30';expect(()=>read(e)).toThrow()})
 it('AP-5: receipt payments cover the oldest due first; the next open invoice gives the due, labelled as a rule result',()=>{
  const e=fixture(),r=e.source.rows[0];r.due_rule.portions=[invoice(1,'2026-09-20','200.00'),invoice(2,'2026-10-05','300.00')];r.due_rule.recorded_due_date=r.liability.earliest_due_date='2026-09-20'
  // Paid 200 covers the 20 Sep invoice: the reminder follows the 5 Oct one, not yet due.
  Object.assign(r.due_rule,{outcome:'OPEN_PORTION',open_portion:1});r.due_date='2026-10-05';r.condition.state='NOT_DUE_YET'
  const x=read(e).rows[0];expect([x.due_date,x.due_basis,x.due_rule.recorded_due_date,x.due_rule.evidence]).toEqual(['2026-10-05','RULE_OLDEST_DUE_FIRST_WITHIN_RECEIPT','2026-09-20','RULE_RESULT_NOT_PER_INVOICE_PAYMENT_EVIDENCE'])
  // One cent short: the 20 Sep invoice is still open and overdue.
  const f=structuredClone(e),s=f.source.rows[0];Object.assign(s.balance!,{paid:'199.99',remaining:'300.01'});s.due_rule.payments_applied='199.99';Object.assign(s.due_rule,{outcome:'OPEN_PORTION',open_portion:0});s.due_date='2026-09-20';s.condition.state='OVERDUE';expect(read(f).rows[0].condition.state).toBe('OVERDUE')
  // The server may not claim a later due than the rule gives, nor the recorded one under the rule label.
  for(const mutate of [(z:Row)=>{Object.assign(z.due_rule,{open_portion:1});z.due_date='2026-10-05';z.condition.state='NOT_DUE_YET'},(z:Row)=>{z.due_basis='NATIVE_POSTED_INVOICE_EARLIEST'},(z:Row)=>{z.due_rule.payments_applied='200.00'},(z:Row)=>{z.due_rule.evidence='PER_INVOICE_PAYMENT'}]){const g=structuredClone(f);mutate(g.source.rows[0]);expect(()=>read(g)).toThrow()}
 })
 it('AP-5: an open portion without a recorded due stays unknown; an unattributed balance keeps the recorded due; order and direct-final dues are checked',()=>{
  const e=fixture(),r=e.source.rows[0];r.due_rule.portions=[invoice(1,'2026-09-20','200.00'),invoice(2,null,'300.00')];r.due_rule.recorded_due_date=r.liability.earliest_due_date='2026-09-20'
  Object.assign(r.due_rule,{outcome:'OPEN_PORTION_DUE_MISSING',open_portion:1});r.due_date=null;r.due_basis='RULE_OPEN_PORTION_DUE_MISSING';r.condition.state='MISSING_DUE_DATE'
  expect(read(e).rows[0].condition.state).toBe('MISSING_DUE_DATE')
  // Every portion covered but a balance remains (a receipt-level credit move): no invoice is named.
  const u=structuredClone(e),v=u.source.rows[0];v.due_rule.portions=[invoice(1,'2026-09-20','200.00')];Object.assign(v.due_rule,{outcome:'UNATTRIBUTED',open_portion:null});v.due_date='2026-09-20';v.due_basis='NATIVE_POSTED_INVOICE_EARLIEST';v.condition.state='OVERDUE'
  expect(read(u).rows[0].due_rule.outcome).toBe('UNATTRIBUTED')
  const w=structuredClone(e);w.source.rows[0].due_rule.portions.reverse();expect(()=>read(w)).toThrow()
  const d=structuredClone(u),z=d.source.rows[0];z.due_rule.portions.push({kind:'RECEIPT_DIRECT_FINAL',invoice_id:null,invoice_number:null,invoice_date:null,due_date:'2026-09-25',amount:'1.00'});expect(()=>read(d)).toThrow()
 })
 it('requires actor, current AP authority, complete unique posted supplier binding and Native WIB clock',()=>{const mutations:((e:ReturnType<typeof fixture>)=>void)[]=[e=>{e.actor_scope_id='foreign'},e=>{e.source.page_complete=false},e=>{e.source.total='2'},e=>{e.source.rows.push(structuredClone(e.source.rows[0]));e.source.total='2'},e=>{e.source.suppliers=[]},e=>{e.source.rows[0].condition.source_revision='1'},e=>{e.source.read_at='2026-09-30T01:00:00Z'},e=>{e.source.rows[0].invoice_coverage=[]}];for(const mutate of mutations){const e=fixture();mutate(e);expect(()=>read(e)).toThrow()}expect(()=>parse(fixture(),q,actor,finance,false)).toThrow()})
})
