// @vitest-environment jsdom
import {act,useRef,useState} from 'react'
import {createRoot,type Root} from 'react-dom/client'
import {reportCrypto,reportBodyDigest} from '../tests/fixtures/reportCrypto.mjs'
import {beforeEach,afterEach,it,expect,vi,type Mock} from 'vitest'
import NativeAnalysisReportsPanel from './NativeAnalysisReportsPanel'
import {parseNativeAnalysis,type NativeAnalysis} from './nativeAnalysis'
import {readReportRequest,type ReportRequest} from './nativeAnalysisReports'
import fixture from '../tests/fixtures/nativeAnalysisStandin.json'
import {recoveryIdentity} from '../tests/fixtures/productionRecovery'
import type {NativeDemandQuery} from './nativeDemandHistory'
const state=vi.hoisted(()=>({auth:null as unknown}))
const client=vi.hoisted(()=>({rpc:vi.fn()}))
vi.mock('./auth/AuthProvider',()=>({useAuth:()=>state.auth}));vi.mock('./lib/supabase',()=>({getUatSupabaseClient:()=>client}))
const access={ownerReports:false,preflight:false},actor=fixture.analysis.scope.actor_scope_id,scope='analysis:cp6-disposable:actor-1',q={from_date:fixture.query.from_date,through_date:fixture.query.through_date,group_mode:fixture.query.group_mode} as NativeDemandQuery
let container:HTMLDivElement,root:Root,start:Mock<()=>void>
function Host(){const sequence=useRef(0),[generation,setGeneration]=useState(0),[context,setContext]=useState<NativeAnalysis|null>(()=>parseNativeAnalysis(fixture,q,actor,access));return <NativeAnalysisReportsPanel context={context} generation={generation} blocked={false} access={access} onReadStart={()=>{const n=++sequence.current;setGeneration(n);setContext(null);start();return n}} isReadCurrent={n=>n===sequence.current} onReadEnd={()=>{}} onAnalysis={(a,n)=>{if(sequence.current===n)setContext(a)}} requireClear={()=>{}}/>}
function wireDocument(r:ReportRequest){const body='Contoh kontrak parser '+r.payload.title;return{contract_version:'cp7.report-publication.v1',actor_scope_id:actor,id:'00000000-0000-4000-8000-000000000014',series_id:'00000000-0000-4000-8000-000000000015',revision:'1',run_id:fixture.run_id,request_id:r.id,kind:r.payload.kind,period_query:r.query,title:r.payload.title.trim(),reason:r.payload.reason.trim(),template_version:'native-report-1',body,body_sha256:reportBodyDigest(body),source_hash:r.payload.source_hash,semantic_hash:r.payload.semantic_hash,published_at:'2026-10-01T00:00:00+00:00',is_latest:true,source_state:fixture.source_state,analysis:structuredClone(fixture),production_go:false}}
function reply(r:ReportRequest){return{contract_version:'cp7.report-command.v1',request_id:r.id,status:'COMMITTED',document:wireDocument(r),analysis:structuredClone(fixture),production_go:false}}
beforeEach(()=>{Object.assign(globalThis,{IS_REACT_ACT_ENVIRONMENT:true});vi.stubGlobal('crypto',reportCrypto);localStorage.clear();client.rpc.mockReset();start=vi.fn();const a=structuredClone(recoveryIdentity);Object.assign(a.runtime,{mode:'DISPOSABLE_TEST',projectRef:'cp6-disposable'});Object.assign(a.identity.profile,{authUserId:actor});a.identity.permissions.push('master.product.view','production.wip.view','warehouse.stock.view','sales.invoice.view');state.auth=a;Object.defineProperty(navigator,'locks',{configurable:true,value:{request:async(_n:string,_o:unknown,fn:(lock:object)=>unknown)=>fn({})}});container=document.createElement('div');document.body.append(container);root=createRoot(container)})
afterEach(async()=>{await act(async()=>root.unmount());container.remove();localStorage.clear();vi.unstubAllGlobals()})
async function render(){await act(async()=>root.render(<Host/>))}
async function click(label:string){const b=[...container.querySelectorAll('button')].find(b=>b.textContent===label)!;expect(b).toBeTruthy();await act(async()=>b.click());await act(async()=>new Promise(resolve=>setTimeout(resolve,20)))}
async function fill(label:string,value:string){const field=container.querySelector<HTMLInputElement|HTMLTextAreaElement>(`[aria-label="${label}"]`)!;await act(async()=>{Object.getOwnPropertyDescriptor(field instanceof HTMLTextAreaElement?HTMLTextAreaElement.prototype:HTMLInputElement.prototype,'value')!.set!.call(field,value);field.dispatchEvent(new Event('input',{bubbles:true}))})}
async function review(){const box=container.querySelector<HTMLInputElement>('[aria-label="Laporan sudah ditinjau"]')!;await act(async()=>box.click())}
it('publishes a linked revision when Postgres returns the same period fields in a different JSON key order',async()=>{
 const requests:ReportRequest[]=[]
 client.rpc.mockImplementation(async()=>{
  const r=readReportRequest(scope).pending!;requests.push(r)
  const d=wireDocument(r)
  d.period_query={from_date:r.query.from_date,group_mode:r.query.group_mode,through_date:r.query.through_date}
  expect(Object.keys(d.period_query)).not.toEqual(Object.keys(r.query))
  if(r.payload.series_id){d.series_id=r.payload.series_id;d.revision=(BigInt(r.payload.expected_revision!)+1n).toString()}
  return{data:{...reply(r),document:d},error:null}
 })
 await render();await fill('Judul laporan tersimpan','Versi pertama');await fill('Alasan laporan tersimpan','Sumber sudah diperiksa');await review();await click('Simpan laporan yang ditinjau')
 expect(container.querySelector('[aria-label="Teks laporan tersimpan"]')?.textContent).toContain('Versi pertama')
 await click('Buat revisi dari laporan ini');await fill('Judul laporan tersimpan','Versi kedua');await fill('Alasan laporan tersimpan','Penjelasan revisi');await review();await click('Simpan revisi laporan')
 expect(requests).toHaveLength(2);expect(requests[1].payload.series_id).toBe('00000000-0000-4000-8000-000000000015');expect(requests[1].payload.expected_revision).toBe('1')
 expect(container.querySelector('[aria-label="Teks laporan tersimpan"]')?.textContent).toContain('Versi kedua');expect(readReportRequest(scope).pending).toBeNull()
})
it('persists the exact request before send and recovers a committed lost reply after remount without replacing user fields',async()=>{let held:ReportRequest|null=null;client.rpc.mockImplementation(async(name:string,args:{p_request:string})=>{const r=readReportRequest(scope).pending!;expect(r.id).toBe(args.p_request);if(name==='erp_cp7_publish_report_v1'){held=r;throw Error('committed reply lost')}return{data:reply(r),error:null}});await render();expect(client.rpc).not.toHaveBeenCalled();await fill('Judul laporan tersimpan','Judul operator');await fill('Alasan laporan tersimpan','Alasan operator');await review();await click('Simpan laporan yang ditinjau');expect(held).toBeTruthy();expect(readReportRequest(scope).pending).toEqual(held);await act(async()=>root.unmount());root=createRoot(container);await render();await click('Periksa hasil laporan tersimpan');expect(client.rpc.mock.calls[1][1]).toEqual(client.rpc.mock.calls[0][1]);expect(readReportRequest(scope).pending).toBeNull();expect(container.querySelector('[aria-label="Teks laporan tersimpan"]')?.textContent).toContain('Judul operator');expect(container.querySelector<HTMLInputElement>('[aria-label="Judul laporan tersimpan"]')?.value).toBe('Judul operator')})
it('retires body, copied text and index before a held current-authority read and on403, retaining unsent title and reason',async()=>{let saved:ReturnType<typeof wireDocument>|null=null;client.rpc.mockImplementation(async(_name:string,_args:{p_request:string})=>{const r=readReportRequest(scope).pending!;saved=wireDocument(r);return{data:reply(r),error:null}});await render();await fill('Judul laporan tersimpan','Judul terbit');await fill('Alasan laporan tersimpan','Alasan terbit');await review();await click('Simpan laporan yang ditinjau');expect(saved).toBeTruthy();expect(container.querySelector('[aria-label="Teks laporan tersimpan"]')).toBeTruthy();await fill('Judul laporan tersimpan','Judul belum dikirim');await fill('Alasan laporan tersimpan','Alasan belum dikirim');let finish!:(r:{data:null;error:{message:string;code:string}})=>void;client.rpc.mockImplementation(()=>new Promise(resolve=>{finish=resolve}));await act(async()=>{const b=[...container.querySelectorAll('button')].find(b=>b.textContent==='Muat laporan tersimpan dari server')!;b.click()});expect(container.querySelector('[aria-label="Teks laporan tersimpan"]')).toBeNull();expect(start).toHaveBeenCalledTimes(2);await act(async()=>finish({data:null,error:{message:'Access denied',code:'42501'}}));expect(container.querySelector('[aria-label="Teks laporan tersimpan"]')).toBeNull();expect(container.querySelector('[aria-label="Perbandingan laporan ERP"]')).toBeNull();expect(container.querySelector<HTMLInputElement>('[aria-label="Judul laporan tersimpan"]')?.value).toBe('Judul belum dikirim');expect(container.querySelector<HTMLTextAreaElement>('[aria-label="Alasan laporan tersimpan"]')?.value).toBe('Alasan belum dikirim')})
