// @vitest-environment jsdom
import {act}from'react'
import {createRoot,type Root}from'react-dom/client'
import {beforeEach,afterEach,describe,it,expect,vi}from'vitest'
import NativeCuttingYieldPanel from'./NativeCuttingYieldPanel'
import {parseNativeCuttingYield,cuttingYieldRequestKey,readCuttingYieldRequest}from'./nativeCuttingYield'
import {recoveryIdentity}from'../tests/fixtures/productionRecovery'
const state=vi.hoisted(()=>({auth:null as unknown}))
const client=vi.hoisted(()=>({rpc:vi.fn()}))
vi.mock('./auth/AuthProvider',()=>({useAuth:()=>state.auth}));vi.mock('./lib/supabase',()=>({getUatSupabaseClient:()=>client}))
const id='11111111-1111-4111-8111-111111111111',other='22222222-2222-4222-8222-222222222222',slice='33333333-3333-4333-8333-333333333333'
function data(request=id){return{contract_version:'cp7.native-cutting-yield-source.v1',knowledge_basis:'CURRENT_CAPTURE_ONLY',model_qualified:false,automatic_activation:false,business_write:false,production_go:false,run_id:other,request_id:request,source_hash:'a'.repeat(64),captured_at:'2026-10-02T10:00:00.123456Z',source_state:'UNCHANGED',rows:[{slice_id:slice,group_id:id,roll_id:other,material_id:id,material_sku:'KAIN-ASLI',pattern_id:id,pattern_revision:'R1',physical_at:'2026-10-01T12:00:00.456789+07:00',known_at:'2026-10-02T10:00:00.123456Z',actual:{consumed:'60.123456',unit:'YARD',total_pcs:'60',by_size:[{yield_id:id,size_id:id,qty_pcs:'20'},{yield_id:other,size_id:other,qty_pcs:'40'}]},family:null,planned_mix:null,recorded_width_cm:null,measured_remaining:null,interval:null,assessment:'UNAVAILABLE',reason:'PROSPECTIVE_FAMILY_MIX_AND_VALIDATED_INTERVAL_REQUIRED',calculated_remaining_is_not_physical_measurement:true,output_mix_is_not_preknown_planned_mix:true,later_laundry_BS_is_not_cutting_cause:true}]}}
let root:Root,container:HTMLDivElement
beforeEach(()=>{Object.assign(globalThis,{IS_REACT_ACT_ENVIRONMENT:true});localStorage.clear();client.rpc.mockReset();const a=structuredClone(recoveryIdentity);Object.assign(a.runtime,{mode:'DISPOSABLE_TEST'});a.identity.permissions.push('production.cutting.view','master.product.view','warehouse.stock.view','sales.invoice.view');state.auth=a;container=document.createElement('div');document.body.append(container);root=createRoot(container)})
afterEach(async()=>{await act(async()=>root.unmount());container.remove();localStorage.clear()})
const flush=async()=>act(async()=>{await new Promise(r=>setTimeout(r,0))})
async function mount(groupId:string|null=id,sourceKey='source-1',parentBusy=false){await act(async()=>root.render(<NativeCuttingYieldPanel groupId={groupId} sourceKey={sourceKey} parentBusy={parentBusy}/>));await flush()}
const button=(label:string)=>[...container.querySelectorAll('button')].find(b=>b.textContent===label)!
async function click(label:string){await act(async()=>button(label).click());await flush()}
describe('Native cutting source boundary',()=>{
 it('preserves exact unit, length, sizes and current knowledge without inventing a range',()=>{const r=parseNativeCuttingYield(data(),id);expect(r.rows[0].actual).toMatchObject({unit:'YARD',consumed:'60.123456',totalPcs:'60'});expect(r.rows[0].actual?.bySize.map(y=>y.qtyPcs)).toEqual(['20','40']);expect(r.rows[0].knownAt).not.toBe(r.rows[0].physicalAt)})
 it('refuses foreign slices, duplicate observations, false totals, imputed widths and fabricated qualification',()=>{const a=data();a.rows[0].group_id=other;const b=data();b.rows.push(structuredClone(b.rows[0]));const c=data();c.rows[0].actual.total_pcs='61';const d=data();Object.assign(d.rows[0],{recorded_width_cm:'150'});const e=data();Object.assign(e,{model_qualified:true});const f=data();f.rows[0].known_at='2026-10-02T10:00:00.123457Z';for(const bad of[a,b,c,d,e,f])expect(()=>parseNativeCuttingYield(bad,id)).toThrow()})
 it('reads real-shaped source only and denies an old source after failed current access',async()=>{client.rpc.mockImplementation(async(name,args)=>({data:name==='erp_cp7_capture_cutting_yield_v1'?data(args.p_request):data(),error:null}));await mount();await click('Muat hasil potong tersimpan');expect(container.textContent).toContain('60.123456 YARD');expect(container.textContent).toContain('60 PCS');expect(container.textContent).toContain('Belum dapat dinilai');expect(client.rpc.mock.calls[0][1].p_query).toEqual({group_ids:[id]});client.rpc.mockResolvedValue({data:null,error:{code:'42501',message:'Akses sekarang ditolak'}});await click('Periksa sumber hasil potong');expect(container.textContent).not.toContain('KAIN-ASLI');expect(container.querySelector('[role="alert"]')).not.toBeNull();expect(new Set(client.rpc.mock.calls.map(c=>c[0]))).toEqual(new Set(['erp_cp7_capture_cutting_yield_v1','erp_cp7_read_cutting_yield_v1']))})
 it('recovers exactly the same UUID and group across a lost committed reply and remount even after a posted draft leaves the picker',async()=>{let first=true;client.rpc.mockImplementation(async(_name,args)=>{if(first){first=false;throw Error('Reply lost after commit')}return{data:data(args.p_request),error:null}});await mount();await click('Muat hasil potong tersimpan');const original=structuredClone(client.rpc.mock.calls[0][1]);expect(readCuttingYieldRequest('disposable:actor-1').pending?.id).toBe(original.p_request);await act(async()=>root.unmount());root=createRoot(container);await mount(null);expect(button('Muat hasil potong tersimpan').disabled).toBe(true);await click('Pulihkan pembacaan hasil potong');expect(client.rpc.mock.calls[1][1]).toEqual(original);expect(readCuttingYieldRequest('disposable:actor-1').pending).toBeNull();expect(container.textContent).toContain('60.123456 YARD')})
 it('retires late facts after the operator edits the form and preserves pending identity',async()=>{let resolve!:(v:unknown)=>void;client.rpc.mockImplementation(()=>new Promise(r=>{resolve=r}));await mount();await click('Muat hasil potong tersimpan');const request=client.rpc.mock.calls[0][1].p_request;await mount(id,'edited');await act(async()=>resolve({data:data(request),error:null}));await flush();expect(container.textContent).not.toContain('KAIN-ASLI');expect(readCuttingYieldRequest('disposable:actor-1').pending?.id).toBe(request);client.rpc.mockResolvedValue({data:data(request),error:null});await click('Pulihkan pembacaan hasil potong');expect(client.rpc.mock.calls[1][1].p_request).toBe(request);expect(container.textContent).toContain('60.123456 YARD')})
 it('retains the immutable old values but labels a changed source as an archive',async()=>{client.rpc.mockImplementation(async(_name,args)=>({data:data(args.p_request),error:null}));await mount();await click('Muat hasil potong tersimpan');const archive=data();archive.source_state='ARCHIVED_STALE';client.rpc.mockResolvedValue({data:archive,error:null});await click('Periksa sumber hasil potong');expect(container.textContent).toContain('Arsip pembacaan');expect(container.textContent).toContain('60.123456 YARD');expect(container.textContent).not.toContain('Normal')})
 it('clears current facts and suppresses late replies when authority changes',async()=>{let resolve!:(v:unknown)=>void;client.rpc.mockImplementation(()=>new Promise(r=>{resolve=r}));await mount();await click('Muat hasil potong tersimpan');const request=client.rpc.mock.calls[0][1].p_request;const a=structuredClone(recoveryIdentity);Object.assign(a.runtime,{mode:'DISPOSABLE_TEST'});state.auth=a;await mount();await act(async()=>resolve({data:data(request),error:null}));await flush();expect(container.textContent).toBe('');expect(readCuttingYieldRequest('disposable:actor-1').pending?.id).toBe(request)})
 it('keeps corrupt recovery and parent transactions from sending another capture',async()=>{localStorage.setItem(cuttingYieldRequestKey('disposable:actor-1'),'broken');await mount();expect(button('Muat hasil potong tersimpan').disabled).toBe(true);expect(container.querySelector('[role="alert"]')).not.toBeNull();localStorage.clear();await mount(null,'empty',true);expect(button('Muat hasil potong tersimpan').disabled).toBe(true);expect(client.rpc).not.toHaveBeenCalled()})
})
