import{parseNativeAnalysis,type NativeAnalysis,type AnalysisFinanceAccess}from'./nativeAnalysis'
import type{NativeDemandQuery}from'./nativeDemandHistory'
import{financeDate}from'./financeReportContract'

export type AttentionAction='ACK'|'DONE'|'NEW'|'SNOOZE'|'SCHEDULE'|'CANCEL_SCHEDULE'
export type AttentionPayload={run_id:string;action_key:string;action:AttentionAction;expected_revision:string;details:Record<string,string|null>}
export type AttentionRequest={id:string;query:NativeDemandQuery;semanticHash:string;payload:AttentionPayload}
export type NativeManualAttention={id:string;title:string;note:string;due_at:string;priority:'URGENT'|'NORMAL'|'LOW';module:string;status:'OPEN'|'DONE'|'CANCELLED';completed_at:string|null;cancelled_at:string|null;cancellation_reason:string|null;created_at:string;updated_at:string;row_version:string}
export type AttentionRow={action_key:string;condition:'REVIEW_REQUIRED'|'SOURCE_CHANGED';attention:{state:'NEW'|'ACK'|'DONE'|'SNOOZED';resume_at:string|null;resume_due:boolean;revision:string;updated_at:string|null};manual:NativeManualAttention|null;business_resolved:false}
export type NativeAttention={analysis:NativeAnalysis;rows:AttentionRow[];readAt:string;result:null|{request_id:string;run_id:string;action_key:string;revision:string|null;status:'COMMITTED'|'NOT_COMMITTED'}}
const fail=():never=>{throw Error('Perhatian tersimpan belum cocok dengan sumber analisis ERP.')}
const obj=(v:unknown):Record<string,unknown>=>v&&typeof v==='object'&&!Array.isArray(v)?v as Record<string,unknown>:fail()
const exact=(v:Record<string,unknown>,keys:string[])=>{if(Object.keys(v).length!==keys.length||keys.some(k=>!Object.hasOwn(v,k)))fail()}
const uuid=(v:unknown):v is string=>typeof v==='string'&&/^[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}$/.test(v)
const uint=(v:unknown):v is string=>typeof v==='string'&&/^(0|[1-9][0-9]{0,18})$/.test(v)&&BigInt(v)<=9223372036854775807n
const stamp=(v:unknown):v is string=>typeof v==='string'&&/^\d{4}-\d{2}-\d{2}T.*(?:Z|[+-]\d{2}:\d{2})$/.test(v)&&financeDate(v.slice(0,10))&&Number.isFinite(Date.parse(v))
function manual(v:unknown):NativeManualAttention|null{if(v===null)return null;const m=obj(v);exact(m,['id','title','note','due_at','priority','module','status','completed_at','cancelled_at','cancellation_reason','created_at','updated_at','row_version']);if(!uuid(m.id)||typeof m.title!=='string'||!m.title.trim()||m.title.length>200||typeof m.note!=='string'||m.note.length>4000||typeof m.module!=='string'||!m.module||!['URGENT','NORMAL','LOW'].includes(String(m.priority))||!['OPEN','DONE','CANCELLED'].includes(String(m.status))||![m.due_at,m.created_at,m.updated_at].every(stamp)||!uint(m.row_version)||m.row_version==='0'||[m.completed_at,m.cancelled_at].some(v=>v!==null&&!stamp(v))||m.cancellation_reason!==null&&typeof m.cancellation_reason!=='string')fail();if(m.status==='OPEN'&&(m.completed_at!==null||m.cancelled_at!==null||m.cancellation_reason!==null)||m.status==='DONE'&&(m.completed_at===null||m.cancelled_at!==null||m.cancellation_reason!==null)||m.status==='CANCELLED'&&(m.cancelled_at===null||!m.cancellation_reason))fail();return structuredClone(m)as NativeManualAttention}
export function parseNativeAttention(v:unknown,q:NativeDemandQuery,actor:string,access:AnalysisFinanceAccess):NativeAttention{
 const e=obj(v);exact(e,['contract_version','analysis','rows','read_at','native_manual_page_complete','delivery',...('request_result'in e?['request_result']:[])])
 if(e.contract_version!=='cp7.analysis-attention.v1'||e.native_manual_page_complete!==true||!stamp(e.read_at)||!Array.isArray(e.rows))fail()
 const delivery=obj(e.delivery);exact(delivery,['status','sent']);if(delivery.status!=='NOT_CONFIGURED'||delivery.sent!==false)fail()
 const analysis=parseNativeAnalysis(e.analysis,q,actor,access),keys=new Set(analysis.analysis.actions.map(a=>a.key))
 const rows=(e.rows as unknown[]).map(raw=>{const r=obj(raw);exact(r,['action_key','condition','attention','manual','business_resolved']);if(typeof r.action_key!=='string'||!keys.has(r.action_key)||r.business_resolved!==false||r.condition!==(analysis.state==='ARCHIVED_STALE'?'SOURCE_CHANGED':'REVIEW_REQUIRED'))fail();const a=obj(r.attention);exact(a,['state','resume_at','resume_due','revision','updated_at']);if(!['NEW','ACK','DONE','SNOOZED'].includes(String(a.state))||!uint(a.revision)||typeof a.resume_due!=='boolean'||a.updated_at!==null&&!stamp(a.updated_at)||(a.state==='SNOOZED'?!stamp(a.resume_at):a.resume_at!==null))fail();if(a.revision==='0'&&(a.state!=='NEW'||a.updated_at!==null)||a.revision!=='0'&&a.updated_at===null||a.resume_due!==(a.state==='SNOOZED'&&Date.parse(String(a.resume_at))<=Date.parse(String(e.read_at))))fail();return{action_key:r.action_key,condition:r.condition,attention:structuredClone(a),manual:manual(r.manual),business_resolved:false}as AttentionRow})
 if(rows.length!==keys.size||new Set(rows.map(r=>r.action_key)).size!==keys.size)fail()
 let result:NativeAttention['result']=null
 if('request_result'in e){const r=obj(e.request_result);exact(r,['request_id','run_id','action_key','revision','status']);if(!uuid(r.request_id)||r.run_id!==analysis.runId||typeof r.action_key!=='string'||!keys.has(r.action_key)||!['COMMITTED','NOT_COMMITTED'].includes(String(r.status))||(r.status==='COMMITTED'?!uint(r.revision)||r.revision==='0':r.revision!==null))fail();result=structuredClone(r)as NativeAttention['result']}
 return{analysis,rows,readAt:e.read_at as string,result}
}
export const attentionRequestKey=(scope:string)=>`erp.cp7.attention-request.v1:${scope}`
function validRequest(v:unknown):v is AttentionRequest{try{const r=obj(v);exact(r,['id','query','semanticHash','payload']);const q=obj(r.query);exact(q,['from_date','through_date','group_mode']);if(!uuid(r.id)||typeof r.semanticHash!=='string'||!/^[a-f0-9]{64}$/.test(r.semanticHash)||!financeDate(q.from_date)||!financeDate(q.through_date)||q.from_date>q.through_date||!['AS_SOLD','RESTATED'].includes(String(q.group_mode)))return false;const p=obj(r.payload);exact(p,['run_id','action_key','action','details','expected_revision']);if(!uuid(p.run_id)||typeof p.action_key!=='string'||!p.action_key||!['ACK','DONE','NEW','SNOOZE','SCHEDULE','CANCEL_SCHEDULE'].includes(String(p.action))||!uint(p.expected_revision))return false;const d=obj(p.details);return Object.keys(d).every(k=>['title','note','due_at','priority','resume_at','reason','expected_native_revision'].includes(k))&&Object.values(d).every(v=>v===null||typeof v==='string')&&JSON.stringify(v).length<=16000}catch{return false}}
export function readAttentionRequest(scope:string):{pending:AttentionRequest|null;error:string|null}{try{const raw=localStorage.getItem(attentionRequestKey(scope));if(raw===null)return{pending:null,error:null};const r=JSON.parse(raw);if(!validRequest(r))throw Error();return{pending:r,error:null}}catch{return{pending:null,error:'Permintaan perhatian tersimpan belum dapat dibaca. Isinya dipertahankan.'}}}
export function persistAttentionRequest(scope:string,r:AttentionRequest){if(!validRequest(r))fail();const held=readAttentionRequest(scope);if(held.error||held.pending&&JSON.stringify(held.pending)!==JSON.stringify(r))throw Error('Pastikan permintaan perhatian tersimpan terlebih dahulu.');localStorage.setItem(attentionRequestKey(scope),JSON.stringify(r));if(JSON.stringify(readAttentionRequest(scope).pending)!==JSON.stringify(r))throw Error('Permintaan perhatian belum tersimpan.')}
export function clearAttentionRequest(scope:string,id:string){const r=readAttentionRequest(scope);if(r.error||r.pending?.id!==id)throw Error('Permintaan perhatian tersimpan berubah.');localStorage.removeItem(attentionRequestKey(scope));if(localStorage.getItem(attentionRequestKey(scope))!==null)throw Error('Permintaan perhatian belum dapat dibersihkan.')}
