import {describe,it,expect}from'vitest'
import {parseNativePayableConditions as parse}from'./nativePayableConditions'
import {nativePayableFixture as fixture}from'../tests/fixtures/nativePayableConditions'
import original from'../tests/fixtures/nativeAnalysisStandin.json'
import type {NativeDemandQuery}from'./nativeDemandHistory'
const q=original.query as NativeDemandQuery,actor=original.analysis.scope.actor_scope_id,finance={ownerReports:false,preflight:false}
const read=(e=fixture())=>parse(e,q,actor,finance,true)
describe('Current accepted Native material AP source, separate from Original',()=>{
 it('copies exact Native BF balance and current due source while preserving original and deep ownership',()=>{const e=fixture(),x=read(e);expect(x.analysis.analysis).toEqual(original.analysis);expect(x.rows[0].balance?.remaining).toBe('300.00');expect(x.rows[0].liability.row_version).toBe('9007199254740993');expect(x.rows[0].condition.business_resolved).toBe(false);e.source.rows[0].balance!.remaining='0.00';expect(x.rows[0].balance?.remaining).toBe('300.00')})
 it('keeps zero-estimate uninvoiced physical receipts unresolved',()=>{const e=fixture(),r=e.source.rows[0];Object.assign(r.balance!,{paid:'500.00',remaining:'0.00'});r.invoice_coverage[0].invoiced_qty='0.000000';r.invoice_coverage[0].price_state='ESTIMATED';r.invoice_coverage[0].invoice_match_state='UNMATCHED';Object.assign(r.condition,{state:'INVOICE_PENDING',invoice_pending:true,business_resolved:false});expect(read(e).rows[0].condition.state).toBe('INVOICE_PENDING');r.condition.state='ZERO_BALANCE';r.condition.business_resolved=true;expect(()=>read(e)).toThrow()})
 it('resolves only Native zero without pending invoice and keeps native negative credit distinct from zero',()=>{const e=fixture(),r=e.source.rows[0];Object.assign(r.balance!,{paid:'500.00',remaining:'0.00'});Object.assign(r.condition,{state:'ZERO_BALANCE',business_resolved:true});expect(read(e).rows[0].condition.business_resolved).toBe(true);Object.assign(r.balance!,{final_ap:'60.00',paid:'100.00',remaining:'-40.00'});Object.assign(r.condition,{state:'CREDIT_REVIEW',business_resolved:false});expect(read(e).rows[0].balance?.remaining).toBe('-40.00');r.balance!.remaining='0.00';expect(()=>read(e)).toThrow()})
 it('uses recorded earliest invoice due, then Native header fallback; missing or impossible dates stay refused or unknown',()=>{const e=fixture(),r=e.source.rows[0];r.liability.earliest_due_date=null;r.receipt_due_date='2026-10-01';r.due_date='2026-10-01';r.due_basis='NATIVE_RECEIPT_HEADER';r.condition.state='DUE_TODAY';expect(read(e).rows[0].due_date).toBe('2026-10-01');r.receipt_due_date=null;r.due_date=null;r.due_basis='MISSING';r.condition.state='MISSING_DUE_DATE';expect(read(e).rows[0].condition.business_resolved).toBe(false);r.due_date='2026-02-30';expect(()=>read(e)).toThrow()})
 it('requires actor, current AP authority, complete unique posted supplier binding and Native WIB clock',()=>{const mutations:((e:ReturnType<typeof fixture>)=>void)[]=[e=>{e.actor_scope_id='foreign'},e=>{e.source.page_complete=false},e=>{e.source.total='2'},e=>{e.source.rows.push(structuredClone(e.source.rows[0]));e.source.total='2'},e=>{e.source.suppliers=[]},e=>{e.source.rows[0].condition.source_revision='1'},e=>{e.source.read_at='2026-09-30T01:00:00Z'},e=>{e.source.rows[0].invoice_coverage=[]}];for(const mutate of mutations){const e=fixture();mutate(e);expect(()=>read(e)).toThrow()}expect(()=>parse(fixture(),q,actor,finance,false)).toThrow()})
})
