// @vitest-environment jsdom
import {act} from 'react'
import {createRoot,type Root} from 'react-dom/client'
import {beforeEach,afterEach,it,expect,vi} from 'vitest'
import NativeModelEvaluationPanel from './NativeModelEvaluationPanel'
import {recoveryIdentity} from '../tests/fixtures/productionRecovery'
import {modelQuery,modelWire} from '../tests/fixtures/nativeModelEvaluation'
const state=vi.hoisted(()=>({auth:null as unknown}))
const client=vi.hoisted(()=>({rpc:vi.fn()}))
vi.mock('./auth/AuthProvider',()=>({useAuth:()=>state.auth}));vi.mock('./lib/supabase',()=>({getUatSupabaseClient:()=>client}))
let root:Root,container:HTMLDivElement;const start=vi.fn(),end=vi.fn(),close=vi.fn()
beforeEach(()=>{Object.assign(globalThis,{IS_REACT_ACT_ENVIRONMENT:true});localStorage.clear();client.rpc.mockReset();start.mockReset();end.mockReset();close.mockReset();const a=structuredClone(recoveryIdentity);Object.assign(a.runtime,{mode:'DISPOSABLE_TEST',projectRef:'cp6-disposable'});Object.assign(a.identity.profile,{authUserId:'auth-user-1'});a.identity.permissions.push('master.product.view','production.wip.view','warehouse.stock.view','sales.invoice.view');state.auth=a;container=document.createElement('div');document.body.append(container);root=createRoot(container)})
afterEach(async()=>{await act(async()=>root.unmount());container.remove();localStorage.clear();vi.restoreAllMocks()})
async function render(){await act(async()=>root.render(<NativeModelEvaluationPanel historyRunId={modelQuery.history_run_id} targetKey={modelQuery.target_key} onSourceReadStart={start} onSourceReadEnd={end} onClose={close}/>))}
function button(name:string){return [...container.querySelectorAll('button')].find(b=>b.textContent===name)!}
async function click(name:string){await act(async()=>button(name).click())}
async function horizon(){await act(async()=>{const input=container.querySelector('input')!;Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,'value')!.set!.call(input,'1');input.dispatchEvent(new Event('input',{bubbles:true}));input.dispatchEvent(new Event('change',{bubbles:true}))})}
const reply=(_name:string,args:{p_request:string})=>Promise.resolve({data:modelWire(args.p_request),error:null})
it('does not request, forecast or fill a horizon until the operator selects it',async()=>{client.rpc.mockImplementation(reply);await render();expect(client.rpc).not.toHaveBeenCalled();expect(container.querySelector('input')!.value).toBe('');expect(button('Bandingkan model ERP').disabled).toBe(true);await horizon();await click('Bandingkan model ERP');expect(container.textContent).toContain('Model terpilih: Rata-rata.');expect(container.textContent).toContain('Belum diketahui');expect(container.textContent).toContain('belum terbukti');expect(client.rpc.mock.calls[0]).toEqual(['erp_cp7_capture_model_evaluation_v1',{p_query:modelQuery,p_request:expect.any(String)}]);expect(start).toHaveBeenCalledTimes(1);expect(end).toHaveBeenCalledTimes(1)})
it('recovers the exact pending UUID after a lost committed reply and remount',async()=>{client.rpc.mockResolvedValueOnce({data:null,error:Error('reply lost')});await render();await horizon();await click('Bandingkan model ERP');const original=structuredClone(client.rpc.mock.calls[0]);expect(container.querySelector('.native-model-result')).toBeNull();await act(async()=>root.unmount());root=createRoot(container);client.rpc.mockImplementation(reply);await render();expect(button('Bandingkan model ERP').disabled).toBe(true);expect(container.querySelector('input')!.value).toBe('1');await click('Ulangi evaluasi yang sama');expect(client.rpc.mock.calls[1]).toEqual(original);expect(container.textContent).toContain('UNIT-MODEL-SKU');expect(localStorage.length).toBe(0)})
it('retires facts and a held reply on shared scope invalidation while preserving the horizon',async()=>{let release:(x:unknown)=>void=()=>{};client.rpc.mockImplementation(()=>new Promise(r=>release=r));await render();await horizon();await click('Bandingkan model ERP');const args=client.rpc.mock.calls[0][1];await act(async()=>window.dispatchEvent(new StorageEvent('storage',{key:null})));await act(async()=>release({data:modelWire(args.p_request),error:null}));expect(container.querySelector('.native-model-result')).toBeNull();expect(container.querySelector('input')!.value).toBe('1');expect(button('Ulangi evaluasi yang sama')).toBeTruthy();expect(start.mock.calls.length).toBe(end.mock.calls.length)})
it('retires the model result before a current access-denied archive reply',async()=>{client.rpc.mockImplementation(reply);await render();await horizon();await click('Bandingkan model ERP');client.rpc.mockResolvedValueOnce({data:null,error:Error('CP7_ACCESS_DENIED')});await click('Periksa arsip evaluasi');expect(container.querySelector('.native-model-result')).toBeNull();expect(container.querySelector('[role=alert]')).toBeTruthy();expect(container.querySelector('input')!.value).toBe('1')})
it('does not open for a missing source permission',async()=>{const a=structuredClone(recoveryIdentity);a.identity.permissions=['warehouse.stock.view'];state.auth=a;await render();expect(container.textContent).toBe('');expect(client.rpc).not.toHaveBeenCalled()})
