import {useCallback,useEffect,useMemo,useRef,useState} from 'react'
import {useAuth} from './auth/AuthProvider'
import {getUatSupabaseClient} from './lib/supabase'
import {normalizeClientError} from './lib/clientError'
import {formatCp6WibDateTime} from './cp6BusinessTime'
import {formatFact} from './cp7/workspace'
import {readNativeDemandRequest,persistNativeDemandRequest,clearNativeDemandRequest,nativeDemandRequestKey,type NativeDemandQuery} from './nativeDemandHistory'
import {parseNativeAnalysis,assertSameAnalysis,analysisProductLabel,analysisReport,analysisPrompt,type NativeAnalysis} from './nativeAnalysis'
import {analysisArchiveKey,readAnalysisArchive,rememberAnalysis,checkAnalysisPointer,type AnalysisPointer} from './nativeAnalysisArchive'
import './native-analysis.css'

type Props={query:NativeDemandQuery;onSourceReadStart:()=>void;onSourceReadEnd:()=>void;onClose:()=>void}
const permissions=['master.product.view','production.wip.view','warehouse.stock.view','sales.invoice.view']
type View='PRODUCTION'|'REPORT'|'REMINDER'|'AI'
const views:{id:View;label:string}[]=[{id:'PRODUCTION',label:'Produksi'},{id:'REPORT',label:'Laporan'},{id:'REMINDER',label:'Pengingat'},{id:'AI',label:'Tanya AI'}]
export default function NativeAnalysisPanel(props:Props){const{runtime,identity}=useAuth();if(runtime.mode!=='DISPOSABLE_TEST'||identity.status!=='AUTHORIZED'||!permissions.every(p=>identity.permissions.includes(p)))return null;return<Workspace {...props} key={`${runtime.projectRef}:${identity.profile.id}:${identity.profile.rowVersion}:${identity.profile.roleRowVersion}:${identity.permissions.join('|')}`}/>}
function Workspace({query,onSourceReadStart,onSourceReadEnd,onClose}:Props){
 const{runtime,identity}=useAuth();if(runtime.mode!=='DISPOSABLE_TEST'||identity.status!=='AUTHORIZED')throw Error('Sesi analisis belum siap.')
 const client=useMemo(()=>getUatSupabaseClient(runtime),[runtime]),scope='analysis:'+runtime.projectRef+':'+identity.profile.id,actor=identity.profile.authUserId,sequence=useRef(0),active=useRef(false)
 const[data,setData]=useState<NativeAnalysis|null>(null),[recovery,setRecovery]=useState(()=>readNativeDemandRequest(scope)),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState(''),[view,setView]=useState<View>('PRODUCTION'),[search,setSearch]=useState(''),[question,setQuestion]=useState('Apa yang perlu diperiksa sebelum rencana produksi diterapkan?')
 const[archive,setArchive]=useState(()=>readAnalysisArchive(scope))
 const begin=()=>{const n=++sequence.current;active.current=true;setBusy(true);setData(null);setError('');setMessage('');onSourceReadStart();return n}
 const end=(n:number)=>{if(n===sequence.current){active.current=false;setBusy(false);onSourceReadEnd()}}
 useEffect(()=>()=>{++sequence.current;if(active.current){active.current=false;onSourceReadEnd()}},[onSourceReadEnd])
 useEffect(()=>{const listener=(e:StorageEvent)=>{if(e.key===null||[nativeDemandRequestKey(scope),analysisArchiveKey(scope)].includes(e.key)){++sequence.current;active.current=false;setBusy(false);setData(null);setRecovery(readNativeDemandRequest(scope));setArchive(readAnalysisArchive(scope));onSourceReadStart();onSourceReadEnd()}};addEventListener('storage',listener);return()=>removeEventListener('storage',listener)},[scope,onSourceReadStart,onSourceReadEnd])
 const load=async(retry=false)=>{const n=begin();try{
  const held=readNativeDemandRequest(scope);if(held.error)throw Error(held.error);if(retry&&!held.pending)throw Error('Permintaan analisis tersimpan tidak tersedia.');if(!retry&&held.pending)throw Error('Pastikan permintaan analisis yang sama terlebih dahulu.')
  const r=retry?held.pending!:{id:crypto.randomUUID(),q:query};if(!retry)persistNativeDemandRequest(scope,r);setRecovery(readNativeDemandRequest(scope))
  const response=await client.rpc('erp_cp7_capture_analysis_v1',{p_query:r.q,p_request:r.id});if(n!==sequence.current)return;if(response.error)throw response.error
  const parsed=parseNativeAnalysis(response.data,r.q,actor);if(parsed.requestId!==r.id)throw Error('Permintaan analisis server berubah.');rememberAnalysis(scope,parsed);setArchive(readAnalysisArchive(scope));clearNativeDemandRequest(scope,r.id);setRecovery(readNativeDemandRequest(scope));setData(parsed)
 }catch(e){if(n===sequence.current)setError(normalizeClientError(e).message)}finally{end(n)}}
 const check=async(copy:'REPORT'|'AI'|null=null)=>{if(!data)return;const previous=data,n=begin();try{
  const response=await client.rpc('erp_cp7_read_analysis_v1',{p_run:previous.runId});if(n!==sequence.current)return;if(response.error)throw response.error
  const parsed=parseNativeAnalysis(response.data,previous.query,actor);assertSameAnalysis(previous,parsed);setData(parsed)
  if(copy){if(parsed.state!=='UNCHANGED')throw Error('Sumber sudah berubah. Ambil analisis baru sebelum menyalin laporan atau pertanyaan.');const text=copy==='REPORT'?analysisReport(parsed):analysisPrompt(parsed,question);if(copy==='AI'&&text.length>1000000)throw Error('Sumber analisis terlalu besar untuk salinan AI ini. Sumber lengkap dipertahankan.');await navigator.clipboard.writeText(text);if(n===sequence.current)setMessage(copy==='REPORT'?'Laporan disalin.':'Pertanyaan dan data sumber disalin; siap ditinjau di AI pilihanmu.')}
 }catch(e){if(n===sequence.current)setError(normalizeClientError(e).message)}finally{end(n)}}
 const openArchive=async(p:AnalysisPointer)=>{const n=begin();try{const response=await client.rpc('erp_cp7_read_analysis_v1',{p_run:p.runId});if(n!==sequence.current)return;if(response.error)throw response.error;const parsed=parseNativeAnalysis(response.data,p.query,actor);checkAnalysisPointer(p,parsed);setData(parsed)}catch(e){if(n===sequence.current)setError(normalizeClientError(e).message)}finally{end(n)}}
 const close=useCallback(()=>{++sequence.current;if(active.current){active.current=false;onSourceReadEnd()}onClose()},[onSourceReadEnd,onClose])
 const blocked=busy||Boolean(recovery.pending||recovery.error),x=data?.analysis,rows=x?.recommendations.filter(r=>analysisProductLabel(r,data??undefined).toLowerCase().includes(search.toLowerCase()))??[]
 return<section className="native-analysis panel" aria-label="Analisis ERP bersama"><header><div><div className="eyebrow">PERENCANAAN · DATA ERP</div><h2>Analisis, laporan & pengingat</h2><p>Empat tampilan memakai hasil analisis yang sama untuk seluruh produk.</p></div><button disabled={busy} onClick={close}>Tutup analisis bersama</button></header>
  <div className="native-analysis-actions"><button disabled={blocked} onClick={()=>void load()}>Ambil analisis ERP terbaru</button>{data?<button disabled={blocked} onClick={()=>void check()}>Periksa sumber analisis</button>:null}</div>
  {busy?<p role="status">Memeriksa sumber ERP dan hak akses saat ini…</p>:null}{error||recovery.error?<p role="alert">{error||recovery.error}</p>:null}{message?<p role="status">{message}</p>:null}
  {recovery.pending?<div role="status"><p>Hasil permintaan analisis belum dipastikan.</p><button disabled={busy} onClick={()=>void load(true)}>Ulangi analisis yang sama</button></div>:null}
  {archive.error?<p role="alert">{archive.error}</p>:null}{archive.rows.length?<details><summary>Arsip analisis yang pernah dibuka</summary><p>Isi arsip dibaca kembali dari server dengan izin saat ini.</p>{archive.rows.map((p,i)=><button key={p.runId} disabled={blocked} aria-label={`Buka arsip analisis ${i+1}`} onClick={()=>void openArchive(p)}>Analisis {formatCp6WibDateTime(p.capturedAt)} · riwayat {p.query.from_date} sampai {p.query.through_date}</button>)}</details>:null}
  {data&&x?<article className="native-analysis-result"><p className={data.state==='UNCHANGED'?'native-demand-current':'native-demand-stale'}>{data.state==='UNCHANGED'?'Sumber sesuai saat diperiksa.':'Arsip lama: sumber berubah. Ambil analisis baru.'} Diambil {formatCp6WibDateTime(x.snapshot.generated_at)}.</p><p className="native-analysis-run">Analisis <span>{data.runId}</span> · jadwal versi {x.scenario.version}.</p>
   <p>Bahan, produksi baru, serta keuangan dan HPP pada analisis perencanaan ini belum dipastikan. Angka belum diketahui tetap ditampilkan apa adanya.</p>
   <div role="tablist" aria-label="Tampilan analisis bersama">{views.map(v=><button role="tab" key={v.id} aria-selected={view===v.id} id={`native-analysis-${v.id}`} aria-controls="native-analysis-content" onClick={()=>setView(v.id)}>{v.label}</button>)}</div>
   <div role="tabpanel" id="native-analysis-content" aria-labelledby={`native-analysis-${view}`}>
    {view==='PRODUCTION'?<><label>Cari pada hasil analisis<input aria-label="Cari hasil analisis bersama" value={search} onChange={e=>setSearch(e.target.value)}/></label><p>{rows.length} dari {x.recommendations.length} produk. Pencarian hanya menyaring tampilan.</p><div className="responsive-table"><table><thead><tr><th>Produk</th><th>Status produksi</th><th>Stok fisik</th><th>Target</th><th>Kurang setelah stok proses terikat</th><th>Kurang setelah pembagian global</th><th>Produksi baru layak</th></tr></thead><tbody>{rows.map(r=><tr key={r.target.key}><td><strong>{analysisProductLabel(r,data)}</strong></td><td data-label="Status produksi">{r.production_state==='ACTIVE'?'Aktif':r.production_state==='PAUSED'?'Ditunda':'Dihentikan'}</td><td data-label="Stok fisik">{formatFact(r.actual_fg)}</td><td data-label="Target">{formatFact(r.target_qty)}</td><td data-label="Kurang setelah stok proses terikat">{formatFact(r.q_base)}</td><td data-label="Kurang setelah pembagian global">{formatFact(r.q_conditional)}</td><td data-label="Produksi baru layak">{formatFact(r.feasible_new)}</td></tr>)}</tbody></table></div><p>Stok proses bukan stok jadi. Perkiraan hasil dan waktu memakai asumsi jadwal yang dipilih.</p><details><summary>Alokasi dan sumber asli</summary>{x.allocation_edges.map((e,i)=><p key={`${e.source_key}:${e.target_key}:${i}`}>{e.source_key} → {data.labels.find(l=>l.key===e.target_key)?.sku??e.target_key}: input {formatFact(e.input_qty)}, proyeksi {formatFact(e.projected_output_qty)}.</p>)}{x.sources.map(s=><p key={s.source_key}>{s.source_key}: fisik {formatFact(s.physical_remaining)}; dialokasikan {formatFact(s.allocated)}; siap {s.eta?formatCp6WibDateTime(s.eta):'belum diketahui'}.</p>)}</details></>:null}
    {view==='REPORT'?<><h3>Laporan perencanaan</h3><button disabled={blocked||data.state!=='UNCHANGED'} onClick={()=>void check('REPORT')}>Periksa & salin laporan</button><pre aria-label="Isi laporan ERP">{analysisReport(data)}</pre></>:null}
    {view==='REMINDER'?<><h3>Hal yang perlu diperiksa</h3><p>Daftar ini berasal dari analisis yang sama. Sumber yang berubah belum dianggap masalah selesai.</p>{x.actions.map(a=><article key={a.key}><h4>{a.primary_reason==='PRODUCTION_POLICY_UNREVIEWED'?'Status produksi perlu diperiksa':'Bahan dan batas produksi perlu diperiksa'}</h4><p>{a.display_priority.basis.join('; ')}</p>{a.target_keys.map(k=><p key={k}>{data.labels.find(l=>l.key===k)?.name??k}</p>)}<details><summary>Sumber pemeriksaan</summary>{a.source_links.map((r,i)=><p key={`${r.kind}:${r.id}:${i}`}>{r.kind} · {r.id} · versi {r.revision}</p>)}</details></article>)}{!x.actions.length?<p>Tidak ada tindakan yang dapat disimpulkan dari sumber ini. Kelengkapan sumber tetap perlu diperiksa.</p>:null}</>:null}
    {view==='AI'?<><h3>Tanya AI dengan sumber yang diperiksa</h3><label>Pertanyaanmu<textarea aria-label="Pertanyaan analisis ERP" value={question} maxLength={10000} onChange={e=>setQuestion(e.target.value)}/></label><button disabled={blocked||data.state!=='UNCHANGED'||!question.trim()} onClick={()=>void check('AI')}>Periksa & salin pertanyaan untuk AI</button><p>Salin pertanyaan dan sumber, lalu buka AI pilihanmu. Jawaban AI tetap perlu ditinjau.</p><pre aria-label="Pertanyaan dan sumber ERP">{analysisPrompt(data,question)}</pre></>:null}
   </div><details><summary>Asumsi dan batas data</summary>{x.assumptions.map(a=><p key={a.id}>{a.label} · {a.confirmed_for_operation?'Dikonfirmasi untuk operasi':'Belum dikonfirmasi untuk operasi'}.</p>)}{x.generation_warnings.map((w,i)=><p key={`${w}:${i}`}>{w}</p>)}<p>Hash hasil {x.semantic_hash}</p></details>
  </article>:null}
 </section>
}
