import {useEffect,useMemo,useRef,useState} from 'react'
import {useAuth} from './auth/AuthProvider'
import {getUatSupabaseClient} from './lib/supabase'
import {normalizeClientError} from './lib/clientError'
import {formatCp6WibDateTime} from './cp6BusinessTime'
import {cuttingInputKey,heldCuttingInput,holdCuttingInput,releaseCuttingInput,parseCuttingInputWorkspace,parseCuttingInputCommand,validateCuttingInputPayload,type CuttingFamily,type CuttingInputPayload,type CuttingInputWorkspace} from './nativeCuttingInputs'
type Props={groupId:string|null;sourceKey:string;parentBusy:boolean}
const required=['production.cutting.view','master.product.view','production.wip.view','warehouse.stock.view','sales.invoice.view']
type Form={marker:string;mix:Record<string,string>;rolls:Record<string,CuttingFamily&{width:string}>;reviewed:boolean}
const empty:Form={marker:'',mix:{},rolls:{},reviewed:false}
const blankRoll={brand:'',mill:'',variant:'',spec_revision:'',width:''}
export default function NativeCuttingInputsPanel(props:Props){
 const{runtime,identity}=useAuth()
 if(runtime.mode!=='DISPOSABLE_TEST'||identity.status!=='AUTHORIZED'||!['OWNER','ADMIN'].includes(identity.profile.role)||!required.every(p=>identity.permissions.includes(p)))return null
 return <Workspace {...props} key={`${runtime.projectRef}:${identity.profile.id}:${identity.profile.rowVersion}:${identity.profile.roleRowVersion}:${identity.permissions.join('|')}`}/>
}
function Workspace({groupId,sourceKey,parentBusy}:Props){
 const{runtime,identity}=useAuth();if(runtime.mode!=='DISPOSABLE_TEST'||identity.status!=='AUTHORIZED')throw Error('Sesi rencana potong belum siap.')
 const scope=runtime.projectRef+':'+identity.profile.id,client=useMemo(()=>getUatSupabaseClient(runtime),[runtime]),seq=useRef(0)
 const[data,setData]=useState<{binding:string;value:CuttingInputWorkspace}|null>(null),[form,setForm]=useState<Form>(empty),[held,setHeld]=useState(()=>heldCuttingInput(scope)),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('')
 const binding=JSON.stringify([groupId,sourceKey,parentBusy]),current=useRef(binding),priorGroup=useRef(groupId);current.current=binding
 useEffect(()=>{++seq.current;setData(null);setBusy(false);setError('');setMessage('');if(priorGroup.current!==groupId)setForm(empty);else setForm(f=>({...f,reviewed:false}));priorGroup.current=groupId;return()=>{++seq.current}},[binding,groupId])
 useEffect(()=>{const listener=(e:StorageEvent)=>{if(e.key===null||e.key===cuttingInputKey(scope)){++seq.current;setBusy(false);setData(null);setHeld(heldCuttingInput(scope))}};addEventListener('storage',listener);return()=>removeEventListener('storage',listener)},[scope])
 const visible=data?.binding===binding&&!busy&&!parentBusy?data.value:null
 const publish=(w:CuttingInputWorkspace,bound:string)=>{if(groupId!==null&&w.requested_group_id!==groupId){setMessage('Permintaan lama selesai. Muat potongan yang sekarang dipilih.');return}setData({binding:bound,value:w})}
 const load=async()=>{const readGroup=groupId??data?.value.requested_group_id;if(!readGroup||parentBusy)return;const n=++seq.current,bound=current.current;setData(null);setError('');setMessage('');setBusy(true)
  try{const r=await client.rpc('erp_cp7_get_cutting_input_workspace_v1',{p_group:readGroup});if(n!==seq.current||bound!==current.current)return;if(r.error)throw r.error;publish(parseCuttingInputWorkspace(r.data,readGroup),bound)}catch(e){if(n===seq.current)setError(normalizeClientError(e).message)}finally{if(n===seq.current)setBusy(false)}
 }
 const adopt=()=>{if(!visible?.anchor)return;const saved=visible.record;setForm({marker:saved?.values.rolls[0]?.context.marker_key??'',mix:Object.fromEntries(visible.anchor.size_ids.map(s=>[s,saved?.values.planned_mix.find(x=>x.size_id===s)?.drawings??''])),rolls:Object.fromEntries(visible.anchor.rolls.map(r=>{const old=saved?.values.rolls.find(x=>x.roll_id===r.roll_id);return[r.roll_id,{brand:old?.context.family.brand??'',mill:old?.context.family.mill??'',variant:old?.context.family.variant??'',spec_revision:old?.context.family.spec_revision??'',width:old?.width_cm??''}]})),reviewed:false})}
 const act=async(lookup=false)=>{
  if(parentBusy)return;const n=++seq.current,bound=current.current,w=visible;setError('');setMessage('');setBusy(true);setData(null)
  try{const pending=heldCuttingInput(scope);if(pending.error)throw Error(pending.error);if(lookup&&!pending.pending)throw Error('Catatan permintaan tidak ada.');if(!lookup&&(!w?.can_record||!w.group||!w.anchor||pending.pending||!form.reviewed))throw Error('Muat sumber dan periksa isian rencana dahulu.')
   let request=pending.pending
   if(!lookup){const payload:CuttingInputPayload={group_id:w!.group!.id,expected_group_version:w!.group!.version,expected_input_version:w!.record?.version??null,marker_key:form.marker,planned_mix:w!.anchor!.size_ids.map(s=>({size_id:s,drawings:form.mix[s]??''})),roll_inputs:w!.anchor!.rolls.map(r=>({roll_id:r.roll_id,family:{brand:form.rolls[r.roll_id]?.brand??'',mill:form.rolls[r.roll_id]?.mill??'',variant:form.rolls[r.roll_id]?.variant??'',spec_revision:form.rolls[r.roll_id]?.spec_revision??''},width_cm:form.rolls[r.roll_id]?.width||null})),explicit_review:true};request={id:crypto.randomUUID(),payload:validateCuttingInputPayload(payload)};holdCuttingInput(scope,request)}
   setHeld(heldCuttingInput(scope));const r=lookup?await client.rpc('erp_cp7_get_cutting_input_request_v1',{p_payload:request!.payload,p_request:request!.id}):await client.rpc('erp_cp7_record_cutting_inputs_v1',{p_payload:request!.payload,p_request:request!.id})
   if(n!==seq.current||bound!==current.current)return;if(r.error)throw r.error;const result=parseCuttingInputCommand(r.data,request!);releaseCuttingInput(scope,request!);setHeld(heldCuttingInput(scope));publish(result.current,bound);setForm(old=>({...old,reviewed:false}));setMessage(result.result.status==='COMMITTED'?'Rencana tercatat. Transaksi potong tetap mengikuti Simpan dan Post.':'Permintaan tadi belum tersimpan dan sudah ditutup. Periksa sumber sebelum menyimpan dengan permintaan baru.')
  }catch(e){if(n===seq.current){setError(normalizeClientError(e).message);setHeld(heldCuttingInput(scope))}}finally{if(n===seq.current)setBusy(false)}
 }
 const canEdit=Boolean(visible?.can_record)&&identity.permissions.includes('production.cutting.edit')&&!held.pending&&!held.error
 return <section className="ccut-card wide" aria-label="Rencana bahan sebelum potong"><header><span>RENCANA POTONG</span><strong>Bahan dan susunan ukuran</strong></header><p>Catat rencana sebelum kain dipotong. Lebar boleh kosong. Catatan yang baru dibuat setelah pemotongan tetap diberi waktu pencatatan yang sebenarnya.</p>
  <div className="ccut-actions"><button type="button" disabled={!groupId||busy||parentBusy||Boolean(held.pending||held.error)} onClick={()=>void load()}>Muat rencana potong</button>{held.pending?<button type="button" disabled={busy||parentBusy} onClick={()=>void act(true)}>Pulihkan rencana potong</button>:null}{visible?<button type="button" disabled={busy||parentBusy||Boolean(held.pending||held.error)} onClick={()=>void load()}>Periksa sumber rencana</button>:null}{visible?.anchor?<button type="button" disabled={!canEdit} onClick={adopt}>Isi formulir dari catatan ini</button>:null}</div>
  {busy?<p role="status">Memeriksa rencana potong…</p>:null}{error||held.error?<p role="alert">{error||held.error}</p>:null}{message?<p role="status">{message}</p>:null}
  {visible?<>{visible.group?<p>Pola {visible.group.pattern_revision??'belum tersedia'} · potong {formatCp6WibDateTime(visible.group.physical_at)}.</p>:<p>Potongan ini sudah tidak tersedia. Catatan lama tetap menjadi arsip dan tidak dipakai untuk menilai hasil sekarang.</p>}{visible.record?<div data-cutting-input-record><p>Catatan versi {visible.record.version}, dibuat {formatCp6WibDateTime(visible.record.known_at)}.</p><p>{!visible.record_matches_native_identity?'Identitas potongan berubah. Catatan lama perlu diperiksa.':visible.preknown_before_physical?'Catatan ini dibuat sebelum waktu potong.':'Catatan ini dibuat setelah waktu potong; tidak digunakan sebagai rencana yang sudah diketahui saat itu.'}</p>{visible.record.values.rolls.map(r=><p key={r.roll_id}>{r.context.family.brand} · {r.context.family.mill} · {r.context.family.variant} · spesifikasi {r.context.family.spec_revision} · lebar {r.width_cm===null?'belum dicatat':r.width_cm+' cm'}.</p>)}</div>:<p>Belum ada catatan rencana untuk potongan ini.</p>}
   <fieldset className="ccut-input-plan" disabled={!canEdit}><legend>Isian rencana yang diperiksa operator</legend><div className="ccut-fields"><label>Nama susunan pola<input value={form.marker} onChange={e=>setForm(f=>({...f,marker:e.target.value,reviewed:false}))}/></label>{visible.anchor?.size_ids.map(s=><label key={s}>Jumlah gambar ukuran {visible.size_labels[s]??s.slice(0,8)}<input inputMode="numeric" value={form.mix[s]??''} onChange={e=>setForm(f=>({...f,mix:{...f.mix,[s]:e.target.value},reviewed:false}))}/></label>)}</div>
    {visible.anchor?.rolls.map(r=><div key={r.roll_id}><p>{visible.roll_labels[r.roll_id]??'Bahan'} · roll {r.roll_id.slice(0,8)} · satuan {r.unit}.</p><div className="ccut-fields">{(['brand','mill','variant','spec_revision']as const).map((k,i)=><label key={k}>{['Merek kain','Pabrik kain','Jenis kain','Revisi spesifikasi'][i]} · {r.roll_id.slice(0,8)}<input value={form.rolls[r.roll_id]?.[k]??''} onChange={e=>setForm(f=>({...f,rolls:{...f.rolls,[r.roll_id]:{...(f.rolls[r.roll_id]??blankRoll),[k]:e.target.value}},reviewed:false}))}/></label>)}<label>Lebar tercatat (cm) · {r.roll_id.slice(0,8)}<input inputMode="decimal" value={form.rolls[r.roll_id]?.width??''} onChange={e=>setForm(f=>({...f,rolls:{...f.rolls,[r.roll_id]:{...(f.rolls[r.roll_id]??blankRoll),width:e.target.value}},reviewed:false}))}/></label></div></div>)}
    <label><input type="checkbox" checked={form.reviewed} onChange={e=>setForm(f=>({...f,reviewed:e.target.checked}))}/> Saya sudah memeriksa bahan dan susunan ukuran.</label><button type="button" disabled={!form.reviewed} onClick={()=>void act()}>Catat rencana potong</button>
   </fieldset><p>Rentang hasil belum dinilai. Rencana tidak mengganti stok, HPP, atau hasil potong.</p></>:<p>Simpan draft, lalu muat sumber potongan untuk mencatat rencananya.</p>}
 </section>
}
