// @vitest-environment jsdom
// Synthetic DOM checks use the real shared mutation/recovery hook. Native
// database, HTTP and browser evidence belongs to the separate runtime probe.
import {act} from 'react'
import {createRoot,type Root} from 'react-dom/client'
import {beforeEach,afterEach,it,expect,vi} from 'vitest'
import NativePlanDraftPanel from './NativePlanDraftPanel'
import {recoveryIdentity,cuttingCommit} from '../tests/fixtures/productionRecovery'
import * as f from '../tests/fixtures/nativePlan'
import {readProductionRecovery,productionKey} from './productionRecovery'
const state=vi.hoisted(()=>({auth:null as unknown}))
const client=vi.hoisted(()=>({rpc:vi.fn()}))
vi.mock('./auth/AuthProvider',()=>({useAuth:()=>state.auth}))
vi.mock('./lib/supabase',()=>({getUatSupabaseClient:()=>client}))
const scope='cp6-disposable:actor-1',start=vi.fn(),end=vi.fn(),close=vi.fn()
let root:Root,container:HTMLDivElement,applied:boolean
beforeEach(()=>{Object.assign(globalThis,{IS_REACT_ACT_ENVIRONMENT:true});localStorage.clear();client.rpc.mockReset();start.mockReset();end.mockReset();close.mockReset();applied=false;const a=structuredClone(recoveryIdentity);Object.assign(a.runtime,{mode:'DISPOSABLE_TEST',projectRef:'cp6-disposable'});Object.assign(a.identity.profile,{authUserId:f.actor});a.identity.permissions.push('master.product.view','warehouse.stock.view','sales.invoice.view','production.cutting.view');state.auth=a;Object.defineProperty(navigator,'locks',{configurable:true,value:{request:async(_n:string,_o:unknown,fn:(l:unknown)=>Promise<unknown>)=>fn({})}});container=document.createElement('div');document.body.append(container);root=createRoot(container)})
afterEach(async()=>{await act(async()=>root.unmount());container.remove();localStorage.clear();Reflect.deleteProperty(navigator,'locks');vi.restoreAllMocks()})
async function render(context=f.context){await act(async()=>root.render(<NativePlanDraftPanel context={context} onSourceReadStart={start} onSourceReadEnd={end} onClose={close}/>))}
function button(name:string){const b=[...container.querySelectorAll('button')].find(b=>b.textContent===name);expect(b,`button ${name}`).toBeTruthy();return b!}
async function click(name:string){await act(async()=>button(name).click())}
async function fill(label:string,value:string){await act(async()=>{const node=container.querySelector(`[aria-label="${label}"]`) as HTMLInputElement|HTMLTextAreaElement|HTMLSelectElement;expect(node).toBeTruthy();const proto=node instanceof HTMLSelectElement?HTMLSelectElement.prototype:node instanceof HTMLTextAreaElement?HTMLTextAreaElement.prototype:HTMLInputElement.prototype;Object.getOwnPropertyDescriptor(proto,'value')!.set!.call(node,value);node.dispatchEvent(new Event('input',{bubbles:true}));node.dispatchEvent(new Event('change',{bubbles:true}))})}
async function check(label:string){await act(async()=>(container.querySelector(`[aria-label="${label}"]`) as HTMLInputElement).click())}
function readWire(){const value=f.saved();if(!applied)return value;return{...value,state:'NATIVE_DRAFT_CREATED',native_intent:{id:f.order,cutting_group_id:f.pattern,group_number:'SYNTHETIC-CUT',material_issue_posted:false}}}
function appliedWire(request:string){return{contract_version:'cp7.plan-apply-outcome.v1',actor_scope_id:f.actor,request_id:request,draft_id:f.draft,revision:'1',target_key:f.context.targetKey,state:'NATIVE_DRAFT_CREATED',kind:'COMMITTED_OUTCOME',intent_id:f.order,physical_production_confirmed:false,reservation_created:false,production_go:false,native:{...cuttingCommit('SAVE_DRAFT'),cutting_group_id:f.pattern,group_number:'SYNTHETIC-CUT'}}}
function reply(name:string,args:{p_request?:string}){let data:unknown;if(name==='erp_cp7_get_plan_options_v1')data=f.options();else if(name==='erp_cp7_save_plan_draft_v1')data=f.saveOutcome(args.p_request!);else if(name==='erp_cp7_read_plan_draft_v1')data=readWire();else if(name==='erp_cp7_preview_plan_action_v1')data=f.preview();else if(name==='erp_cp7_apply_plan_action_v1'){applied=true;data=appliedWire(args.p_request!)}else throw Error('Unexpected RPC '+name);return Promise.resolve({data,error:null})}
async function form(){await click('Muat pilihan Potongan dari ERP');await fill('Gudang bahan rencana',f.location);await click('Muat pilihan Potongan dari ERP');await fill('PO rencana',f.order);await fill('Pola rencana',f.pattern);await fill('Waktu pencatatan draf WIB','2026-10-01T15:00:00');await click('Pilih roll SYNTHETIC-ROLL');await fill('Keluar roll rencana 1','1');await fill('Terpakai roll rencana 1','0.5');await fill('Sisa roll rencana 1','0.5');await fill('Hasil roll rencana 1','60');await fill('Catatan rencana Potongan','Catatan operator sendiri');await fill('Alasan rencana Potongan','Komposisi dan sumber diperiksa');await check('Asumsi dan komposisi rencana sudah diperiksa')}
async function readyApply(){await click('Simpan rencana Potongan');await click('Periksa pratinjau rencana');await fill('Alasan membuat draf Potongan','Pratinjau terkini sudah diperiksa');await check('Pratinjau sudah diperiksa untuk membuat draf')}
it('loads only on explicit request and sends reviewed composition with no posting or reservation claim',async()=>{client.rpc.mockImplementation(reply);await render();expect(client.rpc).not.toHaveBeenCalled();expect((container.querySelector('[aria-label="Waktu pencatatan draf WIB"]') as HTMLInputElement).value).toBe('');await form();await readyApply();expect(container.textContent).not.toContain('belum tertutup 40 PCS');expect(container.textContent).toContain('Hasil bagus start baru belum diketahui');expect(container.textContent).toContain('Tidak dianggap 100%');const save=client.rpc.mock.calls.find(c=>c[0]==='erp_cp7_save_plan_draft_v1')![1];expect(save.p_payload.cutting.cut_at).toBe('2026-10-01T08:00:00.000Z');expect(save.p_payload.cutting).not.toHaveProperty('action');await click('Buat draf Potongan di ERP');expect(container.textContent).toContain('draf Potongan sudah dibuat');expect(readProductionRecovery(scope).pending).toEqual({});expect(start.mock.calls.length).toBe(end.mock.calls.length)})
it.each(['SAVE_DRAFT','APPLY'])('recovers exact %s UUID and payload after a lost reply and remount',async action=>{client.rpc.mockImplementation(reply);await render();await form();if(action==='APPLY')await readyApply();const name=action==='APPLY'?'erp_cp7_apply_plan_action_v1':'erp_cp7_save_plan_draft_v1';client.rpc.mockImplementation((n,args)=>{if(n===name){if(action==='APPLY')applied=true;return Promise.resolve({data:null,error:Error('Committed reply lost')})}return reply(n,args)});await click(action==='APPLY'?'Buat draf Potongan di ERP':'Simpan rencana Potongan');const original=structuredClone(client.rpc.mock.calls.find(c=>c[0]===name)!);expect(readProductionRecovery(scope).pending.PLAN_APPLY?.id).toBe(original[1].p_request);expect(localStorage.getItem(productionKey(scope,'PLAN_APPLY'))).toContain(original[1].p_request);await act(async()=>root.unmount());root=createRoot(container);client.rpc.mockImplementation(reply);await render();expect(button('Muat pilihan Potongan dari ERP').disabled).toBe(true);await click('Reconcile transaksi');const sent=client.rpc.mock.calls.filter(c=>c[0]===name);expect(sent).toHaveLength(2);expect(sent[1]).toEqual(original);expect(readProductionRecovery(scope).pending).toEqual({});expect(container.textContent).toContain(action==='APPLY'?'draf Potongan sudah dibuat':'Rencana versi 1');expect(start.mock.calls.length).toBe(end.mock.calls.length)})
it('retires held choices on source replacement and preserves only the operator fields',async()=>{let release:(x:unknown)=>void=()=>{};client.rpc.mockImplementation(()=>new Promise(r=>release=r));await render();await fill('Catatan rencana Potongan','Pilihan operator');await click('Muat pilihan Potongan dari ERP');await render({...f.context,runId:f.order,sourceHash:'c'.repeat(64)});await act(async()=>release({data:f.options(),error:null}));expect(container.querySelector('.native-plan-result')).toBeNull();expect((container.querySelector('[aria-label="Catatan rencana Potongan"]') as HTMLTextAreaElement).value).toBe('Pilihan operator');expect(button('Simpan rencana Potongan').disabled).toBe(true);expect(start.mock.calls.length).toBe(end.mock.calls.length)})
it('retires held choices on shared storage invalidation without losing operator fields',async()=>{let release:(x:unknown)=>void=()=>{};client.rpc.mockImplementation(()=>new Promise(r=>release=r));await render();await fill('Cari PO rencana','Milik operator');await click('Muat pilihan Potongan dari ERP');await act(async()=>window.dispatchEvent(new StorageEvent('storage',{key:null})));await act(async()=>release({data:f.options(),error:null}));expect(container.querySelector('.native-plan-result')).toBeNull();expect((container.querySelector('[aria-label="Cari PO rencana"]') as HTMLInputElement).value).toBe('Milik operator');expect(start.mock.calls.length).toBe(end.mock.calls.length)})
it('clears current facts and saved header on a current 403 while retaining own notes and the opaque pointer',async()=>{client.rpc.mockImplementation(reply);await render();await form();await readyApply();expect(container.textContent).toContain('Pratinjau yang diperiksa');client.rpc.mockResolvedValueOnce({data:null,error:{code:'42501',message:'CP7_PLAN_ACCESS_DENIED',status:403}});await click('Muat rencana tersimpan');expect(container.textContent).not.toContain('SYNTHETIC-P08');expect(container.textContent).not.toContain('Rencana versi 1');expect(container.textContent).not.toContain('Pratinjau yang diperiksa');expect((container.querySelector('[aria-label="Catatan rencana Potongan"]') as HTMLTextAreaElement).value).toBe('Catatan operator sendiri');expect(container.querySelector('[role=alert]')).toBeTruthy();expect(localStorage.getItem('erp.cp7.plan-pointer.v1:'+scope)).toBe(JSON.stringify({id:f.draft}));expect(start.mock.calls.length).toBe(end.mock.calls.length)})
it('does not admit the bridge without every required current source permission',async()=>{const a=structuredClone(recoveryIdentity);state.auth=a;await render();expect(container.textContent).toBe('');expect(client.rpc).not.toHaveBeenCalled()})
it('reads actual production explicitly and retires it on held current403 while retaining operator notes',async()=>{client.rpc.mockImplementation(reply);await render();await form();await readyApply();await click('Buat draf Potongan di ERP');client.rpc.mockResolvedValueOnce({data:f.actual(),error:null});await click('Bandingkan rencana dengan hasil produksi');expect(container.textContent).toContain('Rencana tersimpan: 60 PCS');expect(container.textContent).toContain('59 PCS');expect(container.textContent).toContain('Sumber rencana lama sudah berubah');let release:(value:unknown)=>void=()=>{};client.rpc.mockImplementationOnce(()=>new Promise(r=>release=r));await click('Bandingkan rencana dengan hasil produksi');expect(container.querySelector('[aria-label="Perbandingan rencana dan hasil produksi"]')).toBeNull();await act(async()=>release({data:null,error:{code:'42501',status:403,message:'CP7_PLAN_ACCESS_DENIED'}}));expect(container.querySelector('[aria-label="Perbandingan rencana dan hasil produksi"]')).toBeNull();expect(container.textContent).not.toContain('Rencana versi 1');expect((container.querySelector('[aria-label="Catatan rencana Potongan"]')as HTMLTextAreaElement).value).toBe('Catatan operator sendiri');expect(start.mock.calls.length).toBe(end.mock.calls.length)})
