import{useState}from'react'
import type{NativeObligationObservation}from'./nativeObligationEpisodes'
import{formatCp6WibDateTime}from'./cp6BusinessTime'
import{receivableStateLabel}from'./nativeReceivableConditions'
import{payableStateLabel}from'./nativePayableConditions'
const conditions:Record<string,string>={...receivableStateLabel,...payableStateLabel,SOURCE_UNKNOWN:'Sumber belum lengkap; masalah tetap terbuka'}
const states={ACTIVE:'Masalah masih terbuka',RESOLVED:'Selesai menurut pemeriksaan ERP',ARCHIVED:'Pemantauan diarsipkan'}
export default function NativeObligationObservationView({data}:{data:NativeObligationObservation}){
 const[page,setPage]=useState(0)
 return<section aria-label="Catatan pemeriksaan tagihan"><h4>Catatan pemeriksaan {data.domain==='AR'?'piutang pelanggan':'utang bahan pemasok'}</h4><p>Pengamatan tersimpan{data.observedAt?' pada '+formatCp6WibDateTime(data.observedAt):''}. Periksa sumber ERP untuk saldo terbaru.</p>{data.status==='NOT_COMMITTED'?<p>Server memastikan pemeriksaan ini belum tersimpan. Permintaan lama sudah ditutup; pemeriksaan baru dapat dimulai.</p>:<><p>{data.sourceStatus==='COMPLETE'?`Sumber diperiksa lengkap: ${data.sourceTotal} dokumen.`:'Data pemeriksaan belum lengkap. Masalah lama tetap terbuka dengan penanda belum diketahui.'} {data.rows.length} catatan.</p>{data.rows.slice(page*25,(page+1)*25).map(o=><article key={o.source_id} aria-label={`Catatan masalah ${o.source_label}`}><h5>{o.source_label}</h5><p>{conditions[o.condition_state]}.</p>{o.episode?<><p>Riwayat masalah {o.episode.number}: {states[o.episode.state]}. {o.episode.freshness==='UNKNOWN'?'Kondisi terbaru belum diketahui.':''}</p><p>Pertama diamati {formatCp6WibDateTime(o.episode.first_observed_at)}.{o.episode.last_known_observed_at?' Data terakhir yang lengkap '+formatCp6WibDateTime(o.episode.last_known_observed_at)+'.':''}</p>{o.transition==='REOPENED_NEW_EPISODE'?<p>Masalah muncul kembali setelah catatan sebelumnya ditutup. Riwayat sebelumnya tetap tersimpan.</p>:null}<details><summary>Rujukan riwayat</summary><p>Identitas sumber {o.source_id}; riwayat {o.episode.id}; versi catatan {o.episode.revision}.</p>{o.episode.previous_episode_id?<p>Riwayat sebelumnya {o.episode.previous_episode_id}.</p>:null}</details></>:<p>Belum ada riwayat masalah aktif untuk dokumen ini.</p>}</article>)}{!data.rows.length?<p>Tidak ada catatan dari pemeriksaan ini.</p>:null}<nav aria-label="Halaman catatan pemeriksaan tagihan"><button disabled={page===0}onClick={()=>setPage(p=>p-1)}>Catatan sebelumnya</button><span>Halaman {page+1} dari {Math.max(1,Math.ceil(data.rows.length/25))}</span><button disabled={(page+1)*25>=data.rows.length}onClick={()=>setPage(p=>p+1)}>Catatan berikutnya</button></nav></>}</section>
}
