// @vitest-environment jsdom
import {act,useRef,useState} from 'react'
import {createRoot,type Root} from 'react-dom/client'
import {beforeEach,afterEach,it,expect,vi} from 'vitest'
import NativeFabricRecipePanel from './NativeFabricRecipePanel'
import {parseNativeAnalysis,type NativeAnalysis} from './nativeAnalysis'
import {readFabricRequest,type FabricRequest} from './nativeFabricRecipe'
import {fabricWorkspaceFixture,fabricOutcomeFixture,fabricMaterialId} from '../tests/fixtures/nativeFabricRecipe'
import original from '../tests/fixtures/nativeAnalysisStandin.json'
import {recoveryIdentity} from '../tests/fixtures/productionRecovery'
import type {NativeDemandQuery} from './nativeDemandHistory'
const state=vi.hoisted(()=>({auth:null as unknown}))
const client=vi.hoisted(()=>({rpc:vi.fn()}))
vi.mock('./auth/AuthProvider',()=>({useAuth:()=>state.auth}));vi.mock('./lib/supabase',()=>({getUatSupabaseClient:()=>client}))
const q=original.query as NativeDemandQuery,actor=original.analysis.scope.actor_scope_id,scope='analysis:cp6-disposable:actor-1',access={ownerReports:false,preflight:false}
let container:HTMLDivElement,root:Root
function Host(){const seq=useRef(0),[generation,setGeneration]=useState(0),[context,setContext]=useState<NativeAnalysis|null>(()=>parseNativeAnalysis(original,q,actor));return <NativeFabricRecipePanel context={context} generation={generation} blocked={false} access={access} onReadStart={()=>{const n=++seq.current;setGeneration(n);setContext(null);return n}} isReadCurrent={n=>seq.current===n} onReadEnd={()=>{}} onAnalysis={(a,n)=>{if(seq.current===n)setContext(a)}} requireClear={()=>{}}/>}
beforeEach(()=>{Object.assign(globalThis,{IS_REACT_ACT_ENVIRONMENT:true});localStorage.clear();client.rpc.mockReset();const a=structuredClone(recoveryIdentity);Object.assign(a.runtime,{mode:'DISPOSABLE_TEST',projectRef:'cp6-disposable'});Object.assign(a.identity.profile,{authUserId:actor});a.identity.permissions.push('master.product.view','master.product.manage','production.wip.view','warehouse.stock.view','sales.invoice.view');state.auth=a;Object.defineProperty(navigator,'locks',{configurable:true,value:{request:async(_n:string,_o:unknown,fn:(lock:object)=>unknown)=>fn({})}});container=document.createElement('div');document.body.append(container);root=createRoot(container)})
afterEach(async()=>{await act(async()=>root.unmount());container.remove();localStorage.clear();vi.restoreAllMocks()})
const render=async()=>act(async()=>root.render(<Host/>))
async function click(label:string){const b=[...container.querySelectorAll('button')].find(b=>b.textContent===label)!;expect(b).toBeTruthy();await act(async()=>b.click())}
async function fill(label:string,value:string){const f=container.querySelector<HTMLInputElement|HTMLTextAreaElement|HTMLSelectElement>(`[aria-label="${label}"]`)!;expect(f).toBeTruthy();await act(async()=>{const proto=f instanceof HTMLSelectElement?HTMLSelectElement.prototype:f instanceof HTMLTextAreaElement?HTMLTextAreaElement.prototype:HTMLInputElement.prototype;Object.getOwnPropertyDescriptor(proto,'value')!.set!.call(f,value);f.dispatchEvent(new Event(f instanceof HTMLSelectElement?'change':'input',{bubbles:true}))})}
const review=async()=>act(async()=>container.querySelector<HTMLInputElement>('[aria-label="Konfirmasi review resep kain"]')!.click())
async function prepared(){await render();await fill('Produk dan ukuran resep kain',original.analysis.recommendations[0].target.key);await click('Baca bahan dan versi resep kain');await fill('Bahan kain yang direview',fabricMaterialId);await fill('Pemakaian kain per PCS','0.000001');await fill('Mulai berlaku resep kain WIB','2026-10-05T07:00:00');await fill('Alasan review resep kain','Review fixture eksplisit')}
it('reads only on request and leaves rate, pattern and effective date blank until reviewed',async()=>{client.rpc.mockResolvedValue({data:fabricWorkspaceFixture(),error:null});await render();expect(client.rpc).not.toHaveBeenCalled();await fill('Produk dan ukuran resep kain',original.analysis.recommendations[0].target.key);await click('Baca bahan dan versi resep kain');for(const label of['Pemakaian kain per PCS','Pola resep kain','Mulai berlaku resep kain WIB'])expect(container.querySelector<HTMLInputElement>(`[aria-label="${label}"]`)!.value).toBe('');expect(container.textContent).toContain('Tidak ada angka bawaan')})
it('requires explicit review then saves one source-bound micro rate with no invented pattern or stock reservation',async()=>{client.rpc.mockImplementation(async(name:string)=>name==='erp_cp7_get_fabric_recipe_v1'?{data:fabricWorkspaceFixture(),error:null}:{data:fabricOutcomeFixture(readFabricRequest(scope).pending!),error:null});await prepared();expect([...container.querySelectorAll('button')].find(b=>b.textContent==='Simpan review resep kain')!.disabled).toBe(true);await review();await click('Simpan review resep kain');const p=client.rpc.mock.calls.at(-1)![1].p_payload;expect(p.config).toMatchObject({qty_per_good_pcs:'0.000001',pattern_id:null,pattern_hash:null,unit:'M'});expect(p.source_hash).toBe(original.analysis.snapshot.source_hash);expect(readFabricRequest(scope).pending).toBeNull();expect(container.textContent).toContain('Ambil analisis ERP terbaru')})
it('retains a lost committed reply and retries the identical UUID and payload after remount',async()=>{let held:FabricRequest|null=null;client.rpc.mockImplementation(async(name:string)=>{if(name==='erp_cp7_get_fabric_recipe_v1')return{data:fabricWorkspaceFixture(),error:null};const r=readFabricRequest(scope).pending!;if(!held){held=r;throw Error('Lost committed reply')}return{data:fabricOutcomeFixture(r),error:null}});await prepared();await review();await click('Simpan review resep kain');expect(readFabricRequest(scope).pending).toEqual(held);await act(async()=>root.unmount());root=createRoot(container);await render();await click('Ulangi resep kain yang sama');expect(client.rpc.mock.calls.at(-1)![1]).toEqual(client.rpc.mock.calls[1][1]);expect(readFabricRequest(scope).pending).toBeNull()})
it('releases a definitively uncommitted stale revision while keeping source facts retired',async()=>{client.rpc.mockImplementation(async(name:string)=>name==='erp_cp7_get_fabric_recipe_v1'?{data:fabricWorkspaceFixture(),error:null}:{data:null,error:{code:'40001',message:'CP7_FABRIC_REVISION_CHANGED'}});await prepared();await review();await click('Simpan review resep kain');expect(readFabricRequest(scope).pending).toBeNull();expect(container.textContent).not.toContain('Ulangi resep kain yang sama');expect(container.textContent).not.toContain('1 dari 1 bahan');expect(container.textContent).toContain('Ambil analisis ERP terbaru lalu review kembali');expect(client.rpc).toHaveBeenCalledTimes(2)})
it('keeps a changed-payload UUID collision fenced because an earlier command may already be committed',async()=>{client.rpc.mockImplementation(async(name:string)=>name==='erp_cp7_get_fabric_recipe_v1'?{data:fabricWorkspaceFixture(),error:null}:{data:null,error:{code:'P0001',message:'CP7_FABRIC_REQUEST_CHANGED'}});await prepared();await review();await click('Simpan review resep kain');const held=readFabricRequest(scope).pending;expect(held).toBeTruthy();await click('Ulangi resep kain yang sama');expect(readFabricRequest(scope).pending).toEqual(held);expect(client.rpc.mock.calls.at(-1)![1]).toEqual(client.rpc.mock.calls[1][1])})
it('retains current authorization denial until the same UUID result can be read under restored authority',async()=>{let held:FabricRequest|null=null;client.rpc.mockImplementation(async(name:string)=>{if(name==='erp_cp7_get_fabric_recipe_v1')return{data:fabricWorkspaceFixture(),error:null};held=readFabricRequest(scope).pending;return{data:null,error:{code:'42501',message:'CP7_SCHEDULE_ACCESS_DENIED'}}});await prepared();await review();await click('Simpan review resep kain');expect(readFabricRequest(scope).pending).toEqual(held);await act(async()=>root.unmount());root=createRoot(container);client.rpc.mockImplementation(async()=>({data:fabricOutcomeFixture(readFabricRequest(scope).pending!),error:null}));await render();await click('Ulangi resep kain yang sama');expect(client.rpc.mock.calls.at(-1)![1]).toEqual(client.rpc.mock.calls[1][1]);expect(readFabricRequest(scope).pending).toBeNull()})
it('retires source facts on a held read and current403 without discarding unsent operator input',async()=>{client.rpc.mockResolvedValue({data:fabricWorkspaceFixture(),error:null});await prepared();let finish!:(v:unknown)=>void;client.rpc.mockImplementation(()=>new Promise(resolve=>{finish=resolve}));await click('Baca bahan dan versi resep kain');expect(container.textContent).not.toContain('1 dari 1 bahan');await act(async()=>finish({data:null,error:{code:'42501',message:'Current access denied'}}));expect(container.textContent).not.toContain('1 dari 1 bahan');expect(readFabricRequest(scope).pending).toBeNull()})
it('blocks save when browser tab locking is unavailable and makes no RPC write',async()=>{client.rpc.mockResolvedValue({data:fabricWorkspaceFixture(),error:null});await prepared();Object.defineProperty(navigator,'locks',{configurable:true,value:undefined});await review();await click('Simpan review resep kain');expect(client.rpc).toHaveBeenCalledTimes(1);expect(readFabricRequest(scope).pending).toBeNull();expect(container.textContent).toContain('pengunci tab')})
