// @vitest-environment jsdom
import{beforeEach,describe,it,expect}from'vitest'
import{parsePlanningProfile,parsePlanningConfig,parseNativeBaseline,planningPayload,checkPlanningOutcome,readPlanningRequest,persistPlanningRequest,clearPlanningRequest,planningRequestKey}from'./nativePlanningProfile'
import{profileWire,baselineWire,planningConfig,planningQuery,planningId}from'../tests/fixtures/nativePlanningProfile'
import{demandRoot,demandSize,demandRequest}from'../tests/fixtures/nativeDemandHistory'
beforeEach(()=>localStorage.clear())
describe('Native planning profile and baseline client contract',()=>{
 it('projects a selected target100 and native FG76 without deriving final gap or enabling apply',()=>{const r=parseNativeBaseline(baselineWire(),planningQuery);expect(r.rows[0]).toMatchObject({target:'100',available:'76',daily:'10',productionState:null,startNew:null,profileRevision:'1'});expect(r.query).toEqual(planningQuery)})
 it('keeps an unreviewed profile unreviewed with no default configuration',()=>{expect(parsePlanningProfile(profileWire(false),demandRoot,demandSize)).toMatchObject({quality:'UNREVIEWED',config:null,profileId:null,revision:'0'})})
 it.each(['apply_enabled','production_go']as const)('refuses enabled execution flag %s',flag=>{const r=baselineWire();r[flag]=true;expect(()=>parseNativeBaseline(r,planningQuery)).toThrow()})
 it.each(['final_gap_pcs','capacity_state','supply_state','timeline_state'])('refuses fake-known missing native source %s',key=>{const r=baselineWire();Object.assign(r.rows[0],{[key]:key==='final_gap_pcs'?'24':'KNOWN'});expect(()=>parseNativeBaseline(r,planningQuery)).toThrow()})
 it('refuses mismatched baseline hash, size, profile refs, mode or current FG',()=>{for(const mutate of[(r:ReturnType<typeof baselineWire>)=>r.rows[0].target.inputs.snapshot_id='c'.repeat(64),(r:ReturnType<typeof baselineWire>)=>r.rows[0].size_id=demandRoot,(r:ReturnType<typeof baselineWire>)=>r.rows[0].refs=[],(r:ReturnType<typeof baselineWire>)=>r.rows[0].target.inputs.mode='STATISTICAL',(r:ReturnType<typeof baselineWire>)=>r.rows[0].available_fg_pcs='100']){const r=baselineWire();mutate(r);expect(()=>parseNativeBaseline(r,planningQuery)).toThrow()}})
 it('allows a known STOP policy to show zero new starts while preserving available stock',()=>{const r=baselineWire();Object.assign(r.rows[0],{production_policy:{policy:{quality:'KNOWN',state:'STOPPED'}},start_new_pcs:'0'});expect(parseNativeBaseline(r,planningQuery).rows[0]).toMatchObject({startNew:'0',available:'76',target:'100'});Object.assign(r.rows[0],{production_policy:null});expect(()=>parseNativeBaseline(r,planningQuery)).toThrow()})
 it('keeps large target quantities exact without Number arithmetic',()=>{const r=baselineWire();r.rows[0].target.target_pcs='900719925474099300000';expect(parseNativeBaseline(r,planningQuery).rows[0].target).toBe('900719925474099300000')})
 it('refuses unknown identity, another size, numeric demand and extra configuration',()=>{const r=profileWire();r.rows[0].quality='IDENTITY_CONFLICT';expect(()=>parsePlanningProfile(r,demandRoot,demandSize)).toThrow();expect(()=>parsePlanningProfile(profileWire(),demandRoot,demandRoot)).toThrow();expect(()=>parsePlanningConfig({...planningConfig,daily_pcs:10})).toThrow();expect(()=>parsePlanningConfig({...planningConfig,capacity_pcs:'1000'})).toThrow();expect(()=>parsePlanningConfig({...planningConfig,lead_days:'3660.0001'})).toThrow()})
 it('preserves unknown lead, review and buffer instead of replacing them with zero',()=>{expect(parsePlanningConfig({...planningConfig,lead_days:null,review_days:null,buffer_days:null})).toMatchObject({lead_days:null,review_days:null,buffer_days:null})})
 it('validates exact saved request outcome and metadata revision',()=>{const request={id:demandRequest,payload:planningPayload(parsePlanningProfile(profileWire(false),demandRoot,demandSize),planningConfig,'review')};const outcome={contract_version:'cp7.planning-profile-outcome.v1',request_id:demandRequest,root_id:demandRoot,profile_id:planningId,revision:'1',quality:'SELECTED_ASSUMPTION'};expect(()=>checkPlanningOutcome(outcome,request)).not.toThrow();expect(()=>checkPlanningOutcome({...outcome,request_id:planningId},request)).toThrow();expect(()=>checkPlanningOutcome({...outcome,revision:'2'},request)).toThrow()})
 it('persists an exact profile request before send and refuses another UUID until reconciliation',()=>{const scope='project:actor:root',r={id:demandRequest,payload:planningPayload(parsePlanningProfile(profileWire(false),demandRoot,demandSize),planningConfig,'review')};persistPlanningRequest(scope,r);expect(readPlanningRequest(scope).pending).toEqual(r);expect(()=>persistPlanningRequest(scope,{...r,id:planningId})).toThrow();expect(()=>clearPlanningRequest(scope,planningId)).toThrow();expect(readPlanningRequest(scope).pending).toEqual(r);clearPlanningRequest(scope,r.id);expect(readPlanningRequest(scope).pending).toBeNull()})
 it('fails closed on corrupt recovery and keeps the original evidence',()=>{const scope='project:actor:root';localStorage.setItem(planningRequestKey(scope),'corrupt');expect(readPlanningRequest(scope).error).toBeTruthy();expect(()=>persistPlanningRequest(scope,{id:demandRequest,payload:{}as never})).toThrow();expect(localStorage.getItem(planningRequestKey(scope))).toBe('corrupt')})
})
