// @vitest-environment jsdom
import {beforeEach,it,expect} from 'vitest'
import original from '../tests/fixtures/nativeAnalysisStandin.json'
import {fabricAnalysisFixture,fabricConfig,fabricWorkspaceFixture,fabricOutcomeFixture} from '../tests/fixtures/nativeFabricRecipe'
import {parseFabricConfig,parseFabricWorkspace,checkFabricOutcome,persistFabricRequest,readFabricRequest,clearFabricRequest,fabricRequestKey,type FabricRequest} from './nativeFabricRecipe'
import {parseNativeAnalysis,analysisPrompt,analysisReport} from './nativeAnalysis'
import {fabricRecipeId} from '../tests/fixtures/nativeFabricRecipe'
import type {NativeDemandQuery} from './nativeDemandHistory'
const q=original.query as NativeDemandQuery,actor=original.analysis.scope.actor_scope_id,target=original.analysis.recommendations[0].target.key,access={ownerReports:false,preflight:false}
const request=():FabricRequest=>({id:'00000000-0000-4000-8000-00000000f010',payload:{run_id:original.run_id,target_key:target,source_hash:original.analysis.snapshot.source_hash,expected_revision:'0',config:structuredClone(fabricConfig),reason:'Explicit receiver fixture review'}})
beforeEach(()=>localStorage.clear())
it('binds the workspace to the complete same global analysis and honest material/pattern pages',()=>{const w=parseFabricWorkspace(fabricWorkspaceFixture(),q,actor,target,access);expect(w.analysis.runId).toBe(original.run_id);expect(w.patterns[0].revision).toBe('R1');expect(w.materials[0].unit).toBe('M')})
it('rejects truncated, duplicate, foreign, stale or promoted metadata pages',()=>{for(const change of[(w:ReturnType<typeof fabricWorkspaceFixture>)=>{w.materials=[]},(w:ReturnType<typeof fabricWorkspaceFixture>)=>{w.materials.push(structuredClone(w.materials[0]))},(w:ReturnType<typeof fabricWorkspaceFixture>)=>{w.actor_scope_id='foreign'},(w:ReturnType<typeof fabricWorkspaceFixture>)=>{w.analysis.source_state='ARCHIVED_STALE'},(w:ReturnType<typeof fabricWorkspaceFixture>)=>{w.production_go=true}]){const w=fabricWorkspaceFixture();change(w);expect(()=>parseFabricWorkspace(w,q,actor,target,access)).toThrow()}})
it('keeps micro decimals and an optional pattern, while refusing zero, mixed types and an invalid effective window',()=>{expect(parseFabricConfig({...fabricConfig,qty_per_good_pcs:'0.000001',pattern_id:null,pattern_hash:null}).qty_per_good_pcs).toBe('0.000001');for(const change of[{qty_per_good_pcs:'0'},{qty_per_good_pcs:'-1'},{qty_per_good_pcs:2},{effective_to:fabricConfig.effective_from},{pattern_id:null},{effective_from:'2026-02-30T00:00:00Z'}])expect(()=>parseFabricConfig({...fabricConfig,...change})).toThrow()})
it('preserves the fabric rate as an assumption in shared report and AI, without installation or feasibility credit',()=>{const x=fabricAnalysisFixture(),a=parseNativeAnalysis(x,q,actor);expect(a.analysis.material_needs.at(-1)?.gross.state).toBe('ASSUMED');expect(analysisReport(a)).toContain('Kain fixture');expect(analysisPrompt(a,'Periksa kain')).toContain('CP7_FABRIC_RECIPE');expect(a.analysis.recommendations[0].feasible_new.state).toBe('UNKNOWN')})
it('refuses Native fabric proof invented from a recipe or an unreferenced rate',()=>{for(const change of[(x:ReturnType<typeof fabricAnalysisFixture>)=>{const m=x.analysis.material_needs.at(-1)!;m.installed_proven={state:'KNOWN',value:'60',unit:'M',refs:m.gross.refs}},(x:ReturnType<typeof fabricAnalysisFixture>)=>{const m=x.analysis.material_needs.at(-1)!;m.gross={state:'KNOWN',value:'186',unit:'M',refs:m.gross.refs}},(x:ReturnType<typeof fabricAnalysisFixture>)=>{x.analysis.material_needs.at(-1)!.gross.refs=[]},(x:ReturnType<typeof fabricAnalysisFixture>)=>{x.analysis.assumptions=x.analysis.assumptions.filter(a=>a.id!==fabricRecipeId)}]){const x=fabricAnalysisFixture();change(x);expect(()=>parseNativeAnalysis(x,q,actor)).toThrow()}})
it('persists one exact request, survives reload and rejects overwrite, foreign receipt or wrong clearing',()=>{const r=request();persistFabricRequest('fixture',r);expect(readFabricRequest('fixture').pending).toEqual(r);expect(()=>persistFabricRequest('fixture',r)).toThrow();checkFabricOutcome(fabricOutcomeFixture(r),r,actor);expect(()=>checkFabricOutcome({...fabricOutcomeFixture(r),revision:'2'},r,actor)).toThrow();expect(()=>clearFabricRequest('fixture','foreign')).toThrow();clearFabricRequest('fixture',r.id);expect(readFabricRequest('fixture').pending).toBeNull()})
it('fails closed on corrupted pending storage across the next attempt',()=>{localStorage.setItem(fabricRequestKey('fixture'),'broken');expect(readFabricRequest('fixture').error).toBeTruthy();expect(()=>persistFabricRequest('fixture',request())).toThrow();expect(localStorage.getItem(fabricRequestKey('fixture'))).toBe('broken')})
