// @vitest-environment jsdom
import{act}from 'react'
import{createRoot,type Root}from 'react-dom/client'
import{afterEach,beforeEach,expect,it,vi}from 'vitest'
import PayrollInstallmentPanel from './PayrollInstallmentPanel'
import{installmentRead,installmentPayment,payrollId,paymentId,cashId,inverseId}from '../tests/fixtures/payrollInstallments'
import{recoveryIdentity}from '../tests/fixtures/productionRecovery'
import{clearProductionEnvelope,persistProductionEnvelope,productionKey,readProductionRecovery}from './productionRecovery'
const state=vi.hoisted(()=>({auth:null as unknown}))
const client=vi.hoisted(()=>({rpc:vi.fn()}))
vi.mock('./auth/AuthProvider',()=>({useAuth:()=>state.auth}));vi.mock('./lib/supabase',()=>({getUatSupabaseClient:()=>client}))
const onRetire=vi.fn(),onReload=vi.fn(async()=>true),onTarget=vi.fn(),onSource=vi.fn()
let root:Root,container:HTMLDivElement
beforeEach(()=>{Object.assign(globalThis,{IS_REACT_ACT_ENVIRONMENT:true});localStorage.clear();client.rpc.mockReset();onRetire.mockReset();onTarget.mockReset();onSource.mockReset();onReload.mockReset().mockResolvedValue(true);const a=structuredClone(recoveryIdentity);a.identity.permissions=['finance.payroll.view','finance.payroll.pay','finance.payroll.approve'];state.auth=a;Object.defineProperty(navigator,'locks',{configurable:true,value:{request:async(_n:string,_o:unknown,fn:(l:unknown)=>Promise<unknown>)=>fn({})}});container=document.createElement('div');document.body.append(container);root=createRoot(container)})
afterEach(async()=>{await act(async()=>root.unmount());container.remove();localStorage.clear();Reflect.deleteProperty(navigator,'locks');vi.restoreAllMocks()})
const flush=async()=>act(async()=>{await new Promise(r=>setTimeout(r,0))})
async function mount(id:string|null=payrollId,parentReady=true){await act(async()=>root.render(<PayrollInstallmentPanel parentReady={parentReady}payrollId={id}readRevision={0}onRetire={onRetire}onReload={onReload}onTarget={onTarget}onSource={onSource}/>));await flush()}
const button=(name:string)=>[...container.querySelectorAll('button')].find(b=>b.textContent===name)!
async function click(name:string){await act(async()=>button(name).click());await flush()}
async function fill(label:string,value:string){await act(async()=>{const el=container.querySelector<HTMLInputElement|HTMLTextAreaElement>(`[aria-label="${label}"]`)!;Object.getOwnPropertyDescriptor(el.tagName==='TEXTAREA'?HTMLTextAreaElement.prototype:HTMLInputElement.prototype,'value')!.set!.call(el,value);el.dispatchEvent(new Event('input',{bubbles:true}))});await flush()}
async function review(){await fill('Alasan pembayaran gaji','Jumlah akun dan tanggal sudah diperiksa');await act(async()=>container.querySelector<HTMLInputElement>('[aria-label="Pembayaran gaji sudah diperiksa"]')!.click());await flush()}
async function prepare(amount='600.00'){await click('Bayar gaji');await fill('Jumlah pembayaran gaji',amount);await fill('Tanggal cicilan gaji','2020-01-02');await click('CASH · Kas native');await review()}
const writes=()=>client.rpc.mock.calls.filter(([n])=>n==='erp_cp7_save_payroll_installment_v1')
function server(initial=installmentRead()){
 const s={current:initial,next:installmentRead('600.00',[installmentPayment()]),effects:0,lost:false,failRead:false,mismatch:false,replayDenied:false},cache=new Map<string,unknown>()
 client.rpc.mockImplementation(async(name,args)=>{
  if(name==='erp_cp7_get_payroll_installments_v1')return s.failRead?{data:null,error:{status:503,message:'Sumber pembayaran belum tersedia'}}:{data:structuredClone(s.current),error:null}
  if(name!=='erp_cp7_save_payroll_installment_v1')throw Error('Unexpected RPC '+name)
  if(cache.has(args.p_request)&&s.replayDenied)return{data:null,error:{status:403,message:'Current permission revoked'}}
  if(!cache.has(args.p_request)){s.effects++;s.current=structuredClone(s.next);cache.set(args.p_request,{contract_version:'cp7.payroll-installment-outcome.v1',kind:'COMMITTED_OUTCOME',action:args.p_action,request_id:s.mismatch?inverseId:args.p_request,request_payload:structuredClone(args.p_payload),expected_version:args.p_expected,payroll_id:payrollId,payment_id:args.p_action==='REVERSE_PAYROLL'?null:args.p_action==='REVERSE_PAYMENT'?args.p_payload.payment_id:paymentId,native_status:s.current.document.native_status,payment_state:s.current.document.payment_state,row_version:s.current.document.row_version,review_token:s.current.document.review_token})}
  return s.lost?{data:null,error:{status:503,message:'Reply lost after commit'}}:{data:cache.get(args.p_request),error:null}
 });return s
}
it('shows native approved1000, paid600 and remaining400 on the same payroll',async()=>{server(installmentRead('600.00',[installmentPayment()]));await mount();expect(container.textContent).toContain('Dibayar sebagian');expect(container.textContent).toContain('Sisa gajiRp400');expect(container.textContent).toContain('Sudah dibayarRp600');expect(container.textContent).toContain('Gaji bersih yang disetujuiRp1.000');expect(onSource).toHaveBeenLastCalledWith(expect.objectContaining({payroll_id:payrollId,managed:true}));expect(writes()).toHaveLength(0)})
it('requires review and exact cash/document tokens for a partial600 payment',async()=>{server();await mount();await click('Bayar gaji');expect(button('Catat pembayaran gaji').disabled).toBe(true);await fill('Jumlah pembayaran gaji','600.00');await fill('Tanggal cicilan gaji','2020-01-02');await click('CASH · Kas native');await review();await fill('Jumlah pembayaran gaji','600.01');expect(button('Catat pembayaran gaji').disabled).toBe(true);await fill('Jumlah pembayaran gaji','600.00');await act(async()=>container.querySelector<HTMLInputElement>('[aria-label="Pembayaran gaji sudah diperiksa"]')!.click());await click('Catat pembayaran gaji');expect(writes()[0][1]).toMatchObject({p_action:'PAY',p_expected:'9007199254740993',p_payload:{payroll_id:payrollId,amount:'600.00',payment_date:'2020-01-02',cash_account_id:cashId,cash_review_token:'b'.repeat(32),review_token:'a'.repeat(32)}});expect(container.textContent).toContain('Sisa gajiRp400');expect(onRetire).toHaveBeenCalled();expect(readProductionRecovery('disposable:actor-1').pending).toEqual({})})
it('later cash400 settles the same native approved1000 without substituting a different payroll',async()=>{const first=installmentPayment(),last={...installmentPayment('400.00'),id:cashId,journal_id:inverseId,journal_number:'JRN-CASH400'},s=server(installmentRead('600.00',[first]));s.next=installmentRead('1000.00',[first,last]);await mount();await prepare('400.00');await click('Catat pembayaran gaji');expect(writes()[0][1].p_payload.payroll_id).toBe(payrollId);expect(container.textContent).toContain('Sisa gajiRp0');expect(container.textContent).toContain('Gaji bersih yang disetujuiRp1.000');expect(button('Bayar gaji')).toBeUndefined();expect(container.querySelectorAll('.cpay-line')).toHaveLength(2)})
it('inverse keeps the original date and linked inverse while reopening the remaining amount',async()=>{const s=server(installmentRead('600.00',[installmentPayment()]));s.next=installmentRead('0.00',[installmentPayment('600.00',true)]);await mount();await click('Balikkan pembayaran JRN-CASH600');await review();await click('Balikkan pembayaran sekarang');expect(writes()[0][1]).toMatchObject({p_action:'REVERSE_PAYMENT',p_payload:{payment_id:paymentId,payroll_id:payrollId}});expect(container.textContent).toContain('2020-01-02');expect(container.textContent).toContain('JRN-INVERSE600 · 2020-01-03');expect(container.textContent).toContain('Sisa gajiRp1.000')})
it('a lost committed reply retires all money; remount replays the exact old intent once',async()=>{const s=server();await mount();await prepare();s.lost=true;await click('Catat pembayaran gaji');const original=structuredClone(writes()[0][1]);expect(container.textContent).not.toContain('Rp');expect(readProductionRecovery('disposable:actor-1').pending.PAYROLL_INSTALLMENT?.id).toBe(original.p_request);await act(async()=>root.unmount());root=createRoot(container);const before=client.rpc.mock.calls.length;s.lost=false;await mount(null);expect(client.rpc.mock.calls.length).toBe(before);await click('Periksa status pembayaran gaji');expect(writes()[1][1]).toEqual(original);expect(s.effects).toBe(1);expect(onTarget).toHaveBeenCalledWith(payrollId);expect(readProductionRecovery('disposable:actor-1').pending).toEqual({})})
it('a revoked replay retains the original uncertainty instead of treating403 as rollback',async()=>{const s=server();await mount();await prepare();s.lost=true;await click('Catat pembayaran gaji');const original=readProductionRecovery('disposable:actor-1').pending.PAYROLL_INSTALLMENT;s.lost=false;s.replayDenied=true;await click('Periksa status pembayaran gaji');expect(readProductionRecovery('disposable:actor-1').pending.PAYROLL_INSTALLMENT).toEqual(original);expect(container.textContent).not.toContain('Rp');expect(s.effects).toBe(1)})
it('a mismatched success UUID preserves the envelope and keeps all facts retired',async()=>{const s=server();s.mismatch=true;await mount();await prepare();await click('Catat pembayaran gaji');expect(readProductionRecovery('disposable:actor-1').pending.PAYROLL_INSTALLMENT).toBeDefined();expect(container.textContent).not.toContain('Rp');expect(container.textContent).toContain('Status pembayaran gaji belum pasti')})
it('failed parent refresh after commit prevents any new writer until the whole read succeeds',async()=>{const s=server();await mount();await prepare();onReload.mockResolvedValue(false);await click('Catat pembayaran gaji');expect(s.effects).toBe(1);expect(container.textContent).not.toContain('Rp');expect(container.textContent).toContain('Aksi sudah tersimpan');expect(readProductionRecovery('disposable:actor-1').pending).toEqual({});onReload.mockResolvedValue(true);await click('Muat ulang pembayaran');expect(button('Bayar gaji').disabled).toBe(false);expect(s.effects).toBe(1)})
it('failed authoritative source refresh retires all balances and payment rows',async()=>{const s=server(installmentRead('600.00',[installmentPayment()]));await mount();s.failRead=true;await click('Muat ulang pembayaran');expect(container.textContent).not.toContain('Rp');expect(container.querySelectorAll('.cpay-line')).toHaveLength(0);expect(button('Bayar gaji')).toBeUndefined();expect(writes()).toHaveLength(0)})
it('shared pending recovery invalidates a held read even if recovery clears before that read returns',async()=>{server();let reply:((r:unknown)=>void)|null=null;client.rpc.mockImplementationOnce(()=>new Promise(resolve=>{reply=resolve}));await mount();const input={action:'POST',payload:{sale_id:payrollId},expectedVersion:1},e={...input,id:paymentId,createdAt:'2026-09-30T03:00:00Z',fingerprint:JSON.stringify(input)};await act(async()=>{persistProductionEnvelope('disposable:actor-1','SALES',e);clearProductionEnvelope('disposable:actor-1','SALES',e)});await act(async()=>reply!({data:installmentRead(),error:null}));await flush();expect(container.textContent).not.toContain('Rp');await click('Muat ulang pembayaran');expect(container.textContent).toContain('Rp1.000')})
it('corrupt recovery storage remains intact and issues no source or mutation RPC',async()=>{server();const key=productionKey('disposable:actor-1','PAYROLL_INSTALLMENT');localStorage.setItem(key,'{');await mount();expect(localStorage.getItem(key)).toBe('{');expect(client.rpc).not.toHaveBeenCalled();expect(container.textContent).not.toContain('Rp')})
it('view-only permissions read source without any payment or whole-payroll reversal action',async()=>{const a=state.auth as typeof recoveryIdentity;a.identity.permissions=['finance.payroll.view'];const r=installmentRead('600.00',[installmentPayment()]);r.capabilities={pay:false,reverse_payroll:false};server(r);await mount();expect(container.textContent).toContain('Rp600');expect(button('Bayar gaji')).toBeUndefined();expect(button('Batalkan payroll dan pembayaran')).toBeUndefined();expect(button('Balikkan pembayaran JRN-CASH600')).toBeUndefined();expect(writes()).toHaveLength(0)})
it('requires parent source readiness and never displays an old payroll after selection changes',async()=>{server();await mount(payrollId,false);expect(client.rpc).not.toHaveBeenCalled();await mount();expect(container.textContent).toContain('Rp1.000');await mount(cashId,false);expect(container.textContent).not.toContain('Rp');expect(writes()).toHaveLength(0)})
