const procurementActiveKey = 'erp.prototypePage'
const procurementPageId = 'procurement-receiving'

type Material = { code:string; name:string; category:'Kain'|'Aksesori'; unit:'yard'|'pcs'; stock:number; lastCost:number; detail:string }
type Supplier = { name:string; kind:string }
const procurementMaterials: Material[] = [
  { code:'FAB-DNM-12',name:'Denim 12 oz · Dark Indigo',category:'Kain',unit:'yard',stock:2012,lastCost:48500,detail:'Roll fabric · Gudang Bahan Utama' },
  { code:'FAB-DNM-10',name:'Denim 10 oz · Mid Blue',category:'Kain',unit:'yard',stock:1225,lastCost:43250,detail:'Roll fabric · Gudang Bahan Utama' },
  { code:'ACC-BTN-17',name:'Kancing Jeans 17 mm · Gunmetal',category:'Aksesori',unit:'pcs',stock:3860,lastCost:1350,detail:'Kancing depan · Rak A-03' },
  { code:'ACC-ZIP-05',name:'Zipper YKK #5 · Navy',category:'Aksesori',unit:'pcs',stock:1420,lastCost:6200,detail:'Resleting celana · Rak A-05' },
  { code:'ACC-RVT-09',name:'Rivet Jeans 9 mm · Antique',category:'Aksesori',unit:'pcs',stock:8240,lastCost:750,detail:'Rivet pocket · Rak A-04' },
]
const procurementSuppliers: Supplier[] = [
  { name:'PT Sumber Denim',kind:'Kain' },{ name:'CV Maju Aksesori',kind:'Aksesori' },{ name:'PT Prima Tekstil',kind:'Kain & finishing' },
]
const initialLines = [{code:'FAB-DNM-12',received:600},{code:'ACC-BTN-17',received:1200}]
function procurementNumber(value:number){return new Intl.NumberFormat('id-ID',{maximumFractionDigits:2}).format(Math.max(0,value||0))}
function procurementMoney(value:number){return new Intl.NumberFormat('id-ID',{style:'currency',currency:'IDR',maximumFractionDigits:0}).format(Math.max(0,value||0))}
function procurementLocalDateTimeValue(date=new Date()){const offsetMs=date.getTimezoneOffset()*60000;return new Date(date.getTime()-offsetMs).toISOString().slice(0,16)}
function procurementSetTopTitle(active=true){const top=document.querySelector<HTMLElement>('.top-title');const strong=top?.querySelector<HTMLElement>('strong');const sub=top?.querySelector<HTMLElement>('span');if(!strong||!sub)return;if(active){strong.textContent='Pembelian & Penerimaan';sub.textContent='Surat jalan masuk dulu, kasbon menyusul'}else{strong.textContent='Modul ERP';sub.textContent='Cepat, jelas, dan aman buat operasional'}}
function procurementGenericPlaceholder(root:HTMLElement){root.className='panel placeholder';root.removeAttribute('data-procurement-ready');root.innerHTML='<div class="placeholder-icon">◇</div><h2>Fondasinya sudah disiapkan.</h2><p>Modul ini berikutnya akan mengikuti flow bisnis yang sama: informasi penting terlihat sebelum user menekan tombol yang mengubah uang atau stok.</p>'}
function procurementUnmount(){const root=document.querySelector<HTMLElement>('.procurement-root');if(root)procurementGenericPlaceholder(root);procurementCloseCatalog();procurementCloseReview();procurementSetTopTitle(false)}
function materialByCode(code:string){return procurementMaterials.find((item)=>item.code===code)??procurementMaterials[0]}
function procurementLineTemplate(code:string,received=0){const item=materialByCode(code);return `<div class="proc-line proc-receipt-line" data-proc-line="${item.code}">
  <div class="proc-line-item"><span class="proc-category">${item.category}</span><strong>${item.code}</strong><small>${item.name}</small><em>${item.detail}</em></div>
  <label><span>Diterima fisik</span><div class="proc-unit-input"><input data-proc-received type="number" min="0" step="1" value="${received}"/><b>${item.unit}</b></div></label>
  <div class="proc-last-cost"><span>HARGA TERAKHIR · REFERENSI</span><strong>${procurementMoney(item.lastCost)}</strong><small>Bukan dasar hutang sebelum kasbon datang.</small></div>
  <div class="proc-stock-after"><span>STOK SEKARANG</span><strong>${procurementNumber(item.stock)} ${item.unit}</strong><small data-proc-after>Setelah terima: ${procurementNumber(item.stock+received)} ${item.unit}</small></div>
  <button type="button" class="proc-remove" data-proc-remove aria-label="Hapus ${item.code}">×</button>
</div>`}
function procurementCatalogTemplate(){return procurementMaterials.map((item)=>`<button type="button" class="proc-catalog-row" data-proc-add="${item.code}" data-proc-search="${item.category} ${item.code} ${item.name} ${item.detail}"><span class="proc-category">${item.category}</span><div><strong>${item.code}</strong><small>${item.name}</small></div><div class="proc-catalog-stock"><span>STOK</span><strong>${procurementNumber(item.stock)} ${item.unit}</strong></div><b>＋</b></button>`).join('')}
function procurementRender(root:HTMLElement){if(root.dataset.procurementReady==='true')return;root.dataset.procurementReady='true';root.className='procurement-root';const physicalAt=sessionStorage.getItem('erp.procurementPhysicalAt')||procurementLocalDateTimeValue();root.innerHTML=`
<section class="hero-copy compact proc-hero"><div class="eyebrow">GUDANG · BARANG DATANG</div><h1>Pembelian & penerimaan</h1><p>Order dilakukan lewat telepon. ERP mulai mencatat saat barang benar-benar datang bersama surat jalan. Kasbon / tagihan boleh muncul beberapa hari kemudian.</p></section>
<section class="proc-layout"><div class="panel proc-workbench">
  <section class="proc-section"><div class="proc-section-head"><div><span>01</span><div><strong>Supplier & surat jalan</strong><small>Tidak ada PO pembelian. Referensi pertama adalah surat jalan yang ikut barang.</small></div></div><span class="proc-status">SURAT JALAN · SIMULASI</span></div>
    <div class="proc-doc-grid proc-arrival-grid">
      <label class="field"><span>Supplier</span><select data-proc-supplier>${procurementSuppliers.map((s,i)=>`<option value="${i}">${s.name}</option>`).join('')}</select><small data-proc-supplier-meta>${procurementSuppliers[0].kind}</small></label>
      <label class="field"><span>No. surat jalan</span><input data-proc-delivery-note value="SJ-0827-177" placeholder="Nomor dari kertas supplier"/></label>
      <label class="field"><span>Tanggal & jam barang datang</span><input data-proc-physical type="datetime-local" value="${physicalAt}"/><small>Waktu fisik barang diterima gudang.</small></label>
      <label class="field"><span>Masuk ke lokasi</span><select data-proc-location><option>Gudang Bahan Utama</option><option>Gudang Aksesori</option></select></label>
    </div>
    <div class="proc-later-note"><div><span>KASBON / TAGIHAN</span><strong>Belum harus ada saat barang datang</strong><small>Nanti dicocokkan ke penerimaan ini saat kasbon supplier muncul.</small></div><b>MENUNGGU</b></div>
  </section>
  <section class="proc-section proc-items-section"><div class="proc-section-head"><div><span>02</span><div><strong>Isi surat jalan</strong><small>Catat barang apa dan berapa yang benar-benar diterima. Tidak ada kolom qty invoice atau reject di tahap ini.</small></div></div><button type="button" class="soft-btn" data-proc-open-catalog>＋ Tambah barang</button></div>
    <div class="proc-line-head proc-receipt-head"><span>BARANG</span><span>DITERIMA FISIK</span><span>HARGA TERAKHIR</span><span>STOK</span><span></span></div>
    <div class="proc-lines" data-proc-lines>${initialLines.map((line)=>procurementLineTemplate(line.code,line.received)).join('')}</div><div class="proc-empty" data-proc-empty hidden>Belum ada barang pada surat jalan ini.</div>
  </section>
  <section class="proc-section"><div class="proc-note-grid"><label class="field"><span>Catatan penerimaan · opsional</span><textarea data-proc-note placeholder="Contoh: roll no. 15 segel terbuka, tetap diterima dan akan dicek saat cutting"></textarea></label><div class="proc-audit-note"><span>RETUR BUKAN DI SINI</span><strong>Kalau barang dikembalikan nanti</strong><small>Retur dilakukan dari stok gudang lewat flow Retur & Penyesuaian, bukan mengurangi penerimaan awal.</small></div></div></section>
</div>
<aside class="panel proc-summary"><div class="eyebrow">RINGKASAN PENERIMAAN</div><h2>Apa yang bergerak sekarang?</h2>
  <div class="proc-summary-metric received"><span>KAIN DITERIMA</span><strong data-proc-fabric>0 yard</strong><small>akan menambah stok bahan</small></div>
  <div class="proc-summary-metric"><span>AKSESORI DITERIMA</span><strong data-proc-accessory>0 pcs</strong><small>akan menambah stok aksesori</small></div>
  <div class="proc-summary-metric neutral"><span>NILAI HUTANG</span><strong>Belum dibentuk</strong><small>menunggu kasbon / tagihan supplier</small></div>
  <div class="proc-check success" data-proc-check><span>✓</span><div><strong>Siap direview</strong><small>Surat jalan dan jumlah fisik sudah jelas.</small></div></div>
  <button type="button" class="primary-btn proc-review-button" data-proc-review>Review barang datang <span>→</span></button><small class="proc-prototype-note">Frontend simulasi · tidak mengubah stok atau backend.</small>
</aside></section>
<section class="panel proc-history"><div class="panel-head"><div><div class="eyebrow">PENERIMAAN TERBARU · SIMULASI</div><h2>Surat jalan & status kasbon</h2></div></div>
  <div class="proc-history-row proc-history-simple"><span class="proc-history-date">27 Agu<br/><b>10:15</b></span><div><strong>PT Sumber Denim</strong><small>SJ-0827-171 · Denim 12 oz</small></div><div><span>DITERIMA</span><strong>1.180 yard</strong></div><span class="proc-history-pill wait">KASBON BELUM DATANG</span></div>
  <div class="proc-history-row proc-history-simple"><span class="proc-history-date">26 Agu<br/><b>15:42</b></span><div><strong>CV Maju Aksesori</strong><small>SJ-260826-088 · Kancing + zipper</small></div><div><span>DITERIMA</span><strong>3.600 pcs</strong></div><span class="proc-history-pill good">KASBON SUDAH DICOCKKAN</span></div>
</section>
<div class="proc-catalog-shield" data-proc-catalog-shield hidden></div><section class="proc-catalog-sheet" data-proc-catalog-sheet hidden><div class="proc-sheet-head"><div><span>KATALOG BAHAN & AKSESORI</span><strong>Tambah isi surat jalan</strong></div><button type="button" data-proc-close-catalog>×</button></div><div class="proc-search"><span>⌕</span><input data-proc-search-input placeholder="Cari kode, bahan, aksesori..."/></div><div class="proc-catalog-list" data-proc-catalog-list>${procurementCatalogTemplate()}</div></section>
<div class="proc-review-shield" data-proc-review-shield hidden></div><section class="proc-review-sheet" data-proc-review-sheet hidden><div class="proc-sheet-head"><div><span>REVIEW BARANG DATANG</span><strong data-proc-review-title>PT Sumber Denim · SJ-0827-177</strong></div><button type="button" data-proc-close-review>×</button></div><div class="proc-review-flow proc-receipt-review"><div><span>Kain masuk</span><strong data-proc-review-fabric>0 yard</strong></div><div><span>Aksesori masuk</span><strong data-proc-review-accessory>0 pcs</strong></div><div><span>Hutang supplier</span><strong>Belum ada</strong><small>kasbon menyusul</small></div></div><div class="proc-sheet-audit"><span>Waktu barang datang</span><strong data-proc-review-physical>—</strong><small>Waktu input sistem tetap terpisah saat backend tersambung.</small></div><div class="proc-routing-note"><strong>Flow berikutnya</strong><span>Kasbon supplier datang beberapa hari kemudian → pilih surat jalan/penerimaan yang cocok → masukkan harga & tagihan → baru hutang terbentuk. Retur barang memakai stok gudang.</span></div><div class="proc-sheet-actions"><button class="soft-btn" type="button" data-proc-close-review>Kembali edit</button><button class="primary-btn" type="button" data-proc-simulate>Simulasikan penerimaan</button></div><div class="proc-simulation-result" data-proc-simulation hidden><strong>Simulasi penerimaan selesai.</strong><span>Jumlah fisik akan menambah stok. Belum ada hutang supplier sampai kasbon/tagihan dicocokkan. Backend belum berubah.</span></div></section>`;procurementBind(root);procurementRecalculate(root)}
function procurementRecalculate(root:HTMLElement){let fabric=0,accessory=0;const rows=Array.from(root.querySelectorAll<HTMLElement>('[data-proc-line]'));rows.forEach((row)=>{const item=materialByCode(row.dataset.procLine??'');const received=Math.max(0,Number(row.querySelector<HTMLInputElement>('[data-proc-received]')?.value||0));if(item.category==='Kain')fabric+=received;else accessory+=received;const after=row.querySelector<HTMLElement>('[data-proc-after]');if(after)after.textContent=`Setelah terima: ${procurementNumber(item.stock+received)} ${item.unit}`});procurementSet(root,'[data-proc-fabric]',`${procurementNumber(fabric)} yard`);procurementSet(root,'[data-proc-accessory]',`${procurementNumber(accessory)} pcs`);document.querySelectorAll<HTMLElement>('[data-proc-review-fabric]').forEach((n)=>n.textContent=`${procurementNumber(fabric)} yard`);document.querySelectorAll<HTMLElement>('[data-proc-review-accessory]').forEach((n)=>n.textContent=`${procurementNumber(accessory)} pcs`);const ref=root.querySelector<HTMLInputElement>('[data-proc-delivery-note]')?.value.trim()??'';const hasQty=rows.some((row)=>Number(row.querySelector<HTMLInputElement>('[data-proc-received]')?.value||0)>0);const blocked=!ref||!hasQty;const check=root.querySelector<HTMLElement>('[data-proc-check]');if(check){check.classList.toggle('success',!blocked);check.classList.toggle('warn',blocked);check.innerHTML=!ref?'<span>!</span><div><strong>No. surat jalan belum diisi</strong><small>Referensi kertas supplier wajib jelas.</small></div>':!hasQty?'<span>!</span><div><strong>Belum ada jumlah diterima</strong><small>Isi minimal satu barang yang benar-benar datang.</small></div>':'<span>✓</span><div><strong>Siap direview</strong><small>Stok bergerak sekarang; hutang menunggu kasbon.</small></div>'}const review=root.querySelector<HTMLButtonElement>('[data-proc-review]');if(review)review.disabled=blocked;const empty=root.querySelector<HTMLElement>('[data-proc-empty]');if(empty)empty.hidden=rows.length>0}
function procurementSet(root:HTMLElement|Document,selector:string,text:string){const node=root.querySelector<HTMLElement>(selector);if(node)node.textContent=text}
function procurementOpenCatalog(){const sheet=document.querySelector<HTMLElement>('[data-proc-catalog-sheet]');const shield=document.querySelector<HTMLElement>('[data-proc-catalog-shield]');if(sheet)sheet.hidden=false;if(shield)shield.hidden=false;document.body.classList.add('proc-sheet-open');document.querySelector<HTMLInputElement>('[data-proc-search-input]')?.focus()}
function procurementCloseCatalog(){const sheet=document.querySelector<HTMLElement>('[data-proc-catalog-sheet]');const shield=document.querySelector<HTMLElement>('[data-proc-catalog-shield]');if(sheet)sheet.hidden=true;if(shield)shield.hidden=true;if(document.querySelector<HTMLElement>('[data-proc-review-sheet]')?.hidden!==false)document.body.classList.remove('proc-sheet-open')}
function procurementOpenReview(root:HTMLElement){const supplier=procurementSuppliers[Number(root.querySelector<HTMLSelectElement>('[data-proc-supplier]')?.value??0)]??procurementSuppliers[0];const ref=root.querySelector<HTMLInputElement>('[data-proc-delivery-note]')?.value.trim()??'—';const physical=root.querySelector<HTMLInputElement>('[data-proc-physical]')?.value??'';procurementSet(document,'[data-proc-review-title]',`${supplier.name} · ${ref}`);procurementSet(document,'[data-proc-review-physical]',physical?physical.replace('T',' · '):'—');const sheet=document.querySelector<HTMLElement>('[data-proc-review-sheet]');const shield=document.querySelector<HTMLElement>('[data-proc-review-shield]');if(sheet)sheet.hidden=false;if(shield)shield.hidden=false;document.body.classList.add('proc-sheet-open')}
function procurementCloseReview(){const sheet=document.querySelector<HTMLElement>('[data-proc-review-sheet]');const shield=document.querySelector<HTMLElement>('[data-proc-review-shield]');if(sheet)sheet.hidden=true;if(shield)shield.hidden=true;const simulation=document.querySelector<HTMLElement>('[data-proc-simulation]');if(simulation)simulation.hidden=true;if(document.querySelector<HTMLElement>('[data-proc-catalog-sheet]')?.hidden!==false)document.body.classList.remove('proc-sheet-open')}
function procurementBind(root:HTMLElement){root.addEventListener('input',(event)=>{const target=event.target as HTMLInputElement|HTMLTextAreaElement|null;if(!target)return;if(target.matches('[data-proc-physical]'))sessionStorage.setItem('erp.procurementPhysicalAt',target.value);procurementRecalculate(root)});root.addEventListener('change',(event)=>{const target=event.target as HTMLSelectElement|null;if(target?.matches('[data-proc-supplier]')){const supplier=procurementSuppliers[Number(target.value)]??procurementSuppliers[0];procurementSet(root,'[data-proc-supplier-meta]',supplier.kind)}procurementRecalculate(root)});root.addEventListener('click',(event)=>{const target=event.target as Element|null;if(target?.closest('[data-proc-open-catalog]'))procurementOpenCatalog();const remove=target?.closest('[data-proc-remove]') as HTMLElement|null;if(remove){remove.closest('[data-proc-line]')?.remove();procurementRecalculate(root)}if(target?.closest('[data-proc-review]'))procurementOpenReview(root)});document.querySelectorAll<HTMLElement>('[data-proc-close-catalog],[data-proc-catalog-shield]').forEach((n)=>n.addEventListener('click',procurementCloseCatalog));document.querySelectorAll<HTMLElement>('[data-proc-close-review],[data-proc-review-shield]').forEach((n)=>n.addEventListener('click',procurementCloseReview));document.querySelector<HTMLElement>('[data-proc-catalog-list]')?.addEventListener('click',(event)=>{const add=(event.target as Element|null)?.closest<HTMLButtonElement>('[data-proc-add]');const code=add?.dataset.procAdd;if(!code)return;const lines=root.querySelector<HTMLElement>('[data-proc-lines]');if(!root.querySelector(`[data-proc-line="${code}"]`)&&lines)lines.insertAdjacentHTML('beforeend',procurementLineTemplate(code,0));procurementCloseCatalog();procurementRecalculate(root)});document.querySelector<HTMLInputElement>('[data-proc-search-input]')?.addEventListener('input',(event)=>{const query=(event.currentTarget as HTMLInputElement).value.toLowerCase();document.querySelectorAll<HTMLElement>('[data-proc-search]').forEach((row)=>row.hidden=!(row.dataset.procSearch??'').toLowerCase().includes(query))});document.querySelector<HTMLButtonElement>('[data-proc-simulate]')?.addEventListener('click',()=>{const result=document.querySelector<HTMLElement>('[data-proc-simulation]');if(result)result.hidden=false})}
function procurementMountIfNeeded(){if(sessionStorage.getItem(procurementActiveKey)!==procurementPageId)return;const placeholder=document.querySelector<HTMLElement>('.placeholder');if(!placeholder)return;procurementSetTopTitle(true);procurementRender(placeholder)}
document.addEventListener('click',(event)=>{const target=event.target as Element|null;const submenu=target?.closest('.submenu button') as HTMLButtonElement|null;if(submenu){const label=submenu.textContent?.replace(/^•\s*/,'').trim()??'';if(label==='Pembelian & Penerimaan')sessionStorage.setItem(procurementActiveKey,procurementPageId);else if(sessionStorage.getItem(procurementActiveKey)===procurementPageId){sessionStorage.removeItem(procurementActiveKey);procurementUnmount()}}const mainNav=target?.closest('.nav-main');if(mainNav&&!submenu&&sessionStorage.getItem(procurementActiveKey)===procurementPageId){sessionStorage.removeItem(procurementActiveKey);procurementUnmount()}},true)
const procurementObserver=new MutationObserver(procurementMountIfNeeded);procurementObserver.observe(document.documentElement,{childList:true,subtree:true});queueMicrotask(procurementMountIfNeeded)
