// @vitest-environment jsdom
import {act} from 'react'
import {createRoot,type Root} from 'react-dom/client'
import {afterEach,beforeEach,describe,expect,it,vi} from 'vitest'
import PurchaseInvoicePanel from './PurchaseInvoicePanel'
import {parsePurchaseInvoices,parsePurchaseInvoiceOutcome} from './purchaseInvoiceContract'
import {readProductionRecovery} from './productionRecovery'
import {recoveryIdentity} from '../tests/fixtures/productionRecovery'
import {invoiceWorkspaceFixture,invoiceReceiptId as purchase,invoiceId as invoice} from '../tests/fixtures/purchaseInvoices'
const state=vi.hoisted(()=>({auth:null as unknown}))
const client=vi.hoisted(()=>({rpc:vi.fn()}))
vi.mock('./auth/AuthProvider',()=>({useAuth:()=>state.auth}))
vi.mock('./lib/supabase',()=>({getUatSupabaseClient:()=>client}))
let root:Root,container:HTMLDivElement
beforeEach(()=>{Object.assign(globalThis,{IS_REACT_ACT_ENVIRONMENT:true});localStorage.clear();client.rpc.mockReset();const a=structuredClone(recoveryIdentity);a.identity.permissions.push('warehouse.procurement.view','warehouse.procurement.post','warehouse.procurement.reverse','finance.ap.view');state.auth=a;Object.defineProperty(navigator,'locks',{configurable:true,value:{request:async(_n:string,_o:unknown,fn:(l:unknown)=>Promise<unknown>)=>fn({})}});container=document.createElement('div');document.body.append(container);root=createRoot(container)})
afterEach(async()=>{await act(async()=>root.unmount());container.remove();localStorage.clear();Reflect.deleteProperty(navigator,'locks');vi.restoreAllMocks()})
async function flush(){await act(async()=>{await new Promise(r=>setTimeout(r,0))})}
async function mount(id:string|null=purchase,refresh=async()=>true){await act(async()=>root.render(<PurchaseInvoicePanel purchaseId={id} onReceiptUpdated={refresh}/>));await flush()}
function button(label:string){const x=[...container.querySelectorAll('button')].find(b=>b.textContent===label);if(!x)throw Error('Missing '+label);return x}
async function click(label:string){await act(async()=>button(label).click());await flush()}
async function input(label:string,value:string){const el=container.querySelector<HTMLInputElement>(`[aria-label="${label}"]`)!;await act(async()=>{Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,'value')!.set!.call(el,value);el.dispatchEvent(new Event('input',{bubbles:true}))});await flush()}
async function check(label:string){await act(async()=>container.querySelector<HTMLInputElement>(`[aria-label="${label}"]`)!.click());await flush()}
const writes=()=>client.rpc.mock.calls.filter(([n])=>n==='erp_cp7_save_purchase_invoice_v1')
function server(){const s={posted:false,reversed:false,lose:false,wrong:false,failRead:false,parentFail:false,effects:0},cache=new Map<string,unknown>();client.rpc.mockImplementation(async(name:string,args:Record<string,unknown>)=>{
 if(name==='erp_cp7_get_purchase_invoices_v1')return s.failRead&&s.posted?{data:null,error:{message:'Invoice read unavailable'}}:{data:invoiceWorkspaceFixture(s.posted,s.reversed),error:null}
 if(name==='erp_cp7_save_purchase_invoice_v1'){const key=String(args.p_request);if(!cache.has(key)){s.posted=true;s.reversed=args.p_action==='REVERSE';s.effects++;cache.set(key,{contract_version:'cp7.purchase-invoice-outcome.v1',kind:'COMMITTED_OUTCOME',action:args.p_action,request_id:key,purchase_id:purchase,invoice_id:invoice,version_subject:s.reversed?'INVOICE':'RECEIPT',row_version:s.reversed?'9007199254740995':'9007199254740994',status:s.reversed?'REVERSED':'POSTED'})}return s.lose?{data:null,error:{status:503,message:'Lost committed reply'}}:{data:s.wrong?{ok:true}:cache.get(key),error:null}}
 throw Error('Unexpected '+name)
 });return s}
async function draft(){await click('Catat invoice supplier');await input('Nomor invoice supplier','INV-TEST');await input('Jumlah invoice 1','4');await input('Harga invoice 1','12,50');await check('Invoice sudah diperiksa')}
describe('purchase invoice connected boundary',()=>{
 it('uses the reviewed exact receipt version, explicit prices and authoritative invoice totals',async()=>{const s=server();await mount();await draft();await click('Sahkan invoice supplier');expect(writes()).toHaveLength(1);expect(writes()[0][1].p_expected).toBe('9007199254740993');expect(writes()[0][1].p_payload.lines[0]).toMatchObject({qty_invoiced:'4',final_unit_price:'12.50',discount_amount:'0'});expect(container.textContent).toContain('Nilai dokumen Rp50');expect(container.textContent).toContain('Belum dicocokkan: 6 YD');expect(s.effects).toBe(1);expect(readProductionRecovery('disposable:actor-1').pending.PURCHASE_INVOICE).toBeUndefined()})
 it('recovers the same invoice after lost reply and a reload with no selected receipt',async()=>{const s=server();await mount();await draft();s.lose=true;await click('Sahkan invoice supplier');const sent=structuredClone(writes()[0][1]);expect(readProductionRecovery('disposable:actor-1').pending.PURCHASE_INVOICE?.id).toBe(sent.p_request);await act(async()=>root.unmount());root=createRoot(container);s.lose=false;await mount(null);await click('Reconcile transaksi');expect(writes()[1][1]).toEqual(sent);expect(s.effects).toBe(1);expect(container.textContent).toContain('Nilai dokumen Rp50')})
 it('retires committed forms and locks subsequent writes when invoice reload fails',async()=>{const s=server();await mount();await draft();const old=button('Sahkan invoice supplier');s.failRead=true;await click('Sahkan invoice supplier');expect(container.textContent).toContain('Aksi sudah tersimpan');expect(container.textContent).not.toContain('Sahkan invoice supplier');await act(async()=>old.click());expect(writes()).toHaveLength(1);s.failRead=false;await click('Muat ulang invoice');expect(container.textContent).toContain('Nilai dokumen Rp50')})
 it('keeps malformed committed outcomes pending and preserves exact review until reconciliation',async()=>{const s=server();await mount();await draft();s.wrong=true;await click('Sahkan invoice supplier');expect(readProductionRecovery('disposable:actor-1').pending.PURCHASE_INVOICE).toBeTruthy();expect(button('Sahkan invoice supplier').disabled).toBe(true)})
 it('requires reviewing the complete invoice and sends its own version for reversal',async()=>{const s=server();s.posted=true;await mount();await click('Tinjau pembatalan INV-TEST');expect(button('Batalkan invoice supplier').disabled).toBe(true);await input('Alasan pembatalan invoice','Dokumen supplier diganti');await check('Konfirmasi pembatalan invoice');await click('Batalkan invoice supplier');expect(writes()[0][1]).toMatchObject({p_action:'REVERSE',p_expected:'9007199254740994',p_payload:{invoice_id:invoice,purchase_id:purchase}});expect(container.textContent).toContain('Invoice dibatalkan')})
 it('refuses truncated or mislabeled documents and a success for another receipt',()=>{const w=invoiceWorkspaceFixture(true);expect(()=>parsePurchaseInvoices(w,purchase)).not.toThrow();expect(()=>parsePurchaseInvoices({...w,receipt_line_count:'2'},purchase)).toThrow();expect(()=>parsePurchaseInvoices({...w,page:{...w.page,total:'2'}},purchase)).toThrow();const changed=structuredClone(w);changed.page.rows[0].line_count='2';expect(()=>parsePurchaseInvoices(changed,purchase)).toThrow();expect(()=>parsePurchaseInvoices({...w,basis:'CURRENT_AP_OUTSTANDING'},purchase)).toThrow();expect(()=>parsePurchaseInvoiceOutcome({contract_version:'cp7.purchase-invoice-outcome.v1',kind:'COMMITTED_OUTCOME',action:'FINALIZE',request_id:invoice,purchase_id:invoice,invoice_id:invoice,version_subject:'RECEIPT',row_version:'1',status:'POSTED'},invoice,'FINALIZE',{purchase_id:purchase})).toThrow()})
 it('does not request or paint invoice money without finance access',async()=>{server();const a=state.auth as typeof recoveryIdentity;a.identity.permissions=a.identity.permissions.filter(p=>p!=='finance.ap.view');await mount();expect(container.textContent).toBe('');expect(client.rpc).not.toHaveBeenCalled()})
 it('invalidates confirmation when quantity or price changes and locks if parent receipt refresh fails',async()=>{const s=server();await mount(purchase,async()=>!s.parentFail);await draft();await input('Harga invoice 1','13');expect(button('Sahkan invoice supplier').disabled).toBe(true);await check('Invoice sudah diperiksa');s.parentFail=true;await click('Sahkan invoice supplier');expect(container.textContent).toContain('Aksi sudah tersimpan');expect(container.textContent).not.toContain('Catat invoice supplier');expect(writes()).toHaveLength(1)})
})
