import {describe,expect,it} from 'vitest'
import {parseSalesChainWorkspace,salesChainPayload,parseSalesChainOutcome} from './salesChainContract'
import {chainSource,chainWorkspace,chainOutcome,payment,request,ret} from '../tests/fixtures/salesChain'
describe('complete reviewed sale-chain contract',()=>{
 it('keeps Native money, microseconds and revisions as exact strings',()=>{const w=chainWorkspace();w.source.payments[0].amount='9007199254740993.01';const r=parseSalesChainWorkspace(w,chainSource);expect(r.source.payments[0].amount).toBe('9007199254740993.01');expect(r.source.payments[0].physical_at).toContain('654321');expect(r.source.row_version).toBe('9007199254740993')})
 it('accepts every child beyond a paginated first page and binds ordered identities',()=>{const w=chainWorkspace();w.source.payments=Array.from({length:26},(_,i)=>({...w.source.payments[0],id:`22222222-2222-4222-8222-${String(i+1).padStart(12,'0')}`}));const p=salesChainPayload(parseSalesChainWorkspace(w,chainSource),'  Semua dokumen diperiksa  ');expect(p.payment_ids).toHaveLength(26);expect(p.return_ids).toEqual([ret]);expect(p.change_reason).toBe('Semua dokumen diperiksa');expect(parseSalesChainOutcome(chainOutcome(request,p),request,p).steps).toHaveLength(28)})
 it('rejects wrong parent, stale version, extra fields and incomplete child evidence',()=>{for(const change of [(w:ReturnType<typeof chainWorkspace>)=>{w.source.sale_id=payment},(w:ReturnType<typeof chainWorkspace>)=>{w.source.row_version='1'},(w:ReturnType<typeof chainWorkspace>)=>{w.source.review_token='c'.repeat(32)},(w:ReturnType<typeof chainWorkspace>)=>{Object.assign(w,{hpp:'0'})},(w:ReturnType<typeof chainWorkspace>)=>{Object.assign(w.source.payments[0],{amount:null})},(w:ReturnType<typeof chainWorkspace>)=>{w.source.returns[0].line_count='0'},(w:ReturnType<typeof chainWorkspace>)=>{w.source.payments.push({...w.source.payments[0]})}]){const w=chainWorkspace();change(w);expect(()=>parseSalesChainWorkspace(w,chainSource)).toThrow()}})
 it('blocks pending drafts and refuses invented eligibility',()=>{const w=chainWorkspace();w.source.pending_children=[{kind:'RETURN',id:request,number:'RET-DRAFT'}];expect(()=>parseSalesChainWorkspace(w,chainSource)).toThrow();w.eligible=false;expect(parseSalesChainWorkspace(w,chainSource).eligible).toBe(false);expect(()=>salesChainPayload(w,'Semua diperiksa')).toThrow()})
 it('requires every ordered committed step with the exact outer request',()=>{const p=salesChainPayload(chainWorkspace(),'Semua dokumen diperiksa'),r=chainOutcome(request,p);expect(parseSalesChainOutcome(r,request,p).sale_id).toBe(p.sale_id);for(const value of [{...r,request_id:ret},{...r,status:'POSTED'},{...r,steps:r.steps.slice(1)},{...r,steps:[r.steps[1],r.steps[0],r.steps[2]]},{...r,steps:[{...r.steps[0],status:'POSTED'},...r.steps.slice(1)]},{...r,steps:[{...r.steps[0],id:ret},...r.steps.slice(1)]},{...r,steps:[...r.steps,r.steps[0]]},{...r,partial:true}])expect(()=>parseSalesChainOutcome(value,request,p)).toThrow()})
})
