import RecordTools,{orderRecordPage,type RecordPageOrder} from './RecordTools'
import {useTransactionSource} from './TransactionSourceNavigation'
import {useCallback,useEffect,useMemo,useRef,useState} from 'react'
import {useAuth} from './auth/AuthProvider'
import {isConnectedRuntime} from './config/runtime'
import {getUatSupabaseClient} from './lib/supabase'
import {normalizeClientError} from './lib/clientError'
import {cp6WibDateTimeInput,cp6WibPhysicalTimeToIso,formatCp6WibDateTime} from './cp6BusinessTime'
import {formatReceiptDecimal as numberText} from './procurementContract'
import {salesCashAmount} from './salesCashContract'
import {salesQtyInput,type SalesRead} from './salesReadContract'
import {parseSalesReturns,salesReturnTotal,type SalesReturnAllocation as Allocation,type SalesReturnLocation as Location,type SalesReturnRecord as Record,type SalesReturnRead as Read,type SalesReturnKind} from './salesReturnContract'
import type {Json} from './types/database.preconnect'
type Source=NonNullable<SalesRead['detail']>
type Line={key:string;source:Allocation;location:Location;qty:string;grade:'GRADE_A'|'GRADE_B'|'HOLD';refund:string;notes:string}
type Props={source:Source;locked:boolean;stale:boolean;onClose:()=>void;onSave:(action:'RETURN'|'RETURN_REVERSE',document:Json,version:string)=>void}
const money=(s:string)=>`Rp${numberText(s)}`
export default function SalesReturnPanel({source,locked,stale,onClose,onSave}:Props){
 const navigation=useTransactionSource('SALE'),focus=navigation?.document.id===source.id&&navigation.document.focus?.kind==='SALES_RETURN'?navigation.document.focus:null
 const {runtime,identity}=useAuth();if(!isConnectedRuntime(runtime)||identity.status!=='AUTHORIZED')throw Error('Sesi retur belum siap.')
 const client=useMemo(()=>getUatSupabaseClient(runtime),[runtime]),seq=useRef(0),query=useRef({ALLOCATIONS:{offset:0,q:''},RETURNS:{offset:focus?.page_offset??0,q:''},LOCATIONS:{offset:0,q:''}})
 const [data,setData]=useState<{allocations:Read<Allocation>;returns:Read<Record>;locations:Read<Location>}|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState('')
 const [q,setQ]=useState(''),[locationQ,setLocationQ]=useState(''),[location,setLocation]=useState<Location|null>(null),[number,setNumber]=useState(''),[at,setAt]=useState(()=>cp6WibDateTimeInput()),[notes,setNotes]=useState(''),[reason,setReason]=useState('Barang retur dan invoice sudah diperiksa'),[review,setReview]=useState(false),[reverse,setReverse]=useState<Record|null>(null),[lines,setLines]=useState<Line[]>([])
 const [historyInput,setHistoryInput]=useState(''),[historyQuery,setHistoryQuery]=useState(''),[historyStatus,setHistoryStatus]=useState('ALL'),[historyOrder,setHistoryOrder]=useState<RecordPageOrder>('SOURCE')
 const load=useCallback(async()=>{
  const ticket=++seq.current,queries=structuredClone(query.current);setData(null);setBusy(true);setError('');setReview(false)
  try{const kinds=['ALLOCATIONS','RETURNS','LOCATIONS'] as const;const rows=await Promise.all(kinds.map(async kind=>{const r=await client.rpc('erp_cp7_get_sales_returns_v1',{p_query:{sale_id:source.id,kind,...queries[kind],limit:25}});if(r.error)throw r.error;return r.data}));if(ticket!==seq.current)return
   const focused=parseSalesReturns<Record>(rows[1],'RETURNS',source,queries.RETURNS.offset);if(focus&&queries.RETURNS.offset===focus.page_offset&&!focused.page.rows.some(x=>x.id===focus.id))throw Error('Retur sumber berubah. Buka ulang sumber dari buku.');
   setData({allocations:parseSalesReturns<Allocation>(rows[0],'ALLOCATIONS',source,queries.ALLOCATIONS.offset),returns:parseSalesReturns<Record>(rows[1],'RETURNS',source,queries.RETURNS.offset),locations:parseSalesReturns<Location>(rows[2],'LOCATIONS',source,queries.LOCATIONS.offset)})
  }catch(e){if(ticket===seq.current)setError(normalizeClientError(e).message)}finally{if(ticket===seq.current)setBusy(false)}
 },[client,source,focus])
 useEffect(()=>{void load();return()=>{++seq.current}},[load])
 const canCreate=identity.permissions.includes('sales.return.create')&&identity.permissions.includes('sales.return.post'),canReverse=identity.permissions.includes('sales.return.reverse')&&['OWNER','ADMIN'].includes(identity.profile.role)
 const disabled=locked||stale||busy||!data,physical=cp6WibPhysicalTimeToIso(at),total=salesReturnTotal(lines.map(l=>l.refund)),quantities=new Map<string,bigint>()
 let validLines=lines.length>0&&lines.length<=100&&total!==null
 for(const l of lines){const qty=salesQtyInput(l.qty);if(!qty){validLines=false;continue}const sum=(quantities.get(l.source.allocation_id)??0n)+BigInt(qty);quantities.set(l.source.allocation_id,sum);if(sum>BigInt(l.source.remaining_qty))validLines=false}
 const valid=review&&reason.trim().length>=5&&(reverse?reverse.status==='POSTED':canCreate&&number.trim()&&physical&&validLines&&['POSTED','PARTIAL_PAID','PAID'].includes(source.status))
 const update=(key:string,change:Partial<Line>)=>{setLines(previous=>previous.map(l=>l.key===key?{...l,...change}:l));setReview(false)}
 const page=(kind:SalesReturnKind,offset:number)=>{query.current[kind].offset=offset;void load()}
 const save=()=>{if(disabled||!valid||!source.review_token)return;const base={sale_id:source.id,review_token:source.review_token,change_reason:reason.trim()}
  if(reverse){if(canReverse)onSave('RETURN_REVERSE',{...base,return_id:reverse.id},source.row_version)}
  else onSave('RETURN',{...base,return_number:number.trim(),physical_at:physical!,notes:notes.trim()||null,items:lines.map(l=>({allocation_id:l.source.allocation_id,location_id:l.location.id,qty_pcs:salesQtyInput(l.qty)!,quality_grade:l.grade,refund_amount:salesCashAmount(l.refund)!,notes:l.notes.trim()||null}))},source.row_version)
 }
 const returnRows=orderRecordPage(data?.returns.page.rows.filter(r=>(focus||historyStatus==='ALL'||r.status===historyStatus)&&(focus||[r.number,r.notes,...r.items.flatMap(i=>[i.product_sku,i.lot_number,i.location_name,i.notes])].join(' ').toLowerCase().includes(historyQuery.toLowerCase()))),focus?'SOURCE':historyOrder,r=>r.number)
 return <section className="panel" aria-label="Retur fisik invoice">
  <div className="cproc-heading"><div><h2>Retur {source.number}</h2><p>{source.customer_name} · barang mengikuti alokasi penjualan asal.</p></div><button disabled={locked} onClick={onClose}>Tutup retur invoice</button></div>
  {stale?<p role="alert">Invoice berubah. Tutup formulir dan muat ulang sebelum mencatat retur.</p>:null}{error?<p role="alert">{error}</p>:null}{busy?<p role="status">Memuat sumber retur…</p>:null}<button disabled={locked||stale||busy} onClick={()=>void load()}>Muat ulang sumber retur</button>
  {data?<section aria-label="Riwayat retur invoice"><h3>Riwayat retur</h3><RecordTools title="riwayat retur invoice" busy={disabled||Boolean(focus)} filterScope="PAGE" browseLabel="Semua retur di halaman ini" submitLabel="Cari riwayat retur di halaman ini" order={focus?'SOURCE':historyOrder} onOrder={setHistoryOrder} onSubmit={e=>{e.preventDefault();setHistoryQuery(historyInput.trim())}} onBrowse={()=>{setHistoryInput('');setHistoryQuery('');setHistoryStatus('ALL');setHistoryOrder('SOURCE')}} search={<label>Cari nomor atau catatan<input aria-label="Cari riwayat retur di halaman ini" value={historyInput} maxLength={120} disabled={disabled||Boolean(focus)} onChange={e=>setHistoryInput(e.target.value)}/></label>} filters={<label>Status<select aria-label="Status retur di halaman ini" value={focus?'ALL':historyStatus} disabled={disabled||Boolean(focus)} onChange={e=>setHistoryStatus(e.target.value)}><option value="ALL">Semua status</option><option value="POSTED">Tercatat</option><option value="REVERSED">Dibatalkan</option><option value="DRAFT">Draft</option></select></label>}/><p>Menampilkan {returnRows.length} dari {data.returns.page.rows.length} retur pada halaman ini. Pencarian dan filter hanya memakai halaman yang sudah dimuat.</p>{data.returns.page.rows.length===0?<p>Belum ada retur tercatat.</p>:null}{data.returns.page.rows.length>0&&returnRows.length===0?<p>Tidak ada retur sesuai pencarian pada halaman ini.</p>:null}{returnRows.map(r=><article className="cproc-item" data-source-selected={focus?.id===r.id} key={r.id}><h4>{r.number} · {r.status==='POSTED'?'Tercatat':r.status==='REVERSED'?'Dibatalkan':'Draft'}</h4><p>{formatCp6WibDateTime(r.physical_at)} · nilai retur {money(salesReturnTotal(r.items.map(i=>i.refund_amount))!)}</p>{r.items.map(i=><p key={i.id}>{i.product_sku} · lot {i.lot_number} · {numberText(i.qty_pcs)} PCS · {i.quality_grade==='GRADE_A'?'Grade A':i.quality_grade==='GRADE_B'?'Grade B':'Ditahan (Hold)'} → {i.location_name} · {money(i.refund_amount)}{i.notes?` · ${i.notes}`:''}</p>)}{r.notes?<p>{r.notes}</p>:null}{canReverse&&r.status==='POSTED'?<button disabled={disabled} onClick={()=>{setReverse(r);setReason('');setReview(false)}}>Koreksi retur {r.number}</button>:null}</article>)}<div className="cproc-pagination"><span>Total {data.returns.page.total} retur</span><button disabled={disabled||data.returns.page.offset===0} onClick={()=>page('RETURNS',Math.max(0,data.returns.page.offset-25))}>Retur sebelumnya</button><button disabled={disabled||data.returns.page.next_offset===null} onClick={()=>page('RETURNS',data.returns.page.next_offset??0)}>Retur berikutnya</button></div></section>:null}
  {reverse||canCreate&&['POSTED','PARTIAL_PAID','PAID'].includes(source.status)?<form aria-label="Catat retur pelanggan" onSubmit={e=>{e.preventDefault();save()}} onChange={()=>setReview(false)}><fieldset disabled={disabled}>
   {reverse?<div className="cproc-review"><h3>Batalkan retur {reverse.number}</h3><p>Barang retur dikeluarkan kembali dari gudang penerima dan jurnal retur dibalik. Barang yang sudah dipakai dapat menahan pembatalan.</p><button type="button" onClick={()=>{setReverse(null);setReview(false)}}>Urungkan koreksi retur</button></div>:<>
    <div className="cproc-grid"><label>Nomor retur<input aria-label="Nomor retur pelanggan" maxLength={60} value={number} onChange={e=>setNumber(e.target.value)}/></label><label>Waktu barang kembali · WIB<input type="datetime-local" aria-label="Waktu retur pelanggan WIB" value={at} onChange={e=>setAt(e.target.value)}/></label></div>
    <div className="cproc-search"><label>Cari gudang penerima<input aria-label="Cari gudang retur" maxLength={120} value={locationQ} onChange={e=>setLocationQ(e.target.value)} onKeyDown={e=>{if(e.key==='Enter')e.preventDefault()}}/></label><button type="button" onClick={()=>{query.current.LOCATIONS={offset:0,q:locationQ.trim()};void load()}}>Cari gudang retur</button></div>
    {data?<section aria-label="Pilih gudang retur">{data.locations.page.rows.map(l=><button type="button" className="cproc-receipt" key={l.id} aria-pressed={location?.id===l.id} onClick={()=>{setLocation(l);setReview(false)}}>{l.name}</button>)}{data.locations.page.rows.length===0?<p>Gudang FG aktif tidak ditemukan.</p>:null}<div className="cproc-pagination"><span>Total {data.locations.page.total} gudang</span><button type="button" disabled={data.locations.page.offset===0} onClick={()=>page('LOCATIONS',Math.max(0,data.locations.page.offset-25))}>Gudang sebelumnya</button><button type="button" disabled={data.locations.page.next_offset===null} onClick={()=>page('LOCATIONS',data.locations.page.next_offset??0)}>Gudang berikutnya</button></div></section>:null}
    <p>Satu alokasi asal memakai satu baris per retur. Untuk grade atau gudang lain dari alokasi yang sama, catat retur terpisah.</p>
    <p>Gudang untuk barang yang ditambahkan: <strong>{location?.name??'belum dipilih'}</strong>.</p>
    <div className="cproc-search"><label>Cari SKU atau lot penjualan<input aria-label="Cari alokasi retur" maxLength={120} value={q} onChange={e=>setQ(e.target.value)} onKeyDown={e=>{if(e.key==='Enter')e.preventDefault()}}/></label><button type="button" onClick={()=>{query.current.ALLOCATIONS={offset:0,q:q.trim()};void load()}}>Cari alokasi retur</button></div>
    {data?<section aria-label="Pilih alokasi retur">{data.allocations.page.rows.map(a=><button type="button" className="cproc-receipt" key={a.allocation_id} disabled={!location||lines.length>=100||lines.some(l=>l.source.allocation_id===a.allocation_id)} onClick={()=>{if(location){setLines(old=>[...old,{key:crypto.randomUUID(),source:a,location,qty:'',grade:'GRADE_A',refund:'',notes:''}]);setReview(false)}}}><span><strong>{a.commercial_sku} · {a.size_code}</strong><small>Lot {a.lot_number} · gudang asal {a.source_location_name}</small><small>Sisa boleh diretur {numberText(a.remaining_qty)} dari {numberText(a.allocated_qty)} PCS</small></span></button>)}{data.allocations.page.rows.length===0?<p>Tidak ada alokasi tersisa sesuai pencarian.</p>:null}<div className="cproc-pagination"><span>Total {data.allocations.page.total} alokasi</span><button type="button" disabled={data.allocations.page.offset===0} onClick={()=>page('ALLOCATIONS',Math.max(0,data.allocations.page.offset-25))}>Alokasi sebelumnya</button><button type="button" disabled={data.allocations.page.next_offset===null} onClick={()=>page('ALLOCATIONS',data.allocations.page.next_offset??0)}>Alokasi berikutnya</button></div></section>:null}
    {lines.map((l,index)=><article className="cproc-item" key={l.key}><h3>{l.source.commercial_sku} · {l.source.size_code}</h3><p>SKU fisik {l.source.product_sku} · lot {l.source.lot_number} → {l.location.name}</p><p>Baris invoice asal {numberText(l.source.sale_item_qty)} PCS senilai {money(l.source.sale_item_net)}. Nilai retur diperiksa terhadap invoice.</p><div className="cproc-grid"><label>Jumlah kembali · PCS<input inputMode="numeric" aria-label={`Jumlah retur ${index+1}`} value={l.qty} onChange={e=>update(l.key,{qty:e.target.value})}/></label><label>Kondisi barang<select aria-label={`Grade retur ${index+1}`} value={l.grade} onChange={e=>update(l.key,{grade:e.target.value as Line['grade']})}><option value="GRADE_A">Grade A</option><option value="GRADE_B">Grade B</option><option value="HOLD">Ditahan (Hold)</option></select></label><label>Nilai pengurang tagihan<input inputMode="decimal" aria-label={`Nilai retur ${index+1}`} value={l.refund} onChange={e=>update(l.key,{refund:e.target.value})}/></label><label>Catatan barang<input aria-label={`Catatan barang retur ${index+1}`} maxLength={2000} value={l.notes} onChange={e=>update(l.key,{notes:e.target.value})}/></label></div><button type="button" disabled={!location} onClick={()=>{if(location)update(l.key,{location})}}>Pakai gudang terpilih untuk barang {index+1}</button><button type="button" onClick={()=>{setLines(old=>old.filter(x=>x.key!==l.key));setReview(false)}}>Hapus barang retur {index+1}</button></article>)}
    {lines.length>0&&!validLines?<p role="alert">Lengkapi jumlah PCS dan nilai retur. Jumlah seluruh baris untuk satu alokasi tidak boleh melebihi sisanya.</p>:null}
    <label>Catatan retur<input aria-label="Catatan retur pelanggan" value={notes} maxLength={2000} onChange={e=>setNotes(e.target.value)}/></label><div className="cproc-total"><span>Nilai pengurang tagihan</span><strong>{total!==null&&lines.length?money(total):'Belum lengkap'}</strong><p>Retur menambah barang ke gudang dan mengurangi tagihan. Jika tagihan sudah dibayar, koreksi pembayaran secara terpisah agar tidak menjadi kelebihan bayar.</p></div>
   </>}
   <label>{reverse?'Alasan koreksi':'Catatan pemeriksaan'}<input aria-label="Alasan tindakan retur" maxLength={1000} value={reason} onChange={e=>setReason(e.target.value)}/></label><label className="cproc-check"><input type="checkbox" aria-label="Retur pelanggan sudah diperiksa" checked={review} onChange={e=>{e.stopPropagation();setReview(e.target.checked)}}/>{reverse?'Retur dan alasan pembatalan sudah saya periksa.':'Alokasi asal, barang kembali, gudang, grade, dan nilai retur sudah saya periksa.'}</label><button className="primary-btn" disabled={!valid}>{reverse?'Batalkan retur tercatat':'Catat retur pelanggan'}</button>
  </fieldset></form>:null}
 </section>
}
