import {useCallback,useEffect,useMemo,useRef,useState} from 'react'
import {useAuth} from './auth/AuthProvider'
import {isConnectedRuntime} from './config/runtime'
import {getUatSupabaseClient} from './lib/supabase'
import {normalizeClientError} from './lib/clientError'
import {cp6WibDateTimeInput,cp6WibPhysicalTimeToIso,formatCp6WibDateTime} from './cp6BusinessTime'
import {useProductionMutation,type ProductionMutationHandlers} from './useProductionMutation'
import ProductionRecoveryNotice from './ProductionRecoveryNotice'
import {formatReceiptDecimal as numberText,parseProcurementOptions,procurementObject,receiptDecimal,type ProcurementOptions} from './procurementContract'
import {parseSupplierReturns,parseSupplierReturnOutcome,parseSupplierReturnSources,type SupplierReturn,type SupplierReturns,type SupplierReturnSources} from './supplierReturnContract'
import type {Json} from './types/database.preconnect'
type Props={purchaseId:string|null;receiptRevision?:string|null;onReceiptUpdated:(purchaseId:string)=>Promise<boolean>}
type Line={key:string;source:string;roll:string|null;qty:string;notes:string}
type Form={id:string|null;version:string|null;purchase:string;purchaseVersion:string;supplier:string;location:string;number:string;at:string;originalAt?:string;reason:string;lines:Line[];sources:SupplierReturns[];complete:boolean}
type Client=ReturnType<typeof getUatSupabaseClient>
function LocationPicker({client,selected,disabled,onChange}:{client:Client;selected:SupplierReturns['selected_location'];disabled:boolean;onChange:(id:string)=>void}){
 const [query,setQuery]=useState({q:'',offset:0}),[search,setSearch]=useState(''),[data,setData]=useState<ProcurementOptions|null>(null),[loading,setLoading]=useState(false),[error,setError]=useState('')
 useEffect(()=>{let current=true;setLoading(true);setError('');void(async()=>{try{const r=await client.rpc('erp_cp7_get_procurement_options_v1',{p_kind:'LOCATION',p_q:query.q,p_offset:query.offset,p_limit:25});if(!current)return;if(r.error)throw r.error;const w=parseProcurementOptions(r.data,'LOCATION');if(w.offset!==query.offset)throw Error('Halaman gudang tidak cocok.');setData(w)}catch(e){if(current)setError(normalizeClientError(e).message)}finally{if(current)setLoading(false)}})();return()=>{current=false}},[client,query])
 return <div className="cproc-picker"><label>Gudang pengirim retur<select aria-label="Gudang pengirim retur" disabled={disabled||loading} value={selected?.id??''} onChange={e=>{if(e.target.value)onChange(e.target.value)}}><option value="">Pilih gudang</option>{selected&&!data?.rows.some(l=>l.id===selected.id)?<option value={selected.id}>{selected.name}</option>:null}{data?.rows.map(l=><option key={l.id} value={l.id}>{l.code} · {l.name}</option>)}</select></label><div className="cproc-inline"><input aria-label="Cari gudang retur" placeholder="Cari gudang pengirim" disabled={disabled} value={search} onChange={e=>setSearch(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'){e.preventDefault();setQuery({q:search.trim(),offset:0})}}}/><button type="button" disabled={disabled||loading} onClick={()=>setQuery({q:search.trim(),offset:0})}>Cari gudang retur</button><button type="button" aria-label="Gudang retur sebelumnya" disabled={disabled||loading||!query.offset} onClick={()=>setQuery(q=>({...q,offset:Math.max(0,q.offset-25)}))}>‹</button><button type="button" aria-label="Gudang retur berikutnya" disabled={disabled||loading||data?.next_offset==null} onClick={()=>setQuery(q=>({...q,offset:data?.next_offset??0}))}>›</button></div>{error?<p role="alert">{error}</p>:null}</div>
}
function ReceiptPicker({client,purchase,supplier,disabled,selected,onPick}:{client:Client;purchase:string;supplier:string;disabled:boolean;selected:string[];onPick:(id:string)=>void}){
 const [search,setSearch]=useState(''),[query,setQuery]=useState({q:'',offset:0}),[data,setData]=useState<SupplierReturnSources|null>(null),[loading,setLoading]=useState(false),[error,setError]=useState('')
 useEffect(()=>{let current=true;setLoading(true);setData(null);setError('');void(async()=>{try{const r=await client.rpc('erp_cp7_get_supplier_return_sources_v1',{p_purchase:purchase,p_q:query.q,p_offset:query.offset,p_limit:25});if(!current)return;if(r.error)throw r.error;setData(parseSupplierReturnSources(r.data,purchase,supplier,query.offset))}catch(e){if(current)setError(normalizeClientError(e).message)}finally{if(current)setLoading(false)}})();return()=>{current=false}},[client,purchase,supplier,query])
 return <section className="cproc-picker" aria-label="Pilih penerimaan retur gabungan"><h4>Penerimaan dari supplier yang sama</h4><div className="cproc-inline"><input aria-label="Cari penerimaan retur" disabled={disabled} value={search} onChange={e=>setSearch(e.target.value)}/><button type="button" disabled={disabled||loading} onClick={()=>setQuery({q:search.trim(),offset:0})}>Cari penerimaan retur</button></div>{error?<p role="alert">{error}</p>:null}{data?.page.rows.map(r=><button type="button" className="cproc-receipt" key={r.id} disabled={disabled||loading||selected.includes(r.id)} onClick={()=>onPick(r.id)}><span><strong>{r.number}</strong><small>{formatCp6WibDateTime(r.physical_at)}</small></span><span>{selected.includes(r.id)?'Sudah tersedia':'Pilih penerimaan'}</span></button>)}{data?.page.total==='0'?<p>Penerimaan yang cocok tidak ditemukan.</p>:null}<div className="cproc-pagination"><span>Total {data?.page.total??'—'} penerimaan</span><button type="button" disabled={disabled||loading||!query.offset} onClick={()=>setQuery(q=>({...q,offset:Math.max(0,q.offset-25)}))}>Penerimaan retur sebelumnya</button><button type="button" disabled={disabled||loading||data?.page.next_offset==null} onClick={()=>setQuery(q=>({...q,offset:data?.page.next_offset??0}))}>Penerimaan retur berikutnya</button></div></section>
}
function document(form:Form):Json|null{
 const at=form.originalAt&&cp6WibDateTimeInput(form.originalAt)===form.at?form.originalAt:cp6WibPhysicalTimeToIso(form.at)
 if(!at||!form.number.trim()||!form.reason.trim()||!form.lines.length||!form.lines.some(l=>form.sources.find(w=>w.purchase_id===form.purchase)?.source_lines.some(s=>s.id===l.source)))return null
 const items:Json[]=[]
 for(const l of form.lines){const source=form.sources.flatMap(w=>w.source_lines).find(s=>s.id===l.source),qty=receiptDecimal(l.qty,true);if(!source||!qty||!source.material_active||source.material_type==='FABRIC'&&!source.rolls.some(r=>r.id===l.roll)||source.material_type!=='FABRIC'&&l.roll!==null)return null;items.push({purchase_item_id:source.id,material_id:source.material_id,roll_id:l.roll,qty,notes:l.notes.trim()||null})}
 return {purchase_id:form.purchase,...(form.id?{id:form.id}:{}),return_number:form.number.trim(),supplier_id:form.supplier,location_id:form.location,physical_at:at,reason:form.reason.trim(),change_reason:form.reason.trim(),items}
}
const statusLabel={DRAFT:'Draft retur',POSTED:'Retur sudah dikirim',REVERSED:'Retur dibatalkan'}
const money=(v:string|null)=>v===null?'Belum ditetapkan':`Rp${numberText(v)}`
export default function SupplierReturnPanel(props:Props){
 const {runtime,identity}=useAuth()
 if(!isConnectedRuntime(runtime)||identity.status!=='AUTHORIZED'||!identity.permissions.includes('warehouse.procurement.view'))return null
 return <ReturnWorkspace key={`${runtime.projectRef}:${identity.profile.id}:${identity.profile.rowVersion}:${identity.profile.roleRowVersion}:${identity.permissions.join('|')}`} {...props}/>
}
function ReturnWorkspace({purchaseId,receiptRevision,onReceiptUpdated}:Props){
 const {runtime,identity}=useAuth();if(!isConnectedRuntime(runtime)||identity.status!=='AUTHORIZED')throw Error('Sesi retur belum siap.')
 const client=useMemo(()=>getUatSupabaseClient(runtime),[runtime]),valueAccess=identity.permissions.includes('finance.ap.view'),mutation=useProductionMutation('SUPPLIER_RETURN')
 const {beginRead,finishRead,isReadCurrent,run,reconcile,invalidate}=mutation
 const [data,setData]=useState<SupplierReturns|null>(null),[loading,setLoading]=useState(false),[error,setError]=useState(''),[form,setForm]=useState<Form|null>(null)
 const [sourcePicker,setSourcePicker]=useState(false),[sourceLoading,setSourceLoading]=useState(false),[sourceError,setSourceError]=useState('')
 const [selected,setSelected]=useState<string|null>(null),[review,setReview]=useState<{id:string;version:string;action:'POST'|'REVERSE'}|null>(null),[confirmed,setConfirmed]=useState(false),[reason,setReason]=useState('')
 const requested=useRef({purchase:purchaseId,location:null as string|null,offset:0}),sequence=useRef(0),pendingRef=useRef(mutation.pending),busyRef=useRef(mutation.busy);pendingRef.current=mutation.pending;busyRef.current=mutation.busy
 const load=useCallback(async()=>{const s=++sequence.current,ticket=beginRead(),q={...requested.current};setLoading(true);setError('');try{
  if(!q.purchase){setData(null);return false}
  const r=await client.rpc('erp_cp7_get_supplier_returns_v1',{p_purchase:q.purchase,p_location:q.location,p_offset:q.offset,p_limit:25})
  if(!isReadCurrent(ticket)||s!==sequence.current)return false;if(r.error)throw r.error
  const w=parseSupplierReturns(r.data,q.purchase,valueAccess);if(w.page.offset!==q.offset||q.location&&w.selected_location?.id!==q.location)throw Error('Gudang atau halaman retur tidak cocok.')
  setData(w);return finishRead(ticket)
 }catch(e){if(isReadCurrent(ticket)){setData(null);setError(normalizeClientError(e).message)};return false}finally{if(s===sequence.current)setLoading(false)}},[client,valueAccess,beginRead,finishRead,isReadCurrent])
 useEffect(()=>{
  if(busyRef.current)return
  let purchase=purchaseId,location=requested.current.location
  if(pendingRef.current){try{const outer=procurementObject(pendingRef.current.payload),p=procurementObject(outer.document);if(typeof p.purchase_id==='string')purchase=p.purchase_id;if(typeof p.return_id==='string')setSelected(p.return_id);if(typeof p.id==='string')setSelected(p.id);if(typeof outer.source_location==='string')location=outer.source_location;else if(typeof p.location_id==='string')location=p.location_id}catch{/* Shared recovery retains invalid envelopes. */}}
  if(requested.current.purchase!==purchase){requested.current={purchase,location:pendingRef.current?location:null,offset:0};setForm(null);setReview(null);setConfirmed(false)}
  else if(pendingRef.current)requested.current.location=location
  void load()
 },[purchaseId,receiptRevision,load])
 const handlers:ProductionMutationHandlers={
  send:e=>{const p=procurementObject(e.payload);return client.rpc('erp_cp7_save_supplier_return_v1',{p_action:e.action,p_payload:p.document as Json,p_request:e.id,p_expected:p.expected_version as string|null})},
  validate:(r,e)=>{parseSupplierReturnOutcome(r,e.id,e.action,procurementObject(e.payload).document as Json)},
  retire:(r,e)=>{const out=parseSupplierReturnOutcome(r,e.id,e.action,procurementObject(e.payload).document as Json);const location=procurementObject(e.payload).source_location;requested.current={...requested.current,purchase:out.purchase_id,location:typeof location==='string'?location:requested.current.location,offset:0};setSelected(out.return_id);setForm(null);setSourcePicker(false);setSourceError('');setReview(null);setConfirmed(false);setReason('');setData(null)},
  reload:async()=>{if(!requested.current.purchase||!await onReceiptUpdated(requested.current.purchase)){invalidate();setData(null);return false};return load()},
 }
 const locked=mutation.writerLocked||loading||sourceLoading,current=data?.page.rows.find(d=>d.id===selected),sourceReady=data?.purchase_status==='POSTED'&&data.supplier_id&&data.selected_location?.available
 const stale=Boolean(form&&(!data||form.purchase!==data.purchase_id||form.purchaseVersion!==data.purchase_version||form.location!==data.selected_location?.id||form.id&&(!current||current.id!==form.id||current.row_version!==form.version)))
 const completeSource=Boolean(current&&current.lines.every(l=>l.purchase_id&&l.purchase_item_id)),payload=form&&data?document(form):null,activeReview=review&&current?.id===review.id&&current.row_version===review.version&&completeSource&&(review.action==='POST'?current.status==='DRAFT':current.status==='POSTED')
 const write=(action:string,p:Json,version:string|null)=>run(action,{document:p,expected_version:version,source_location:action.startsWith('SAVE')?form?.location??null:current?.location_id??requested.current.location},null,handlers)
 const blankLine=():Line=>({key:crypto.randomUUID(),source:data?.source_lines.find(s=>s.material_active)?.id??'',roll:null,qty:'',notes:''})
 const create=()=>{if(!data||!data.supplier_id||!data.selected_location)return;setSelected(null);setReview(null);setForm({id:null,version:null,purchase:data.purchase_id,purchaseVersion:data.purchase_version,supplier:data.supplier_id,location:data.selected_location.id,number:'',at:cp6WibDateTimeInput(),reason:'Barang dikembalikan menjadi tanggung jawab supplier',lines:[blankLine()],sources:[data],complete:false});setSourcePicker(false);setSourceError('')}
 const readSource=async(id:string,location:string,offset=0)=>{const r=await client.rpc('erp_cp7_get_supplier_returns_v1',{p_purchase:id,p_location:location,p_offset:offset,p_limit:25});if(r.error)throw r.error;const w=parseSupplierReturns(r.data,id,valueAccess);if(w.selected_location?.id!==location||w.page.offset!==offset)throw Error('Gudang sumber retur tidak cocok.');return w}
 const addSource=async(id:string)=>{if(!form||locked)return;const captured=form;setSourceLoading(true);setSourceError('');try{const w=await readSource(id,captured.location);if(w.supplier_id!==captured.supplier||w.purchase_status!=='POSTED')throw Error('Penerimaan harus tercatat dari supplier yang sama.');const first=w.source_lines.find(l=>l.material_active);if(!first)throw Error('Penerimaan ini tidak memiliki barang aktif.');setForm(current=>current===captured&&!current.sources.some(s=>s.purchase_id===id)?{...current,complete:true,sources:[...current.sources,w],lines:[...current.lines,{key:crypto.randomUUID(),source:first.id,roll:null,qty:'',notes:''}]}:current);setSourcePicker(false)}catch(e){setSourceError(normalizeClientError(e).message)}finally{setSourceLoading(false)}}
 const edit=async(d:SupplierReturn)=>{if(!data||locked)return;setSourceLoading(true);setSourceError('');setReview(null);const anchor=data.purchase_id;try{const ids=[...new Set(d.lines.map(l=>l.purchase_id).filter((id):id is string=>id!==null))];const sources=await Promise.all(ids.map(id=>readSource(id,d.location_id,id===anchor?requested.current.offset:0)));if(requested.current.purchase!==anchor)return;if(sources.some(w=>w.supplier_id!==d.supplier_id))throw Error('Supplier sumber retur tidak cocok.');const primary=sources.find(w=>w.purchase_id===anchor);if(!primary)throw Error('Sumber utama retur belum lengkap.');requested.current.location=d.location_id;setData(primary);setForm({id:d.id,version:d.row_version,purchase:anchor,purchaseVersion:primary.purchase_version,supplier:d.supplier_id,location:d.location_id,number:d.number,at:cp6WibDateTimeInput(d.physical_at),originalAt:d.physical_at,reason:d.reason??'',lines:d.lines.map(l=>({key:l.id,source:l.purchase_item_id??'',roll:l.roll_id,qty:l.qty,notes:l.notes??''})),sources,complete:!d.single_receipt});setSourcePicker(false)}catch(e){setSourceError(normalizeClientError(e).message)}finally{setSourceLoading(false)}}

 const update=(key:string,delta:Partial<Line>)=>setForm(f=>f?{...f,lines:f.lines.map(l=>l.key===key?{...l,...delta}:l)}:f)
 return <section className="panel cproc-returns" aria-label="Retur supplier">
  <div className="cproc-heading"><div><div className="eyebrow">BARANG KEMBALI KE SUPPLIER</div><h2>Retur supplier</h2><p>{data?`Sumber ${data.purchase_number}`:'Pilih penerimaan untuk mencatat retur supplier.'}</p></div>{requested.current.purchase?<button type="button" disabled={mutation.busy||loading} onClick={()=>void handlers.reload()}>Muat ulang retur</button>:null}</div>
  {requested.current.purchase||mutation.pending||error?<ProductionRecoveryNotice recovery={{...mutation,notice:mutation.notice?'Data retur supplier sudah diperbarui.':'',...(mutation.pending&&!mutation.corruptedEnvelope?{error:'Hasil pencatatan retur belum diketahui. Periksa hasil transaksi dengan kiriman yang sama.',blockReason:''}:{})}} onReconcile={()=>reconcile(handlers)} className="cproc-review"/>:null}
  {error?<p role="alert">{error}</p>:null}{sourceError?<p role="alert">{sourceError}</p>:null}{sourceLoading?<p role="status">Memuat seluruh sumber retur…</p>:null}{loading?<p role="status">Memuat retur…</p>:null}
  {data?<><p className="cproc-help">Retur mengeluarkan barang dari gudang yang dipilih. Draft belum mengubah stok atau utang. Nilai retur mengikuti dokumen sumber.</p>
   <LocationPicker client={client} selected={data.selected_location} disabled={locked||Boolean(form)||Boolean(review)} onChange={id=>{requested.current.location=id;void load()}}/>
   {data.selected_location&&!data.selected_location.available?<p role="alert">Gudang ini tidak tersedia untuk pengiriman retur baru.</p>:null}
   <div className="cproc-grid">{data.source_lines.map(l=><article className="cproc-item" key={l.id}><strong>{l.material_name} · {l.unit_code}</strong><small>Diterima {numberText(l.receipt_qty)} · sudah diretur {numberText(l.posted_return_qty)}</small><small>Belum diretur dari penerimaan ini: {numberText(l.unreturned_qty)} {l.unit_code}</small>{l.material_type==='FABRIC'?<details><summary>Stok {l.rolls.length} roll di {data.selected_location?.name??'gudang yang dipilih'}</summary>{l.rolls.map(r=><p key={r.id}>{r.number}: {r.location_qty===null?'Pilih gudang':`${numberText(r.location_qty)} ${l.unit_code}`}</p>)}</details>:<small>Stok gudang: {l.location_qty===null?'Pilih gudang':`${numberText(l.location_qty)} ${l.unit_code}`}</small>}{!l.material_active?<small>Master bahan tidak aktif</small>:null}</article>)}</div>
   <button type="button" className="primary-btn" disabled={locked||!sourceReady||!data.capabilities.create||Boolean(form)||!data.source_lines.some(s=>s.material_active)} onClick={create}>Buat retur supplier</button>
   {form?<form className="cproc-editor" onSubmit={e=>{e.preventDefault();if(payload&&!locked&&!stale&&data.capabilities.create)void write(form.complete?'SAVE_DOCUMENT':'SAVE',payload,form.version)}}>
    <div className="cproc-heading"><h3>{form.id?'Perbaiki draft retur':'Retur baru'} · {data.purchase_number}</h3><button type="button" disabled={mutation.busy} onClick={()=>setForm(null)}>Tutup formulir retur</button></div>
    {stale?<p role="alert">Sumber atau draft retur berubah. Buka kembali formulir dari data terbaru.</p>:null}
    <fieldset disabled={locked||stale}><div className="cproc-grid"><label>Nomor retur<input aria-label="Nomor retur supplier" required value={form.number} onChange={e=>setForm({...form,number:e.target.value})}/></label><label>Waktu barang keluar · WIB<input aria-label="Waktu retur supplier WIB" type="datetime-local" required value={form.at} onChange={e=>setForm({...form,at:e.target.value})}/></label></div>
     <p>Gudang pengirim: {data.selected_location?.name}. Nilai dan satuan mengikuti sumber barang.</p><p>Sumber tersedia: {form.sources.map(w=>w.purchase_number).join(', ')}.</p><button type="button" disabled={locked||form.lines.length>=100} onClick={()=>setSourcePicker(v=>!v)}>{sourcePicker?'Tutup pilihan penerimaan':'Tambah penerimaan lain'}</button>{sourcePicker?<ReceiptPicker client={client} purchase={form.purchase} supplier={form.supplier} disabled={locked} selected={form.sources.map(w=>w.purchase_id)} onPick={id=>void addSource(id)}/>:null}
     {form.lines.map((l,i)=>{const source=form.sources.flatMap(w=>w.source_lines).find(s=>s.id===l.source);return <section className="cproc-line" key={l.key}><div className="cproc-heading"><h4>Barang retur {i+1}</h4><button type="button" disabled={form.lines.length===1} onClick={()=>setForm({...form,lines:form.lines.filter(x=>x.key!==l.key)})}>Hapus barang retur {i+1}</button></div><div className="cproc-grid"><label>Barang pada penerimaan<select aria-label={`Barang retur ${i+1}`} value={l.source} onChange={e=>update(l.key,{source:e.target.value,roll:null,qty:''})}>{form.sources.flatMap(w=>w.source_lines.map(s=><option key={s.id} value={s.id} disabled={!s.material_active}>{w.purchase_number} · {s.material_name} · {s.unit_code}</option>))}</select></label>{source?.material_type==='FABRIC'?<label>Roll yang dikembalikan<select aria-label={`Roll retur ${i+1}`} value={l.roll??''} onChange={e=>update(l.key,{roll:e.target.value||null})}><option value="">Pilih roll</option>{source.rolls.map(r=><option key={r.id} value={r.id}>{r.number} · stok {r.location_qty===null?'belum diketahui':numberText(r.location_qty)} {source.unit_code}</option>)}</select></label>:null}<label>Jumlah ({source?.unit_code??'satuan sumber'})<input aria-label={`Jumlah retur ${i+1}`} inputMode="decimal" required value={l.qty} onChange={e=>update(l.key,{qty:e.target.value})}/></label></div><label>Catatan barang<input aria-label={`Catatan barang retur ${i+1}`} value={l.notes} onChange={e=>update(l.key,{notes:e.target.value})}/></label></section>})}
     <button type="button" disabled={form.lines.length>=100} onClick={()=>setForm({...form,lines:[...form.lines,blankLine()]})}>Tambah barang retur</button><label>Alasan retur<input aria-label="Alasan retur supplier" required value={form.reason} onChange={e=>setForm({...form,reason:e.target.value})}/></label>
     <button className="primary-btn" disabled={locked||stale||!payload||!data.capabilities.create}>Simpan draft retur</button>
    </fieldset>
   </form>:null}
   <h3>Dokumen retur</h3>{!data.page.rows.length?<p>Belum ada retur untuk penerimaan ini.</p>:null}
   <div className="cproc-grid">{data.page.rows.map(d=><button type="button" className="cproc-receipt" key={d.id} aria-pressed={selected===d.id} disabled={locked||Boolean(form)} onClick={()=>{setSelected(d.id);setReview(null);setConfirmed(false)}}><span><strong>{d.number}</strong><small>{d.location_name} · {formatCp6WibDateTime(d.physical_at)}</small><small>{d.line_count} barang</small></span><span className={`cproc-status ${d.status.toLowerCase()}`}>{statusLabel[d.status]}</span></button>)}</div>
   {selected&&!current?<p>Dokumen yang dipilih tidak ada pada halaman ini. Pilih dokumen pada daftar retur untuk melanjutkan.</p>:null}
   {current?<section className="cproc-return-detail"><div className="cproc-heading"><h3>{current.number}</h3><span className={`cproc-status ${current.status.toLowerCase()}`}>{statusLabel[current.status]}</span></div><p>Gudang {current.location_name} · {formatCp6WibDateTime(current.physical_at)}</p><p>{current.reason}</p>
    {current.lines.map(l=><article className="cproc-item" key={l.id}><strong>{l.material_name} · {numberText(l.qty)} {l.unit_code}</strong><small>Sumber {l.purchase_number??'belum lengkap'}{l.roll_number?` · roll ${l.roll_number}`:''}</small>{l.notes?<p>{l.notes}</p>:null}{l.finance?<small>Nilai per {l.unit_code} dari sumber: {money(l.finance.credit_unit_price)}</small>:null}</article>)}
    {current.finance?<div className="cproc-total"><span>Pengurangan pada dokumen sumber</span><strong>Utang {money(current.finance.ap_relief_amount)}</strong><span>Penerimaan belum ditagih {money(current.finance.grni_relief_amount)}</span><small>{current.status==='DRAFT'?'Dihitung saat retur disahkan.':'Angka ini adalah catatan saat retur disahkan. Alokasi kredit saat ini diatur di Utang & kredit retur supplier.'}</small></div>:null}
    {!current.single_receipt?<p>Retur gabungan: seluruh baris dari semua penerimaan ikut diproses.</p>:null}{!completeSource?<p>Identitas sumber belum lengkap. Muat ulang sebelum memproses retur.</p>:current.status==='DRAFT'?<div className="cproc-actions"><button type="button" disabled={locked||Boolean(form)||!data.capabilities.create} onClick={()=>void edit(current)}>Perbaiki draft retur</button><button type="button" disabled={locked||Boolean(form)||!data.capabilities.post} onClick={()=>{setReview({id:current.id,version:current.row_version,action:'POST'});setReason('Barang retur dan supplier telah diperiksa');setConfirmed(false)}}>Tinjau pengiriman retur</button></div>:current.status==='POSTED'&&data.capabilities.reverse?<button type="button" disabled={locked||Boolean(form)} onClick={()=>{setReview({id:current.id,version:current.row_version,action:'REVERSE'});setReason('');setConfirmed(false)}}>Tinjau pembatalan retur</button>:null}
    {review?<div className="cproc-review"><h4>{review.action==='POST'?'Sahkan barang keluar':'Batalkan retur supplier'}</h4><p>{review.action==='POST'?'Pastikan barang, roll, gudang pengirim, supplier dan jumlah sudah sesuai pengembalian fisik.':'Pembatalan mengembalikan stok dan nilai sumber. Alokasi kredit yang masih dipakai perlu dikembalikan terlebih dahulu.'}</p>{!activeReview?<p role="alert">Versi retur berubah. Buka kembali pemeriksaan.</p>:null}<label>Alasan tindakan<input aria-label="Alasan tindakan retur" disabled={locked||!activeReview} value={reason} onChange={e=>{setReason(e.target.value);setConfirmed(false)}}/></label><label className="cproc-check"><input type="checkbox" aria-label="Retur sudah diperiksa" disabled={locked||!activeReview} checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>Seluruh barang dan alasan tindakan sudah diperiksa.</label><button type="button" className="primary-btn" disabled={locked||!activeReview||!confirmed||!reason.trim()||(review.action==='POST'?!data.capabilities.post:!data.capabilities.reverse)} onClick={()=>void write(current.single_receipt?review.action:review.action+'_DOCUMENT',{purchase_id:data.purchase_id,return_id:current.id,change_reason:reason.trim(),...(!current.single_receipt?{reviewed_purchase_ids:[...new Set(current.lines.map(l=>l.purchase_id!))].sort()}: {})},review.version)}>{review.action==='POST'?'Sahkan pengiriman retur':'Batalkan retur supplier'}</button><button type="button" disabled={mutation.busy} onClick={()=>setReview(null)}>Tutup pemeriksaan retur</button></div>:null}
   </section>:null}
   <div className="cproc-pagination"><span>{data.page.rows.length} dokumen · total {data.page.total}</span><button type="button" disabled={locked||Boolean(form)||Boolean(review)||data.page.offset===0} onClick={()=>{requested.current.offset=Math.max(0,data.page.offset-25);void load()}}>Retur sebelumnya</button><button type="button" disabled={locked||Boolean(form)||Boolean(review)||data.page.next_offset===null} onClick={()=>{requested.current.offset=data.page.next_offset??0;void load()}}>Retur berikutnya</button></div>
  </>:null}
 </section>
}
