// @vitest-environment jsdom
import{act,useEffect,useState}from'react'
import{createRoot,type Root}from'react-dom/client'
import{afterEach,beforeEach,describe,expect,it,vi}from'vitest'
import SupplierPaymentCorrectionPanel from'./SupplierPaymentCorrectionPanel'
import{useRetainedFormInput}from'./useRetainedFormInput'
import{useProductionMutation}from'./useProductionMutation'
import{parseSupplierPaymentCorrectionRead,parseSupplierPaymentCorrectionOutcome}from'./supplierPaymentCorrectionContract'
import{recoveryIdentity}from'../tests/fixtures/productionRecovery'
import{supplierPaymentFixture,supplierPaymentReadFixture}from'../tests/fixtures/supplierPayments'
import{supplierCorrectionFixture,supplierCorrectionLink,supplierCorrectionOutcome,replacementId}from'../tests/fixtures/supplierPaymentCorrections'
const mock=vi.hoisted(()=>({auth:null as unknown,rpc:vi.fn()}))
vi.mock('./auth/AuthProvider',()=>({useAuth:()=>mock.auth}))
vi.mock('./lib/supabase',()=>({getUatSupabaseClient:()=>mock}))
let root:Root,box:HTMLDivElement,source= supplierPaymentReadFixture(),payment=supplierPaymentFixture();const saved=vi.fn()
function Harness({edit=true,locked=false,show=true}:{edit?:boolean;locked?:boolean;show?:boolean}){const recovery=useProductionMutation('SUPPLIER_PAYMENT'),inputs=useRetainedFormInput('supplier-correction-leaf',recovery.committedSequence),[ready,setReady]=useState(false);useEffect(()=>{const ticket=recovery.beginRead();recovery.finishRead(ticket);setReady(true)},[recovery.beginRead,recovery.finishRead]);return ready&&show?<SupplierPaymentCorrectionPanel source={source} payment={payment} initialEdit={edit} locked={locked} inputs={inputs} currentReadTicket={recovery.currentReadTicket} isReadCurrent={recovery.isReadCurrent} onInvalid={()=>{}} onSave={saved} onClose={()=>{}}/>:null}
beforeEach(()=>{Object.assign(globalThis,{IS_REACT_ACT_ENVIRONMENT:true});localStorage.clear();saved.mockReset();mock.rpc.mockReset();const a=structuredClone(recoveryIdentity);a.identity.permissions.push('warehouse.procurement.view','finance.ap.view','finance.ap.pay');mock.auth=a;source=supplierPaymentReadFixture();payment=supplierPaymentFixture();payment.payment_date='2026-09-26T05:00:00.123456+00:00';source.page.rows=[payment];const data=supplierCorrectionFixture();data.document=payment;mock.rpc.mockResolvedValue({data,error:null});box=document.createElement('div');document.body.append(box);root=createRoot(box)})
afterEach(async()=>{await act(async()=>root.unmount());box.remove();localStorage.clear()})
const flush=async()=>act(async()=>{await new Promise(r=>setTimeout(r,0))})
async function mount(edit=true,locked=false,show=true){await act(async()=>root.render(<Harness edit={edit} locked={locked} show={show}/>));await flush()}
const input=(label:string)=>box.querySelector<HTMLInputElement>(`[aria-label="${label}"]`)!
const button=(label:string)=>[...box.querySelectorAll('button')].find(b=>b.textContent===label)!
async function fill(label:string,value:string){await act(async()=>{const e=input(label);Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,'value')!.set!.call(e,value);e.dispatchEvent(new Event('input',{bubbles:true}))});await flush()}
async function click(e:HTMLElement){await act(async()=>e.click());await flush()}
async function review(){await fill('Alasan koreksi pembayaran supplier','Jumlah sumber dan pengganti sudah diperiksa');await click(input('Koreksi pembayaran supplier sudah diperiksa'))}
describe('supplier payment editor and strict declared stand-ins',()=>{
 it('emits one reviewed exact source payload, normalized cents and untouched microseconds',async()=>{await mount();expect(button('Simpan koreksi pembayaran supplier').disabled).toBe(true);await fill('Nominal koreksi pembayaran supplier','9,01');await review();await click(button('Simpan koreksi pembayaran supplier'));expect(saved).toHaveBeenCalledOnce();expect(saved).toHaveBeenCalledWith({purchase_id:source.purchase.id,payment_id:payment.id,review_token:payment.review_token,change_reason:'Jumlah sumber dan pengganti sudah diperiksa',replacement:{amount:'9.01',cash_account_id:payment.cash_account_id,payment_date:payment.payment_date}});expect(new Set(mock.rpc.mock.calls.map(c=>c[0]))).toEqual(new Set(['erp_cp7_get_supplier_payment_correction_v1']))})
 it('refuses no change, cents rounding and Native replacement overcapacity without a write',async()=>{source.Native_AP!.remaining='0.00';source.Native_AP!.paid='1000.00';const data=supplierCorrectionFixture();data.document=payment;data.Native_AP=source.Native_AP;mock.rpc.mockResolvedValue({data,error:null});await mount();await review();expect(button('Simpan koreksi pembayaran supplier').disabled).toBe(true);for(const amount of['10.01','9.001','0']){await fill('Nominal koreksi pembayaran supplier',amount);await review();expect(button('Simpan koreksi pembayaran supplier').disabled).toBe(true)}expect(saved).not.toHaveBeenCalled()})
 it('preserves cents beyond Number precision and interprets edited time as WIB',async()=>{payment.amount='90071992547409.91';source.Native_AP!.final_ap='90071992547409.93';source.Native_AP!.paid=payment.amount;source.Native_AP!.remaining='0.02';const data=supplierCorrectionFixture();data.document=payment;data.Native_AP=source.Native_AP;mock.rpc.mockResolvedValue({data,error:null});await mount();await fill('Nominal koreksi pembayaran supplier','90071992547409.92');await fill('Waktu koreksi pembayaran supplier WIB','2026-09-27T01:30');await mount(true,false,false);await mount();expect(input('Waktu koreksi pembayaran supplier WIB').value).toBe('2026-09-27T01:30');await review();await click(button('Simpan koreksi pembayaran supplier'));expect(saved.mock.calls[0][0].replacement).toEqual({amount:'90071992547409.92',cash_account_id:payment.cash_account_id,payment_date:'2026-09-26T18:30:00.000Z'})})
 it('retains original adjacent contents for a new reviewed restoration',async()=>{payment.id=replacementId;payment.amount='9.00';payment.review_token='b'.repeat(32);const data=supplierCorrectionFixture();data.document=payment;const old=supplierPaymentFixture();old.status='REVERSED';old.journal!.status='REVERSED';old.inverse={...old.journal!,id:'c3000000-0000-4000-8000-000000000099',number:'JRN-INVERSE',status:'POSTED'};data.previous={document:old,link:supplierCorrectionLink('a1000000-0000-4000-8000-000000000010','Jumlah sebelumnya diperbaiki')};mock.rpc.mockResolvedValue({data,error:null});await mount(false);await click(button('Pulihkan isi pembayaran supplier sebelum koreksi'));expect(input('Nominal koreksi pembayaran supplier').value).toBe('10.00');expect(saved).not.toHaveBeenCalled();await review();await click(button('Simpan koreksi pembayaran supplier'));expect(saved.mock.calls[0][0].replacement.payment_date).toBe(old.payment_date);expect(saved.mock.calls[0][0].payment_id).toBe(replacementId)})
 it('permits current readonly history while omitting a writer',async()=>{const a=structuredClone(recoveryIdentity);a.identity.profile.role='STAFF';a.identity.permissions.push('warehouse.procurement.view','finance.ap.view');mock.auth=a;source.capabilities.reverse=false;const data=supplierCorrectionFixture();data.document=payment;data.can_correct=false;mock.rpc.mockResolvedValue({data,error:null});await mount();expect(box.textContent).toContain(payment.number);expect(box.querySelector('form')).toBeNull();expect(saved).not.toHaveBeenCalled()})
 it('rejects changed native source content and retires money after an explicit failed read',async()=>{await mount();mock.rpc.mockResolvedValue({data:null,error:{message:'Sumber ditolak saat ini',code:'42501'}});await click(button('Muat ulang perubahan pembayaran supplier'));expect(box.textContent).not.toContain('Rp');expect(box.querySelector('form')).toBeNull();const changed=supplierCorrectionFixture();changed.document={...payment,amount:'9.00'};mock.rpc.mockResolvedValue({data:changed,error:null});await click(button('Muat ulang perubahan pembayaran supplier'));expect(box.textContent).not.toContain('Rp');expect(saved).not.toHaveBeenCalled()})
 it('keeps exact bank page offsets and rejects an incomplete or foreign page/lineage/outcome',async()=>{const data=supplierCorrectionFixture();data.document=payment;data.cash_accounts={rows:Array.from({length:25},(_,i)=>({id:`d4000000-0000-4000-8000-${String(i+1).padStart(12,'0')}`,code:'BANK-'+i,name:'Bank '+i,kind:'BANK'})),total:'26',offset:0,limit:25,next_offset:25};mock.rpc.mockResolvedValue({data,error:null});await mount();const next=structuredClone(data);next.cash_accounts={rows:[{id:'d4000000-0000-4000-8000-000000000026',code:'BANK-26',name:'Bank terakhir',kind:'BANK'}],total:'26',offset:25,limit:25,next_offset:null};mock.rpc.mockResolvedValue({data:next,error:null});await click(button('Rekening supplier berikutnya'));expect(mock.rpc.mock.calls.at(-1)?.[1].p_query.bank_offset).toBe(25);expect(box.textContent).toContain('Bank terakhir');expect(()=>parseSupplierPaymentCorrectionRead(next,source,payment,0)).toThrow();const request='a1000000-0000-4000-8000-000000000010',payload={purchase_id:source.purchase.id,payment_id:payment.id,change_reason:'Jumlah sudah diperiksa',review_token:payment.review_token,replacement:{amount:'9.00',cash_account_id:payment.cash_account_id,payment_date:payment.payment_date}};const outcome=supplierCorrectionOutcome(request,payload);expect(parseSupplierPaymentCorrectionOutcome(outcome,request,payload).payment_id).toBe(replacementId);expect(()=>parseSupplierPaymentCorrectionOutcome({...outcome,payment_id:payment.id},request,payload)).toThrow();expect(()=>parseSupplierPaymentCorrectionOutcome(outcome,request,{...payload,change_reason:'Maksud yang lain'})).toThrow()})
 it('cannot revive a late read after parent source replacement or writer locking',async()=>{let release:(v:unknown)=>void=()=>{};mock.rpc.mockImplementationOnce(()=>new Promise(r=>{release=r}));await mount();const old=supplierCorrectionFixture();old.document=payment;source={...source,purchase:{...source.purchase,id:'a1000000-0000-0000-0000-000000000002'}};mock.rpc.mockResolvedValue({data:null,error:{message:'Parent berubah'}});await mount(true,true);await act(async()=>release({data:old,error:null}));await flush();expect(box.querySelector('form')).toBeNull();expect(box.textContent).not.toContain('Rp');expect(saved).not.toHaveBeenCalled()})
})
